### ISSUE TITLE
blocking player left click on items in item frames

### ISSUE THREAD

**Issue by DerEinpacker** [DenizenScript/Denizen-For-Bukkit#1000]
Is there a way to block players from taking items out of item frames?

on player left clicks block doesn't fire
on hanging breaks doesn't fire
player damages entity doesn't fire

I can prevent players from destroying item frames with "on hanging breaks" but not from taking the item in the item frame.

**Comment by AnthonyAMC** [comment]
```on player right clicks item_frame:```
What is your ultimate goal here?

**Comment by Morphan1** [comment]
*`on player left clicks item_frame:`?

**Comment by AnthonyAMC** [comment]
oh right, right clicks is for rotating, ```on player damages item_frame:``` is for breaking it and also popping items out.

**Comment by DerEinpacker** [comment]
Hey, on player left clicks item_frame didn't fire, 

on player damages item_frame:
- determine cancelled 

had no effect, too. Did you test it? Did I make a mistake there?

**Comment by mcmonkey4eva** [comment]
Try `/denizen debug -e` and then hit the frame - it will list all events that fired. Or.. well, most. Modern ScriptEvents won't show up, but I don't believe damage is one of those.

**Comment by DerEinpacker** [comment]
Anthony was right. It works now. Thank you all!
