### ISSUE TITLE
on player enters notable should fire when a player joins

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#1001]
Title says it all.

**Comment by AnthonyAMC** [comment]
Oh, exit notable should fire on logout. Haven't verified if it does/doesn't, just throwing that in there while the topic is open.

**Comment by Morphan1** [comment]
Is this still/was it ever an issue?

**Comment by mcmonkey4eva** [comment]
Fixed.
