### ISSUE TITLE
Error in Denizen Script Queue timing

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Denizen-For-Bukkit#1004]
Error: http://mcmonkey.org/paste/14877

I noticed on line 67 it is doing Double.valueof(), would it make more sense to use Double.parseDouble() since all we need is the value, not a whole Double object.

**Comment by Morphan1** [comment]
It should be parsing a duration though shouldn't it?

**Comment by Talamar1** [comment]
says delay, not duration...not sure

**Comment by mcmonkey4eva** [comment]
Technically, the error isn't at all on our side, it's on yours. But, there is an error on our part that's unrelated and sorta helped push you into the error you made... the above commit fixes the error on our side... now it's up to you to figure out why your server is timing out, cause it ain't our fault.

**Comment by Talamar1** [comment]
Looks like it has something to do with using recursive looping vs while looping.
Original script used something like this:
```
script:
  - commands
  - run script delay:5s
```
new script uses:
```
script:
  - while true {
    - commands
    - wait 5s
    }
```
