### ISSUE TITLE
<e@entity.describe> enhancement request

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1005]
Currently when using ```<e@entity.describe>``` on a horse, you get something like this:
```
e@horse[color=gray|white|donkey;jump_strength=0.8151890103508361;tame=true|Uledrith]
```
I'm requesting a couple of things to make this tag much more useful when dealing with the complexities of minecraft's horses.
```
1.) Add speed=
2.) change <player.name> to owner=<player>
3.) Add contents=<entity.inventory.list_contents>
```
So with those changes, it would look more like:
```
e@horse[color=gray|white|donkey;jump_strength=0.8151890103508361;speed=.2526345973482856;tame=true;owner=p@64554132-c402-44e8-8315-fd74e9607f25;contents=i@saddle|i@air|i@grass[quantity=5]|I@air|i@dirt]
```

It would also be nice if ```<e@entity.describe>``` would report back equipment.  (i.e. a zombie holding an iron sword currently only reports back e@zombie.

Thanks!

**Comment by uledrith** [comment]
edit:

Would also be nice to have
```health=``` and ```max_health=```

**Comment by mcmonkey4eva** [comment]
All on the todolist, just ... few people want it, so it gets dev'd slowly. Will push it up.

**Comment by mcmonkey4eva** [comment]
BAM ^

**Comment by uledrith** [comment]
thanks :)

**Comment by mcmonkey4eva** [comment]
That is weird. Sorta-patch for it added. I think it doesn't know to give the donkey a chest and that's the actual problem... not sure how to fix that... hmmmm...

**Comment by uledrith** [comment]
mcmonkey,

I'm having a couple of problems..
Here is my script:
http://mcmonkey.org/haste/14998

As you can see from the script, I'm just dumping a ```<context.entity.describe>``` into a flag and then ```- spawn <player.flag[]>```

This works fine except I'm getting bugginess with horses and saddles.  I'm not getting any errors, but when I release the horse, it doesn't have the saddle.  I'm ensuring the entity is tamed and I'm the owner so I don't get it.  Also at that the point the horse is basically bugged.

To replicate this issue, I simply do this:
1. Load the above script
2. ```/ex give I@herder```
3. ```/ex spawn e@horse[tame=true|<player>] <player.location>```
4. Give the horse a saddle.
5. Right click the horse with herder.
6. Right click the ground.

I also occasionally get this odd error in the console about health.  Maybe that is the problem?

http://mcmonkey.org/haste/14998

**Comment by mcmonkey4eva** [comment]
I think that second link is wrong?

**Comment by mcmonkey4eva** [comment]
This -> https://github.com/mcmonkey4eva/Denizen/commit/609bde69e23f967c66d10497c1fef97a9b620f59 -> fixes that particular error probably

**Comment by mcmonkey4eva** [comment]
I have no idea about the rest of it :/ I'll look deeper into it later if someone reminds me
