### ISSUE TITLE
request for tag notable.exists

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Denizen-For-Bukkit#1006]
I think it would be helpful to have a .exists tag for notables to see if they are defined.  Example
```
- if !<cu@notable.exists> {
  - note cu@loc1|loc2 as:notable
}
```

This would allow for a script to easily test for notables and create them if needed.

**Comment by mcmonkey4eva** [comment]
Not possible in that form due to our object system.

Perhaps a `server.notable_exists[ID]` though.

What do you think, @Morphan1 ?

**Comment by Morphan1** [comment]
What's wrong with `<server.list_notables[cuboids].contains[cu@notable]>`?

**Comment by Talamar1** [comment]
if I have notables cu@chappelonhill cu@chappelinthepark and I do a search to see if cu@chappel exists with that form, won't it return true even if it doesn't?

**Comment by mcmonkey4eva** [comment]
That's `element.contains_text` not `list.contains`
