### ISSUE TITLE
Remove decimal from <player.flag[flag_name]>

### ISSUE THREAD

**Issue by adexgold** [DenizenScript/Denizen-For-Bukkit#1007]
Here is the script im trying to run, http://jpst.it/xXdI it works, just a slight annoyance is that when it returns the flag amount it returns it as a decimal and not a whole number. Is there any way to make this a whole number?

**Comment by mcmonkey4eva** [comment]
`.as_int` at the end of the tag.

**Comment by adexgold** [comment]
Sweet, thanks! 

I figured it was something simple, just couldn't seem to find what it was.
