### ISSUE TITLE
tag <&quo> not working

### ISSUE THREAD

**Issue by Xericore** [DenizenScript/Denizen-For-Bukkit#1008]
Tested with latest denizen dev build 180.
http://mcmonkey.org/denizen/lngs/#useful_lists says:
" = &quo

Yet
```
/ex narrate "<&quo>TEST"
returns:
&quoTEST
```
Console:
```
ERROR! Tag <&quo> is invalid!
```

**Comment by mcmonkey4eva** [comment]
```
[12:08:04] <mcmonkey> !tag &quo
[12:08:05] <monkeybot> That tag doesn't seem to exist.
```

**Comment by mcmonkey4eva** [comment]
I'm fairly sure you're mixing up property escapes and tags, which are two different things.

**Comment by Xericore** [comment]
Yes thanks. I was actually looking for <&dq>.
