### ISSUE TITLE
<location.switched> always reports true on doors

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1011]
To replicate, just do this:
Stand somewhere with your cursor pointing on door (around it's hinge).
```/ex narrate <player.location.cursor_on.switched>```
open/close the door
```/ex narrate <player.location.cursor_on.switched>```

As a further test, you can try using the 'switch' command while pointing your cursor at the door.
Note that state:on will never open or close the door.  However, using the following command with the 'state:off' will open/close door repeatedly because as mentioned above, the <location.switched> tag on doors always reports true.
```/ex switch <player.location.cursor_on> state:off```

**Comment by mcmonkey4eva** [comment]
Are you pointing at the *top* or the *bottom* half of the door?

**Comment by uledrith** [comment]
uh, I tried both just now.  The top ALWAYS reports true and the bottom ALWAYS reports false.

**Comment by Morphan1** [comment]
Can this be confirmed?

**Comment by mcmonkey4eva** [comment]
@Morphan1 yeah sure test it - you can confirm things yourself, you have a server

**Comment by Morphan1** [comment]
@mcmonkey4eva I was wondering if anybody could test it before I get home. (I'm still at school)

**Comment by AnthonyAMC** [comment]
I fiddled with it when it was reported and confirmed it
