### ISSUE TITLE
some 'animate' animations do not work

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1012]
I've done thorough testing with the 'animate' command.  The following animations have issues:

To replicate, simply do the following:
```/npc create BoB```
```/ex equip <npc> hand:i@apple```
```/ex animate <npc> animation:eat_food```  (does nothing - tried multiple types of food in hand)
```/ex animate <npc> animation:start_use_item``` (does nothing - tried equipping multiple items in npc's hand)
```/ex animate <npc> sleep``` (npc's nameplate appears around the npc's knees, but npc stays standing)
I tried putting the npc on top of a bed with the sleep command, but still does exact same thing.

Thanks!
Uledrith

**Comment by mcmonkey4eva** [comment]
Animations are not implemented by Denizen, they are implemented by Citizens.
