### ISSUE TITLE
SQL return delimiter is too common

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#1016]
The save:id entry returns a list of rows with columns split by ```/```. This [delimiter](https://github.com/DenizenScript/Denizen-For-Bukkit/blob/master/src/main/java/net/aufdemrand/denizen/scripts/commands/core/SQLCommand.java#L202) is too common and makes storing split lists to a db unintuitive and impossible for any value to contain a ```/```.
```
- define this 'a/split/list'
- define that 'derp'
- sql id:%db% "update:INSERT INTO %tableName% (this, that) VALUES ('%this%', '%that%');" save:save
- narrate "<entry[id].result.get[1].split[/]||null>"
```
That would return ```li@a|split|list|derp``` giving the false impression that there are 4 columns in the db.

**Comment by mcmonkey4eva** [comment]
Wtf should it be then

**Comment by AnthonyAMC** [comment]
lol. Yeah, i kinda had the same reaction when it dawned on me that that is an issue. Idk, maybe the grave accent? **`** Which i can't for the life of me make a code block in this comment. I've been trying to think of rarely used characters and that's about the best i can come up with, unless it's a combination of characters.

**Comment by AnthonyAMC** [comment]
Actually, if there was an escape character for `/` it'd be possible to store the escaped value to the db and  .unescaped after we call the values. That way existing scripts would still function and be none the wiser.

**Comment by mcmonkey4eva** [comment]
Yeah, a property escape is probably the best way. I'll see about doing that.
