### ISSUE TITLE
Giving skulls

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#1017]
Here's a little testing script giving a decorated player skull. Doing this works just fine
```
SkullCommand:
  type: world
  speed: 0
  debug: false
  events:
    on newskull command:
    - execute as_player 'give @p skull 1 3 {display:{Name:"Hamburger"},SkullOwner:{Id:"f597e06f-e01a-492d-b63f-c23b9809ce01",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzVlMjc5ODhhNjUzODAxMGVmYzBlMjQ3NTZiYzNlM2VlYTI0ZDc1MzZiMjA5MzJjMTdlMDQwNGU1Y2M1NWYifX19"}]}}}'
```
Now, holding that item you can check the details and it appears to report correctly
```/ex narrate <player.item_in_hand>```
But using the give command throws an [error](http://mcmonkey.org/haste/15264)
```/ex give <player.item_in_hand>```

**Comment by mcmonkey4eva** [comment]
@Morphan1 :(

**Comment by Morphan1** [comment]
It looks like it's just failing the skin lookup....does this error happen every time?

**Comment by AnthonyAMC** [comment]
yerp. I'm also on a bungee server, so idk if the fact that the server is in offline mode makes things go bonkers.

**Comment by Morphan1** [comment]
That shouldn't matter. I remember using dScript pokeballs on the dServer
I'll look into it... Maybe something internal changed

**Comment by AnthonyAMC** [comment]
Oh yeah, you did do that.

**Comment by AnthonyAMC** [comment]
Actually, why don't item script containers have the options to set skull skins natively?

**Comment by AnthonyAMC** [comment]
Eh... here's yet another [example](http://mcmonkey.org/haste/15354).
Can't even adjust the damn thing :/

**Comment by AnthonyAMC** [comment]
Seems to be working now with developmental builds, though some errors still persists... namely an error occurring from too many lookups.

**Comment by Morphan1** [comment]
576c32e
