### ISSUE TITLE
<p@player.type> returns element for offline players

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#1018]
I'm not sure if the same is true for all .type tags, but it certainly is for players.
Using an offline player
```/ex narrate <p@bob.name>```
Returns ```bob```
```/ex narrate <p@bob.type>```
Returns ```element```
Event tacking in ```.as_player``` still returns ```element``` despite the player being valid.

**Comment by mcmonkey4eva** [comment]
Fixed in dev builds.

**Comment by AnthonyAMC** [comment]
All is good here now. Closing.
