### ISSUE TITLE
Item Script - Enhancement Request (durability)

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1021]
I know you can use a mech to alter the durability ('max_durability' tag) of an item after it's created, but would it be possible to add a 'durability:' line straight into the item script?

i.e.
```
DurableIronSword:
  type: item
  debug: false
  material: iron_sword
  display name: <&a>Durable Iron Sword
  durability: 450
  lore:
  - <&f>One Handed                Sword
  - <&f>12-15 Damage
  - <&a><&o>uncommon
```

**Comment by uledrith** [comment]
I know this is an old issue and was closed after 'durability' was added, but would it be possible to add max_durability also on item scripts pleeease?

Thanks! Uledrith

**Comment by mcmonkey4eva** [comment]
@uledrith As I said in other issue: Literally not possible within minecraft.
