### ISSUE TITLE
Empty line in lore

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1023]
When I create an item (script) without a lore, there is an empty line under the item name.
For example:
`teleporter:`
`--type: item`
`--material: compass`
`--display name: <&4>Teleporter`

Please fix this, it just looks ugly:
![2015-04-30_16 51 23](https://cloud.githubusercontent.com/assets/8706734/7415488/8b6194ea-ef59-11e4-82cc-cc9d1b07a7ea.png)
How it should look:
![2015-04-30_16 55 27](https://cloud.githubusercontent.com/assets/8706734/7415521/d68195ce-ef59-11e4-91a1-e9f26ef51b12.png)

**Comment by AnthonyAMC** [comment]
The empty lore line is not really empty. It stores an invisible id so denizen knows it's a custom item.
Take a look at the [item script container](http://mcmonkey.org/denizen/lngs/item%20script) details. You'll see an option for no_id but you'll lose the ability to identify the item by item.scriptname

**Comment by brainscript** [comment]
Denizen could also indentify the item with the name, because in  this case the players aren't able to "fake" the item with an anvil, because of the color code.

Or it could add the id directly behind the name, because when I call the item  "<&4>T" the id in the lore is also only one letter long.

**Comment by mcmonkey4eva** [comment]
The ID in the lore is like 16 or 32 or something letters long. It's just hidden in color codes.

Anyway, people can /destroy/ your ID via an anvil, making it non-viable for us as an official system.

You are, of course, welcome to identify items by display name with `no_id: true` and manual detection code using `if` statements.

**Comment by brainscript** [comment]
Closing this here ...

**Comment by Morphan1** [comment]
As of bc5b1bb (in the latest developmental builds) that blank line is no longer necessary.
