### ISSUE TITLE
BUG: NPC killed with the hurt command respawn instantly

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1026]
Every NPC I kill with the hurt command respawns instantly. No matter what respawn time I set. With or without sentry trait.

**Comment by AnthonyAMC** [comment]
I doubt this is exclusive to the hurt command.

**Comment by mcmonkey4eva** [comment]
What traits does the NPC have? What are these traits set to?

**Comment by Morphan1** [comment]
Is this still an issue?

**Comment by mcmonkey4eva** [comment]
This should be fixed by using the `cause` argument.
