### ISSUE TITLE
'on entity killed' event does NOT fire when determine manual damage is used

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1027]
'on entity killed:' events do NOT fire when determine manual (i.e. determine 100) is used.

Mcmonkey seemed aware of this problem already and provided a work-around by having me manually execute a death event from the 'on entity damages entity:' event using math checking ```<context.final_damage>``` against ```<context.entity.health>```.  This is OK, but has other issues.  I'd much rather use the actual event designed for events like this.

Thanks!!!
Uledrith

```
Damage_World:
  type: world
  debug: false
  events:
  on entity damages entity:
  - if <context.damager.is_player> {
    - determine 100
    }

Death_World:
  type: world
  debug: true
  events:
  on entity killed:
  - announce "test"
 ```

**Comment by Morphan1** [comment]
This will most likely be available after all events are moved over to ScriptEvents. After that we'll have all sorts of fun things like `<context.is_cancelled>` and multiple determines and things that some events already support. :smile_cat:

Until then, I'd stick with the workaround.

**Comment by mcmonkey4eva** [comment]
In addition to being a script event, 'kills' and 'damages' need to be separated into two events firing in order (damages first, then kills) to ensure proper functionality.

**Comment by mcmonkey4eva** [comment]
Fixed in the dev builds.
