### ISSUE TITLE
'On item crafted' behaving unexpectedly

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1028]
'On item crafted' fires when the crafting recipe entered can give a result item, instead of when the result item is actually taken out. Could this event be changed to 'on recipe completed' and could a new event be introduced that actually fires when the result item is taken out of the workbench? This way we can still use 'on recipe completed' to adjust the result item as it would display in the result slot, and also fire other commands when they actually take out the item.

**Comment by Morphan1** [comment]
This event is working as it is meant to. You want `on player clicks in inventory`.

**Comment by BlackCoyote** [comment]
I could swear i was able to see limitations with doing it like that

**Comment by Morphan1** [comment]
@BlackCoyote If somehow you find an issue in manually handling it, just reply and we'll reopen this issue.

**Comment by BlackCoyote** [comment]
reply

**Comment by mcmonkey4eva** [comment]
Limitation: it's ridic complex to handle that manually, you have to do loops and if's and etc.

**Comment by mcmonkey4eva** [comment]
@fortifier42 suggest 'on player crafts <item>` as the alternate form

**Comment by Fortifier42** [comment]
@mcmonkey4eva yes.

Event: on player crafts item, on player crafts <item>
tags:
`<context.quantity>` returns the quantity crafted
`<context.item>` returns the dItem crafted

**Comment by BlackCoyote** [comment]
i suggest "on item crafted" to change functionallity to when the item is actually crafted, instead of when the recipe is completed.

Then introduce on recipe completed for the original way the event worked

**Comment by Fortifier42** [comment]
@BlackCoyote change that event to "on recipe formed"

**Comment by BlackCoyote** [comment]
you change it

**Comment by Fortifier42** [comment]
@BlackCoyote I mean that is what should be done... change that event to that... Not you do it... idiot.

**Comment by BlackCoyote** [comment]
it's called a joke

**Comment by Fortifier42** [comment]
@BlackCoyote It's called this is not helping the issue. This is off topic. shut up son.

**Comment by Morphan1** [comment]
No hateful comments pls

**Comment by Fortifier42** [comment]
Yessir.

**Comment by BlackCoyote** [comment]
That was a joke

**Comment by mcmonkey4eva** [comment]
`on player crafts item` when an item is actually crafted.
`on recipe formed` or `on <item> recipe formeded` when it is made in the workbench, while maintaining back-support for `on item crafted` (undocumented) for a while


That's my vote.

**Comment by Fortifier42** [comment]
Any update on whether this will be added?

**Comment by mcmonkey4eva** [comment]
@Morphan1 pls

**Comment by Morphan1** [comment]
Oh hey, I'll add this to my todo list

**Comment by Devotedworker** [comment]
Very Interested
@Morphan1 Plzzzz

**Comment by BlackCoyote** [comment]
"on player crafts item" fires twice per item crafted, well done, 2/1

**Comment by Morphan1** [comment]
@BlackCoyote with what script exactly? I definitely was not experiencing that.

**Comment by BlackCoyote** [comment]
`on player crafts item:`
`- narrate <context.item> `

narrates the same item twice every time i make one

**Comment by Morphan1** [comment]
I really meant what item script

**Comment by BlackCoyote** [comment]
none, regular stone sword

**Comment by Morphan1** [comment]
Hm. Well... We don't control that one, Spigot does. If you reload scripts a few times does it get worse?

**Comment by BlackCoyote** [comment]
i'll check that a bit later today if it's any help
