### ISSUE TITLE
On item enchanted returning wrong XP amounts due to 1.8 enchanting update

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1029]
The new way of enchanting in 1.8 makes it so you only lose 1-3 xp levels for enchanting, however <context.cost> still returns the original amounts such as 30 levels.

it's possible this is a spigot limit, if so can we leave this issue in here untill spigot applies a fix?

**Comment by Morphan1** [comment]
http://www.spigotmc.org/threads/everything-about-exp-and-the-level-process-is-outdated.37402/
This is definitely a Spigot problem. Nothing on the actual issue tracker, but that thread's been there for months. I might end up posting it on the tracker tonight if nobody beats me to it.

**Comment by Morphan1** [comment]
Is this still an issue?

**Comment by BlackCoyote** [comment]
probably

**Comment by Morphan1** [comment]
@BlackCoyote ...could you check now?
