### ISSUE TITLE
on item repaired lacking in denizen

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1030]
There is no on item repaired event, which could be substituted for sure using on player clicks in inventory, but this wouldn't give us the XP levels used for the action, so could we see an event for this?

**Comment by BlackCoyote** [comment]
update: another motivation to include this is to be able to work with the name changing mechanism that anvils introduce.

**Comment by BlackCoyote** [comment]
Perhaps, just like crafting, this will require 2 seperate events, one for when the result item appears and one for when the result item is taken out

**Comment by Morphan1** [comment]
The reason this does not exist is because Bukkit never added it. We'd have to tap into NMS, which most likely would just be like `<in@anvil_inventory.anvil.required_levels>` or something. I need to see how Anvil internals work.

**Comment by BlackCoyote** [comment]
what about the name string entered in the anvil?

**Comment by Morphan1** [comment]
Also would be an NMSified tag

**Comment by Morphan1** [comment]
Looks like someone actually requested support for this
https://hub.spigotmc.org/jira/browse/SPIGOT-869

**Comment by mcmonkey4eva** [comment]
@Morphan1 I recall you were investigating the NMS option for this - how'd that go?

**Comment by mcmonkey4eva** [comment]
Apparently the Spigot thing was added (per that Spigot jira post)

**Comment by mcmonkey4eva** [comment]
There's no event for this, and I don't know the Spigot issue was marked 'resolved' when its request was entirely unfulfilled. Regardless, I've added the mentioned tags at least, and added a pair of mechanisms as well.
