### ISSUE TITLE
scoreboard tags

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1031]
Could denizen introduce a few scoreboard related tags? Most necessary would be the <sb@scoreboard.exists> tag, as minecraft or spigot itself tends to remove scoreboards at times when it has no linked players, when a script might still be trying to fetch this scoreboard.

**Comment by mcmonkey4eva** [comment]
Who uses `- scoreboard`? The cool kids use `- sidebar` which has tags

**Comment by BlackCoyote** [comment]
OH GEEZ I HAD NO IDEA THANK YOU MACMOKNEY

**Comment by mcmonkey4eva** [comment]
You're welcome :)
