### ISSUE TITLE
Not using the most efficient show_boss_bar method

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1032]
The current method of getting to show the boss bar in denizen currently leaves visible artifacts of a wither entity
http://i.gyazo.com/c8575f40f29e9bb90bbe40bc2e2456ac.png

It's possible to do it without leaving this artifact, meaning there is a more efficient way of displaying the boss bar. I don't know how, and i'm sure you guys don't know either, but maybe we can try and find out how it's done.
http://i.gyazo.com/eb4c3f1469440bb991d46f786fa0e012.png

(both screenshots are on the same client version)

**Comment by Morphan1** [comment]
I can't currently look at the images (school blocks that site I guess :cat:) but it sounds like you're talking about when the wither is below or at 50% health? If so, does whatever server using the second image ever actually go below that?

**Comment by BlackCoyote** [comment]
oh my god you're 100% spot on, good job pounce
