### ISSUE TITLE
Bigger numbers turning into scientific notation and failing IF statements

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1033]
http://mcmonkey.org/paste/15635
as you can see in the debug

the flag holding value 10000099 is turned into 1.9000099E7.
the tag substracting some from this works completely,
but the if statement comparing this to the random number '200' doesn't pass due to the notation having other characters than numbers.

**Comment by mcmonkey4eva** [comment]
Fixed by https://github.com/mcmonkey4eva/Denizen-Core/commit/6a246c56669d5f80ac09360d81dfe7369560b5d5
