### ISSUE TITLE
<w@world.time.full> give null result

### ISSUE THREAD

**Issue by monnierant** [DenizenScript/Denizen-For-Bukkit#1034]
Hi when i try to access to my `<w@world.time.full>` i get an null and an error message 
```
ERROR! Tag <w@Harlan2.time.full> is invalid!
```
I have the same issue on other world. We use multiworld plugin.

but for the `<w@Harlan2.time> `i get an number that seems to be normal
```
/ex narrate <w@Medel.time>
give: 7083
```
But i see the code seems to be okay in dWorld.java line 498
```
// <--[tag]
        // @attribute <w@world.time.full>
        // @returns Duration
        // @description
        // Returns the in-game time of this world.
        // -->
        if (attribute.startsWith("time.full"))
            return new Element(getWorld().getFullTime())
                    .getAttribute(attribute.fulfill(1));
```

**Comment by AnthonyAMC** [comment]
And what happens when you try
```
/ex narrate <player.world.time.full>
```

**Comment by monnierant** [comment]
The same i have also an null object. I have try with the latest build and still the same issue
test on #1575 and #1573

**Comment by monnierant** [comment]
/ex narrate <w@Harlan2.time.period>

For your information it give me the correct answer (night in my test)

**Comment by mcmonkey4eva** [comment]
Fixed in https://github.com/mcmonkey4eva/Denizen/commit/143af57c53a55c9d48d0e6549301df445bcf2806 
```
[09:18:19] * mcmonkey twitches
[09:18:21] <mcmonkey> who writes this shit
```

**Comment by mcmonkey4eva** [comment]
@Morphan1 https://github.com/DenizenScript/Denizen-For-Bukkit/commit/74aa659f92b1f37fc1518fcf5de5a13db2e1ac24#diff-c3933a526cc3ff36567ad2dbbf4e3073R484 is testing so hard

**Comment by monnierant** [comment]
thanks a lot for your help and for the quick answer. You do an amazing job.

**Comment by Morphan1** [comment]
@mcmonkey4eva check the time period. Do you really expect any less from me 17 months ago?
What I'm wondering is how nobody noticed it until today :cat:
