### ISSUE TITLE
item_message mechanism fails to reset

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1037]
Can't really show well efficiently, but it's easily replicated. Adjust the item_message mechanism on your item in hand and spam it a couple of times and it will result in the item keeping the message as it's name

**Comment by mcmonkey4eva** [comment]
@Morphan1

**Comment by BlackCoyote** [comment]
#Morphan1

**Comment by Morphan1** [comment]
Try not to use it in Creative mode. It's a Mojang issue.

**Comment by BlackCoyote** [comment]
does it only occur in creative?

**Comment by Morphan1** [comment]
@BlackCoyote as far as I know. You're welcome to test it, though

**Comment by BlackCoyote** [comment]
If it only happens in creative then i don't even need it fixed ^^

**Comment by BlackCoyote** [comment]
http://i.gyazo.com/1b05a25da0707991e7b1857f04c4f1df.png issue persists in survival ;(

**Comment by Morphan1** [comment]
That's very odd. It doesn't make much sense, seeing as the code only sends packets, it never touches the item on the server.

**Comment by BlackCoyote** [comment]
Perhaps it was a clientside bug only, but droppign it/dragging it and all that did not update the item name so i assumed it was server side. I will try a relog next time it happens

**Comment by BlackCoyote** [comment]
I can't replicate the problem in survival anymore, perhaps the glitched item was still from when i was in creative mode. I'm going to close this untill i can replicate it again
