### ISSUE TITLE
fake_item mechanism suggestion

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1038]
We've had the fake health, fake equipment, fake xp, fake item names, can we now have fake items please? :D

**Comment by Morphan1** [comment]
What do you expect this to do?

**Comment by BlackCoyote** [comment]
- adjust <player> fake_item:i@item  (including item scripts)
or - adjust dInventory.slot fake_item:i@item

would show a fake item on the specified slot in the specified inventory that preferably only exists on the client, or if it has to be, exists on the server (which then it would kind of be a replacement for trying to make an untouchable item in the inventory in dscript which is almost impossible)

if possible a duration would be possible to be added as a 2nd value behind the dItem.
if the player tries to grab the item it would update and dissapear

**Comment by Morphan1** [comment]
What would be the use case of a fake item that can't be used and only you can see?

**Comment by mcmonkey4eva** [comment]
Sounds useful to me.

**Comment by BlackCoyote** [comment]
possibilities could be:
- a flashing example of the recipe in a workbench a player has to complete that doesn't interrupt his progress in the recipe.

Using the hotbar as a temporary GUI without it interrupting the behaviour to the server or obstructing the player too much

**Comment by BlackCoyote** [comment]
Could replace the item_message mechanism by doing
- adjust player.item_in_hand "display_name:beautiful day today" save:item
- adjust player.item_in_hand.slot fake_item:entry[item].result|10s

(though this isn't exactly a benefit, i thought i'd point it out)

**Comment by BlackCoyote** [comment]
The general idea is trying to get the possiblities to make some items clientside only to avoid any potential issues at all when trying to use Items for a more graphical than physical purpose

**Comment by Morphan1** [comment]
I think this would be a command, rather than a mechanism.
`fakeitem [<inventory>] [<#>] [<item>] (duration:<duration>)`
so
`- fakeitem <player.inventory> 4 i@red_wool duration:3s`
would show fake red wool at slot 4 in the player's inventory for 3 seconds

**Comment by mcmonkey4eva** [comment]
I vote `slot:4` just for clarity - beyond that, I like it @Morphan1

**Comment by mcmonkey4eva** [comment]
could make `slot:<#>` optional, and the default is to show at the first open slot, like - give would.

**Comment by AnthonyAMC** [comment]
What happens in the event they have something in that slot and are actively using it? Such as holding a sword and fighting? Would the item be changed only in the hotbar, or in their hand as well?

**Comment by mcmonkey4eva** [comment]
@AnthonyAMC it would change it in their hand because of the way Minecraft calculates that

**Comment by AnthonyAMC** [comment]
Fun times... so would the player then be (un)able to place the block that is in that slot?

**Comment by mcmonkey4eva** [comment]
@AnthonyAMC In theory, if they right click, it should act just like if the real item is the only item involved. EG if you're holding a block before the fakeitem is applied, you'll still place that block.
it will probably also reset the item in your bar when you do that.

**Comment by BlackCoyote** [comment]
make it able to use the quantity property in the dItem beyond normal stack sizes just like unlimit_stack_size goes in the give command please, if that is not already default

**Comment by BlackCoyote** [comment]
I highly agree it being better as a command. can you add a player argument that takes a list input, so you can send the packets to multiple people at once, still only applying to the specified inventory?

**Comment by mcmonkey4eva** [comment]
Or just a list of inventories.
`- fakeitem <server.list_online_players.parse[inventory]> i@stick`

**Comment by BlackCoyote** [comment]
as long as there is full control over who gets the packet, and what inventories the packet recievers will see the item in, seperately

**Comment by mcmonkey4eva** [comment]
Oh I misunderstood your request, you have multiple people opening one inventory? In that case, yeah, a player list. Good idea.

**Comment by mcmonkey4eva** [comment]
@Morphan1 add pls

**Comment by mcmonkey4eva** [comment]
@Morphan1 you going to add?

**Comment by BlackCoyote** [comment]
Where's the inventory argument? it seems to only work for player inventories?

**Comment by Morphan1** [comment]
It works with any inventory the player has open. The inventory argument is actually illogical because if you don't have it open, you won't be able to see it

**Comment by BlackCoyote** [comment]
I was expecting you to be able to specify a location based inventory too, and send the packet to all players with that inventory opened

**Comment by Morphan1** [comment]
@BlackCoyote at that point, it's not even a fake item. It's an item that just doesn't save when the server shuts down and that you can't take, but is otherwise actually known by the server, albeit weirdly. If you wanna do that, use an event with the command

**Comment by BlackCoyote** [comment]
FINE D:<

**Comment by BlackCoyote** [comment]
oh and thanks btw c:
