### ISSUE TITLE
banner modifying

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1039]
Currently there's no way of modifying the data of banners, i don't know how it works, but it'd be nice to adjust the kind of banner that is placed down.

**Comment by KeangDavid** [comment]
This should probably also be considered a bug. Seeing as whenever denizen does anything with banners, it will erase the data on the banner. That means I always have to check for banners before doing anything with player inventories. If they do have a banner, I need to stop the script/event just to have the player git rid of it safely or it will be pretty much deleted.

Not to mention there are a bunch of neat things you'll be able to do with banners. Such as letters that only take1-2 blocks and custom "items" or buttons in GUIs if you know the correct patterns. Like left and right arrows, accept and cancel buttons.

**Comment by mcmonkey4eva** [comment]
Yeah banners are pretty awesome. If @Morphan1 doesn't claim it I might tackle full support this weekend. Somebody remind me to do that.

**Comment by BlackCoyote** [comment]
:)

**Comment by Morphan1** [comment]
Forgot to say, this was added to the dev builds with 84f26ef

**Comment by KeangDavid** [comment]
If you want to start using it right away i made quite a few basic banners as usable items.
http://mcmonkey.org/denizen/repo/entry/39
