### ISSUE TITLE
Denizen does not copy JSON data on books

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1040]
holding a book in my hand that has json data, with click events and all that, and doing give player.item_in_hand  gives me  the book without the click event and other json data

**Comment by mcmonkey4eva** [comment]
I blame bukkit.

**Comment by BlackCoyote** [comment]
Could we see an improvement in JSON handling in denizen in overall, or if it's already functional, could i see some documentation?

**Comment by BlackCoyote** [comment]
could we, on item scripts and book scripts, have a 'JSON:' key that would allow you to put in raw jason (with dodgy symbol escaping if needed) that would be put directly in the item as working json data?

scriptname:
  type: item
  material i@stone_sword
  json: raw json here

**Comment by Morphan1** [comment]
@BlackCoyote JSON is valid YAML so

**Comment by mcmonkey4eva** [comment]
`raw jason`
Someone, somewhere, named Jason, is very confused.

**Comment by BlackCoyote** [comment]
its early and i'm dutch

**Comment by Morphan1** [comment]
Not even sure what to do here. @mcmonkey4eva ?

**Comment by mcmonkey4eva** [comment]
@Morphan1 change the property to be like
`book_json={{{{{{{}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}""""""""""""`
while keeping the old tags and mechanisms available.

Something NMSy to read/edit the books might be needed.

**Comment by mcmonkey4eva** [comment]
This is done now!
https://github.com/DenizenScript/Denizen-For-Bukkit/commit/58383ab1f002ba272053c8dfbaef11ac93e14af6
It, er, was quite simple actually.
