### ISSUE TITLE
name/chatname/tabname/servername mechanisms or commands

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1041]
We currently have a mechanism to change a player's chat nickname, one to change the tab name, and one that does does all of them together, including the nameplate above a player's model (name mechanism) could we have 4 seperate and independent commands/mechanisms that does it's own thing only? Could prefixes and suffixes be used to increase the length of these values?

**Comment by BlackCoyote** [comment]
the dPlayer.name mechanism now only changes the nameplate without affecting the result of the <player.name> tag. woot! thank you morphan! perhaps you guys can rename that mechanism to dPlayer.nameplate?

all what's left now is to use prefixes and suffixes to triple the size of the nameplate!

**Comment by BlackCoyote** [comment]
on a sidenote, dPlayer.name currently also edits a plkayer's tab list name. since there already is a seperate mechanism for that (dPlayer.player_list_name), perhaps if it would be possible you guys could make the dPlayer.name only adjust the nameplate and not the tab list name

**Comment by Morphan1** [comment]
Uh... Is this still... Necessary for any reason?

**Comment by BlackCoyote** [comment]
i believe there is some incorrect stuff in the name mechanism description to what it actually does right now

**Comment by BlackCoyote** [comment]
i believe 'name' only changes their nameplate now?

**Comment by Morphan1** [comment]
Yup, and I just fixed that meta.. I'm gonna go ahead and close this
