### ISSUE TITLE
Animate ARM_SWING Triggers Left-Click when item in hand.

### ISSUE THREAD

**Issue by adw123** [DenizenScript/Denizen-For-Bukkit#1042]
Please see attached code example that demonstrates this issue along with video demonstration:

When a player has an animate command with ARM_SWING in it under an on player right clicks event it appears to trigger an on player left clicks event. I believe it can occur during other click type events but I did not test them all extensively. 

This only occurs under these conditions:

1. The player must have a block or other item in their hand.
2. The player must right-clicks on air. (The video does not mention this but it appears to only happen on air, clicking the ground doesn't trigger, as I thought initially when making the video)

http://youtu.be/GrNj7R3VdE8 

```
ClickBug: 
  type: world 
  speed: 0 
  debug: true  
  events:
    on player left clicks:
    - if <player.is_op>
      {
      - narrate "Left"
      }
    on player right clicks:
    - if <player.is_op>
      {
      - narrate "Right"
      - animate <player> animation:ARM_SWING
      }
```

Thanks.

**Comment by mcmonkey4eva** [comment]
This sounds more like a low level Mojang/Spigot-end issue
