### ISSUE TITLE
String to MD5 Hashing Mechanism/Tag?

### ISSUE THREAD

**Issue by OzOwnz** [DenizenScript/Denizen-For-Bukkit#1044]
I was wondering if it'd interest anyone to add a tag that'd return a MD5 hash when an element is given to it. Some uses may be to store passwords as hashes for security, save flags as MD5 hashes instead to further secure sensitive data, etc.

If this can be done with a procedure script, then this would probably be clutter to add...

**Comment by mcmonkey4eva** [comment]
http://mcmonkey.org/denizen/tags/hash

**Comment by Morphan1** [comment]
@mcmonkey4eva but what about without color codes?

**Comment by mcmonkey4eva** [comment]
@Morphan1 strip them. `.replace[<red.substring[1,1]>]`

**Comment by Morphan1** [comment]
@mcmonkey4eva doesn't it also limit it to 6 though?

**Comment by mcmonkey4eva** [comment]
I don't remember that being a thing 0.o

**Comment by mcmonkey4eva** [comment]
```
Filled tag <el@val[potato].to_itemscript_hash.replace[§]> 
                   with 'c908ac6f27a282e4938'.
```

**Comment by Morphan1** [comment]
@mcmonkey4eva ... I'm thinking of inventories, sorry <.<

**Comment by OzOwnz** [comment]
Shit this is cool :D
