### ISSUE TITLE
Item script uncraftable

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1045]
I can't craft the item shown in the script in the paste below.

http://mcmonkey.org/haste/15842

i had it working before and then it just stopped working.. there's no debug or anything, and i can't figure out why this isn't working pls send halp

**Comment by BlackCoyote** [comment]
after a while i figured out why it wasn't working. i had this other item script as shown in the following link:
http://mcmonkey.org/haste/15843

I was using redstone_dust instead of redstone, this seemed to have stopped the recipe for the other unrelated item to stop working.. i have no idea why

**Comment by BlackCoyote** [comment]
it didn't give an error when loading the scripts or anything.. the recipe for item 1 simply wouldn't work because the recipe of item 2 contained an unexisting item

**Comment by mcmonkey4eva** [comment]
@Morphan1 pls

**Comment by Morphan1** [comment]
@mcmonkey4eva this sounds more like a general scriptcontainer issue doesn't it?
Probably just a try-catch block that needs to be moved

**Comment by mcmonkey4eva** [comment]
@Morphan1 fix pls

**Comment by mcmonkey4eva** [comment]
@Morphan1 pls sir

**Comment by Morphan1** [comment]
@mcmonkey4eva why is this my job? just because the case that was provided happens to be item-related? :confused:

**Comment by mcmonkey4eva** [comment]
@Morphan1 this is very specifically linked to item script crafting... it's likely something missing in the ItemScriptHelper code... code I can't navigate without serious concentration, which you should know well already...

**Comment by mcmonkey4eva** [comment]
@Morphan1 I did look myself... and got confused and lost trying to figure it out

**Comment by Morphan1** [comment]
This miiight be fixed in the latest development build

**Comment by mcmonkey4eva** [comment]
... is... is this fixed?
