### ISSUE TITLE
Define Chat of NPC

### ISSUE THREAD

**Issue by PaulTheCrusher** [DenizenScript/Denizen-For-Bukkit#1047]
One Question
I wand to define the last thing the player said to the NPC in a variable.
How i do that?

like that:

`- define lastsentence "<the tag>"`

thx for answers

**Comment by mcmonkey4eva** [comment]
If you're in a chat trigger,
`<context.message>` gets the message that triggered the chat trigger.
Otherwise, `<player.chat_history>` is the latest message from the player.

**Comment by PaulTheCrusher** [comment]
that worked perfectly. thank you.

i have another question:

I want that the npc accept all anwers

i remember something like that:

              Name:
                  trigger: /*/

but that dont worked

thx for answers

**Comment by Morphan1** [comment]
`trigger: /regex:.*/`
