### ISSUE TITLE
Error when removing NPC on death

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1048]
Denizen Script:
http://pastebin.com/Y5hmMUuP

Error:
http://pastebin.com/eZMCjZ76

**Comment by mcmonkey4eva** [comment]
Change your script to:
http://mcmonkey.org/haste/16023

The most important bit is that you have to `wait` 1 tick before removing the NPC, because deleting an entity mid-event is a pretty poor idea, especially with Citizens.

**Comment by Fortifier42** [comment]
I replaced it with the code you gave me, however I am not sure what you mean by
"# Please replace 'player' with a valid player link."

I still get an error:
[13:05:08] [Server thread/INFO]: [0;35;1m [0;37;1mFilled tag <npc.location> with 
                   'l@246.60511540788576,64.0,43.192822659978724,0.0,149.66881,world'. [m
[13:05:08] [Server thread/INFO]: [0;35;1m [0;37;1mFilled tag 
                   <npc.flag[respawn_location]||l@246.60511540788576,64.0,43.192822659978724,0.0,149.66881,world> 
                   with 
                   'l@246.60511540788576,64.0,43.192822659978724,0.0,149.66881,world'. [m
[13:05:09] [Server thread/INFO]: [0;33;1m+> [dNPC] [0;37;1mUh oh! Denizen has encountered a NPE while trying to 
                   fetch an NPC. Has this NPC been removed? [m
[13:05:09] [Server thread/INFO]: [0;33;1m+> [dNPC] [0;37;1mUh oh! Denizen has encountered a NPE while trying to 
                   fetch an NPC. Has this NPC been removed? [m

**Comment by mcmonkey4eva** [comment]
*Edited your comment for sanity's sake*

I see no errors.

**Comment by Morphan1** [comment]
@Fortifier42 what he means to say is that that "error" is just Denizen seeing that you deleted an NPC and saying something just in case you didn't delete one. in which case that should be reported.

But you did delete an NPC.
So that's not an error.

**Comment by Fortifier42** [comment]
Okay then, that makes a bit more sense.. I just saw the "uh oh" and read the rest and figured it was trying to delete it multiple times or something and spat out the error when It couldnt.
