### ISSUE TITLE
SUGGESTION Make location.add and location.simple work together

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1049]
Atm I can't use something like  `<player.location.simple.add[1,0,10]>` or `<player.location.add[1,0,10].simple>` it just says null

**Comment by mcmonkey4eva** [comment]
```
[03:41:50 INFO]:  Filled tag <p@mcmonkey4eva.location.add[1,0,10].simple> with 
                   '120,68,77,world'. 
```
?

**Comment by GomaTerzu** [comment]
This seemed to be an issue with my spigot build somehow. No problems in the updated version anymore.
