### ISSUE TITLE
schematic command

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1054]
Make the schematic command more server friendly by making it work like modifyblock where it only pastes as many blocks per tick as it can without lagging the server down pls ty

**Comment by GomaTerzu** [comment]
You could take a look at asynchworledit plugins code maybe. Works the same for worldeedit

**Comment by BlackCoyote** [comment]
modifyblock already does it accoridng to the monkey so i'm sure he'll just reuse that code on the schematic command
