### ISSUE TITLE
A way to manage Citizen's waypoints (/npc path)

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#1055]
Would we nice to allow a way to control the waypoints, for example the script could be:
`- path add <location>`

The reason I ask for this is because of the 'walk' command doesn't seem to work along with the plugin 'Sentry'. When the NPC has targets, it ignores them while walking with that command.

Either add the way to manage npc paths or fix the problem with Sentry targets with 'walk'.

**Comment by mcmonkey4eva** [comment]
Why not use dSentry?

**Comment by Mwthorn** [comment]
I have tried using that but I don't know how I can make the NPCs target another NPC.
I have tried using /dsentry target flagged:SideA
And then mark the other NPC with the same flag-name.

**Comment by Mwthorn** [comment]
After tesing with both Sentry and DSentry, I found a solution to the problem I had.
It requires the NPCs to be given "time" in order to make them shot while walking. This includes only recent created NPCs. Basically I spawn the npc, then wait 10-15 seconds to give them the 'walk' command.
I close this issue since I don't need this suggestion/enchancement anymore.
