### ISSUE TITLE
Armor Stands

### ISSUE THREAD

**Issue by Morphan1** [DenizenScript/Denizen-For-Bukkit#1057]
We have absolutely nothing related to armor stands! :smile_cat: Fix pls!

**Comment by KeangDavid** [comment]
Shhhh im tierd, some idea of where to start.
Can't remember how to put tags in Github comments.


- entity.equipment
  - equipment:head|chest|legs|feet|HAND

- entity.angle[part] || entity.angle.part
  - pose:[part]|[angle]
  - head, body, left_arm, right_arm, left_leg, right_leg

- entity.size
  - size:small|normal

- entity.visible
  - tag returns list li@true|false|true
  - visible:[boolean]|(arms[boolean])|(baseplate[boolean])

- entity.has_gravity
  - has_gravity:[boolean]

**Comment by KeangDavid** [comment]
Maybe take into account that both hands will be able to hold things in 1.9 as well.

**Comment by mcmonkey4eva** [comment]
@Morphan1 how's this going? Is anything still needed?

**Comment by KeangDavid** [comment]
Has size been done?

**Comment by Devotedworker** [comment]
I've noted the following issue with Armor Stands

- They can not be selected with the NPC selection wand ( Stick )
- They can not be right clicked, as in any right click will not register
- They can only be selected by using their ID
- They can not be equiped using the Equip menu
- They can not be "removed" without despawning them first, and they give this error
http://puu.sh/mf7f3/3551bb7e13.png
- They can not be turned invisible, through any method or command

**Comment by mcmonkey4eva** [comment]
Should report all of that except the last one to Citizens actually.

**Comment by Fortifier42** [comment]
I have added the visible property to entities for armorstands.
`<e@entity.visible>`
and mechanism `- adjust e@entity visible:true/false`

can be used in an entity `e@entity[visible=false/true]`

**Comment by Morphan1** [comment]
Is this done yet?

**Comment by Fortifier42** [comment]
@Morphan1 will check

**Comment by Fortifier42** [comment]
This has been completed. awaiting mcmacklemore's PR acceptance.

**Comment by Devotedworker** [comment]
@mcmonkey I think everything has been added now

**Comment by Morphan1** [comment]
Do we have things for markers?

**Comment by Devotedworker** [comment]
Not that I'm aware. I don't think Denizen has any support or Mecs for it

**Comment by Fortifier42** [comment]
@Morphan1 what the heck are markers?

**Comment by mcmonkey4eva** [comment]
@Fortifier42 random boolean on armor stands that makes it... act weird. Messes with hitbox and such. Check minecraft wiki yo

**Comment by Fortifier42** [comment]
@mcmonkey4eva we still doing markers?

**Comment by mcmonkey4eva** [comment]
Oh we got that :D
