### ISSUE TITLE
Can't pass event EntityDamageEvent.

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Denizen-For-Bukkit#1059]
No scripts involving damage events work. Throwing the following error.
Log: http://mcmonkey.org/paste/16459

**Comment by mcmonkey4eva** [comment]
Update to the new latest dev build, that was a temporary error from the way our new coder updated the event - I patched it quickly, but forgot to build >.>

**Comment by KeangDavid** [comment]
I just tried build 242 and it still doesn't appear to be passing the event. Although now I don't get any information besides the console receiving the narrate text.

**Comment by mcmonkey4eva** [comment]
Is this still an issue on latest dev builds?
