### ISSUE TITLE
renoting cuboid issue

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1063]
If you have a cuboid, and then renote the cuboid to a different (in my tests nearly identical) cuboid, and if you have determine cancelled on the on player exits notable cuboid event (with a check for this cuboid only) the player will trigger the exit event anywhere inside the cuboid, untill he is brought out of the cuboid manually. once he is placed back in it works as expected.

tested by doing:

```
on player exits notable cuboid:
- if <player.location.cuboids.get[1]> == cu@test determine cancelled
```

1:
`/ex note cu@<player.location.add[2,2,2]>|<player.location.add[-2,-2,-2]> as:test`

everything works as expected, the player can move around freely within the cuboid, but gets teleported back when he hits a boundary.

2:
`/ex note cu@<player.location.add[3,3,3]>|<player.location.add[-3,-3,-3]> as:test`

the player will be unable to move entirely, not even rotate their screen, untill the cuboid or script is removed to let the player out of the cuboid, or some bypass allows him out of the cuboid. Once step 2 is repeated from there on, it works fine.

**Comment by BlackCoyote** [comment]
idk how to fix the tags in the commands pls fix som1 pls i is lonly

**Comment by mcmonkey4eva** [comment]
Yes, yes that will happen. The cuboid is gone; it is left; the player is no longer inside it...

**Comment by BlackCoyote** [comment]
so does the new cuboid with the same notable name that should work the same to the event in my script not count as a valid one?

**Comment by mcmonkey4eva** [comment]
It counts as a different cuboid. If you want it to count as the same cuboid, adjust the existing one, don't renote it.

**Comment by BlackCoyote** [comment]
according to my research those mechanisms are either deprecated or were never fully implemented!

**Comment by mcmonkey4eva** [comment]
"according to **my** research" ascuse you sir

**Comment by BlackCoyote** [comment]
whatever shall we do???

**Comment by BlackCoyote** [comment]
is there anything possible to fix this?

**Comment by Morphan1** [comment]
@mcmonkey4eva could make those mechs actually do something

**Comment by Morphan1** [comment]
@mcmonkey4eva will this ever happen

**Comment by mcmonkey4eva** [comment]
@Morphan1 why don't you do it :O ?

**Comment by Morphan1** [comment]
@mcmonkey4eva I'm not even sure what this is asking for or how to accomplish said thing

**Comment by mcmonkey4eva** [comment]
@Morphan1 reading am hard.
Make the dCuboid mechanisms work.
