### ISSUE TITLE
teleport not working in event

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1064]
I'm doing `- teleport <context.entity> <player.flag[guild_entry_origin]||<player.bed_spawn>>`

Everything works according to the debug except for that the context entity doesn't get used by the teleport command, despite the tag being filled in successfully in the debug

`08:25:28 [INFO]  Queue 'GUILDWORLD_SECURITY_DiscussionsSpecialtyBeverage'  
                   Executing: TELEPORT "<context.entity>"  
                   "<player.flag[guild_entry_origin]||<player.bed_spawn>>"  
08:25:28 [INFO] +- Executing dCommand: TELEPORT/p@TheBlackCoyote ---------+  
08:25:28 [INFO]  Filled tag <context.entity> with  
                   'e@f15ddcc5-e309-4325-8dce-0b5e9b5435bf'.  
08:25:28 [INFO]  Filled tag  
                   <player.flag[guild_entry_origin]||<player.bed_spawn>> with  
                   'l@223.713442668724,21.0,1330.7127618479747,88.16488,-211.72752,world'.  
08:25:28 [INFO] +> Executing 'TELEPORT':  
                   location='l@223.713442668724,21.0,1330.7127618479747,88.16488,-211.72752,world'  
                    entities='[]'  `

**Comment by BlackCoyote** [comment]
(i'm certain the pig is still there, in fact i'm looking at it right now as i keep trying)

**Comment by Talamar1** [comment]
Which event is this inside of?

**Comment by BlackCoyote** [comment]
on player damages entity

**Comment by mcmonkey4eva** [comment]
How many times must we tell people to not edit anything but the event itself inside an event?

**Comment by BlackCoyote** [comment]
that comment is entirely useless to solving my issue

**Comment by mcmonkey4eva** [comment]
ffs.
`- wait 1t` before teleporting.

**Comment by BlackCoyote** [comment]
result remains identical

**Comment by BlackCoyote** [comment]
http://mcmonkey.org/paste/16648#359 waiting
http://mcmonkey.org/paste/16648#412 teleporting

**Comment by mcmonkey4eva** [comment]
Can you post a full sample script (MCVE)?

**Comment by Morphan1** [comment]
@BlackCoyote is this still an issue?
