### ISSUE TITLE
Entity attributes mechanism suggestion

### ISSUE THREAD

**Issue by lmorgh** [DenizenScript/Denizen-For-Bukkit#1065]
It would be nice to have other entity mechanisms available directly in entity scripts, for example:

ExampleZombie:
  type: entity
  entity_type: zombie  
  Knockback_Resistance: 2
  Attack_Damage: 10

Where last 2 attributes aren't supported by Denizen (also other attributes of course, if possible). It would be much easier than catching the events in a world script like we have to do now.

**Comment by mcmonkey4eva** [comment]
This would require we do the exact same thing you currently do, except do it internal to Denizen.

At least, until an Attributes API is available in Bukkit/Sponge.

**Comment by mcmonkey4eva** [comment]
Bit delayed, but this is now available :D in build DEV-958+
Use `!mech entitytag.attributes` in the Denizen discord for details.
