### ISSUE TITLE
Remove npc support in "on <player/npc> closes inventory"

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Denizen-For-Bukkit#1067]
npc doesn't appear to be supported in the bukkit code:
```
public class InventoryCloseEvent extends InventoryEvent {
    private static final HandlerList handlers = new HandlerList();

    public InventoryCloseEvent(InventoryView transaction) {
        super(transaction);
    }

    public final HumanEntity getPlayer() {
        return this.transaction.getPlayer();
    }

    public HandlerList getHandlers() {
        return handlers;
    }

    public static HandlerList getHandlerList() {
        return handlers;
    }
}

```

**Comment by mcmonkey4eva** [comment]
@Morphan1 what up with dat event?

**Comment by Morphan1** [comment]
I'm confused as to what this is for

**Comment by Talamar1** [comment]
In my new src/main/java/net/aufdemrand/denizen/events/player/PlayerClosesInvScriptEvent.java, I was carrying over support for npc, but when I tried to get an npc object, there didn't seem to be a way to do it.  Everything was player based.  So I was making the point that if bukkit doesn't support NPC for this event, why are we trying to do it? (it also java barfs at times trying to locate the npc object).

**Comment by Morphan1** [comment]
Meh... Remove it. I don't think anyone uses it or has any reason to use it anyway

**Comment by Talamar1** [comment]
the only use case I can see is for scripts like dRestaurant or the shops where you want npcs to go around and open and close things.  By allowing them to do that, you don't have to do double animations (the npc using armswing/open and the chest/cabinet opening and closing).  You would also be able to trap when they did it and use that as a trigger to perform an action.

**Comment by mcmonkey4eva** [comment]
@Talamar1 Has it been removed?

**Comment by Talamar1** [comment]
It has been removed, it is a player only event now.
