### ISSUE TITLE
suggestion: script priority

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1068]
As any other denizen user, after a while our scripts start to have duplicate events across various scripts. sometimes the same event can be listed even 10 times in my code on the server. Now, if one of those scripts should cancel the event under certain conditions, the other scripts fired by the same event in another script container would have to do the exact same condition checks to ensure the script only runs when the event is allowed. One solution would be for me to have a single script that lists all events and injects the code that would normally be fired in a different container by the same event, that way it gets added to the current queue so the same condition checks still apply to it.

Another idea that came to my mind is to have a priority argument for every world script container, that would sort the scripts and run them from the event based in order. that way you can precisely decide which scripts run before which.
it would look as following:

world_script_name:
  type: world
  priority: 1
  events:
    on player damages player:
     - narrate "This will show up before any other player damages player fired scripts."

Using priority 1, assuming there are no other scripts with a priority equal or less than 1, this queue will be the first to fire.

In addition to this, a world event could have the addition on the determine command that would look as following:

world_script_name:
  type: world
  priority: 1
  events:
    on player damages player:
     - if `<context.location.is_within[cu@safezone]>` {
       - narrate "`<&c>`You can't do that here!"
       - determine cancelled globally
       }

now this example would cancel the event as it already would, but it would also make all the queues fired from the same event but with a lower priority not run anymore. this way, all the other scripts don't have to do the same check or have to be injected into a single queue.

I see this being a bit more advanced but very powerful addition to denizen that would avoid making us either put the same condition checks in multiple queues or put everything in a single queue.

Would this be possible?

**Comment by Pigman168** [comment]
Great idea!

**Comment by mcmonkey4eva** [comment]
I love how much effort you put into this.

Also, you're a buffoon.

We have this already <3

`on player damages player priority:3:`

**Comment by BlackCoyote** [comment]
What about the global determine cancelled?

**Comment by mcmonkey4eva** [comment]
Wut. Oh. A way to block other scripts from running... maybe. Seems a bit dickish to not let them run tho. Even Bukkit lets eventhandler's run when the event itself is cancelled.

Why not just `- if !<context.cancelled> { YOUR_CODE_HERE }`?

**Comment by BlackCoyote** [comment]
does that exist already?

**Comment by mcmonkey4eva** [comment]
Yes.

**Comment by Pigman168** [comment]
My comment stands. Great idea!
