### ISSUE TITLE
Tag request: inventory.full, inventory.can_fit, inventory.empty

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Denizen-For-Bukkit#1071]
Original idea / inspiration thanks to @Fortifier42

`<player.inventory.full>` whether the player has at least one item in every slot.
`<player.inventory.can_fit[stick]>` whether the player's inventory has room for a stick item to be added.
`<player.inventory.can_fit[stick].qty[32]>` whether the player's inventory has room for 32 stick items to be added.
`<player.inventory.empty>` whether the player's inventory is entirely devoid of items.

**Comment by mcmonkey4eva** [comment]
Oh also `<player.inventory.list_contents.include_item[stick].qty[32]>` adds 32 sticks to the list, in the most appropriate place (adding to stack sizes, before adding a new stack)

**Comment by mcmonkey4eva** [comment]
@Morphan1 ?

**Comment by Fortifier42** [comment]
`<in@inventory.can_fit>` -> [https://github.com/Fortifier42/Denizen/commit/d7ce795152198ab170b4dd2581d27b08406fddb1]

**Comment by mcmonkey4eva** [comment]
Actually... full and empty could easily be replicated using a bit of list_contents magic. So... yeah. Can_fit is all that's needed, and Fort added it :D

**Comment by Fortifier42** [comment]
I was uh, just adding is_empty

**Comment by mcmonkey4eva** [comment]
Doesn't hurt, but I'm considering this issue solved whenever your code is pulled.

**Comment by Fortifier42** [comment]
It is in my PR.... Also, did you want me to put the code anywhere in particular? Bottom/top/alphabetical?

**Comment by Fortifier42** [comment]
`<in@inventory.is_empty>` -> https://github.com/Fortifier42/Denizen/commit/6d987299868d11fb3abc5761b49fb5a08cefdfb2

**Comment by Fortifier42** [comment]
`<in@inventory.is_full>` -> https://github.com/Fortifier42/Denizen/commit/ff8afa59cd6a667dd33308cc5566f0144af79b3d
