### ISSUE TITLE
command addition request - follow 

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1072]
add ability to use an entity without a - the follow command to make an entity without AI follow another entity (Liked a guided missile)

**Comment by KeangDavid** [comment]
How about push then? Just put that in a loop.

**Comment by mcmonkey4eva** [comment]
Appears to be done.

**Comment by Fortifier42** [comment]
Ah this is when I was an idiot. Basically, I wanted the ability to make non-ai entities follow another entity, e.g. an arrow follow a player, so it is /guaranteed/ to hit

**Comment by mcmonkey4eva** [comment]
Olol. Then yeah push.
