### ISSUE TITLE
event on player respawns determine failure

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1074]
Event "on player respawns" determine failure

Script: http://mcmonkey.org/haste/16890
Debug: http://mcmonkey.org/paste/16888

**Comment by Talamar1** [comment]
paste code url as well

**Comment by Morphan1** [comment]
This was determined to be an issue with EssentialsSpawn
:heart:

**Comment by Fortifier42** [comment]
Updated with script

**Comment by Talamar1** [comment]
Tags in tag?

**Comment by Fortifier42** [comment]
@Talamar1 It works - Essentials spawn was conflicting
