### ISSUE TITLE
world.spawn_location does not accept decimal values

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1075]
Attemping to set the world spawn to the center of the block - rather than the corner

[Script](http://mcmonkey.org/haste/16916)
[Debug](http://mcmonkey.org/paste/16914)

**Comment by Morphan1** [comment]
This is more of a Spigot issue I think. We can't do a whole lot about it, it's best to just use the respawn event and whatnot
