### ISSUE TITLE
JSON in Narrate/Chat Feature

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1076]
It would be good to be able to embed json into a narrate command - like done with the /tellraw command (Add tooltips to text and add click events)

This would allow for a clickable menu in chat - with the click event being able to execute a server or denizen command (zap around an interact script simply by clicking for example)

Currently we need to use execute as_server to do this and default json click event runs the command as the player who clicked it - which isnt the most efficient - and doesn't allow for easy integration of denizen commands into the json data 

With Denizen JSON could add an option to execute the command when the player clicks the item in chat, as the server, or the player.

```
/tellraw @p ["",{"text":"Test","clickEvent":{"action":"run_command","value":"Hello"},"hoverEvent":{"action":"show_text","value":{"text":"Clicking this makes you say Hello"}}}]
```

**Comment by mcmonkey4eva** [comment]
We have plans to support this in a significantly less stupid way that frippin JSON support.

**Comment by mcmonkey4eva** [comment]
Honestly MCL is so solid we're realistically just going to use that as the official supported option for D1 stuff at the moment https://github.com/AnthonyAMC/Public-Denizen-Scripts/blob/master/MessageConstructors.yml
