### ISSUE TITLE
group command - set

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1077]
Add the "set" option to the group command

Syntax: `- group [add/remove/set] [<group>] (<world>)`

**Comment by mcmonkey4eva** [comment]
@Talamar1 this could be good practice for you, it's relatively straight forward

**Comment by Talamar1** [comment]
So... what does set do?  Example?

**Comment by mcmonkey4eva** [comment]
Remove all existing groups, then add the new one.

**Comment by Talamar1** [comment]
That's what I was thinking, just wanted confirmation.

**Comment by Talamar1** [comment]
Done
https://github.com/Talamar1/Denizen/commit/3171b2bb71e797066d87efa322b5692d1f5d1395
