### ISSUE TITLE
Unable to check for Denizen book

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1080]
Using denizen book script container and `<player.inventory.contains[i@bookname]>` does not work, as inventory does not contain that item, it contains i@written_book{blahblah]

**Comment by mcmonkey4eva** [comment]
Wut.

**Comment by mcmonkey4eva** [comment]
@Morphan1 ?

**Comment by Fortifier42** [comment]
Fixed in previous release.
