### ISSUE TITLE
Event on entity enters vehicle and on entity exits vehicle does not fire for npcs

### ISSUE THREAD

**Issue by Cromis** [DenizenScript/Denizen-For-Bukkit#1081]
The events on entity enters vehicle and on entity exits vehicle do not fire when a player mounts/dismounts a npc.

How to reproduce:
create a world script with the events on entity enters vehicle and on entity exits vehicle
create a npc and make it controllable
mount the npc
dismount the npc
neither of the events will fire

**Comment by mcmonkey4eva** [comment]
Is it a vehicle-type NPC?

**Comment by Cromis** [comment]
no i am using mob types

**Comment by Talamar1** [comment]
version/build of spigot/cit/denizen?  That code hasn't been modified lately.

**Comment by Cromis** [comment]
i have Craftbukkit version git-spigot-f928e7a-994b2aa mc 1.8.7 api version 1.8.7-r0.1-snapshot
citizens version 2.0.16-snapshot build 1244
denizen version 0.9.6-snapshot build 1584 core version 1.10(build unknown)

**Comment by mcmonkey4eva** [comment]
Mojang/Bukkit code refuses to fire the internal vehicle event for NPCs that aren't of vehicle-type. Nothing we can do about it ... yet. Sorry.

**Comment by Cromis** [comment]
Darn guess ill mark the player with a flag the player upon mounting and use on sneak/on quit to check for the flag and find any other possible events that will happen for dismounting. Thanks for the speedy response.
