### ISSUE TITLE
on player right clicks with <item> determine failure

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1082]
Trying to stop a food item from being eaten before the animation plays.
When a player eats a food item, the animation plays, particles appear and the player is slowed down while "eating" however, I wish to cancel the eating event before the animation begins.

Tried the on player consumes event however It still plays the animation and only cancels when the player actually "Eats" the item.

Denizen version 0.9.6-SNAPSHOT (build 269)

    on player right clicks with pumpkin_pie:
        - determine cancelled

**Comment by mcmonkey4eva** [comment]
Unfortunately, this is calculated clientside, you can't stop it quickly enough.

**Comment by Fortifier42** [comment]
Okay, thanks @mcmonkey4eva
