### ISSUE TITLE
event options to trigger contexts

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Denizen-For-Bukkit#1084]
Some events like "on portal created" have some contexts that can take a while to produce (list of all blocks).  Should we add something like:
on portal created by enderdragon list:true:

Where that switch would turn on <context.list>, otherwise, we don't spend the cycles computing it.

We could use forms like context:dlist instead, where we only return the contexts requested...

context:entity|location|item

**Comment by mcmonkey4eva** [comment]
Morph or someone suggested earlier a better idea that what's suggested here:

only calculate context when someone actually calls it.

EG,

~ no context calculated ~
script says `<context.blocks>`
~ context.blocks calculates and returns ~
~ Now only context.blocks exists within the system ~
Script says `<context.blocks>`
~ context.blocks immediately returns the same value it did previously (Possibly: unless a determine command modified it?) ~

**Comment by Talamar1** [comment]
so the event reads the script container looking for context requests and fills them as needed.  How much overhead does that add building the context list and filling it versus my way (scripter tells you directly) vs just filling it?  That is probably pretty arbitrary given different events return different amounts of context.  Maybe we should offer a build of denizen that reports statistics of what and how many times certain events are called (could be expanded to tags, mech, etc).

**Comment by mcmonkey4eva** [comment]
This should probably be a Core request. Repost there if you still want it done.
