### ISSUE TITLE
inventory item definitions fail to parse tags

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1086]
hey morphan

i'm looking at you morphanone

  definitions:
    fancy_item: `<proc[fancy_item]context.[bananas]>`

it just doesn't work

neither does

slots:
- [`<proc[fancy_item]context.[bananas]>`] [] [] [] [] [] [] [] []

it just doesn't do the procedure

i tried using flags

it didn't do it either

morphanone

could you please make it do that

please

thanks
amen

**Comment by BlackCoyote** [comment]
also when going from any script to an inventory script (to an item script) to a procedure script it loses the player linked! :(

**Comment by mcmonkey4eva** [comment]
@Morphan1 ?

**Comment by mcmonkey4eva** [comment]
@Morphan1 ??!!??!

**Comment by Morphan1** [comment]
@mcmonkey4eva I don't know what's happening here. The tags he specified aren't even valid. But besides that, the code for tags definitely exists.

**Comment by mcmonkey4eva** [comment]
Lmao he has a stray `.` on his tags. Nice job @BlackCoyote 

Feel free to comment below if you can replicate this with valid input, and we'll reopen.

**Comment by BlackCoyote** [comment]
i've spent my time finding a workaround for this so theres no point in me reopening this, but besides this example i did try it in different tags including flags.. once again, no point for me to reopen, but if i encounter it again i'll let you know

**Comment by Morphan1** [comment]
@BlackCoyote for what it's worth, this issue should be resolved and your workarounds are now nil
