### ISSUE TITLE
"on structure grows from bonemeal"

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Denizen-For-Bukkit#1087]
"on bonemeal" doesn't work.  
event.isFromBonemeal() always returns false, looks like a bukkit issue.

**Comment by mcmonkey4eva** [comment]
`looks like a bukkit issue` then why report it here?

**Comment by Talamar1** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-1018

**Comment by mcmonkey4eva** [comment]
@Talamar1 looks like a fix was sent in spigot-side. Working on latest?

**Comment by Talamar1** [comment]
Kinda, it works but "on structure grows" and "on block grows" both fire, not sure if there is enough difference in the materials to separate the two events, unless we build a list of growing things and compare against that.
