### ISSUE TITLE
Player break block face context.

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Denizen-For-Bukkit#1088]
I don't know how possible it is but could <context.face> or <context.side> be added to get the side that a player broke the block on. Possibly returning 1-6 or north, south, east, west, bottom, top.

**Comment by Talamar1** [comment]
You should be able to do this by comparing the block location and the player location
<l@location.direction[<location>]>
Returns the compass direction between two locations. 
If no second location is specified, returns the direction of the location. 
Example returns include "north", "southwest", ...

**Comment by KeangDavid** [comment]
That does NOT tell you what side was broken. What you are suggesting tells you what side they MIGHT have broken with accuracy as low as 50%.

**Comment by mcmonkey4eva** [comment]
`<player.eye_location.precise_impact_normal>`, a tag I just added, will tell you the answer :)
