### ISSUE TITLE
add "item" value to tryItem/runWithCheck

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Denizen-For-Bukkit#1089]
To make this consistent with the entityMatches and runInCheck, shouldn't this also include the basic 
if (comparedto.equals("item")) return true;
at the very top, since we need to handle the case of, scripter doesn't care what the item is?

**Comment by mcmonkey4eva** [comment]
Yup. Add it yo.

**Comment by Talamar1** [comment]
Done
