### ISSUE TITLE
Duplicate chat and command

### ISSUE THREAD

**Issue by davebergmans** [DenizenScript/Denizen-For-Bukkit#1092]
After installing Denizen, the mcmmo adminchat will be duplicated, also some of the commands will be duplicated (executed two times)

**Comment by Talamar1** [comment]
Do you have any scripts written in Denizen or is this immediately after the install?  If you remove Denizen, does it stop?

**Comment by davebergmans** [comment]
This happend immediately after the install. We unloaded the plugin (plugman) this didn't solve the problem, we didnt have the oporunity to restart the server just yet.
The server btw is Spigot 1.8.7-R0.1-SNAPSHOT

**Comment by davebergmans** [comment]
Weve just removed denizen and restarted the server, this solved the problem.

**Comment by mcmonkey4eva** [comment]
@Morphan1 submitted a fix for this I believe, we're working on waking our build server to get that out.

**Comment by davebergmans** [comment]
Thats great! Does this mean its included in the latest version, or still to come?

**Comment by mcmonkey4eva** [comment]
It'll be available, ideally, in a few minutes. As soon as our build server finishes building.

**Comment by mcmonkey4eva** [comment]
This build includes it, probably: http://ci.mineconomy.org/job/Denizen_Developmental/290/

**Comment by davebergmans** [comment]
Perfect thank you! Let me try it out and I will report back to you :smile:!
Thanks again for the quick support

**Comment by mcmonkey4eva** [comment]
Did you try it?

**Comment by davebergmans** [comment]
We weren't able to try it out just yet.

**Comment by mcmonkey4eva** [comment]
.. How 'bout now?

**Comment by Morphan1** [comment]
@davebergmans any update on this?
