### ISSUE TITLE
on entity death: <context.entity>

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1096]
<context.entity> returns e@entitytype not the actual entity itself, this makes it impossible to check the entity for flags or other data on death. 
Denizen version 0.9.7-SNAPSHOT (build 293)

    on entity death:
      - narrate <context.entity> targets:<context.damager>

**Comment by mcmonkey4eva** [comment]
It still works somewhat, you can read, say, `<context.entity.location>`... it's just that the entity no longer exists, so identifying a UUID would /fail/ to provide that information.

It should probably return a full description info actually.

**Comment by Fortifier42** [comment]
Is there a way to check the entity for a flag then? Determine cancelled? Then check and remove?

Trying to see if the entity has been flagged for a certain death method.

**Comment by mcmonkey4eva** [comment]
Death is post-facto... the entity is gone, as are it's flags.

Used the `killed` event to react to flag details.


I mean we could workaround it by giving you an extra tick to read the flags or something... maybe...

**Comment by Fortifier42** [comment]
Right.. Will look at a different method then I guess?

**Comment by mcmonkey4eva** [comment]
... Yup! :D
