### ISSUE TITLE
send_to not working

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1097]
I have a bungeecord network and I want my players to get sent to the `lobby` server when they right click a slimeball on a game server.

My world script event:
`on player right clicks with SLIME_BALL:`
`----- adjust <player> send_to:server@lobby`

When they right click the slimeball, an error message appears in the console:
`+> Executing 'ADJUST':`
`object='p@jUsT-aRAn-d0mU-UIDb-lablablablab'`
`mechanism='send_to'  mechanism_value='server@lobby'`
`ERROR! Invalid dServer specified.`

I've got Denizen installed on both the game server and the proxy server. Also Depenizen on the client and Depenizen-For-Bungee on the proxy.

Where's my problem? :question: :confused:

**Comment by Morphan1** [comment]
Did you set up each side of Depenizen's config.yml correctly? It goes by the name of the server in there. Also, you must start the proxy before the Bukkit server. If it fails, there should be errors in your console on startup and possibly when you attempt to use it

**Comment by mcmonkey4eva** [comment]
@brainscript ?

**Comment by brainscript** [comment]
@mcmonkey4eva Don't you understand my question?

**Comment by Morphan1** [comment]
@brainscript don't you understand MY question?

**Comment by brainscript** [comment]
Yes, I did, :smile:, but it doesn't work. I'll look for some output in the proxy console. Wait a moment ... :watch:

**Comment by brainscript** [comment]
There's nothing ...

**Comment by Morphan1** [comment]
@brainscript actually, I might be wrong about which name the mech uses.. have you tried using the name of the server as it is in the bungee config?

**Comment by brainscript** [comment]
It is the same name. Or do you mean without the `server@` in front?

**Comment by mcmonkey4eva** [comment]
@Morphan1 ?

Also why is this in Denizen and not Depenizen?

**Comment by Morphan1** [comment]
@brainscript are you 100% sure you started the proxy server, THEN started the Bukkit server, with 100% valid configurations

**Comment by brainscript** [comment]
Why isn't Denizen just doing this like ChestCommands? https://github.com/filoghost/ChestCommands/blob/fb129c417360a922eeb525d04dca14c202ab6150/ChestCommands/src/com/gmail/filoghost/chestcommands/bridge/bungee/BungeeCordUtils.java

**Comment by Morphan1** [comment]
@brainscript try the latest Depenizen build
http://ci.citizensnpcs.co/job/Depenizen/lastSuccessfulBuild/

**Comment by brainscript** [comment]
Does it now work with the name in the BungeeCord config or do I have to configure it in the Depenizen config.

**Comment by Morphan1** [comment]
The problem with automatically using the BungeeCord's server name is that there isn't really any way of servers knowing their own name, and as far as I'm aware, the only way you would be able to get it correctly is if you had a player online and knew which server they were on (so that BungeeCord tracks which name they're on)
