### ISSUE TITLE
On entity killed doesn't fire when entity dies from "natural" causes

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1098]
an entity dying by fire, or lava, or even fall damage doesn't cause the on entity killed event to fire.. 
This leaved a gap for metadata to be retrievable between on entity death and on entity killed.... :(
Please fix <3

**Comment by mcmonkey4eva** [comment]
That... doesn't make much sense, unless @Talamar1 broke something and made it require a damager or something.

**Comment by Fortifier42** [comment]
On entity killed only does when it is killed by another entity

**Comment by mcmonkey4eva** [comment]
Try the latest dev build, I possibly fixed it maybe.

**Comment by Fortifier42** [comment]
Okay will when I surface

**Comment by mcmonkey4eva** [comment]
Did you test it?

**Comment by Fortifier42** [comment]
@mcmonkey4eva I did yesterday, told you in IRC it works.. :heart:
