### ISSUE TITLE
Denizen causing disconnect.spam

### ISSUE THREAD

**Issue by Elvi81** [DenizenScript/Denizen-For-Bukkit#1099]
[20:52:00] [Server thread/INFO]: Elvi81 lost connection: disconnect.spam
[20:52:00] [Server thread/INFO]: Elvi81 left the game.
[20:52:00] [Server thread/WARN]: handleDisconnection() called twice

I found out by chanse that this was caused by denizen while looking for an answer, does not seem to be the first time it's done something like this.
It can happen randomly but for 1 of my users it happend just by chatting.
Made a test server, same plugins just different builds of denizen, happens on 1588 and 1589 but as of yet not on 1587.
Run on spigot build 507.

**Comment by mcmonkey4eva** [comment]
We fixed that bug though.

**Comment by mcmonkey4eva** [comment]
@Elvi81 does the latest dev build fix the issue?

**Comment by Elvi81** [comment]
Seems to work, havn't been able to get it to kick me as of yet, do note that this does not affect op's just normal players.
