### ISSUE TITLE
- determine cancelled for some events resets player yaw

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1100]
on player right clicks entity:
        - determine cancelled

Resets pitch/yaw of the player, sometimes making them face a complete opposite direction..
Current work-around is to save the player's location, then teleport them back to it after the determine cancelled..

Video: https://youtu.be/c1rKEIY0dwQ

**Comment by mcmonkey4eva** [comment]
What the... this has got to be a Spigot issue. Right, @Morphan1 ?

**Comment by mcmonkey4eva** [comment]
I'm going to go ahead and say this is a spigot issue, not Denizen.
