### ISSUE TITLE
Shoot & Push flips out a players view when repeated.

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1102]
Script: http://mcmonkey.org/haste/18003
Debug: http://mcmonkey.org/paste/18002
Video Evidence: http://youtu.be/svKF0E-GGF0
Denizen version 0.9.7-SNAPSHOT (build 298)

**Comment by Fortifier42** [comment]
Shoot command is fixed!
Push is not!

**Comment by Morphan1** [comment]
Is this still... a thing?

**Comment by Fortifier42** [comment]
I don't think it was ever fixed for push

**Comment by mcmonkey4eva** [comment]
I dunno what you expect to happen if you spam push, if not "view glitching"...

**Comment by Fortifier42** [comment]
Idk, it didn't occur with shoot, tis all.
