### ISSUE TITLE
Issues with the animate command

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1103]
When i use  `/ex animate <player> sit`

I get the following error http://mcmonkey.org/paste/18005
I also can't use lshift to dismount

When I use `/ex animate <player> stop_sitting`

It teleports me over 8000 blocks up in the air

It would also be nice to use a location for animate sit because otherwise you would always fly in the air

**Comment by Morphan1** [comment]
Is this still a problem?

**Comment by GomaTerzu** [comment]
Hey Morphan, thanks for asking, almost forgot about it.

Tested it now: The error is gone and when i make stop_sitting the player can move again.

I don't know if this is an issue but I like the way it works: When I make players sit, they can't stand up on their own with shift. So the sitting animation forces them to sit on the spot.
