### ISSUE TITLE
Speed argument in walk command not working

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1104]
`09:22:44 [INFO] +- Executing dCommand: WALK ---------+  
09:22:44 [INFO]  Filled tag <def[target].above> with  
                   'l@197.5,7.0,292.5,world'.  
09:22:44 [INFO] +> Executing 'WALK': location='l@197.5,7.0,292.5,world'   
                   speed='0.2'  auto_range='true'  stop='false'   
                   entities='[n@24]'`

results in ]http://i.gyazo.com/ae35953d662f48092f7961e5838c89b4.gif

(disclaimer: fooage was not altered or sped up)

**Comment by Morphan1** [comment]
What exactly isn't working about that?

**Comment by BlackCoyote** [comment]
0.2 was expected to be a rather slow amount for the speed argument, that should make them go slower, the GIF shows the npc moving at a high speed. Using different amounts of speed inputs, such as 0.1, 0.01 and 1.0 don't affect the speed of which the NPC walks with.

**Comment by BlackCoyote** [comment]
2 Very different speed arguments shown in practice:

0.1:
http://i.gyazo.com/a1e3c9b6f54c20d9d16232002af3dffd.gif

1.0:
http://i.gyazo.com/5e1004f45e383a1d331353c3af8e06f4.gif

**Comment by BlackCoyote** [comment]
Bonus:
0.01:
http://i.gyazo.com/56b73c404237e91d92ca276e9ff96a90.gif

**Comment by hsmallbone** [comment]
Fixed. Speed wasn't being changed properly mid-path.

**Comment by Morphan1** [comment]
I believe this was fixed in C2
