### ISSUE TITLE
allow location input for entity.can_see[entity]

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1105]
Currently we have entity.can_see[entity], but i'm looking for something that can work for location,s if an entity can see a location, (or even if a location 'can see' a location)

**Comment by Fortifier42** [comment]
Spigot limitation. Currently only can check if entity can see another entity.
See [HERE](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html#hasLineOfSight%28org.bukkit.entity.Entity%29) (Spigot, JavaDocs.)

**Comment by mcmonkey4eva** [comment]
That doesn't mean we can't add it, it just means... we need to do slightly more work to add it.

**Comment by Morphan1** [comment]
Added in the above commit
`For example, <player.eye_location.line_of_sight[l@CanYouSeeMe]>`
