### ISSUE TITLE
suggestion: instance support

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1107]
Don't we all hate it if you have a quest, or dungeon in your custom minecraft server, but you're limited to what you can do to it because it has to be reused for other people, and you have to take the possibility into account that two or more players might be trying it at once?

If you really wanted to, you could load up a new world for every player for these kinds of locations, and do massive amounts of work to keep these areas secure, fully operational, and constantly updated with new content you push out. not to mention the stress it might cause on your server to load up so many different worlds!

Why not have denizen do this work internally?

Allow me to suggest the Instance command:

`- instance create <schematic>/<world> as:<name> real_blocks:true/false real_entities true/false (duration:<duration>)`
Create an instanced area from a schematic or world folder, with a specified name, and a duration. Real_entities and real_blocks would toggle whether the blocks and entities would exist server side, or clientside only.
`- instance save <name> (schematic:<schematic>) (world:<worldname>)`
Save the instance as a schematic or world. (in case you allow changes to your instance and want to save them to load them up again later)
`- instance unload <name>`
Unloads (or completely dismisses) the specified instance.

Doing this in dScript is unimaginable to me, and perhaps it might be equally challenging in java, but maybe, if you're brave enough, this could be attempted?

Thanks for the time.

**Comment by Pigman168** [comment]
Worst idea I've ever seen on the internet. Absolutely useless; only for lazy noobs. Never implement this ever. I definitely don't need this for my server. Especially for dungeoneering. I'd rather use interact scripts to make it.

**Comment by Pigman168** [comment]
(To clarify: ^ Sarcasm ^)

**Comment by Xenmai** [comment]
I need this. It would be very useful, if not totally required, for implementing dungeons and any kind of closed group events. If it's possible to make... please :3

**Comment by mcmonkey4eva** [comment]
Why the hell can't you use an instancing plugin why do we have to do everything in Denizen what is the benefit

**Comment by BlackCoyote** [comment]
"why do we have to do everything in denizen what is the benefit"     rrreeeeeaaaaalllyyyy? i guess you should take out cuboids cause worldguard can do that, take out modifyblock cause worldedit can do that, take out entity support since mythicmobs can do that, etc etc

**Comment by BlackCoyote** [comment]
The benefits are the endless possibilities of integrated utilities around the instances, just like with any other addition to denizen

**Comment by Xenmai** [comment]
From my point of view, it's easier being able to do everything or as much as possible with a single plugin than having one plugin for each thing you want to make. Also... we want to make Denizen the king of the plugins, so then we can say "If Denizen can't do that, it's not possible".

**Comment by BlackCoyote** [comment]
And if you'd argue that it can already be done through denizen using elaborate scripts, I suppose you're right, but you're speaking about the top scripters then, like what, 5% of denizen users would figure out a way to fully do that safely, and still not as good as it could be if handled internally, whilst if the time would be spent on making it an internal feature, Everyone is going to be able to use it to the fullest, creating nearly unimaginable content for their server, making their players wonder how they did it, when the only answer needed is 'denizen'.

**Comment by brainscript** [comment]
+1 :smirk_cat:

**Comment by THEPS** [comment]
Let it be known this is also a thing I am interested in.

**Comment by Devotedworker** [comment]
Very Interested in this Feature.
