### ISSUE TITLE
Internal Exception?

### ISSUE THREAD

**Issue by teateatea** [DenizenScript/Denizen-For-Bukkit#1108]
Hello!

I have a Sentry NPC running a task that starts with 
```
- while <npc.is_spawned||false> {
```
When the NPC gets killed, the console gives me "ERROR! Internal exception was thrown!", and "[dNPC] Uh oh! Denizen has encountered a NPE while trying to fetch an NPC. Has this NPC been removed?" There's also a lot of [SEVERE] gray text, so something has obviously gone wrong.

I've tried queue q@serverflag[queue.id] clear-ing on death, which runs successfully but does not resolve the issue.
I've also tried adding "if npc.is_spawned||false {" before every command, and running the task instantly. I was hoping that no commands would ever been given to a dead NPC, but the errors still occur.
Yes, I've updated everything. Denizen Dev build 301, Citizens build 1248, latest version of Spigot.
I have citizens, denizen, permissionsEx, sentry and vault on a local server.

Here's a debug recording:
http://mcmonkey.org/paste/18289

This is one task, that throws a ton of gray text. It walks the NPC towards crops, or has them wander, while it's spawned.
http://mcmonkey.org/haste/18294

This task also throws the same errors, but only about one paragraph on death rather than several pages. It just plays particles near the NPC.
http://mcmonkey.org/haste/18295

What is the best way to handle this?

Cheers, Tea

**Comment by teateatea** [comment]
Actually, I think this has to do with the walk command specifically. It only happens when the NPC is removed while it is walking.

I took a look at dSentry to compare to see how mcmonkey was creating NPC behaviours, and the exact same error is thrown when the dSentry is removed when walking.

The NPCs I'm trying to make spend 90% of their time walking, which explains why I was constantly throwing errors. I think I'm a little out of my league here, is there any way for me to work around this?

**Comment by mcmonkey4eva** [comment]
This was fixed.
