### ISSUE TITLE
Mobs without AI don't move when using the walk command

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1109]
http://mcmonkey.org/paste/18297#27

as seen in the debug the input was correct, however the entitiy remains motionless.

**Comment by KeangDavid** [comment]
dev-build:301, I just tested this and they do walk. As far as I can tell they must be touching the ground. Making bunnies unable to walk, because they hop.

**Comment by BlackCoyote** [comment]
I'm on 302

**Comment by KeangDavid** [comment]
Corrected, either way that command has worked from 274 on my scripts. Do you have more information, debug, or trouble shooting you can do?

**Comment by BlackCoyote** [comment]
What version of citizens are you on?

**Comment by KeangDavid** [comment]
Well it would seam it is a bug with NPCs than, because I don't have Citizens.

**Comment by BlackCoyote** [comment]
It's not with NPC's but it could still be citizens related perhaps, i am still using it on regular non-npc AI-less zombies

**Comment by BlackCoyote** [comment]
The debug is there, you can see i filled in everytihng correctly, here's me doing it in practice: http://i.gyazo.com/f11e7e392b4dd9511a38d2a4273e350f.gif

**Comment by KeangDavid** [comment]
Updated to build 1248, and it stopped working. Probably a Citizen problem than.

**Comment by Morphan1** [comment]
Oh,,, this is fixed in the latest dev build
