### ISSUE TITLE
<cuboid@cuboid.get_blocks[torch]>

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1112]
It returns `li@` an empty list..
Cannot actually find any torches using this.. at all.. works with all other materials I tested.. Just torches suck ass.

tested with `/ex narrate <region@region,world.cuboid.get_blocks[m@torch/torch]>` (not both at the same time, but tested both with and without object notation!

**Comment by mcmonkey4eva** [comment]
I bet datavalues are to blame. It's always datavalues' fault.

**Comment by Fortifier42** [comment]
Then fix em honey :heart:

**Comment by mcmonkey4eva** [comment]
Handled probably.
