### ISSUE TITLE
right click event doesn't handle map area

### ISSUE THREAD

**Issue by Croat** [DenizenScript/Denizen-For-Bukkit#1119]
Hello.

I tried using "on player right clicks at `<entity>` in `<area>`" with "on player right clicks at villager in my_map". I doesn't work but "on player right clicks at villager" works. Also, "on player breaks block in my_map" works, so I am assuming the first one is a bug.

As you can see, right clicking a villager with the first event mentioned doesn't launch anything: http://mcmonkey.org/paste/18686

**Comment by Croat** [comment]
mine_map_restriction:
  type: world
  events:
    on player right clicks at villager in mine_map:
    - narrate "one"
    on player right clicks at villager:
    - narrate "two"
   on player takes sponge in mine_map:
    - narrate "three"

"two" and "three" will work, "one" will not.

**Comment by Fortifier42** [comment]
For the time being, use an if statement to check it

    on player right clicks at villager:
      - if <player.world.name> == mine_map {
        - narrate "Stuff"
      }

**Comment by Talamar1** [comment]
Fortifier, your check is against a world, his is against a notable cuboid I assume.  "in area" check doesnt support location or world currently.

The right player clicks us only checking cuboids, it hasn't been converted to the new event format.

**Comment by Talamar1** [comment]
@Morphan1 was supposed to do those...

**Comment by Fortifier42** [comment]
@Talamar1 
According to mcmonkey <area> supports all types. (World, Notable, Cuboid, Ellipsoid or location).

**Comment by Talamar1** [comment]
World should be supported in new script events, apparently he added that at some point.  Location is not supported in general "in <area>" format, it is used for specific events using a separate procedure.

**Comment by mcmonkey4eva** [comment]
Two things, first, at the unrelated discussion above: world is supported in theory, but the click events haven't been updated yet.

Second, you're using the wrong event. Please read the freakin' `triggers` line before implementing an event.

http://mcmonkey.org/denizen/evts/clicks

You're trying to use the event

`Triggers	when a player right clicks at an entity (Similar to right clicks entity, but for armor stands). `

With... not a freakin' armor stand. Just next on the list is

`Triggers	when a player right clicks on an entity. `

Perhaps you should try that? :)
