### ISSUE TITLE
Add support for unbreakable items

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Denizen-For-Bukkit#1120]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/ItemMeta.Spigot.html
This meta is supported via spigot, not sure how to implement this so I'm posting it here.

**Comment by mcmonkey4eva** [comment]
Not part of Bukkit; cannot implement.

**Comment by Talamar1** [comment]
Can we copy what they did in Spigot and do it in Denizen?

**Comment by mcmonkey4eva** [comment]
Maybe. Bug @Morphan1

**Comment by Talamar1** [comment]
*bugs @Morphan1  *
