### ISSUE TITLE
Denizen items disappearing from inventory (and other weird itemstack behavior)

### ISSUE THREAD

**Issue by blablubbabc** [DenizenScript/Denizen-For-Bukkit#1121]
As already pointed out in this ticket: #1114 

I originally noticed this while spam click all kinds of mouse buttons on itemstacks of denizen created items, but I think I was able to reliable reproduce this now by doing the following:
- Be in survival mode (creative does not seem to have this problem, at least I can't currently reliable reproduce it).
- Start with a stack of multiple denizen created items (though by more spam clicking and dragging an itemstack with only 1 item can disappear as well sometimes).
- Somehow split this item stack over multiple (2 is enough) inventory slots, for example by dragging or splitting of the item.
- Then pick up one itemstack of those denizen items onto the cursor and move with the mouse above another slot with these items.
- Left-click and hold left click and slightly move the mouse while keeping it over the slot (similar to how dragging is started).
- Release the left mouse button: The items in the slot will very likely disappear.

The items also won't show up again after a fresh relog or server restart.

I also noticed other weird itemstack behavior, like itemstacks on the cursor sometimes not dropping a single item but the whole stack from the cursor when right clicking or dragging over a single empty slot, or itemstacks which were combined to one stack and now lays in one inventory slot suddenly splitting again into the previously separated stacks when trying to pick up this combined itemstack from the slot.
However I cannot reliable reproduce these 2-3 issue right now. Just noticed this a bunch of times while testing.

**Comment by Morphan1** [comment]
What other plugins are you using?

**Comment by blablubbabc** [comment]
@Morphan1 You are right, I think I tracked it down: This might be an incompatibility with the plugin Magic version 1.1 (http://dev.bukkit.org/bukkit-plugins/magic/).

**Comment by schmiddel89** [comment]
Unfortunately I am not using this plugin.. and got the same problems... And the newest denizen dev do not fix it... ^^

**Comment by Morphan1** [comment]
@schmiddel89 I can't reproduce this at all. Are you sure the items aren't just in places you wouldn't expect? Such as back in a stack again or something? Spread out? Have you tried combining any stacks and seeing if it was the same amount you started with?

This just doesn't seem like anything Denizen could be doing, although I've been wrong before about that

**Comment by blablubbabc** [comment]
Maybe you could add a feature for disabling the item-lore-hiding-feature? So one could check if the issues are there even when this is disabled. Also, in case there are incompatibiltities with other plugins, this would allow for a temporary and easy workaround for those issues.
And it could make debugging of other issues easier (if you don't have to expect that this is interfering in some unknown way).

**Comment by Morphan1** [comment]
Is this still a problem?
