### ISSUE TITLE
Particle quantity not working

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1125]
The `quantity` option of the `playeffect` command doesn't effect the count of the particles.
`- playeffect <player.location> effect:FLAME quantity:100 targets:<player>` returns **ONE** single particle.

I'm using Denizen build `1589` and Spigot build `6d0ae89-a03743b`.

**Comment by mcmonkey4eva** [comment]
The default offset is `0.5` I wouldn't be shocked if it /looked/ like one particle. Try setting something like `offset:2` and see how that effects it.

**Comment by brainscript** [comment]
That's not the problem! It also doesn't work with higher offset values.

**Comment by mcmonkey4eva** [comment]
You're running the latest dev build, right?

**Comment by brainscript** [comment]
Build `1589` when I type `/denizen version`.

**Comment by Fortifier42** [comment]
This is fixed in the latest **developmental** build.

http://ci.mineconomy.org/job/Denizen_Developmental/lastSuccessfulBuild/

**Comment by mcmonkey4eva** [comment]
You're several releases behind, and that's a release build, not a dev build.

The latest dev build is this: http://ci.mineconomy.org/job/Denizen_Developmental/lastSuccessfulBuild/

**Comment by brainscript** [comment]
This version doesn't work. Do I have to run it with the latest Spigot version?

**Comment by brainscript** [comment]
For example the `on player joins` event doesn't work.

**Comment by mcmonkey4eva** [comment]
Yeah you need latest Spigot.

**Comment by brainscript** [comment]
It works now! Thanks! :smile_cat:
