### ISSUE TITLE
on block falls cancellation causes block to disappear

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1126]
Denizen version: Dev build 339

can be worked around by refreshing the chunk, however would not be efficient in large numbers...

script:

```
Falling Block:
  type: world
  events:
    on block falls:
      - announce "Cancelled"
      - determine cancelled
```

Video of it in action:
https://www.dropbox.com/s/z6qkm3yzd3kiphm/2015-08-02-1606-33.flv?dl=0

**Comment by mcmonkey4eva** [comment]
0.o bukkit flaw - we'd have to workaround it somehow.

**Comment by mcmonkey4eva** [comment]
Perhaps a quick showfake of the correct block to all in range would work better?

**Comment by Fortifier42** [comment]
The problem I see, is doing that on a large scale - e.g. a mound or something similar collapsing all at once, since falling blocks fall in a domino effect, it would be very intense.

**Comment by Morphan1** [comment]
That's kinda weird, I remember "on sand physics" etc working just fine for that

**Comment by Morphan1** [comment]
Is this still a problem?
