### ISSUE TITLE
improvement. new arg for push and shoot cmds

### ISSUE THREAD

**Issue by calico-kid** [DenizenScript/Denizen-For-Bukkit#1127]
it would be nice to have the push and shoot cmds to have the script arg capable of carrying over definitions. something that would be very handy in some situations.

**Comment by mcmonkey4eva** [comment]
Eh... why not flag relevant objects?

**Comment by calico-kid** [comment]
it would be more uniform with the run CMD to do a def carryover... i could use flags but that would also mean deleting flags and having a def carryover would be handy in some cases
:D

**Comment by Fortifier42** [comment]
Initial commit in place. Awaiting **Mr SiR MaCmOnKaY** to check it.

**Comment by Fortifier42** [comment]
@mcmonkey4eva Wasn't this added?

**Comment by mcmonkey4eva** [comment]
Yup https://github.com/DenizenScript/Denizen-For-Bukkit/commit/dac4f17dd8aa63889356b339c82a5d968f6034d5
