### ISSUE TITLE
Player specific tags not parsing in items, for inventory scripts.

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1128]
Script: http://mcmonkey.org/haste/18930

Tag parses with `give` command, however not in the inventory script.

Inside inventory: http://puu.sh/jnknG/f3251fdca9.jpg
With the give command: http://puu.sh/jnkFk/7a1a5196a7.jpg

**Comment by Fortifier42** [comment]
@Morphan1 fix pls <3

**Comment by Morphan1** [comment]
This age-long issue should be fixed in the latest development builds

**Comment by Fortifier42** [comment]
Two new problems:
   One:
     Script: http://mcmonkey.org/haste/18940
     Debug: http://mcmonkey.org/paste/18939 
   Two:
     Script: http://mcmonkey.org/haste/18937
     Debug: http://mcmonkey.org/paste/18938

**Comment by BlackCoyote** [comment]
this is like a duplicate of my issue post

**Comment by mcmonkey4eva** [comment]
Yup.

**Comment by BlackCoyote** [comment]
closed against my will ;(

**Comment by mcmonkey4eva** [comment]
`i've spent my time finding a workaround for this so theres no point in me reopening this,`
- you

**Comment by BlackCoyote** [comment]
goverment forced me

**Comment by Fortifier42** [comment]
Well you see @BlackCoyote, Morphan implemented a 'fix' for this today, however in the process, broke it even further.

**Comment by BlackCoyote** [comment]
GOOD JOB MORPHAN

**Comment by Fortifier42** [comment]
So in the process of allowing use of player tags in the Inventory, he broke item scripts in the inventory

**Comment by Morphan1** [comment]
Would've been nice to open another issue instead of making me think this was actually related to that at all

**Comment by Fortifier42** [comment]
Well, it came about because of the fix you implemented so one can assume!
