### ISSUE TITLE
suggestion: cuboid full outline

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1129]
Right now we have a get_outline tag for cuboids which return the corners of a cuboid and the lines connecting them. Could we have a similar tag that gets every single block on the outline of the cuboid?

**Comment by mcmonkey4eva** [comment]
... do you know what an outline is :o

**Comment by BlackCoyote** [comment]
IT NOT BOUT ENGLISH IT BOUT MAKING HAPPEN IT

**Comment by BlackCoyote** [comment]
cuboid.get_shell or somethin' ya feel
