### ISSUE TITLE
on player changes sign determine bug

### ISSUE THREAD

**Issue by mawej1** [DenizenScript/Denizen-For-Bukkit#1131]
When I place first sign with this code, 1st line changes to [Bounty]. After that I place a blank sign (or with anything else), and it also gets replaced by [Bounty]. Using latest versions.

        on player changes sign: 
        - if <c.new.get[1]> == [Bounty] { 
            - determine <blue>[Bounty] 
        }

**Comment by Morphan1** [comment]
Interesting, I had this happen before but was sure I was just going insane :cat: I'll look into it

**Comment by Morphan1** [comment]
Fixed in ed08e55
It was exactly what I thought it would be :crying_cat_face: 
Should be in the next development build, whenever that is
