### ISSUE TITLE
Sheep aren't detected as entities

### ISSUE THREAD

**Issue by mawej1** [DenizenScript/Denizen-For-Bukkit#1133]
Every time when I kill entity with this script running, I get output - except sheep.

    on player kills entity: 
    - narrate "You've killed <c.entity.name>"

**Comment by Talamar1** [comment]
/denizen debug -r
kill sheep
/denizen submit
send us url to link, or just ask us in the IRC room you are sitting in right now...

**Comment by Morphan1** [comment]
I can confirm. Debug was blank when I did it though

**Comment by Talamar1** [comment]
Fix? https://github.com/Talamar1/Denizen/commit/eda21759580923d855253dca80b2697732a86642

**Comment by mawej1** [comment]
Fixed, thanks
