### ISSUE TITLE
wait does not work when injected from a task script

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1135]
The queue doesn't wait when using ' - wait' in a while loop... pls fix :heart:

**Comment by Morphan1** [comment]
Um... What? In what build exactly? I use this all the time

**Comment by Morphan1** [comment]
Also, script/debug? Something useful that doesn't make me just assume this is invalid?

**Comment by Fortifier42** [comment]
When injecting a task script the wait does not do anything.
