### ISSUE TITLE
Essentials Sudo + Denizen = Instant Crash

### ISSUE THREAD

**Issue by Log1x** [DenizenScript/Denizen-For-Bukkit#1136]
Crash report here.

Using c: in various other plugins within' chat causes Denizen to crash Spigot instantly.

Plugins specifically causing this bug would be Essentials' /sudo command. When doing /sudo PLAYER c:test -- (c: is an "alias" to make them talk in normal chat instead of executing a command), the server will stop responding immediately.

[Error Log](http://pastie.org/pastes/10349352/text?key=hxjonnpwtiyttx9upzr6g) 
[Video of Crash](http://log1x.com/files/2015-08-13_16-15-09_KrzV9.mp4)

How to reproduce this bug:
1) Install Essentials
2) Install Denizen
3) Do "/sudo PLAYER c:Test!"
4) Watch your server go bye bye.

Any fix for this would be appreciated. :)

Thanks!

**EDIT:** Thought I'd mention I tried setting Triggers > Chat > Enabled to false as well as Use asynchronous event to false located under Events. The crashing persists.

Another oddity would be that Denizen's ProximityTrigger seems to use a good amount of resources despite me having Proximity disabled in my config, but this may be better left to another Issue report. I just found it odd for Denizen to be in my top 5 most resource heavy plugins out of 73 and I only have a single NPC that does a single player command on right click (and it hasn't even been interacted with since the server has started).

![Screenshot](http://log1x.com/screenshots/2015-08-13_16-59-19_wpj21.png)

**Comment by Morphan1** [comment]
Update to latest developmental build, please
http://ci.mineconomy.org/job/Denizen_Developmental/lastSuccessfulBuild/

**Comment by Log1x** [comment]
Gah. Worked. Thanks!

Sorry about that. I'm new to Denizen so I had just downloaded it a few weeks ago. Didn't think a whole lot happened with the source code since then.

**Comment by mcmonkey4eva** [comment]
Bear in mind, we're still in beta - things like proximity trigger handling and chat handling are still being developed, and will be better and better with each passing day.
