### ISSUE TITLE
Optimize PlayerInteractEvent

### ISSUE THREAD

**Issue by Log1x** [DenizenScript/Denizen-For-Bukkit#1137]
Hi.

Updated to the latest Dev build and it fixed the resource usage of ProximityTrigger as well as the Essentials Sudo crash bug when making players type in chat. 

Thanks for that! 

But along has come the PlayerInteractEvent which is about 5-10x more intensive than ProximityTrigger was a few builds ago.

![Screenshot](http://log1x.com/screenshots/2015-08-13_20-37-34_FqEn3.png)

As you can see in the screenshot, this is with no players interacting with any Denizen-running NPC's since server start (in fact, there are no players in the same world as an NPC)

Any optimizations that could be made to help with Denizen's footprint would be greatly appreciated! I feel like it should be substantially lower resource-wise than being the number 1 highest resource usage plugin out of 73 with only a single NPC in hub world that runs a single player command on right click.

Thank you very much! -- and my apologies in advanced if this is already a known 'issue'.

**Comment by mcmonkey4eva** [comment]
Weeeee're working on it.

**Comment by Log1x** [comment]
![Heart](http://i.imgur.com/oacdGMH.png)

**Comment by Talamar1** [comment]
Just for clarification, that event, PlayerInteractsEvents fires when players do things with nearly anything, not just npcs.  A player stepping on something, clicking something, etc.  This is server wide, not world based.

**Comment by Talamar1** [comment]
I would request a list of the world events you have in Denizen scripts to see what you are doing that is triggering those requests.

**Comment by mcmonkey4eva** [comment]
This should be cleaned very soon, we have @Talamar1 converting the event to our new system. Just need to get his PR cleaned up and confirmed.
