### ISSUE TITLE
on player picks up problem

### ISSUE THREAD

**Issue by mawej1** [DenizenScript/Denizen-For-Bukkit#1139]
When I pickup 1 wool, it clears my inventory. When I pickup more than one wool (a stack), it does not.

         on player picks up white_wool:
        - inventory clear d:<player.inventory>

**Comment by Fortifier42** [comment]
The issue have, is that the event doesn't seem to ignore the quantity of the item being picked up

**Comment by Talamar1** [comment]
it compares 1 item of the clicked item to the item in the event.  white_wool is not a valid item.

**Comment by mawej1** [comment]
@Talamar1 ok, so how should I clear all of the items? Also, if I do /ex give i@white_wool it gives me white wool

**Comment by Talamar1** [comment]
white_wool is an alias for wool, try using just wool.

**Comment by Fortifier42** [comment]
@Talamar wool refers to wool of no data value, white_wool is specific, similarly to red_wool

**Comment by mawej1** [comment]
@Talamar1  If using just wool, it doesn't work completely - even no output in console. But that doesn't answer my question, how to remove all items from the inventory, regardless of quantity immediately after picking up.

**Comment by mawej1** [comment]
Also, if I add wait 0.1, it removes the whole stack

**Comment by mcmonkey4eva** [comment]
uh... yeah use `- wait 1t` probably. You shouldn't edit the inventory in an inventory event directly.

**Comment by Fortifier42** [comment]
Just tested this - has been fixed. :smile:

Issue can be closed!
