### ISSUE TITLE
Denizen auto parsing tags hardcoded scripts.

### ISSUE THREAD

**Issue by ChemicalDatas** [DenizenScript/Denizen-For-Bukkit#1141]
Denizen no longer auto parses tags from hardcoded yaml_keys within the script. Is there a reason that this has changed? Its not exactly an unsafe source. Just as safe as the source you got the script from.

**Comment by Fortifier42** [comment]
please elaborate?

**Comment by mcmonkey4eva** [comment]
This was changed months ago - it's stupid to enforce tag parsing when it can be optional.

Just throw a `<parse: >` around it.

**Comment by ChemicalDatas** [comment]
The behavior of yaml_key tags used to auto parse. I guess its stupid now because its optional.

**Comment by mcmonkey4eva** [comment]
YEah, sorry about ... changing that, usually we go for legacy support but this was just too horrible to leave untouched.
