### ISSUE TITLE
on player animates ARM_SWING: fail

### ISSUE THREAD

**Issue by ChemicalDatas** [DenizenScript/Denizen-For-Bukkit#1142]
The event for on player animates ARM_SWING: Isn't activating when the player animates their arms.
The event on player animates: works.

**Comment by ChemicalDatas** [comment]
The event for "on player right clicks entity:" is seeming to fail as well. 
"on player right clicks at entity" seems to work, but only if they actually click on the entity, and not if its beyond reach.

**Comment by mcmonkey4eva** [comment]
What entity is being clicked?

**Comment by mcmonkey4eva** [comment]
ARM_SWING/etc. bug fixed - @Talamar1 broked it :(

**Comment by Talamar1** [comment]
"when a player right clicks at an entity (Similar to right clicks entity, but for armor stands). "
Are you using the right event?

**Comment by ChemicalDatas** [comment]
The issue has been resolved.
