### ISSUE TITLE
555 years

### ISSUE THREAD

**Issue by mawej1** [DenizenScript/Denizen-For-Bukkit#1145]
Doing /ex narrate <p@mawej1.last_played> displays this: http://mcmonkey.org/paste/19738 . Doesn't matter if I try it on offline/online players.

**Comment by Pigman168** [comment]
Same here: http://mcmonkey.org/paste/19739

**Comment by Morphan1** [comment]
`<server.current_time_millis.sub[<player.last_played.in_milliseconds>].div[1000].as_duration.formatted>`

**Comment by Talamar1** [comment]
last_played returns a date stamp, not time passed.  Use what Morphan1 said or <util.date.time.duration.sub[<player.plast_played>].formatted>
