### ISSUE TITLE
Failure to fire 'on <item> crafted' event

### ISSUE THREAD

**Issue by THEPS** [DenizenScript/Denizen-For-Bukkit#1147]
The event will work correctly, provided the item contextual item is preceded by a 'i@'. However, if only the name of the item is present, the event will not fire

**Comment by mcmonkey4eva** [comment]
Is this still an issue in the latest dev release?

**Comment by Fortifier42** [comment]
No. http://mcmonkey.org/paste/22008

**Comment by mcmonkey4eva** [comment]
Wonderful!
