### ISSUE TITLE
Add/Change - The 'Sit' system could use ArmorStands instead of Arrows

### ISSUE THREAD

**Issue by Blue0Dwarf** [DenizenScript/Denizen-For-Bukkit#1150]
ArmorStands are magnificent things. They can be invisible, unhittable(using the Marker tag, mind you this will change where entities sit while mounting it to near the feet instead of on the head), and perhaps most importantly they can sit or float anywhere, entirely still, never despawning.

Relevant NBT tags for the stands to make them pretty much uninteractable+invincible:
{Marker:1,Invisible:1,Invulnerable:1,NoGravity:1,DisabledSlots:2039583}
Could even use the CustomName tag to easily define each armorstand based on the NPC's name/ID that is sitting in it (if that would be useful in any way, I don't know...)

The current arrow system is far from reliable. ArmorStands are rock solid and awesome.
Screenshots of myself using an ArmorStand to sit on: http://imgur.com/a/tk47d

**Comment by brainscript** [comment]
@Blue0Dwarf But the armorstand has a bigger hitbox and cancels block-placing.

**Comment by Blue0Dwarf** [comment]
The block placing seems like an absolute non-issue to me given the fact that the NPC itself will cancel block placing. That's already a flaw with the current system. You just need to teleport your NPC to what they're meant to be sitting on. They only stop block placing where the base would be (if the Marker flag is set), and that is right where the NPC would be sitting anyway.

An armorstand with the Marker attribute pretty well has no hitbox... I'm not entirely convinced it DOES have a hitbox, I certainly can't seem to hit them. It'll stop blocks being placed in the block that its base occupies, but I'm not seeing it have any sort of "Hitbox blocking interaction" issues.

**Comment by brainscript** [comment]
@Blue0Dwarf Maybe you're right ... :smile::smiley:

**Comment by sajphon** [comment]
it makes me wonder, how is this not implemented yet O_o Extremely better solution than arrows (affected by gravity so the citizens are not able to be suspended in mid air sitting (meditating - levitating))

**Comment by mcmonkey4eva** [comment]
That. Is an excellent question. >.>

This is actually the current system for `/ex animate <npc> animation:sit`
But not for `/npc sit`
0.o

Hopefully someone'll remember to make it work for both sometime soon >.>

**Comment by mcmonkey4eva** [comment]
this uses Citizens sit animation, which uses armor stands
