### ISSUE TITLE
Projectile event missing snowballs

### ISSUE THREAD

**Issue by ChemicalDatas** [DenizenScript/Denizen-For-Bukkit#1151]
The projectile event is missing snowballs. It works for arrows and fires accordingly.
```
Snowball Events:
    type: world
    events:
        on snow_ball hits block:
        - announce "snowball hits block!"
        on projectile hits block:
        - announce "<script.name> <context.location.material> <context.projectile>"
```

**Comment by Talamar1** [comment]
Is this still happening with the latest Dev build?

**Comment by Fortifier42** [comment]
@ChemicalDatas Any updates?

**Comment by ChemicalDatas** [comment]
@Fortifier42 None. You know just here chilling out, Cooking breakfast, drinking tea.
@Talamar1 It is still happening.

**Comment by ChemicalDatas** [comment]
@Fortifier42 Do you have any updates?

**Comment by Talamar1** [comment]
Which build of Denizen are you using?

**Comment by Talamar1** [comment]
Use snowball for now, looks like someone coded the item name wrong.
@mcmonkey4eva

**Comment by mcmonkey4eva** [comment]
You mean Bukkit chose to do it different for entities than items?

**Comment by Talamar1** [comment]
yes... >.>   snow_ball is the item name, snowball is the entity.  We should add an alias to make bukkit less dumb.

**Comment by ChemicalDatas** [comment]
@Talamar1, snowball doesn't work either. The whole event on projectile hits block is not firing when using a snowball. Shouldn't it register when any projectile hits a block or am I using the wrong event for a snowball?

**Comment by ChemicalDatas** [comment]
I was using 0.9.7 build 367.

**Comment by mcmonkey4eva** [comment]
Either the Bukkit event doesn't include snowballs in the event and thus we can't possible either, or it corrupts the data somehow (EG, a bad location value) which Denizen responds to by refusing to fire the event.

**Comment by Fortifier42** [comment]
I'll test this today see what I can find

**Comment by Talamar1** [comment]
Looking at the code, the event is firing, something is blocking it... looking into it.

**Comment by Talamar1** [comment]
projectile.location is blank so we are killing the event for having invalid data.
Can we do anything about it?  @mcmonkey4eva

**Comment by Fortifier42** [comment]
According to the verbose log, the event never fires http://mcmonkey.org/paste/20371

**Comment by mcmonkey4eva** [comment]
@Talamar1 why the hell is the location blank?

**Comment by Talamar1** [comment]
Because bukkit sucks?
```
        dB.log("Event test 1: "+projectile.getName());
        if (projectile.getLocation() == null)
            return; // No, I can't explain how or why this would ever happen... nonetheless, it appears it does happen sometimes.
        dB.log("Event test 1.5: "+projectile.getName());
```
I never see the second test string when throwing snowballs.

**Comment by mcmonkey4eva** [comment]
Compelled to ping md_5 or ToD and demand explanation >.>

**Comment by Talamar1** [comment]
Compel more... do nothing less :P

**Comment by Talamar1** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-1204

**Comment by mcmonkey4eva** [comment]
Closing as this is a spigot issue. Please reply below when any word from Spigot team is had.

**Comment by Talamar1** [comment]
No one from spigot has event looked at it... I doubt it will be fixed, just make sure they fix it in sponge.
