### ISSUE TITLE
ItemMergeEvent bug

### ISSUE THREAD

**Issue by ElnanMillstone** [DenizenScript/Denizen-For-Bukkit#1153]
Denzien is generating an exception for the itemmergeevent, here's my console log: http://pastebin.com/7jgbabrz 

Note: I just downloaded the .jar from bukkit for the 1.8.6 release, so corruption is unlikely.

**Comment by mcmonkey4eva** [comment]
Update your everything, you're running old versions of your everything

**Comment by ElnanMillstone** [comment]
I would gladly update to 1.8.8, however, I cannot since this is just my personal testing server.  I am using it so I can restart it as much as needed without affecting players on the main server, which is 1.8.6.  If I updated the main server to 1.8.8, many plugins would break and very few have updated to 1.8.8 and would not be replaceable.

**Comment by mcmonkey4eva** [comment]
Well Denizen will break if you include the wrong version of it on your server.
As you just experienced.

**Comment by ElnanMillstone** [comment]
I am using version 0.9.7 as shown by the log.  Am I mistaken by 0.9.7 being 1.8.8?  Since I had believed it is 1.8.6...  If so, what is 1.8.6's version number?

**Comment by mcmonkey4eva** [comment]
1.8.8, 1.8.7, and 1.8.6 are all cross-compatible

**Comment by ElnanMillstone** [comment]
Upon updating spigot to 1.8.8, Citizens to 1.8.7, and Denizen to 1.8.8, it has appeared to fix itself, however, since you said 1.8.6 - 1.8.8 are cross compatible, how come it broke with 1.8.6?

**Comment by Fortifier42** [comment]
@mcmonkey4eva @ElnanMillstone Item Merge event was introduced in 1.8.7 (mid to late builds).

You MUST be running atleast 1.8.7 for current Denizen builds

**Comment by ElnanMillstone** [comment]
So essentially I cannot use Denizen unless I get it to 1.8.7, but were there any builds for Denizen that ran before 1.8.7 (So 1.8.6.  Basically I'm asking if there are old builds out there that I can use for 1.8.6)?

**Comment by Fortifier42** [comment]
@ElnanMillstone you can check the jenkins repo's

http://ci.mineconomy.org/job/Denizen_Developmental/lastSuccessfulBuild/
or
http://ci.citizensnpcs.co/job/Denizen/lastSuccessfulBuild

Although we cannot guarantee their full functionality, as we do not maintain versions for old spigot builds.

**Comment by ElnanMillstone** [comment]
Alright, thanks for both of your guy's support.  I appreciate it a lot.

**Comment by ElnanMillstone** [comment]
For anyone else who encounters the same problem as me, just use 2.0.16 (alpha 1 for MC 1.8.6) and Denizen build #230 which was uploaded on June 3rd http://ci.mineconomy.org/job/Denizen_Developmental/230/
