### ISSUE TITLE
suggestion: on <time> for server: event

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1154]
an event to fire on a specific timestamp, possibly limited to minutes, like the world time is.

looping tasks are great and all and would allow you to do most that this event could, but some things have to be really precise, and if your server slows down or shuts down unexpectedly this might affect the durations you're working with in your script.

You could log the current server time and work with that, but it'd get messy. A single event doing this would make scripting a lot easier.

for example a fake growing tree, that grows at the rate of one block per half an hour. rather than having a looping script which might slow down if the server does,  or may skip a portion of the loop on restart, the event could make its growrate very accurate.

another example is for example having a premium rank (assuming you have a reason not to use flags), which counts down the remaining days of premiumship daily, but has to be really accurate, but your server experiences unexpected downtimes or restarts daily too, but due to inaccuracies, every couple of days it's another hour late.

anyway an event like this would be nice:

  on time for server:

on 23:00 for server:

additionally, the player could use "- determine cancelled" to stop time for humanity entirely, freezing space and time as we know it.

**Comment by mcmonkey4eva** [comment]
ehehe http://mcmonkey.org/paste/20618

**Comment by BlackCoyote** [comment]
cool

**Comment by BlackCoyote** [comment]
is this in already?

**Comment by mcmonkey4eva** [comment]
Dev builds? Yes. Release? No.
