### ISSUE TITLE
Can't read list from server flag

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1155]
```
    #  ______   ______   ______  _______  ______   _        ______ 
    # | |  | \ / |  | \ | |  | \   | |   | |  | | | |      / |     
    # | |__|_/ | |  | | | |__| |   | |   | |__| | | |   _  '------.
    # |_|      \_|__|_/ |_|  \_\   |_|   |_|  |_| |_|__|_|  ____|_/
    
    on addportal command:
    - if <player.has_permission[pvp.portals.add]> {
        - determine PASSIVELY FULFILLED
        - define portal <player.location.simple>
        - adjust <player> velocity:l@0,1,0,world
        - wait 0.1
        - modifyblock ENDER_PORTAL %portal%
        - flag server "pvp.portals:->:l@%portal%"
        - execute as_server "denizen save"
        - narrate "Portal hinzugef<&uuml>gt!" format:pvp_format
        }
    
    on removeportal command:
    - if <player.has_permission[pvp.portals.remove]> {
        - determine PASSIVELY FULFILLED
        - define portal <player.location.simple>
        - adjust <player> velocity:l@0,2,0,world
        - wait 0.3
        - modifyblock AIR %portal%
        - flag server "pvp.portals:<-:l@%portal%"
        - execute as_server "denizen save"
        - narrate "Portal entfernt!" format:pvp_format
        }
    
    on player enters portal:
    - determine PASSIVELY CANCELLED
    - define portals <server.flag[pvp.portals]>
    - define portal <%portals%.random>
    - announce %portal%
    - teleport <player> <%portal%.above>
    - adjust <player> velocity:l@0,2,0,world
```
This is a portal script for my PvP/SkyPvP server. When a player enters a portal he should get teleported to another random portal. But when I add to portals using `/addportal` and then read out the list using `/ex narrate <server.flag[pvp.portals]>` I get the last added portal as result.

That is why I can't use ...
```
    - define portals <server.flag[pvp.portals]>
    - define portal <%portals%.random>
```
... for selecting a random portal.

**Another question related to this:** How can I cancel the `on player enters portal` event?

**Comment by zozer** [comment]
you need to add a `.as_list` at the end of the flag (like `<server.flag[pvp.portals].as_list>`)

**Comment by brainscript** [comment]
@zozer Thanks! I didn't know that I can use `determine` to set the new location because this is [not documented](http://mcmonkey.org/denizen/evts/).

**Comment by brainscript** [comment]
@zozer The determine doesn't work, I get teleported in the end.

**Comment by zozer** [comment]
use `on player uses portal` instead of `on player enters portal` . 'uses' has a determine while 'enters' does not.

**Comment by brainscript** [comment]
@zozer Then `on player enters portal` is pretty much useless ...

**Comment by brainscript** [comment]
@zozer Now it works, but I need to cancel the event and then teleport the player, because otherwise a nether portal will spawn at the given location. **Thanks for your help!**
