### ISSUE TITLE
Players can't see announces

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1156]
Nobody, except me with `*` permissions, can see `announce`.
`narrate "This is a test" targets:<server.list_online_players>`
This happens on all my servers with the latest DEV version.
Plugins: **Denizen**, *OnlyProxyJoin*, *BungeePerms*, *FarmProtect*, *EditableSigns*, *Multiverse-Core*

**Comment by zozer** [comment]
try `announce "This is a test"` ... also if you have quick questions like this go to http://mcmonkey.org/ircchat_denizen first and ask the people there

**Comment by brainscript** [comment]
@zozer Really? Sure, I tried this. But that doens't work, that's why I created this issue. `narrate "This is a test" targets:<server.list_online_players>` works, everybody sees it but not with `announce "This is a test"`. This is a **BUG**!

**Comment by zozer** [comment]
i just tested the announce command and it seems to working just fine, can you display the script you are using it in?

**Comment by brainscript** [comment]
I also tried this using `/ex` but I'm the only one who sees the message, when I op another player and then try it again, he sees it too.

**Comment by mcmonkey4eva** [comment]
Two possibilities here:

You're somehow injecting a `TO_OPS` or similar without realizing it.

OR

You have another plugin or bukkit mod screwing with announces.

'cause y'see.. announce (TO_ALL, the default) does this:
`DenizenAPI.getCurrentInstance().getServer().broadcastMessage(message);`
IE, calling the Bukkit built in broadcast method. It's reasonably possible for something to override or mody this Bukkit server method...

**Comment by Talamar1** [comment]
Are you sure that is the whole list of plugins? No essentials?  No Vault?  No economy?

**Comment by brainscript** [comment]
@Talamar1 I've got a server network, why should I use Essentials? And why economy on a development server?

**Comment by Talamar1** [comment]
Try restarting the server without Multiverse-Core, it does stuff with broadcasts because it has to handle inter-world communications.

**Comment by brainscript** [comment]
@Talamar1 Same problem without MV, maybe this big is related to BungeeCord.

**Comment by brainscript** [comment]
@Talamar1 It's not related to BungeeCord, I tried it without **OnlyProxyJoin** and joined directly on the cracked server. Players without OP can't see the announces.

**Comment by Fortifier42** [comment]
Can we get a debug? (just tells us everything we need to know about the server(s) and how you are doing it!) ;)

**Comment by brainscript** [comment]
The debug for `/ex narrate "This is just a test!"`:
```
[11:01:33 INFO]: Denizen dBugger is now: ENABLED
[11:01:39 INFO]: brainscript issued server command: /ex announce "This is just a
 test!"
[11:01:39 INFO]:  Starting InstantQueue 'EXCOMMAND_GraduallyZenAllocated'...
[11:01:39 INFO]:  Queue 'EXCOMMAND_GraduallyZenAllocated' Executing: ANNOUNCE
                   "This is just a test!"
[11:01:39 INFO]: +- Executing dCommand: ANNOUNCE/p@brainscript ---------+
[11:01:39 INFO]: +> Executing 'ANNOUNCE': Message='This is just a test!'
                   Type='ALL'
[11:01:39 INFO]: This is just a test!
[11:01:39 INFO]:  Completing queue 'EXCOMMAND_GraduallyZenAllocated' in 7ms.
[11:01:55 INFO]: brainscript issued server command: /deop Dominikaner1
[11:01:55 INFO]: [brainscript: De-opped Dominikaner1]
[11:01:57 INFO]: brainscript issued server command: /ex announce "This is just a
 test!"
[11:01:57 INFO]:  Starting InstantQueue 'EXCOMMAND_WatchesCreatureTank'...
[11:01:57 INFO]:  Queue 'EXCOMMAND_WatchesCreatureTank' Executing: ANNOUNCE
                   "This is just a test!"
[11:01:57 INFO]: +- Executing dCommand: ANNOUNCE/p@brainscript ---------+
[11:01:57 INFO]: +> Executing 'ANNOUNCE': Message='This is just a test!'
                   Type='ALL'
[11:01:57 INFO]: This is just a test!
[11:01:57 INFO]:  Completing queue 'EXCOMMAND_WatchesCreatureTank' in 1ms.
>
```
Dominikaner1 is OP at the start of the Debug (he sees the announce), then I deopped him (he can't see the announce).

**Comment by Fortifier42** [comment]
A proper debug using `/denizen debug -r` and `/denizen submit`.

**Comment by brainscript** [comment]
The server crashes when i do `/denizen submit`.

**Comment by brainscript** [comment]
@Fortifier42 Now it worked: http://mcmonkey.org/paste/20397

**Comment by brainscript** [comment]
I used the server with MultiVerse because there are no players on it and no loop scripts are spamming the record. The announce has worked with older version on servers **with MultiVerse**.

**Comment by Fortifier42** [comment]
That is a LOT more plugins than you said at the start of this issue. Can almost guarantee one of them is stopping your player's from recieving the announce.

**Comment by brainscript** [comment]
@Fortifier42 Then I was trying it on another server with only these plugins. This is now my build server.

**Comment by Fortifier42** [comment]
Your issue hasn't been replicated so it is your server setup(s)

**Comment by brainscript** [comment]
@Fortifier42 What configuration could be wrong? For example in `bukkit.yml`, `spigot.yml` or `server.properties`?

**Comment by Fortifier42** [comment]
Plugin configurations.

**Comment by brainscript** [comment]
@Fortifier42 I'm going to setup a complete clean server now and try it out again.

**Comment by Fortifier42** [comment]
You said earlier you are doing this on a BungeeCord server - you aren't trying to get announces to go to ALL servers are you...?

**Comment by brainscript** [comment]
@Fortifier42 No.

**Comment by brainscript** [comment]
@Fortifier42 However I can't figure out why and when that bug happens, maybe it's related to [this](https://bukkit.org/threads/many-users-dont-receive-bukkit-getserver-broadcastmessage.49042/). Maybe the DEVs @mcmonkey4eva @aufdemrand could just add a config option to do announces like @md-5 said in that thread:
> Instead of the bukkit broadcast methods I use:
```
for(Player p : Bukkit.getServer().getOnlinePlayers()){
p.sendMessage("Hello");
}
```

**Comment by BlackCoyote** [comment]
don't expect denizen to implement an alternate method as workaround just for your unique bug. Instead you can simply do the same in your script. 
`- foreach <server.list_online_players> {`
`  - narrate "Hello"`
`  }`

**Comment by brainscript** [comment]
@BlackCoyote It is not that much effort to add that workaround (I think). Maybe I stumble upon the problem in a few years ... :skull: 

*I just close this here, because you can't currently help me. I'm going to "investigate" a bit further. Maybe I'll find the problem.*
