### ISSUE TITLE
(flags using sub keys with expir...) edit: list_flags tags do not force an update on flags to check expiration

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1158]
flag key.subkey:value duration:10s

player.flag[key.subkey] will return value forever, untill player.flag[key.subkey].expiration is checked

**Comment by mcmonkey4eva** [comment]
You're abusing the everything :(

**Comment by BlackCoyote** [comment]
i've found my way around this, and I don't really know what your expected behaviour was on this, so I thought i'd just report it ;)

**Comment by mcmonkey4eva** [comment]
Wait I think I misread it... now I'm just confused. Can you give an example or something?

**Comment by BlackCoyote** [comment]
further testings shows that any "list_flags[regex/search]" tags do not force an update on the flags to check if they're expired yet.

replicate with:

`ex flag "test.test:yes" duration:5s`
`ex repeat 100 { -  narrate <player.list_flags[test.]> - wait 1s }`
`ex narrate <player.flag[test.test]>`
the repeat will keep reporting the flag as existant untill you check the value of the flag

**Comment by mcmonkey4eva** [comment]
Do we /want/ to fix it? It would probably slow down the listing a fair bit...

**Comment by mcmonkey4eva** [comment]
@Morphan1 what do you think of this issue?

**Comment by BlackCoyote** [comment]
i've found my workaround so it's not a necessary thing to fix, if it really would slow things down significantly maybe it's not the best thing to do

**Comment by Morphan1** [comment]
@mcmonkey4eva we could probably add a tag specifically for listing only non-expired flags
`<player.list_verified_flags[test.]>` or something along those lines

**Comment by mcmonkey4eva** [comment]
@Morphan1 do that then? :D

**Comment by mcmonkey4eva** [comment]
Done in build DEV-475+ 
I just made it check expiration on all flags found in the list
Potentially a bit slow, but eh... list_flags doesn't need to be fast
