### ISSUE TITLE
Remove command error

### ISSUE THREAD

**Issue by mawej1** [DenizenScript/Denizen-For-Bukkit#1159]
When using http://mcmonkey.org/haste/20136 , the script works perfectly, but throws this error on the adjust command (but the npc will get removed) http://mcmonkey.org/haste/20137 on bottom. Also, when I try to use the commented part of the code, so when the player logs out, it removes the npc, I get the same error and some more as a bonus http://mcmonkey.org/haste/20138 - and again, everything works as it should, the player's npc gets removed, and the original shows up. Thanks for reply.

**Comment by Fortifier42** [comment]
hiding an entity from a player is not persistent and cannot be changed while the player is offline. simply remove the npc :smirk:

**Comment by mawej1** [comment]
Ok, but what is the error about in the first server log (at the bottom) when the player is still online?

**Comment by Fortifier42** [comment]
Not a clue, can you replicate it after changing the remove/adjust?

**Comment by mawej1** [comment]
I can not replicate this when I'm not using adjust <player> show_entity:<def[masternpc]> - but that command needs to be there, otherwise the player will not be able to see the master npc.

**Comment by Fortifier42** [comment]
http://mcmonkey.org/haste/20449

Look at this script - see what I mean, where I mean.

**Comment by mawej1** [comment]
http://mcmonkey.org/paste/20453

Also, please look at line 30 in the script - that adjust command is causing problems (that only applies when the player doesn't disconnect)

**Comment by Fortifier42** [comment]
http://mcmonkey.org/haste/20458

Give this a go! :)

**Comment by mawej1** [comment]
http://mcmonkey.org/paste/20462

Keeps looping until restart

**Comment by Fortifier42** [comment]
Ugh rightio, let's move it around a bit more!

http://mcmonkey.org/haste/20464
Difference: http://mcmonkey.org/haste/20463

**Comment by mawej1** [comment]
online - http://mcmonkey.org/paste/20466 ; can't see the original npc
offline - http://mcmonkey.org/paste/20467 ; original npc OK

I don't think this is the script issue, but rather denizen/citizens issue - the thing is, on mcmonkey's tutorial on npc guides it works perfectly (only difference is that he's not checking if the player is offline) - I have really similar script to his.

**Comment by mawej1** [comment]
So.. any ideas? :(

**Comment by mcmonkey4eva** [comment]
is this still an issue?
