### ISSUE TITLE
Denizen loading script error

### ISSUE THREAD

**Issue by Zektopos** [DenizenScript/Denizen-For-Bukkit#1161]
i tried to create a script but when i try to load the scripts the console says:
23.09 07:26:22 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
23.09 07:26:22 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
23.09 07:26:22 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
23.09 07:26:22 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
23.09 07:26:22 [Server] WARN at net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1156)
23.09 07:26:22 [Server] WARN at net.aufdemrand.denizen.utilities.command.CommandManager.executeSafe(CommandManager.java:157)
23.09 07:26:22 [Server] WARN at net.aufdemrand.denizen.utilities.command.CommandManager.execute(CommandManager.java:65)
23.09 07:26:22 [Server] WARN at net.aufdemrand.denizen.utilities.command.CommandManager.executeMethod(CommandManager.java:130)
23.09 07:26:22 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:497)
23.09 07:26:22 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23.09 07:26:22 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23.09 07:26:22 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23.09 07:26:22 [Server] WARN at net.aufdemrand.denizen.DenizenCommandHandler.reload(DenizenCommandHandler.java:408)
23.09 07:26:22 [Server] WARN at net.aufdemrand.denizencore.DenizenCore.reloadScripts(DenizenCore.java:114)
23.09 07:26:22 [Server] WARN at net.aufdemrand.denizencore.DenizenCore.loadScripts(DenizenCore.java:98)
23.09 07:26:22 [Server] WARN at net.aufdemrand.denizencore.scripts.ScriptHelper.reloadScripts(ScriptHelper.java:38)
23.09 07:26:22 [Server] WARN at net.aufdemrand.denizen.Denizen.buildCoreContainers(Denizen.java:1257)
23.09 07:26:22 [Server] WARN at net.aufdemrand.denizencore.scripts.ScriptRegistry._buildCoreYamlScriptContainers(ScriptRegistry.java:75)
23.09 07:26:22 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
23.09 07:26:22 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
23.09 07:26:22 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
23.09 07:26:22 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
23.09 07:26:22 [Server] WARN java.lang.reflect.InvocationTargetException
23.09 07:26:22 [Server] INFO ERROR! Internal exception was thrown! 
23.09 07:26:22 [Server] INFO +> [Denizen] Adding script TOMMY as type INTERACT 
23.09 07:26:22 [Server] INFO OKAY! All scripts loaded! 
23.09 07:26:22 [Server] INFO +> [Denizen] Processing '/Tommy.yml'... 
23.09 07:26:22 [Server] INFO +> [Denizen] Processing unnamed script... 
23.09 07:26:22 [Server] INFO +> [Denizen] Processing outside scripts... 

Do anyone know how to fix it? I really need Denizen on my server..

**Comment by Talamar1** [comment]
Can you get on the IRC channel?  If not, please post your script on http://mcmonkey.org/haste
and paste the link here.  Also, what build of Denizen and Spigot are you running?

**Comment by Zektopos** [comment]
IRC channel?
i use Denizen version 0.9.7 and Spigot 1.8.8

**Comment by Zektopos** [comment]
what is IRC Channel, maybe i sound stupid but.... yeah...

**Comment by Talamar1** [comment]
http://webchat.esper.net/?nick=r_denizen_...&channels=denizen-dev&prompt=1
IRC is an online chat system.

**Comment by Talamar1** [comment]
We would actually need to see the build number of Denizen.
/denizen version

**Comment by Zektopos** [comment]
i still gets the error

**Comment by mcmonkey4eva** [comment]
You seem to have been helped on IRC.
