### ISSUE TITLE
sidebar per_player handling "breaks" with <proc[]> tag in value:

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Denizen-For-Bukkit#1162]
```
- sidebar set title:test lines:1 "value:<proc[procedurecrap].context[<player.money>]>" players:<w@world.players> per_player
```
Errors with:
```
[16:37:18 INFO]:  ERROR! Invalid or missing player for tag <player.money>!
[16:37:18 INFO]:  ERROR in script 'PRISONSCOREBOARD'! Tag <player.money> is
                   invalid!
[16:37:18 INFO]:  ERROR! 'player.money' is not a valid number.
```

**Comment by mcmonkey4eva** [comment]
Full debug rec for reference pls

**Comment by Talamar1** [comment]
http://mcmonkey.org/paste/20322

**Comment by mcmonkey4eva** [comment]
That's... just a long list of errors with debug disabled throughout.

**Comment by Talamar1** [comment]
http://mcmonkey.org/paste/20323

**Comment by Talamar1** [comment]
I realized that after I posted it

**Comment by mcmonkey4eva** [comment]
Now you enabled debug for the wrong script?

**Comment by Talamar1** [comment]
http://mcmonkey.org/paste/20324

**Comment by Talamar1** [comment]
I turned on the sidebar that wasn't erroring.. blah blah.. that has errors

**Comment by mcmonkey4eva** [comment]
and forgot the procedure ;-;

**Comment by Talamar1** [comment]
http://mcmonkey.org/paste/20330
The proc shouldn't matter, its the .context[] which is trying to process the tag before per_player kicks in

**Comment by Talamar1** [comment]
Script:
http://mcmonkey.org/paste/20656
Broken ones are the commented out ones.

**Comment by Morphan1** [comment]
@mcmonkey4eva why does this make no sense?
There most certainly is a player in the BukkitTagContext.

**Comment by Talamar1** [comment]
Because proc: is being processed before it is going into the sidebar?

**Comment by Talamar1** [comment]
![2015-10-16_18 19 18](https://cloud.githubusercontent.com/assets/6541073/10554569/8f318ce8-7432-11e5-8290-ce6b1afc53dc.png)

**Comment by mcmonkey4eva** [comment]
This was fixed.
