### ISSUE TITLE
- sidebar giving odd result

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Denizen-For-Bukkit#1163]
this command:
```
- sidebar set "title:<red>Ranking Info" "lines:1|2|3|4|5|6|7" "values:<blue><bold>Rank|<&sp>|<blue><bold>Balance|<&sp>|<blue><bold>NextRank|<&sp>|<blue><bold>Needed" players:<player>
```
gives this output:
![capture](https://cloud.githubusercontent.com/assets/6541073/10059042/9fe88e34-6216-11e5-83b4-1e26ef317f63.PNG)

**Comment by mcmonkey4eva** [comment]
You can't use the exact same text twice. Scoreboards don't allow it.

**Comment by Talamar1** [comment]
So, to create blank lines I have to use different color codes...
