### ISSUE TITLE
on player chat's determine bug

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1165]
when 2 players chat at the (almost) exact same time, when you use - determine to change the format, sometimes it shows the first player's message twice and the other player's message not at all, rather than one of each

**Comment by Fortifier42** [comment]
I can confirm that this is NOT ONLY for determine as I cancel the message and narrate it separately afterwards, but rather for the event as a whole.

I *think* it may have to do with chat async?

**Comment by Morphan1** [comment]
Oh hey. Looks like the reason this is happening might be because ScriptEvents only get one instance, so when an async chat updates its variables and another async chat updates it immediately before the other can finish, they both go with whichever was last.

@mcmonkey4eva fixpls

**Comment by mcmonkey4eva** [comment]
That has to be a `super duper rapid fire` for that to happen. I vote we just burn async chat in hell as we should have.

**Comment by BlackCoyote** [comment]
it happens about 10 times a day and its getting really annoying >:O

**Comment by Fortifier42** [comment]
@mcmonkey4eva Don't need to be *super fast* as it occurs simply when two people send a message within a tick or two of each other. It happens on a server with 3 people who have regular discussion... I simply disabled the Chat Async in the config and it is gone..

**Comment by BlackCoyote** [comment]
was this ever attempted to fix? it's really obnoxious D:

**Comment by Fortifier42** [comment]
@BlackCoyote turning off async chat fixes the problem?

**Comment by mcmonkey4eva** [comment]
As far as I'm aware, it's just the concept of Async disagreeing with our current ScriptEvent design >.>

**Comment by mcmonkey4eva** [comment]
yeah just don't use async chat event unless you want some breakage
