### ISSUE TITLE
<player.item_in_hand.material.formatted> gives 'null'

### ISSUE THREAD

**Issue by apesgrapes** [DenizenScript/Denizen-For-Bukkit#1166]
this seems to have happened recently (sorry that's vague). using #1597

**Comment by Talamar1** [comment]
material.formatted is not a supported tag, you probably want <player.item_in_hand.formatted>

**Comment by apesgrapes** [comment]
don't leave me in suspense..

**Comment by BlackCoyote** [comment]
`<player.item_in_hand.formatted>`

**Comment by apesgrapes** [comment]
thx, working fine now.
