### ISSUE TITLE
Not loading?

### ISSUE THREAD

**Issue by balatr0** [DenizenScript/Denizen-For-Bukkit#1167]
I down loaded the pack and am receiving this error in council when I try to access help.

27.09 12:17:39 [Server] INFO ... 15 more
27.09 12:17:39 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:17:39 [Server] INFO at net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1140) ~[?:?]
27.09 12:17:39 [Server] INFO Caused by: java.lang.NullPointerException
27.09 12:17:39 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
27.09 12:17:39 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:17:39 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:17:39 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:17:39 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:672) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:17:39 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:17:39 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
27.09 12:17:39 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
27.09 12:17:39 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:17:39 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:17:39 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:17:39 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:17:39 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:17:39 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:619) ~[craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:17:39 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:17:39 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:17:39 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'denizen' in plugin Denizen v0.9.7-SNAPSHOT (build 1591)
27.09 12:17:39 [Server] ERROR null

I believe I have the proper download for my build. 
But I'm still quite new to this so. What I read this is helpful.

https://gyazo.com/e3b9b1c2de33a1fda08702b44c9cb446

**Comment by balatr0** [comment]
It my be worth mentioning I haven't had it long just recently added it in as a supplement for the outdated Sentry.

**Comment by Talamar1** [comment]
What is your denizen version?
Also, do a /denizen debug -r       try to run the command and then /denizen submit
Paste the url here to that log.

**Comment by balatr0** [comment]
"Version 0.9.7-SNAPSHOT (build 1591) by aufdemrand"
According to the Plugin loader on the hosting site.

Debug giving me the same-
https://gyazo.com/869767f927fedbf9bd8b2b9b497350c7

Heres console on that.
27.09 12:57:02 [Server] INFO ... 15 more
27.09 12:57:02 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:57:02 [Server] INFO at net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1140) ~[?:?]
27.09 12:57:02 [Server] INFO Caused by: java.lang.NullPointerException
27.09 12:57:02 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
27.09 12:57:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:57:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:57:02 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:57:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:672) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:57:02 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:57:02 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
27.09 12:57:02 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
27.09 12:57:02 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:57:02 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:57:02 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:57:02 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:57:02 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106) [craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:57:02 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:619) ~[craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:57:02 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:57:02 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit42.jar:git-Bukkit-9935adc]
27.09 12:57:02 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'denizen' in plugin Denizen v0.9.7-SNAPSHOT (build 1591)
27.09 12:57:02 [Server] ERROR null

**Comment by Talamar1** [comment]
Denizen 1597 is the latest production build, but we typically recommend using the dev builds if you are are latest and greatest spigot builds.  Those are at http://ci.mineconomy.org/job/Denizen_Developmental/
Dev is 7 days old, production build is over 1 month old.

**Comment by balatr0** [comment]
So 1591 is the safe bet?

**Comment by Talamar1** [comment]
no, use 1597 or switch to dev builds.  1591 is old.

**Comment by balatr0** [comment]
It appears to be working thanks Talamar!
