### ISSUE TITLE
make particles render from further away

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1168]
https://github.com/DenizenScript/Denizen-For-Bukkit/blob/master/src/main/java/net/aufdemrand/denizen/scripts/commands/world/PlayEffectCommand.java#L267

all deez 

`PacketPlayOutWorldParticles o = new PacketPlayOutWorldParticles(particleEffect.effect, false, (float) location.getX(), `
                       `  (float) location.getY(), (float) location.getZ(), osX, osY, osZ, data.asFloat(), qty.asInt());  `

should be 

 `PacketPlayOutWorldParticles o = new PacketPlayOutWorldParticles(particleEffect.effect, true, (float) location.getX(),  `
                        ` (float) location.getY(), (float) location.getZ(), osX, osY, osZ, data.asFloat(), qty.asInt());  `

the boolean controls whether or not it should render beyond 16 blocks 

thanks fullwall for finding this out

**Comment by Morphan1** [comment]
Oooh cool... Sadly, I won't be able to do this until Tuesday or so... @mcmonkey4eva PLS WE NEED THIS, IS IMPORTANT

**Comment by BlackCoyote** [comment]
^ THIS GUY GETS IT

**Comment by mcmonkey4eva** [comment]
Fixed yo
