### ISSUE TITLE
Wierd command take bug.

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Denizen-For-Bukkit#1169]
Problem: take command not working on custom dItem.
Cause: Unknown.
Result: http://mcmonkey.org/paste/20505

I had an item that had a material of web[quantity=10]. I guess that is not "supported" and may have something to do with the bug. The command appears to try and grab a bunch (but not all) tags  from a different script, 10 times. I have removed the [quantity=10] from the item script, but the bug persists. It has even persisted through server restarts, updates, and wiped saves. I have not done much trouble shooting beyond confirming that this is not intended behavior.
More trouble shooting will be done latter.

**Comment by mcmonkey4eva** [comment]
Replication script pls?
