### ISSUE TITLE
suggestion: make outgoing particle packets async

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1172]
morphan1 knows what im talking about

**Comment by mcmonkey4eva** [comment]
@Morphan1 how what

**Comment by mcmonkey4eva** [comment]
Async command! `:D` ?

**Comment by BlackCoyote** [comment]
From what mophan told me, the outgoing packets do not get handled async, and can still lock up the server even if it comes from an async queue, he told me he could change this

**Comment by Morphan1** [comment]
@mcmonkey4eva I talked to you at some point about it I think. particle packets are added to a queue that sends them per tick

**Comment by mcmonkey4eva** [comment]
@Morphan1 and the code is where?

**Comment by Morphan1** [comment]
@mcmonkey4eva somewhere around here http://git.mcmonkey.org/mcmonkey/mc-dev/blob/master/net/minecraft/server/NetworkManager.java#L129

**Comment by mcmonkey4eva** [comment]
Not sure what if anything can be done about this...
@Morphan1 do you have any idea?

To my knowledge queuing is unavoidable, except if there's multiple separate queues, in which case a few of the queues can be skipped.

**Comment by mcmonkey4eva** [comment]
Disregarding due to lack of explanation.
Also rather unnecessary.
