### ISSUE TITLE
Npc equipment issues

### ISSUE THREAD

**Issue by ChemicalDatas** [DenizenScript/Denizen-For-Bukkit#1173]
http://mcmonkey.org/paste/20533

After creating a npc, selecting it, then running ./ex equip <npc> head:i@diamond_helmet hand:i@bone_meal the npc fails to equip anything at all. Ive run it on my self, the same command using <player> and it adjust my equipment accordingly. So I'm at a loss for what's going on here.

**Comment by ChemicalDatas** [comment]
Well... I just slept in a bed and came back to the npcs to find him wearing his equipment.

**Comment by mcmonkey4eva** [comment]
can you equip properly with `/npc equip`, or does it have a similar bug?

**Comment by ChemicalDatas** [comment]
I am unable to repeat the bug after updating Spigot to the newest version.
