### ISSUE TITLE
dsentry melee NPCs don't follow targets.

### ISSUE THREAD

**Issue by balatr0** [DenizenScript/Denizen-For-Bukkit#1174]
as title.

dose the dsentry script support melee NPC who follow targets?
(Can't find any guides, and Im horrible at reading scripts)

**Comment by mcmonkey4eva** [comment]
They should follow automatically? 0.o if your server is configured correctly

**Comment by balatr0** [comment]
Yah, they kinda just stand there.

It also gives a kill message if its a steve model.

Any idea how I can check?

**Comment by mcmonkey4eva** [comment]
`It also gives a kill message if its a steve model.` Might have to disable that via an event 0.o not sure.

And I have no idea under what circumstances the NPCs would fail to follow -  I guess I'll have to start up minecraft at some point and play around a bit, see if I can find anything wrong in the script itself...

**Comment by mcmonkey4eva** [comment]
Is this still an issue? Sorry for largely ignoring it.
