### ISSUE TITLE
something banner related not working

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1175]
http://mcmonkey.org/paste/20587

placed down a banner, have another edited banner in my hand, execute `ex adjust <pl.location.cursor_on> patterns:<pl.item_in_hand.patterns>` and the above happens

**Comment by mcmonkey4eva** [comment]
Try latest dev build. Should maybe be fixed, assuming all the other code is fine and it was just the one @Morphan1 mistake.
