### ISSUE TITLE
Clicky clicky click where

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Denizen-For-Bukkit#1177]
`on player right clicks <material> at:<Location>` where Location can be a dLoc, a notable loc, anything that can be parsed as a dLoc. Switches!

**Comment by mcmonkey4eva** [comment]
oh and `in <area>` is needed too :o

**Comment by Talamar1** [comment]
Its not done yet?  Oh, wait, @Morphan1 hasn't converted the clicky events yet....  You want me to break them?

**Comment by mcmonkey4eva** [comment]
Go for it, @Talamar1 - why not

**Comment by Talamar1** [comment]
Maybe done...
https://github.com/Talamar1/Denizen/commit/ce8850ce58e51e663ca2ba7e286b1efce2f95cac

**Comment by mcmonkey4eva** [comment]
is good enough with script event dynamic in area handling
