### ISSUE TITLE
CanDestroy Item Flag

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1184]
Enhance adventure mode mechanics by allowing items with the CanDestroy flag to be created through denizen (easily).
Encourages adventure playwork

**Comment by brainscript** [comment]
:heavy_plus_sign::+1: Please add `CanPlaceOn` too.

**Comment by mcmonkey4eva** [comment]
@brainscript please open a separate issue for that. We're trying to keep each bit separate here, as they are technically separate, despite being similar in how they work.

**Comment by brainscript** [comment]
@mcmonkey4eva That's the opposite of `CanDestroy`. I don't see a reason to create a seperate issue for that. I would rename the issue to "Adventure Mode Item Flags".

**Comment by mcmonkey4eva** [comment]
@brainscript They would have to be implemented entirely separately, therefore they should be separate issues. That way we can do one commit that closes CanDestroy, and another issue that closes CanPlaceOn.

**Comment by mcmonkey4eva** [comment]
Added in latest dev builds thanks to
