### ISSUE TITLE
Custom Item Bug #1114

### ISSUE THREAD

**Issue by schmiddel89** [DenizenScript/Denizen-For-Bukkit#1186]
Hi there,

just found a bug... I noticed that items after death are not the same as before... So it should be a "determine drop" issue...  Everytime when I died and pick up the same custome items they cannot be stacked or trade with villager... They are really buggy...

Mcmonkey fixed the lower and upper Case in the latest build but I think this results to this bug

**Comment by Talamar1** [comment]
Fixed?
https://github.com/Talamar1/Denizen/commit/9fb4967eb2a6ad88834fdfe41a49916a0bd73d7e

**Comment by mcmonkey4eva** [comment]
@Talamar1 professional grade level of not paying attention

**Comment by Talamar1** [comment]
I work really hard to be this slow.  So, your fix fixed something but not everything?

**Comment by mcmonkey4eva** [comment]
I have no idea what dropping and picking up an item would change...

**Comment by Fortifier42** [comment]
@mcmonkey4eva it's the same issue experienced by @schmiddel89 with shopkeepers :cry:

**Comment by schmiddel89** [comment]
So this actually also the main problem for the shopkeepers problem.. I use a script with event on death - determine drop specific items which I flagged...

One of my players noticed that after death this items cannot be stacked with the same items.. So they must be different and shopkeepers noticed it also

**Comment by schmiddel89** [comment]
Maybe the problem results through the hidden id issue? Like the Issue Bug #1114..

Perhaps it places some hidden codes wrong ? So I got two different items, which cannot be stacked or trade with shop keepers...

**Comment by schmiddel89** [comment]
https://www.youtube.com/watch?v=-8pQeMPMi5Y mcmonkey you can see in this video that they cannot be stacked

**Comment by schmiddel89** [comment]
http://mcmonkey.org/haste/20835 so it seems that the problem occurs through this script... But only if I am not in op and in gamemode... It also seems that the problem happens not through -determine drop.. It also happens when I flag slot 1 and give it the player by respawning.. So maybe sth is wrong with tag <player.inventory.slot[]> ??

**Comment by Morphan1** [comment]
If any of this is valid (I haven't seen any reasonable confirmation of this) then it's most likely related to #1188. Redirect discussion there, as it isn't a duplicate of a 3 month old issue and isn't extremely vague with a lot of "maybe"s
