### ISSUE TITLE
Attribute Support - MaxHealth

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#1187]
It would be neat to implement the Attribute: MaxHealth using NBTEditor's source code.
I havn't read much about the license and the code but i think its possible.

Bukkit Page:
http://dev.bukkit.org/bukkit-plugins/nbteditor/
Source Code:
https://github.com/goncalomb/NBTEditor

Uses in a example script:

ScriptName:
type: item
material: diamond_helmet
name: <&a>Body Helmet
Attributes:
- MaxHealth: 4.0

And the results would be something like this:
![Example Picture](http://i.imgur.com/jk3K3Cq.png)

I was suggested to make it specefic, so i suggested one of the attributes from the NBTEditor but there are many other Attributes as well... Another thing is I don't know which part of the code does it but I tried to look around and thought this might be it:
https://github.com/goncalomb/NBTEditor/blob/master/src/main/java/com/goncalomb/bukkit/nbteditor/nbt/attributes/ItemModifier.java
Anyways I hope this could help with the feature of adding Attributes (starting with MaxHealth)

**Comment by Morphan1** [comment]
When I said "add to denizen itself", I meant to not rely on NBTEditor or any other plugin at all.

**Comment by Mwthorn** [comment]
Yes, I know what you mean, I just thought like taking a part of a source code would help to code it into Denizen.

**Comment by mcmonkey4eva** [comment]
We don't need external / unrelated plugins to support things.

Tell us Minecraft or general stuff you need, and we add it. That simple :)

**Comment by Oruss7** [comment]
Is available now ?

**Comment by mcmonkey4eva** [comment]
Oh. Yes. nbt_attributes mech/tag is available on items now :)
