### ISSUE TITLE
Custom Item Tag Bug

### ISSUE THREAD

**Issue by Bloodyflair** [DenizenScript/Denizen-For-Bukkit#1188]
Good morning guys,

I noticed some weird thing with tags which display everything about a custom item like `<player.item_in_hand>.`

Well when I store this tag and want to give me the item with `- give <player.flag[customitem]>` then this item cannot be stacked with other same items which have been already in my inventory..? Seems they are different :(

Could someone explain me that?

Thank you in advane guys!

**Comment by Morphan1** [comment]
Could you provide a simple script and the debug of said script via `/denizen debug -r`?

**Comment by Bloodyflair** [comment]
http://mcmonkey.org/paste/20866 and this is my script which I am using http://mcmonkey.org/paste/20869... first of all I give me through /ex give bronzer the item and after it fulfilled the script I cannot stack the second item because it is not the same :/

**Comment by mcmonkey4eva** [comment]
... helps to er... enable debug on each script when doing a debug recording... that debug rec is blank

**Comment by Bloodyflair** [comment]
Hi mcmonkey4eva,

hopefully this is the right one http://mcmonkey.org/paste/20912 :)

Maybe the unique id is placed wrong to the given item?

BR
....

**Comment by Talamar1** [comment]
This script seems to work fine with my new "player clicks block" code:
http://mcmonkey.org/paste/21059
He is using an invalid event call in his script (with the new code), though, it's not throwing an error. (He left of "block" so the material is "with" and the event doesn't fire).  That is "expected" behavior.

**Comment by schmiddel89** [comment]
I tried this script... but it also give me two different items, which cannot be stacked. Is there sth wrong with it? Please use also custome items for it...

Script: http://mcmonkey.org/haste/21074
Debug:http://mcmonkey.org/paste/21076

BR :)

**Comment by Fortifier42** [comment]
This is because you're losing the hidden identifier for item scripts, since it isn't included in the item's tag. Flag the itemscript isntead of the full item.

**Comment by Morphan1** [comment]
This has finally been fixed in the latest development build
