### ISSUE TITLE
odd structure generating when pasting large schematics

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1190]
When i paste a schematic, the size of an entire chunk, using `        - schematic paste name:%x%_%z% l@<def[start].add[%x%].sub[1].mul[16]||0>,0,<def[z].sub[1].mul[16]||0>,guildworld delayed` , it tends to immediataly generate existing structures back in its place, resulting in large holes in the ground leading to villages or strongholds or such.

example: https://i.gyazo.com/55057fba40a8bf2d14f1442f0e93989e.jpg

( the natural-ish terrain is what is being pasted in a flat world)

**Comment by mcmonkey4eva** [comment]
I can't help but wonder if this is related to your other chunk errors? That's really really weird.

**Comment by BlackCoyote** [comment]
no, this one has been around for ages, where as those other issues only started happening this week.

**Comment by mcmonkey4eva** [comment]
Can anyone else test/confirm this? @Talamar1  @Fortifier42 ?

**Comment by Fortifier42** [comment]
![Schematic Paste](http://puu.sh/l43wF.png)

couldn't confirm with this (relatively) big schematic.

**Comment by mcmonkey4eva** [comment]
@BlackCoyote can you perhaps provide more detailed replication steps / investigate further?

**Comment by BlackCoyote** [comment]
the best way to replicate it i think would be to create a flat world that still has generating structures on, and repeatedly paste a schematic in a long line, that would be the closest to what i'm doing. i dont know if whether or not the schematics are exactly the size of a chunk plays a role in it or not.

**Comment by Morphan1** [comment]
@mcmonkey4eva think it'd be worth it to try loading in surrounding chunks before editing a chunk?

**Comment by BlackCoyote** [comment]
me and mcmonkey tried fixing this and even with the entire 32x32 chunks preloaded it still occured

**Comment by mcmonkey4eva** [comment]
`"mojang is satan's mother-in-law"`
/dies

But yeah, I preloaded everything - all the relevant chunks and all nearby chunks as well, using chunkload + chunk.regenerate. It refused to fucking stop spawning villages when chunks were spawned. I have no idea what to do about this or wtf is going on. It's like... Mojang code is only spawning villages when players get near or something ridiculous like that.

**Comment by BlackCoyote** [comment]
blame mojang
