### ISSUE TITLE
HorseInventory

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1192]
Is there an easy way to give a horse a saddle and armor like the Bukkit [HorseInventory](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/HorseInventory.html)?
Currently I can't see any specific tags and mechanisms for that.
Maybe you could add some, I need them for a hub mounts script.

```
ItemStack getSaddle() -> <e@entity.saddle>
ItemStack getArmor() -> <e@entity.horse_armor>
void setSaddle(ItemStack stack) -> saddle (mechanism)
void setArmor(ItemStack stack) -> horse_armor (mechanism)
```

**Comment by mcmonkey4eva** [comment]
I think you just put them in the relevant item slots of the inventory.

Dedicated functions might be better, but it should be doable without them...

**Comment by Talamar1** [comment]
Like, add support for horses to - equip?

**Comment by brainscript** [comment]
@Talamar1 Good idea!

**Comment by Fortifier42** [comment]
I've given NPC horses a saddle like this: 
```
- inventory set o:saddle d:<entry[horse].created_npc.inventory> slot:1
```
And Armor like this:
```
- inventory set o:i@diamond_barding d:<entry[horse].created_npc.inventory> slot:2
```

**Comment by brainscript** [comment]
@Fortifier42
```
on zombiehorse command:
- determine PASSIVELY FULFILLED
- mount <player>|e@horse[color=BLACK|NONE|UNDEAD_HORSE;tame=true]
- inventory set o:saddle <player.vehicle.inventory> slot:1
```
... doesn't work. It spawns the horse and tames it, but it has no saddle.

**Comment by Fortifier42** [comment]
This should work

```
on zombiehorse command:
  - spawn e@horse[color=BLACK|NONE|UNDEAD_HORSE;tame=true;owner=<player>] save:horse
  - inventory set o:i@saddle d:<entry[horse].spawned_entities.get[1]> slot:1
  - mount <player>|<entry[horse].spawned_entities.get[1]>
  - determine fulfilled
```

**Comment by brainscript** [comment]
@Talamar1 Thanks! It works perfect! :smile: I don't know if @mcmonkey4eva wants to add these tags and mechanism I requested. If not he can close it.

**Comment by Fortifier42** [comment]
@brainscript didn't realise I was Talamar all of a sudden :fearful:

could be an improvement to equipment!

**Comment by brainscript** [comment]
@Fortifier42 Sorry, I corrected it. :sweat_smile:

**Comment by brainscript** [comment]
@Fortifier42 Last question: How does this work with pigs? And is it possible to control them without a carrot on a stick?

**Comment by Fortifier42** [comment]
@brainscript pigs only have 1 inventory slot, so I imagine reusing the saddle code I gave you would work super easy. *Not* having to use a carrot on a stick... I believe that's part of the Pig's AI, so I don't see another way to control them, sorry.

**Comment by mcmonkey4eva** [comment]
If you spawn an /NPC/ pig, you can control them directly with keyboard keys.

**Comment by brainscript** [comment]
@mcmonkey4eva I don't want it to be an NPC.

**Comment by Talamar1** [comment]
Added in:
https://github.com/Talamar1/Denizen/commit/761048970e88688b8065b782cf2522e27c1ae775

**Comment by mcmonkey4eva** [comment]
Tags/mechs were added for the main issue.

And you can write a script using the `walk` command to control an entity NPC more directly, though it will be a bit complicated. Especially since I don't think you can listen to player input controls easily.
(Feel free to open a separate issue to discuss that).

**Comment by Fortifier42** [comment]
@mcmonkey4eva correction, was added to the equip command :)

**Comment by mcmonkey4eva** [comment]
I'm going through issues too rapidly, my bad. Thanks Fortifier.
