### ISSUE TITLE
timezone tag

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1194]
We have the ability to fetch the date and time of the system, however it would be good to be able to retrieve it's timezone aswell, for usability, formatting and reference (so we know the timezone that the time is being fetched from).

`<util.date.time.zone>` return the short name e.g. "PST"
`<util.date.time.zone.formatted>` return the long name e.g. "Pacific Standard Time"

**Comment by brainscript** [comment]
@Fortifier42 Did you mean `<util.date.time.zone.formatted>`?

**Comment by Fortifier42** [comment]
@brainscript thanks buddy, corrected :)

**Comment by Fortifier42** [comment]
https://github.com/ausFort/Denizen-Core/commit/f01df2ffcdd0875de8266c5f71c04f164a1db3d4

PR'd

**Comment by mcmonkey4eva** [comment]
This was pulled.
