### ISSUE TITLE
<player.time> issue

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1195]
`<player.time>` returns `36814000` when the time is `14000` and `36826000` when the time is `6000`. I set the time using the `- adjust <player> time:%time%` mechanism. Why?! :open_mouth:

**Comment by Fortifier42** [comment]
Can confirm.. it's, not the *right* value. however the code relies on spigot. must be something wrong in spigot?

http://mcmonkey.org/paste/21147

**Comment by mcmonkey4eva** [comment]
Spigot issue. Will reopen if there's any reason to believe it's not Spigot causing this.
(Please just reply below if you believe this closing is in error)
