### ISSUE TITLE
npc Chat Action debug always appears.

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1196]
I've been unable to stop the "on chat" action with npc assignment scripts from showing in console. To the extent, I have disabled debug in the script itself, and debug still shows.

Script:

```
Assignment:
  type: assignment
  debug: false
  actions:
    on chat:
      - narrate <context.message>
```

**Comment by mcmonkey4eva** [comment]
That... makes no sense. You did something wrong. 'Cause that report call handles debug mode checking the same as everything else.

**Comment by mcmonkey4eva** [comment]
Was this fixed yet?

**Comment by Fortifier42** [comment]
Nope. Action still gives debug. Seems to be when what said isn't causing a cancel of the event 
http://puu.sh/l43l2.png

**Comment by mcmonkey4eva** [comment]
Please tell me how this is even possible.

The call is `dB.report(script, name, ...`

The first line of `dB.report`?
  `if (!showDebug) return;`

Can anyone replicate this? @Morphan1 @Talamar1 ?

**Comment by Fortifier42** [comment]
@mcmonkey4eva Put my dBanker script on http://mcmonkey.org/denizen/repo/entry/52
Assign the npc
just say something in proximity

**Comment by mcmonkey4eva** [comment]
Replicating things myself is boring.

**Comment by Fortifier42** [comment]
http://mcmonkey.org/paste/22012#21 
You can view the debug here -> Line 21 is the trigger, which  doesn't get chat debug

**Comment by GomaTerzu** [comment]
Can confirm this. Just tested.

debug:false but still this while chatting in proximity range

[09:32:45 INFO]: +> Executing 'CHAT': Player='Goma_Terzu'  NPC='Warehouse/8'  Radius(Max)='2.034712295424615(3.0)'  Trigger text='Hi'
                   LOS='true'  Facing='true'
[09:32:45 INFO]: [CHAT] Goma_Terzu Hi
[09:32:54 INFO]: +> Executing 'CHAT': Player='Goma_Terzu'  NPC='Warehouse/8'  Radius(Max)='1.8910771874337577(3.0)'  Trigger text='Lol'
                   LOS='true'  Facing='true'
[09:32:54 INFO]: [CHAT] Goma_Terzu Lol

**Comment by mcmonkey4eva** [comment]
It makes no sense though ;-; @Morphan1 why why @Morphan1 why

**Comment by Morphan1** [comment]
@mcmonkey4eva the call uses `script` instead of `scriptEntry`? Because if iirc it wants scriptEntry for debug stuff

**Comment by mcmonkey4eva** [comment]
it wants any debuggable object and should run fine with whatever~

**Comment by Morphan1** [comment]
@mcmonkey4eva and everything is prepared to handle that?

**Comment by mcmonkey4eva** [comment]
@Morphan1 Yes.

**Comment by Fortifier42** [comment]
This is still a problem, but as I mention above, cancelling the action makes the debug not show?

**Comment by mcmonkey4eva** [comment]
Fixed in latest.

It, er, was reading the debug yaml key value of the interact script. Which, in your case, didn't exist. And thus, wasn't knowing it needed to shut up.
