### ISSUE TITLE
Item flag to hide banner patterns

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1199]
Be able to hide banner patterns on the item, similar to hiding enchantments etc.

Tried hide_attributes and it didn't work.

**Comment by Morphan1** [comment]
We don't control this, spigot does. Ask them.

**Comment by Fortifier42** [comment]
https://www.spigotmc.org/threads/hideattributes-does-not-hide-bannermeta-patterns.91230/

**Comment by Fortifier42** [comment]
@Morphan1 it's already there ;_;

**Comment by mcmonkey4eva** [comment]
@Fortifier42 Read the thread you linked yourself to solve your issue :)
