### ISSUE TITLE
CanPlaceOn Item Flag

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1201]
Enhance adventure mode mechanics by allowing items (blocks) with the `CanPlaceOn` flag to be created through denizen (easily).
Encourages adventure playwork

**Comment by Fortifier42** [comment]
nice copy paste there @brainscript :sweat_smile:

**Comment by brainscript** [comment]
@Fortifier42 :laughing: Thanks!
