### ISSUE TITLE
problem with npc's sleeping in bed at a slidly offset block

### ISSUE THREAD

**Issue by GeForcez** [DenizenScript/Denizen-For-Bukkit#1203]
i tried to test some new features of citizens and is came accross sleep i saw that he bugs one block farther if you do that and after a little he wont sleep anymore oh and also if you let an npc sits the arrow despawns and the npc stands again :D

**Comment by mcmonkey4eva** [comment]
Can you show a screenshot of the sleeping issue?

The sit issue is known and we're still unsure how to fix it.

**Comment by GeForcez** [comment]
here ya go
http://prntscr.com/8vaw4i

**Comment by GeForcez** [comment]
oh yeah and if you break the bed you get this he is returned into ashes
http://prntscr.com/8vawfx

**Comment by mcmonkey4eva** [comment]
For the bed, have you tried forcing the NPC to sleep at the /other/ bed block (there's 2 blocks per bed)

**Comment by GeForcez** [comment]
not really working http://prntscr.com/8vaxir

**Comment by mcmonkey4eva** [comment]
Issues have been mismanaged a bit, sorry for this getting ignored. I believe this should not still be an issue on latest builds - if it is, please reply below and we'll open it and investigate it more properly.
