### ISSUE TITLE
Document what events have a player and/or npc link

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Denizen-For-Bukkit#1204]
I think this should just be `@Player <info>` and `@NPC <info>` in the meta.

Examples:
`@Player when the damager is a player`
`@NPC when the entity is an NPC`

**Comment by Fortifier42** [comment]
I can work on putting the meta in, you can handle it how you please?

**Comment by mcmonkey4eva** [comment]
That'd work.

**Comment by Fortifier42** [comment]
@Talamar1 you interested in doing some of this?
