### ISSUE TITLE
Listing all flagged players

### ISSUE THREAD

**Issue by mawej1** [DenizenScript/Denizen-For-Bukkit#1205]
I think I have found a bug; If you try to list online + offline (all) players flagged 'bounty' (`<server.get_players_flagged[bounty]>`), it displays only one of them. 

However`<server.get_online_players_flagged[bounty]>`works good - see http://mcmonkey.org/paste/21663

For me it seems that it narrates everyone flagged except the player that executed the narrate command, but that's just my guess.

**Comment by mcmonkey4eva** [comment]
I don't see anything wrong with the code... can anyone test / confirm this issue - @Fortifier42 @Talamar1 ?

**Comment by Fortifier42** [comment]
@mcmonkey4eva @mawej1 Just tested on the irc
http://puu.sh/kZqWZ.png

**Comment by mawej1** [comment]
Could it have something with server mode?.. I have no idea :(

**Comment by mcmonkey4eva** [comment]
@mawej1 start by updating your server to latest builds, that's a slightly older Denizen.

**Comment by mcmonkey4eva** [comment]
Will reopen when more info / ... is provided.

**Comment by Fortifier42** [comment]
Can confirm this is an issue, albeit strange.
http://mcmonkey.org/paste/22262

**Comment by mawej1** [comment]
I'm sorry I wasn't able to give more information, but I will shortly.
I tried to reproduce this on a different server with basically the same configuration, and didn't spot any problems.

**Comment by Fortifier42** [comment]
@mawej1 Source code wise, there is no real reason it shouldn't work...

**Comment by mcmonkey4eva** [comment]
Is this still an issue?
