### ISSUE TITLE
dsentry denizen script cant load saved dsentry presets

### ISSUE THREAD

**Issue by GeForcez** [DenizenScript/Denizen-For-Bukkit#1206]
hey guys me (again) i found that dsentry saves the preset correctly but cant load it ? any help ?
love G_4s

**Comment by mcmonkey4eva** [comment]
- What are you trying exactly (What commands)?
- What errors/messages does it give you?

**Comment by GeForcez** [comment]
Well /dsentry save (name) that makes a file so that works but if you try to load it with /dsentry load (name) with tje exact name as in the file it doesnt find it

**Comment by mcmonkey4eva** [comment]
That's not exact messages, that's a rough transcription of what you think happened.

**Comment by mcmonkey4eva** [comment]
Oh, you did `load`. The command is` create`.

**Comment by GeForcez** [comment]
I meant that sorry but it says name not found

**Comment by GeForcez** [comment]
And ther is clearly that name in the dsentry save file

**Comment by mcmonkey4eva** [comment]
`not found` is not an error message dSentry has coded.

**Comment by GeForcez** [comment]
I dont remember the exact message i got in minecraft but it was name not found it does try to load the presets but it doesnt find the name

**Comment by mcmonkey4eva** [comment]
Can't help you with minecraft if you can't even _open_ minecraft. 0.o
I need exact messages here.

**Comment by GeForcez** [comment]
No thats not what i mean 2 houres ago i was on minecraft trying that create command after i saved a guard preset if i create a dsentry guard it says that it could not find a preset with that name

**Comment by mcmonkey4eva** [comment]
Okay I'm going to make this as clear as I possibly can...

Do **NOT** reply to this issue until you are able to **Open Minecraft** and get the **Exact** response message.

Any discussion until then is mere guesswork.

Also, do be sure you're running the latest repo copy of the script.

**Comment by mcmonkey4eva** [comment]
UPDATE: I fixed a minor bug that may be the cause of your issue (with help from another user reporting an error). Please update dSentry off -> http://mcmonkey.org/denizen/repo/entry/0

**Comment by GeForcez** [comment]
yup that was the fix...

**Comment by mcmonkey4eva** [comment]
Yay
