### ISSUE TITLE
<context.item> is invalid and questions

### ISSUE THREAD

**Issue by o0ower0o** [DenizenScript/Denizen-For-Bukkit#1207]
Hi, I have some script that use the "on player clicks in CustomInventory and then in the body I check with <context.item.simple> or <context.item.id> to check the item the players clicked. The scripts work fine, but it just randomly spam this error in console and I can't understand when or why:

ERROR! [0;37;1mInvalid context ID 'item'!
ERROR! [0;37;1mTag <context.item.id> is invalid!

Also I have some questions:

1) Is it reasonable to have a script that executes /denizen save every 15 minutes? Is there a better way to save flags on disk to avoid to lose everything if the server crashes?

2)How can i use the cooldown command in a task script? "cooldown p@player <duration> s:s@script" will work?

3) I saw that the listen command is now outdated, could you give me some advices on how to replace them? Do I just use flags or there is a better way?

Thank you, Ower

git-Spigot-06ad352-4a7472d (MC: 1.8.8)
Denizen 0.9.7-SNAPSHOT (build 1599)

**Comment by mcmonkey4eva** [comment]
For the first part, we'll need to see a script + full debug logs.

for "1": yes, that's actually done quite commonly.

for "2": `- cooldown <DURATION> s:<SCRIPT>` -> optionally add `player:<PLAYER>` to change the player link.

for "3": Events replace listeners.

**Comment by o0ower0o** [comment]
This is the error
http://mcmonkey.org/paste/21674
I got it when I closed the inventory by pressing ESC, but then I tried again and it didn't happen

This is the script
http://mcmonkey.org/paste/21675
I just copied the command script and the world script for the clicks, if you need I can copy the Item scripts too.

Oh! Also 4) Can I set the speed for the scripts to 0.0 in the config or should I keep it a little bit higher to avoid lag/other awful things that can happen?

**Comment by mcmonkey4eva** [comment]
For the main issue, I pushed a patch to Denizen - that build is available here: http://ci.mineconomy.org/job/Denizen_Developmental/390/

for "4", keep script speeds at 1 or higher. If you need things running instantly, use the "instantly" argument when running a task, or the `^` symbol where you can't.

**Comment by o0ower0o** [comment]
Ok, thank you! I'll let you know if I get the error again :D
