### ISSUE TITLE
last_played doesn't fill in correctly for first time players

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1208]
When a player joined the server for the first time, for as long as he hasn't logged off yet, the tag `<p@player.last_played>` will not return the proper information. 

Wherever the data is stored, it should also be updated on login and not just logout, to avoid that issue

**Comment by Fortifier42** [comment]
Check if player is currently online first before using it?

**Comment by BlackCoyote** [comment]
That's not how it fails. The player can be online and this tag could still fail or atleast return incorrect data. When the player logs on for the first time, if you then try to use the tag on him for as long as he is online and has not logged of yet, it'll return incorrectly. i believe it returns d@0t (making my server thing he's been inactive since january 1970). This data is already updated every single time the player logs out, i doubt it'll be that much more intense if it also updates when the player logs in.

**Comment by Fortifier42** [comment]
Oh, I misinterpreted your request, I thought you meant constantly update the value, not on login only!
:+1:

**Comment by BlackCoyote** [comment]
:+1:

**Comment by Fortifier42** [comment]
would seem we rely on a spigot function for this.
http://puu.sh/kZqpT.png

I believe, then the best solution would be, if the player is currently online, return the current time rather than lastPlayed.

Consider if that would be acceptable, @BlackCoyote ?

**Comment by BlackCoyote** [comment]
that would probably be a way better solution in various ways than what I initially asked
