### ISSUE TITLE
Denizen related EXCEPTION_ACCESS_VIOLATION and server crash

### ISSUE THREAD

**Issue by PsychoLynx** [DenizenScript/Denizen-For-Bukkit#1212]
Hey there! After recently updating to Spigot 1.8.8 and updating all of our plugins to the newest version, our server has begun crashing semi-regularly with some sort of Java error that mentions DenizenPacketListener. This happened with Denizen build 1600 of denizen and Citizens build 1267 (so the latest dev builds to date). So far we've been unable to link it to any specific player event.

Here's the Javadump:
http://pastebin.com/Mbzvj0Ap

Thank you in advance!

**Comment by mcmonkey4eva** [comment]
@Morphan1 any ideas on what this is?

**Comment by Fortifier42** [comment]
try the actual dev build http://ci.mineconomy.org/job/Denizen_Developmental/lastSuccessfulBuild/

If that doesn't work, disable async chat in the config.

**Comment by PsychoLynx** [comment]
Thanks guys! I dunno why I was following the other repo for updates, but I'll see if this fixes the problem.

**Comment by Fortifier42** [comment]
Denizen is still in development, but we keep an 'extra-dev' build, before pushing into the main release :smile:

**Comment by PsychoLynx** [comment]
Okay, so we crashed again with the latest dev build from the above link. I will disable async chat and see if it helps.

**Comment by Morphan1** [comment]
@PsychoLynx what kind of JVM are you using? Updating it might help

**Comment by PsychoLynx** [comment]
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode).

**Comment by PsychoLynx** [comment]
Well, another crash occured with the same error code. I guess I'll have to look into updating the JVM :/

**Comment by Talamar1** [comment]
Java Hotspot?  Try a regular JRE?

**Comment by PsychoLynx** [comment]
Seems to be resolved now. This can be closed.
