### ISSUE TITLE
Can't use <player.health> for offline player

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1213]
Hey there `<player.health>` `<player.health.max>` etc return always null for offline players. Could you maybe change that?

**Comment by Morphan1** [comment]
Forgot to say, should be fixed in the latest dev builds

**Comment by Fortifier42** [comment]
Yeah this is fixed. tested now.

**Comment by GomaTerzu** [comment]
Thanks, closed
