### ISSUE TITLE
"on player fishes" returns an error on <context.entity>

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#1215]
"on player fishes" will pretty much always return an error when I use <context.entity>. 
Can it be set to null if there is no entity instead of breaking the entire tag/script?
Here is the debug, when I try to call <context.entity> whenever I use the fishing rod:
http://mcmonkey.org/paste/22202
Notice I first right-click to throw the hook and returns the error, it hits the pigs, then I right-click again to pull it back and the tag returns correct, being the pig.

**Comment by Fortifier42** [comment]
this is why we have fallbacks. 
`<context.entity||null>`
```
- if <context.entity||null> == null {
  - queue clear
}
```

**Comment by Mwthorn** [comment]
Oh, right... whoops!
