### ISSUE TITLE
[Question] Characters (Symbols)

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1216]
I want to use these two symbols ...
* [» RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK](http://www.fileformat.info/info/unicode/char/00bb/index.htm)
* [« LEFT-POINTING DOUBLE ANGLE QUOTATION MARK](http://www.fileformat.info/info/unicode/char/00ab/index.htm)

... but I don't know how to use them in a script. I found the `[<&chr[character]>](http://mcmonkey.org/denizen/tags/&chr)` tag on the documentation page but I don't know what I have to put in the brackets.

Putting `\u00BB` directly into the script returns "\u00BB" in the chat. Pasting the symbol itself into the script returns a weird looking "A" in front of the symbol.

Converting the script to UTF-8 breaks the script and definitions like `%rank%` don't work any longer.

**Comment by Fortifier42** [comment]
It's a unicode id. `<&chr[00BB]>` `<&chr[00AB]>`

**Comment by brainscript** [comment]
@Fortifier42 Thanks so much! Maybe @mcmonkey4eva could add a better description to the documentation with an example usage.

**Comment by mcmonkey4eva** [comment]
Anybody is welcome to PR improved meta descriptions.

**Comment by Fortifier42** [comment]
@mcmonkey4eva I did
