### ISSUE TITLE
Commas should be escaped...

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1218]
Commas should be able to be escaped... Simple :)

**Comment by Morphan1** [comment]
"self explanatory" for what purpose  tho

**Comment by Fortifier42** [comment]
Nowhere did I say it was self explanatory... But as an example

`- if <def[Input]> != <def[Input].escaped>` to ensure input is completely plain text..

**Comment by Morphan1** [comment]
Oops, I guess I responded with one of your other issues in mind
Anyways, that seems kinda like a hackish way to do that...idk though, let's see what @mcmonkey4eva says

**Comment by mcmonkey4eva** [comment]
That's not what the escape system is for ;-;

**Comment by Fortifier42** [comment]
Okiedokie then!
