### ISSUE TITLE
unequip command

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1219]
Self explainatory.. Ability to unequip items from specified slot (same as equip)

**Comment by Morphan1** [comment]
... `- equip head:i@air`

**Comment by Fortifier42** [comment]
doesnt give the item back tho ;_;

**Comment by Morphan1** [comment]
That's... Not our job, that's like saying the equip command should take an item from them

**Comment by Talamar1** [comment]
What if they don't have inv space when you unequip, where do you put it?  This is why it is the coders responsibility to deal with it.

**Comment by Morphan1** [comment]
Yeah, I'm just gonna...
