### ISSUE TITLE
 Fallback is failing with an Internal Exception error?

### ISSUE THREAD

**Issue by teateatea** [DenizenScript/Denizen-For-Bukkit#1220]
Hello!

I have some previously functioning scripts, that are now throwing a lot of Internal Exception Errors.
I had not updated since dev build 360 (because I wasn't coding and everything was generally working), and today I updated to build 408.

Consistently, any tag that runs like <c.args.get[2].escaped||null> or <player.nation.name||null> seems to break down.

Here's a script of mine:
http://mcmonkey.org/haste/22308

And here's the debug:
http://mcmonkey.org/paste/22306

Note that Internal Exceptions are thrown on both the first if command and the define command that occurs after the if completes. Both would require the fallback to fill, but something goes wrong in there.

Is this on your end?

How can I work around this?

Thank you for all your help,
tea

**Comment by mcmonkey4eva** [comment]
Update Depenizen.

**Comment by teateatea** [comment]
Thank you! I'll thoroughly update *everything* next time!
