### ISSUE TITLE
Leash command NullPointerException.

### ISSUE THREAD

**Issue by mw1fly** [DenizenScript/Denizen-For-Bukkit#1221]
Code taken from the video tutorials (RancherQuest)
http://mcmonkey.org/haste/22357
recorded logs
http://mcmonkey.org/paste/22359

leash command is giving a java.lang.NullPointerException when trying to take the leash from the player and attaching it to a fence post that the npc has placed.

**Comment by mcmonkey4eva** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/CraftWorld.java#1080 is the error - it can't seem to find an appropriate place to put the leash hitch, if I read this javababble correctly.
I don't see any reason the error should happen though, beyond pure bad logic in Bukkit's code.

It appears to be expecting a solid block next to the fence which it can attach to. Try putting a block or secondary fence post immediately next to (touching) that block.

Probably we need to go complain to Spigot that there's an error with that code.

**Comment by mw1fly** [comment]
I have done as you suggested,  I can confirm that when I put a block next to the fence post the script executes as expected,  the leash gets attached to the post.
Do I need to log this with Spigot somehow?

**Comment by mcmonkey4eva** [comment]
I sent in a message at Spigot's development IRC channel, hopefully someone will respond. If not, we'll need somebody to post an official issue on Spigot's issue tracker...

**Comment by mcmonkey4eva** [comment]
Spigot issue, up to them to fix
