### ISSUE TITLE
Command for Text above XP Bar

### ISSUE THREAD

**Issue by GravityX** [DenizenScript/Denizen-For-Bukkit#1222]
So I believe in 1.8 they added the ability for text over the XP Bar. I think it would be useful to add a command similar to the title command that allowed text to be displayed there.

Here's an example of how Jobs uses it:
![Jobs Example](https://i.gyazo.com/83c427c0d5cf2b369dbdfb4dc5a900f4.png)

**Comment by mcmonkey4eva** [comment]
You say that like we don't already have one :P 
`- adjust <player> "action_bar:<&e>You gained a <&b>potato<&e>!"

**Comment by GravityX** [comment]
Ok :P Thank you mcmonkey, asked in chat and couldn't find anything on it.

**Comment by mcmonkey4eva** [comment]
What chat? Denizen has an official chatroom -> http://mcmonkey.org/ircchat_denizen
