### ISSUE TITLE
Wood planks in Item scripts

### ISSUE THREAD

**Issue by o0ower0o** [DenizenScript/Denizen-For-Bukkit#1223]
Hello, I have this simple script: http://hastebin.com/ayizozoras.rb

My issue is that I can get this craft only if I use Oak Planks, but I want to craft it with any type of planks. I tried with i@5 or only wood, but the outcome is the same. I tried i@planks too, but it doesn't work for any type of planks.

Is there any way to accomplish this? Should I use the "on item crafted" event to do this?
Thank you, Ower

**Comment by Fortifier42** [comment]
You need to create a script for each type of plank.

OR

Use an on item crafted script and `- determine i@newitem` when crafting wooden sword.

**Comment by o0ower0o** [comment]
What if I want to create a new recipe with wood like this: http://hastebin.com/ayupexonoy.rb
I want it to be different from the basic mineacraft axe, how can I use the events in this case?

**Comment by Fortifier42** [comment]
That will require a different itemscript for each wood type.

**Comment by o0ower0o** [comment]
Ok, thank you for your answer
