### ISSUE TITLE
shapeless custom recipe overlays normal mc recipes

### ISSUE THREAD

**Issue by GomaTerzuTheSecond** [DenizenScript/Denizen-For-Bukkit#1225]
I made thisvery small recipe:

String:
  type: item
  material: 287
  no_id: true
  shapeless_recipe: i@wool

Now whenever i try to craft something that contains white wool - like a bed  I can see the bed for a small moment in the result slot, but then it gets overlaid by string. 
When I click on the result slot it uses every material i needed for a bed and I get a string for it.

**Comment by BlackCoyote** [comment]
a potential temporary fix untill it gets solved within denizen might be to make the recipe shapeless_recipe: i@wool|i@air|i@air|i@air|i@air|i@air|i@air|i@air|i@air

**Comment by GomaTerzuTheSecond** [comment]
Nope, won't work. I still get the string as result, even when there is other material in the crafting slots

**Comment by Fortifier42** [comment]
@Morphan1 This needs to be fixed pls <3

**Comment by dearvoodoo** [comment]
Test this:
`  recipe:
  - i@air|i@air|i@air
  - i@air|i@white_wool|i@air
  - i@air|i@air|i@air`

You need to create a recipe for all wools. For the wool ID proceed like this:
1: Take for exemple Red wool in your hand (in-game)
2: Type the command /ex narrate <player.item_in_hand>
3: Chat appears red wool ID `i@red_wool`

PS: sorry for my bad english and up post dating 2 months ;)

**Comment by mcmonkey4eva** [comment]
Redirecting to #1851

**Comment by mcmonkey4eva** [comment]
Fixed by the resolution to #1851
