### ISSUE TITLE
Mobile/Phone Support

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#1226]
This may sound over the top and unrealistic...
Can we have mobile support for Denizen? We would write a command that sends an SMS to a specefic number:
- mobile (CALL/SMS/PLAY) (number) (text/sound)

For example you could recieve a SMS using a denizen commmand like:
- mobile SMS +12501398532 text:"The server <def[server]> has crashed! Please do something!"

Or say if we wanted to call the user:
- mobile CALL +12501398532

Use some kind of service for the user to hear or listen to:
- mobile PLAY +12501398532 sound:"welcome.mp3"

We could also have events, if the server has a number as well:
- On mobile SMS:
- On mobile CALL (Begins/Ends):
- On mobile presses (NUMBER):

With tags like:
<context.phone> returns the number that called or wrote the sms
<context.message> returns the message of the SMS
<context.duration> returns the duration of the call
<context.number> returns the number that was pressed

**Comment by mcmonkey4eva** [comment]
Please do not make joke posts.
