### ISSUE TITLE
Map command crashing server.

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Denizen-For-Bukkit#1227]
crash dump: [http://mcmonkey.org/paste/22485] (http://mcmonkey.org/paste/22485)

I gave myself map 0
then tried to use - map 0 image:test.png
the server would not register any movement while i was holding map 0 ie. using - narrate <player.location> would result in the location the map first went into my inventory.
Figuring this was a bug i decided to put the map in an item frame to see if the image would show up.
As soon as i put map 0 in an item frame the server crashed. when ever joining the server to remove the map the server crashed.
I remove Denizen.jar and loaded up the server, removed the item frame with map 0 and reloaded Denizen to fix the chunk.

**Comment by mcmonkey4eva** [comment]
What is test.png?

**Comment by mcmonkey4eva** [comment]
The `resize` argument might be of relevance here.

**Comment by KeangDavid** [comment]
I tried with and without resize. Either way, the server crashing should not happen. even if the parameters are wrong. I was following the example documented for the map command. I just simply could not get it to work. As well as the whole crashing thing.

**Comment by mcmonkey4eva** [comment]
Can you perhaps give us a copy of `test.png` to see if we can replicate this?

**Comment by KeangDavid** [comment]
image: [test.png] (https://gyazo.com/f0275a6b7be53a23cae02bd4aa44707e)

**Comment by Fortifier42** [comment]
cannot replicate this
http://puu.sh/lxNPr.jpg

**Comment by KeangDavid** [comment]
What commands did you use to set it to this?

**Comment by Fortifier42** [comment]
`/ex map 0 image:https://i.gyazo.com/f0275a6b7be53a23cae02bd4aa44707e.png resize`
while I had map 0 in my hands..
