### ISSUE TITLE
Take command replaces with air

### ISSUE THREAD

**Issue by GomaTerzuTheSecond** [DenizenScript/Denizen-For-Bukkit#1230]
When I use the take command to take something from an inventory, it replaces the inventory content with air. 

Example:

i@stone_axe|i@apple|i@dirt|i@clay_brick

Now i take away the apple and list the inventory of the player and it says:

i@stone_axe|i@air|i@dirt|i@clay_brick

I always expected it to look like

i@stone_axe|i@dirt|i@clay_brick

**Comment by Talamar1** [comment]
No, inventory is slot based, so when you take from inventory, you replace it with air.

**Comment by GomaTerzuTheSecond** [comment]
Nevermind I just realized your right. Just had never to look at it that closely
