### ISSUE TITLE
<context.damager> stopped working for CUSTOM cause

### ISSUE THREAD

**Issue by GomaTerzuTheSecond** [DenizenScript/Denizen-For-Bukkit#1231]
I just updated one of my server to the latest dev build where I use the hurt command with cause:custom a lot. It basicaly looks like this:

on player right clicks with Weapon:
`- shoot button origin:<player> script:WeaponDamage`

"WeaponDamage":
type: task
`- hurt 10 entities:<def[hit_entities]> cause:custom`

on player damaged by custom:
`- announce "<context.damager.name> shot <context.entity.name>"`

This worked fine until now. It does not resolve <context.damager> anymore.

I also tried to hurt myself with `/ex hurt <player> 1 cause:custom`. The event fires but `<context.damager>` does not work.

I also tried to make something like this

on player right clicks with stone:
`- hurt <player> 1 cause:custom`

Nothing works for `<context.damager>` anymore

**Comment by mcmonkey4eva** [comment]
You need to use `source:<ENTITY HERE>` to specify the damager.


Bear in mind specifying a damager, especially a player, can cause the damage to fail, as it tends to get blocked by random things. (EG, NoCheatPlus will not like a player damaging an entity from too far away)

**Comment by GomaTerzuTheSecond** [comment]
I looked into my Backup files and noticed that "source" was there before I updated. Dunni why it was gone. Maybe I made some changes I forgot about. Thanks.
