### ISSUE TITLE
"skull_skin" in item script

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1233]
```
# "op_" is the prefix of my options scripts

op_back:
    type: item
    material: SKULL_ITEM,3
    skull_skin: MHF_ArrowLeft
    display name: "<&7><&l>Back"
```
... does not show up with the skin in my GUI and in my inventory.

`/ex give i@op_back[skull_skin=MHF_ArrowLeft]` works.

But I want to set the skin directly in the item script.

**Comment by mcmonkey4eva** [comment]
No such item script key ( http://mcmonkey.org/denizen/lngs/item%20script%20containers )
You can do `material: human_skull[skull_skin=MHF_ArrowLeft]`

**Comment by brainscript** [comment]
@mcmonkey4eva Ok, I thougt I can use any dItem mechanism in item scripts.

**Comment by brainscript** [comment]
@mcmonkey4eva Why `human_skull`? Is this an alias implemented in Denizen? I can't see it on the [Spigot Documentation](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html).

**Comment by mcmonkey4eva** [comment]
Yes, Denizen has its own special list of items to handle the potential (Threatened by Mojang) future loss of datavalues.
