### ISSUE TITLE
alphanumeric sorting inconsistencies

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1236]
``` <BlackCoyote> >tag <li@1|2|0.alphanumeric>```

```<Tag-Parser> BlackCoyote: the tag '<li@1|2|0.alphanumeric>' fills with 'li@0|1|2'```

```<BlackCoyote> >tag <li@1A|2A|0A.alphanumeric>```

```<Tag-Parser> BlackCoyote: the tag '<li@1A|2A|0A.alphanumeric>' fills with 'li@1A|2A|0A'```

```<BlackCoyote> it puts 0 first but 0A last ```

As you can see, when it's only numbers, it'll sort 0 first, but if it's a string with both numbers and letters, it'll sort values starting with 0 before values starting with 1

**Comment by Talamar1** [comment]
Because the library they are using doesn't do what they think it does:
```
            // skip over leading spaces or zeros
            while (Character.isSpaceChar(ca) || ca == '0')
            {
                if (ca == '0')
                {
                    nza++;
                }
                else
                {
                    // only count consecutive zeroes
                    nza = 0;
                }

                ca = charAt(a, ++ia);
            }
```
As seen in this result as well:
```
ex narrate <li@0c|0A|2b.alphanumeric>

[11:38:01 INFO]:  Filled tag <li@0c|0A|2b.alphanumeric> with 'li@2b|0A|0c'.
[11:38:01 INFO]: +> Executing 'NARRATE': Narrating='li@2b|0A|0c'
                   Targets='null'
[11:38:01 INFO]: li@2b|0A|0c

**Comment by Fortifier42** [comment]
is this acceptable? http://puu.sh/lBEJM.png

**Comment by Talamar1** [comment]
Looks like that works.

**Comment by Fortifier42** [comment]
Well hey! It doesn't!

**Comment by Fortifier42** [comment]
@Talamar1 Feel free to rewrite the comparator or add a new one.

**Comment by Talamar1** [comment]
Ultimately, what is the proper sort for strings, that's been a debate for a while.
A99 vs A101
What is the proper order, A99,A101 because 99 is less than 101, or A101,A99 because 1 < 9, each sorting method has it's merits.  Maybe there should be tags for ascii sort and alphanumeric?

**Comment by mcmonkey4eva** [comment]
@Talamar1 there are both those tags already 0.o

**Comment by Talamar1** [comment]
So, .alphabetical is really .ascii and .alphanumerical is really .naturalorder

**Comment by Talamar1** [comment]
@BlackCoyote if you use .alphabetical, you will get the results that you want....

**Comment by BlackCoyote** [comment]
If i use alphabetical, i will not get the results I want. my example clearly demonstrated my use case that is not purely numerical

**Comment by BlackCoyote** [comment]
Either way i worked around it by adding 0.1 to every number in front of the string, eliminating the possibility of one being 0

**Comment by mcmonkey4eva** [comment]
Shouldn't really rely on this either way.

**Comment by BlackCoyote** [comment]
I have no choice as procedural sorting is slow as hell, and doing it async is impossible
