### ISSUE TITLE
Inventory Titles Can be Longer Than 32

### ISSUE THREAD

**Issue by Mickket** [DenizenScript/Denizen-For-Bukkit#1238]
Inventories can be longer than 32 characters. I believe they can contain as many characters  as e@custom_name  does. Going above the limit on entity names (Putting the item in an item frame) causes errors on the Minecraft client.

/i hopper 1 name:&1This_&2Title_&3Is_&4Longer_&526_&9Characters_&0Long.

**Comment by Fortifier42** [comment]
What exactly is the issue...

**Comment by mcmonkey4eva** [comment]
I assume it's limiting his input in Denizen.
@Morphan1 ?

**Comment by Mickket** [comment]
Sorry about the obscure title. Denizen Inventory scripts don't allow for inventory titles longer than 32 characters. I assume this was the case in previous Minecraft versions. Going above the 32 character limit defined in Denizen, right now, will result in a blank title. Normally this is not an issue but when using a moderate title length with several colors you tend to hit that limit real quick.

**Comment by mcmonkey4eva** [comment]
`Inventory scripts`
`Going above the 32 character limit defined in Denizen, right now, will result in a blank title.`
Denizen only applies this limit to **notable** inventories, not any given script, and applies it by cutting the name short, not blanking the title.

**Comment by Fortifier42** [comment]
This would appear to be a Bukkit/Spigot limitation.
```JAVA
        public MinecraftInventory(InventoryHolder owner, int size, String title) {
            this.maxStack = 64;
            Validate.notNull(title, "Title cannot be null");
            Validate.isTrue(title.length() <= 32, "Title cannot be longer than 32 characters");
            this.items = new ItemStack[size];
            this.title = title;
            this.viewers = new ArrayList();
            this.owner = owner;
            this.type = InventoryType.CHEST;
        }
```
