### ISSUE TITLE
Player name problem

### ISSUE THREAD

**Issue by vicknyaz112** [DenizenScript/Denizen-For-Bukkit#1240]
I've got a big problem here.
For example, my nickname is Test. When I type /ex narrate player.name, it returns "Test". But when i type /ex narrate p@Test.name, it returns "test". Is there any way to avoid this conversion to lowercase? Because the flags in saves.yml are saved differently, too. Though it seems like it doesn't work for most of the players. Thanks for your help!

saves.yml example: http://pastebin.com/tA6UnrZn

**Comment by Morphan1** [comment]
You're using a really old version

**Comment by brainscript** [comment]
@vicknyaz112 The players are saved with their names. :open_mouth: That has to be a reaaaaaalllyyy old version.
In newer versions they ared saved with their unique UUID.

**Comment by Morphan1** [comment]
The best we can really tell you to do is fiddle around with things until it works. Try upgrading or downgrading a few builds. We can't really support old versions.

**Comment by mcmonkey4eva** [comment]
@vicknyaz112 We can tell you, though, to **seriously update to latest version of everything!** This fixes so many issues and gets you so many more features!
