### ISSUE TITLE
Another server crash error

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1243]
I get these kind of crashes 3 days on a row now.

Anyone got an idea what might be the cause?

http://mcmonkey.org/haste/22928

**Comment by Morphan1** [comment]
@GomaTerzu it looks like you're doing something with an inventory in an unloaded chunk? Most likely in an async thread, possibly in an "on server list ping" event?

**Comment by GomaTerzu** [comment]
I stopped using the "unique ping" counter in BlackCoyotes script and had no crash in 3 days now. I am using a bungeecord setting and the "on server ping" won't work with that. Maybe this caused the errors. You can close this if you have no clue if you can find a fix or not.

**Comment by GomaTerzu** [comment]
I had to delete my previous comment. It happened again at 2:40 am this night.

http://mcmonkey.org/paste/23025

**Comment by mcmonkey4eva** [comment]
@GomaTerzu Can you please post all scripts that use `list ping` events that you still have active?

**Comment by GomaTerzu** [comment]
Only this from BlackCoyote. I just overlooked that it of course still uses the event ..I only deactivated logging...

http://mcmonkey.org/denizen/repo/entry/58

**Comment by GomaTerzu** [comment]
I have to inform you, that I did not have a single crash for this reason in almost two weeks now. So the only thing I changed was remove blackcoyotes script and webizen.

**Comment by BlackCoyote** [comment]
;(
