### ISSUE TITLE
bug with enderdragon entity

### ISSUE THREAD

**Issue by Culvanen** [DenizenScript/Denizen-For-Bukkit#1244]
Hi,
I have a strange bug with my script:

At the dragon that killed the script does not execute the reward code, or can you just tell me the problem?

http://mcmonkey.org/haste/22930

Thanks

**Comment by mcmonkey4eva** [comment]
You're doing everything wrong from the start.

Please check out http://mcmonkey.org/denizen/vids for examples on how to do things, in particular http://mcmonkey.org/denizen/vids/Putting%20It%20Together:%20A%20Kill%20Quest is of relevance
