### ISSUE TITLE
Villager support

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Denizen-For-Bukkit#1245]
There is no support for villager trades.

~~Adjusting a villager's name removes the ability to trade with it.~~ This is not consistent. More testing required.

Could also do with a entity.trades tag, and an adjust entity trades mechanic.

**Comment by brainscript** [comment]
+1

**Comment by Talamar1** [comment]
@Morphan1 ?

**Comment by Fortifier42** [comment]
This will require some pretty shitty NMS D:

**Comment by Fortifier42** [comment]
We have ShopKeepers support as of now, so you can use that if it's super urgent. (Depenizen)

**Comment by mcmonkey4eva** [comment]
added via https://github.com/DenizenScript/Denizen-For-Bukkit/pull/1892
