### ISSUE TITLE
Permission group problems

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1249]
Sometimes the `<player.groups>` flag returns an empty list... (`li@`)
... althoug the player has at least one group.

The "older" Groups like Owner, Admin, Builder, Mod, ... work as expected.
But newer Groups like Youtuber, Donator, Streamer, ... don't work.

I'm using latest Spigot, Pex and Vault.

**Comment by Fortifier42** [comment]
we recommend <player.in_group[group].global> to check for groups :)
