### ISSUE TITLE
Give Heroesexp

### ISSUE THREAD

**Issue by o0ower0o** [DenizenScript/Denizen-For-Bukkit#1250]
Hi, I saw in old scripts that there was the option to give the players heroes experience using:
- give heroesexp qty:#

From the code it looks like it has been removed. Is there any chance to get it back (here or in Depenizen)? I'm using 

```
 execute as_server "hero admin exp <player.name> <player.heroes.primary_class.name> 200"
```
But it gives logs in console and to the players so it's not really optimal

**Comment by mcmonkey4eva** [comment]
This is a request more suited for **Depenizen** https://github.com/DenizenScript/Depenizen-For-Bukkit
