### ISSUE TITLE
bungeetag doesn't parse definitions outside of tags

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1251]
http://mcmonkey.org/paste/23414#170

          `- define tag <def[args].get[3]>`
          `- define server "server@<def[args].get[2].after[server<&co>]>"`
          `- ~bungeetag %tag% "server:%server%" save:tag`

from the debug it looks like it's trying to do the command with both %tag% and %server% unparced. I tried using <parse:%def%> with no luck either

**Comment by Morphan1** [comment]
Just use <def[]>, it's bring sent to the server regardless anyway

**Comment by BlackCoyote** [comment]
That worked for the server argument, but with the tag argument, it parsed the definition on the target server, and returned the tag, unparsed, as outcome

**Comment by mcmonkey4eva** [comment]
... uh, for clarity:

- What is the contents of each relevant definition?
- What is it returning?
- What do you expect it to return?

**Comment by BlackCoyote** [comment]
see debug recording included with issue plox

**Comment by mcmonkey4eva** [comment]
That neither answers all questions nor does it provide consideration to morphan's response.

**Comment by BlackCoyote** [comment]
the contents are identical to in the debug recording
as stated before: it returned the tag within the definition, unparsed, as outcome
what i expect it to return: the parsed outcome of the tag that is stored within the definition

**Comment by mcmonkey4eva** [comment]
Being obtuse will get you nowhere.

**Comment by BlackCoyote** [comment]
don't be grumpy, i genuinely do not know what more you'd like to know

**Comment by mcmonkey4eva** [comment]
```
The def 'args' is equal to "li@x|y|z"
The command is returning "bob Smith"
I expected it to return "<Bob Johnson>"
```
For example.

**Comment by BlackCoyote** [comment]
filled definition %tag% with '<server.list_online_players>'.  
The command is returning "<server.list_online_players>"
I expected it to return "li@p@4c570928-3648-4583-9148-ee5ca157e175"

**Comment by mcmonkey4eva** [comment]
@BlackCoyote if the tag won't parse locally, it won't parse remotely either.

You need `<parse:>` to parse tags that were input in the form of raw text (which an IRC message is.)

**Comment by Fortifier42** [comment]
to elaborate further, @BlackCoyote you tried `<parse:%tag%>`. You need to do `<parse:<def[Tag]>>`

**Comment by BlackCoyote** [comment]
I also tried the latter, it sends <parse:<def[tag]>> to the other server and returns <server.list_online_players>

**Comment by mcmonkey4eva** [comment]
` it sends <parse:<def[tag]>> to the other server and returns <server.list_online_players>`
Show us the (ideally full this time) script + debug from where you tried this?

**Comment by BlackCoyote** [comment]
turns out it sends `<def[tag]>` to the server

          `- define tag <def[args].get[3]>`
         ` - define server "server@<def[args].get[2].after[server<&co>]>"`
      `    - ~bungeetag <parse:<def[tag]>> "server:<def[server]>" save:tag`


http://mcmonkey.org/paste/23447#129

**Comment by mcmonkey4eva** [comment]
**mcmonkey falls over and dies**

Just for giggles, @BlackCoyote , try `tag:<parse:<def[tag]>>`

**Comment by BlackCoyote** [comment]
it worked but it didn't make me giggle

**Comment by mcmonkey4eva** [comment]
Excellent, I know what's wrong then. Will fix momentarily.

**Comment by BlackCoyote** [comment]
okay it made me giggle a little bit

**Comment by mcmonkey4eva** [comment]
Fixed via https://github.com/DenizenScript/Depenizen-For-Bukkit/commit/9265c1c7b440dc0c03db9f715a9d819ce5c16ac9 (build 276 of Depenizen)
