### ISSUE TITLE
wordguard regions detection

### ISSUE THREAD

**Issue by silentspectr** [DenizenScript/Denizen-For-Bukkit#1252]
Hi 
i'm making a quest where the player needs to go to a specific location in order to continue the quest but i can't manag to do it. 
does it works with worldguard regions ? 
or a specific denizen region ?
and what's the command ? 
i found <player.inregion[region_name]> but in what kind of script do i put it ? 
a worldscript ? 
or in an assignment one with a proximity trigger ? 

Thanks

**Comment by BlackCoyote** [comment]
yes

**Comment by mcmonkey4eva** [comment]
...
Come on IRC and ask questions slowly and coherently.
http://mcmonkey.org/ircchat_denizen
