### ISSUE TITLE
Error: Generating player heads too fast

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1254]
I made a custom inventory (as a GUI) with custom items made from player heads.

example of a head button:
http://mcmonkey.org/paste/23608

The inventory contains 5 heads. Sometimes when I open it I get these errors:

http://mcmonkey.org/paste/23607

The inventory still opens and every head has a texture. So basically it works but annoys my console.

Same thing happens when I use /ex give item alot.
When I use a command block to give me the same item, I won't get any errors at all.

Example of command block code:
http://hastebin.com/bubevaqece.sm

So a Mojang command won't get me any errors, the denizen stuff does. Is there a way to catch it?

**Comment by mcmonkey4eva** [comment]
What version of Denizen are you running?

**Comment by GomaTerzu** [comment]
Denizen Dev Build #419 (29.11.2015 16:11:25)

**Comment by mcmonkey4eva** [comment]
Dealt with.

**Comment by GomaTerzu** [comment]
Problem wasn't solved with this attempt.

http://hastebin.com/cicobelusi.apache

**Comment by mcmonkey4eva** [comment]
Uhm... are you sure you have a jar with the relevant fix included?

**Comment by GomaTerzu** [comment]
Yes of course

**Comment by GomaTerzu** [comment]
This issue is not solved and the errors still come up in the console

**Comment by mcmonkey4eva** [comment]
@Morphan1 wat.

**Comment by Devotedworker** [comment]
Has been fixed. I have yet to encounter this bug in recent builds, it may have been squashed.

**Comment by GomaTerzu** [comment]
No, it is still there http://mcmonkey.org/paste/30462

**Comment by GomaTerzu** [comment]
Seems to be fixxed now. Won't get any error anymore. Thank you guys!
