### ISSUE TITLE
Bug: can't take (some) custom items with take command

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1255]
Custom items that use tools like swords, axes, shovels as material can't be taken away with the denizen take command. You get no error and the debug says that the command was executed.

http://mcmonkey.org/paste/23676

Every other custom item does not seem to have this problem

**Comment by mcmonkey4eva** [comment]
Please post relevant script(s)

**Comment by GomaTerzu** [comment]
http://mcmonkey.org/paste/23703

/ex give p30

/ex take p30

Won't work. But I found out that it probably has something to do with the random decimal I use in the lore. I once made a system where every single weapon is unique. So probably the take command does not know which p30 to remove? But why does it check the lore instead of just the item script name?

**Comment by mcmonkey4eva** [comment]
Yeah that random decimal kills it.

it checks for an exact match - that's how Bukkit does it, that's how Mojang does it, that's how other games do it... it's how everyone does it. If the items don't match **exactly**, they're not the same.

You can take `iteminhand`, or `bydisplay`, ... or, you can loop through the inventory yourself, checking matches however you please.
A random method to do this (untested):
`- take <player.inventory.list_contents.filter[scriptname.is[==].to[p30]].get[1]> qty:1`

**Comment by GomaTerzu** [comment]
Ok thanks! If this is something that can not changed I am going to change the way I did it
