### ISSUE TITLE
The tag "	<hero@hero.has_party>" does not work

### ISSUE THREAD

**Issue by Devotedworker** [DenizenScript/Denizen-For-Bukkit#1260]
http://pastie.org/10649248 My conversation with BlackCoyote on the Topic

The tag does not work, it returns the tag without the < > as all broken or invalid tags do. Hero.party and all other Hero tags work fine, just this tag seems to have issues

**Comment by mcmonkey4eva** [comment]
Depenizen issue -> https://github.com/DenizenScript/Depenizen-For-Bukkit/issues

**Comment by Fortifier42** [comment]
I assume you don't have Depenizen installed - http://puu.sh/m6C7S.png.

So this is infact not even an issue.

**Comment by mcmonkey4eva** [comment]
@Fortifier42 he does have it installed though.

**Comment by Fortifier42** [comment]
This was resolved :)
