### ISSUE TITLE
Bats can not - walk

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Denizen-For-Bukkit#1261]
Attempting to have a bat follow the player results in it just flying around like normal.

Script i used to discover the problem: http://mcmonkey.org/haste/26748
This script works fine for land animals.

If I remove AI right after a ~walk command it will just teleport around without ai.
If you have no AI then have it walk it will give it AI and fail to go to the location. Leaving it to just wander around.

**Comment by Fortifier42** [comment]
Perhaps the follow command would be better? 

`- follow (followers:<entity>|...) (stop) (lead:<#.#>) (max:<#.#>) (speed:<#.#>) (target:<entity>) (allow_wander)`

**Comment by KeangDavid** [comment]
That appears to just teleport around without AI.

**Comment by Fortifier42** [comment]
> - leaving AI enabled.

**Comment by KeangDavid** [comment]
With AI enabled, though it seams more responsive, ie. will teleport to you every time it gets too far. It still has the same general problem of wondering off as though it is just a normal bat.

**Comment by Fortifier42** [comment]
Seems to be an error in the Bat's AI then? @mcmonkey4eva

**Comment by mcmonkey4eva** [comment]
Is this still an issue?

**Comment by KeangDavid** [comment]
A quick simple test shows this to still be an issue on dev build 480.
With, and without AI.

**Comment by mcmonkey4eva** [comment]
Considering this won'tfix, as the issue is something involving strange NMS internals... if you want a bat that you can tell to walk around, use Citizens.
If you want to push a bat entity around, use the `push` command or `velocity` mechanism.
