### ISSUE TITLE
Wolf attacks with - walk

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Denizen-For-Bukkit#1262]
A wolf with has_ai:false will still attack sheep when using the - walk command.
I assume you temporary enable AI during the - walk. I would suggest also keeping it from targeting.

**Comment by Fortifier42** [comment]
Without AI, entities cannot move, as the AI determines how the entity moves, the way it finds a path, etc.
You could catch the `entity target` event and cancel it (dScript wise), this is what we'd be doing in Java too.

http://mcmonkey.org/denizen/evts/targets

**Comment by KeangDavid** [comment]
That is what I am suggesting. I think you just rephrased what I said?

**Comment by Fortifier42** [comment]
No - I'm suggesting you do it in dScript, since it'd be more work to do it source-wise.

**Comment by KeangDavid** [comment]
I am posting it here so it can be fixed in the code rather than everyone needing a script.

**Comment by BlackCoyote** [comment]
Every time a suggestion for improvement gets denied for the reason "you can do it in dScript", denizen loses a bit of its value

**Comment by mcmonkey4eva** [comment]
Good thing Fort isn't allowed to deny requests then.

**Comment by mcmonkey4eva** [comment]
Is this still an issue?

**Comment by KeangDavid** [comment]
Seams worse now. It will aggro sheep with the AI disabled. Just wont move.
Will still attack sheep instead of walking to position though.

**Comment by mcmonkey4eva** [comment]
Committed a partial fix for this.
Not perfect... but if you want perfectly functional wolves that do only what you want them to and nothing more, use an NPC.
