### ISSUE TITLE
Allow non-braced if commands..

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1264]
We need the ability to:

``` yaml
- if <some tags>:
  - do stuff
```

**Comment by Morphan1** [comment]
This would effectively need a new command, too, probably
```
- if <blah>:
  - things
- else:
  - more things
```

**Comment by KeangDavid** [comment]
To be consistent this would want to be done for all multi line commands. While, foreach, repeat... right?

**Comment by Fortifier42** [comment]
It already is done for while, foreach, repeat, async... etc

**Comment by mcmonkey4eva** [comment]
Issue tracked at https://github.com/DenizenScript/Denizen-Core/issues/18
