### ISSUE TITLE
Async doesn't properly carry over Context Information from Events

### ISSUE THREAD

**Issue by Devotedworker** [DenizenScript/Denizen-For-Bukkit#1265]
On the newest build
"Build #1605 (Dec 21, 2015 4:44:35 AM)"

Event context tags and "determined cancelled" do not give any effect when referenced inside of a "Async" tag. The only way to bring any context tag through to Async is through a "Define". Currently it is impossible to cancel an Event within a Async Tag. Not sure if a Bug or Limitation, but reporting anyway

Example
```
Events: 
    type: world 
    debug: false 
    events: 
        on player clicks in inventory:
        - async:
          - announce "<context.item>"
```
Will result in "context.item" being returned. ( Not the item, the words )

The Workaround to that is this
```
Events: 
    type: world 
    debug: false 
    events: 
        on player clicks in inventory:
        - define item '<context.item>'
        - async:
          - announce "<def[ti]>"
```

**Comment by mcmonkey4eva** [comment]
@Morphan1

**Comment by Fortifier42** [comment]
Wouldn't it be impossible to cancel the event async, since it runs on a different thread? With this, you could be trying to cancel the event after it has occurred - to my knowledge.

**Comment by mcmonkey4eva** [comment]
@Fortifier42 ... what?

**Comment by Devotedworker** [comment]
@Fortifier42 That still leaves the "Context" issues unsolved. I can understand how the Cancel Event may not work, but the Context tags should still carry

**Comment by mcmonkey4eva** [comment]
@Devotedworker We're waiting on Morphan to address that, as that is his thing.

Also, why are you using async at all here?

**Comment by mcmonkey4eva** [comment]
Fixed in https://github.com/DenizenScript/Denizen-Core/commit/e901b7507cc011d4be3b8e86cfa62a7a2ce78cc3 apparently.

**Comment by Devotedworker** [comment]
Thanks
