### ISSUE TITLE
When setting players inventory, lore, item names are written with syntax errors breaking plugin items

### ISSUE THREAD

**Issue by CorporalBruno** [DenizenScript/Denizen-For-Bukkit#1269]
Such as:
- backpacks from a backpacks plugin,
- pets from battlepets plugin.
- any armor/tools with enchantments get written as broken lore syntax and no longer carry the enchantment

**Comment by mcmonkey4eva** [comment]
... what?

**Comment by CorporalBruno** [comment]
i cant reproduce now. I will let you know if it comes back.
