### ISSUE TITLE
Mechanism for changing rotation of blocks, e.g. sign and skull

### ISSUE THREAD

**Issue by Devotedworker** [DenizenScript/Denizen-For-Bukkit#1270]
There are currently no Mecs to change the Rotation of Signs or Playerskulls, nor are there any Tags to detect their current Rotation.

**Comment by Fortifier42** [comment]
This is dependent on the type of block, different methods exist for Chests, Dispensers, Signs, Skulls, etc. am looking into it :)

**Comment by Devotedworker** [comment]
Okie dokie

**Comment by Devotedworker** [comment]
Bump~

**Comment by Fortifier42** [comment]
@mcmonkey4eva I'm not sure how to go about this... :disappointed:

**Comment by Devotedworker** [comment]
@mcmonkey4eva @Morphan1 ^^

**Comment by Morphan1** [comment]
`dLocation.head_rotation` mechanism and `<l@location.head_rotation>` tag added in developmental builds
