### ISSUE TITLE
Title Mechanism Not Supporting Titles Longer than 32 Characters

### ISSUE THREAD

**Issue by Mickket** [DenizenScript/Denizen-For-Bukkit#1272]
Denizen is not allowing inventory script containers which contain titles that are more than 32 characters long. Minecraft supports inventory titles longer than 32 characters.
![unsupportedtitlemech](https://cloud.githubusercontent.com/assets/11625939/12195331/6c55e5f6-b5c4-11e5-85fb-a891ce7d9d40.jpg)

Taken from: dInventory.java

    public void makeUnique(String id) {
        String title = inventory.getTitle();
        if (title == null || title.startsWith("container."))
            title = inventory.getType().getDefaultTitle();
        // You can only have 32 characters in an inventory title... So let's make sure we have at least 3 colors...
        // which brings notable inventory title lengths down to 26... TODO: document this/fix if possible in later version
        if (title.length() > 26) title = title.substring(0, title.charAt(25) == '§' ? 25 : 26);
        String colors;
        while (true) {
            colors = Utilities.generateRandomColors(3);
            if (!InventoryScriptHelper.notableInventories.containsKey(title + colors)) {
                ItemStack[] contents = inventory.getContents();
                if (getInventoryType() == InventoryType.CHEST) {
                    inventory = Bukkit.getServer().createInventory(null, inventory.getSize(), title + colors);
                }
                else {
                    inventory = Bukkit.getServer().createInventory(null, inventory.getType(), title + colors);
                }
                inventory.setContents(contents);
                InventoryScriptHelper.notableInventories.put(title + colors, this);
                break;
            }
        }
        idType = null;
        idHolder = null;
        loadIdentifiers();
        NotableManager.saveAs(this, id);
    }

**Comment by Fortifier42** [comment]
Clone of https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1238
