### ISSUE TITLE
Duration tags no longer working

### ISSUE THREAD

**Issue by Berufeng** [DenizenScript/Denizen-For-Bukkit#1273]
It won't let me post tags so I'll just attach my issue as a text document.  -.-
[BerufengIssue.txt](https://github.com/DenizenScript/Denizen-For-Bukkit/files/83384/BerufengIssue.txt)

**Comment by Fortifier42** [comment]
Tags must be enclosed within '**`**' symbol (the grave accent key)

**Comment by mcmonkey4eva** [comment]
This bug... never existed! *waves hand*

**Comment by Berufeng** [comment]
Thank you mcmonkey!
