### ISSUE TITLE
dynamic inventory script contents

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1275]
I'd like for inventory scripts to have a procedural section in which the contents of the inventory can be determined as a dList.

This becomes interesting if we assume that we'd make provided dList only fill in the slots which have not been filled yet by the 'slots:' section. This would give you the oppertunity to have a predefined design for the inventory whilst still having a more dynamic range over what else gets put in the inventory, for example, by reading a config file.

an example: http://mcmonkey.org/haste/28357

**Comment by mcmonkey4eva** [comment]
Quality idea.
