### ISSUE TITLE
Allow bringing arguments into a format script

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1277]
I've been running into issues when trying to use a format script, especially in a bungee network enviroment. things like 'player.name.display' and such aren't working anymore, even if after a lot of trouble i manage to keep a player tied to it. There's a ton of other examples where you'd want certain variables in a format script but might end up not finding a way to do it without using flags.

i'm suggesting to allow bringing arguments into a format script much like you can bring them into task or procedure scripts. perhaps using format:format_script_name|args_1|args_2 would work

thank you very much i love you all

**Comment by mcmonkey4eva** [comment]
Use a procedure script
