### ISSUE TITLE
Convert flag expiration and task delay to bukkit scheduler.

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1279]
Make flag expiration use the bukkit scheduler, so that flags expire properly, without needing to check them.
Make the run command use the scheduler, reduces the number of running queues etc.

**Comment by mcmonkey4eva** [comment]
No. Ridiculously pointlessly expensive.

**Comment by Morphan1** [comment]
lololololol rekt
