### ISSUE TITLE
Take command Errors in lastest builds

### ISSUE THREAD

**Issue by Pyroxis** [DenizenScript/Denizen-For-Bukkit#1281]
Spigot / CraftBukkit 1.8.8
Citizens Version: 2.0.16-SNAPSHOT (build 1297)
Denizen 0.9.7 Version: 0.9.7-SNAPSHOT (build 1607) / Dev (build 441)

The NPC "Take" command will spam 4 errors in the console
It says "Tag player.name.display Is Invalid" while I don't use this tags in this script.
>Script: http://mcmonkey.org/paste/28819 
>Console: http://mcmonkey.org/paste/28822

**Comment by Fortifier42** [comment]
Foreach issue has been fixed, awaiting @mcmonkey4eva to build.

Sure you aren't using that tag in another script somewhere?

**Comment by Pyroxis** [comment]
I'm sure, I tested with many scripts, everytimes a npc give an item it shoot me 4 Errors lines. 
But The command work, I get the item, it's just the spammy errors that says ERROR! Tag player.name.display is invalid!

**Comment by mcmonkey4eva** [comment]
Are you sure you don't have a separate script executing with `debug: false` in the background?

**Comment by Pyroxis** [comment]
I'm sure, what could trigger when i click on the npc? on right clicks at entity? I don't use that event.
