### ISSUE TITLE
Many Inventory Script Issues

### ISSUE THREAD

**Issue by ghost** [DenizenScript/Denizen-For-Bukkit#1282]
There are so many issues/bugs, I`m going to save time and post them all here
- [ ]  1. There is no "Furnace" inventory Script Type, despite Denizen having the support to create one
  ( Do `/ex inventory open d:in@generic[holder=FURNACE]` it will work fine, besides it not burning )
- [ ]  2. Hopper and Dispenser inventorys can not be named via a Inventory Script, despite having support to do so.
  ( Do `/ex inventory open d:in@generic[holder=HOPPER;title=NotHopper]` )
  ( Do `/ex inventory open d:in@generic[holder=DISPENSER;title=NotDISPENSE]` )
- [ ]  3. Furnaces do not have any support to "Show" fake burning, not sure if this is a feature request or bug. Just putting it here.
- [ ] 4 Items saved via flags in Inventorys do not stack with items outside of it. Just letting you know
- [ ]  5. No Beacon inventory type, yet can create one via command
  (  `/ex inventory open d:in@generic[holder=BEACON]`, Does not function though, as expected)
- [ ] 6. No Anvil inventory type, yet can create one via command
  (  `/ex inventory open d:in@generic[holder=ANVIL]` , Does function. Wth )
- [ ] 7. Calling a Custom "Horse" inventory will open the Inventory of the nearest Horse npc? Wth
  (  `/ex inventory open d:in@generic[holder=HORSE]`, Does function. WIERD )
  http://puu.sh/mEBCf/4dbb4dbf5e.jpg
  http://puu.sh/mEBEy/91f23eb3c9.png

<3 <3 <3
Sadly Github deleted my Brackets and stuff, so insert them in the commands where needed

**Comment by Devotedworker** [comment]
Bump

**Comment by mcmonkey4eva** [comment]
Issues have been mismanaged a bit, sorry for this getting ignored. I'm not sure if this is still an issue on latest builds - if it is, please reply below and we'll open it and investigate it more properly.
