### ISSUE TITLE
Better Name Matching! D:

### ISSUE THREAD

**Issue by Berufeng** [DenizenScript/Denizen-For-Bukkit#1283]
The server.match_player and server.match_offline_player tags are wonky. They should check "starts_with" before anything else-- for example, on my server, that tag for the value "vi" returns "KeangDavid" rather than "Vise44" because the former comes first alphabetically. Logically, it should return "Vise44" first because it is the beginning of the name rather than an arbitrary segment of it. ;)

**Comment by BlackCoyote** [comment]
Good suggestion! I agree with this.

**Comment by mcmonkey4eva** [comment]
this was done
