### ISSUE TITLE
i kinda really need a way to check if a schematic is loaded or not

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1286]
schematic.is_loaded or schematic.list, whatever floats your boats

**Comment by Fortifier42** [comment]
https://github.com/mcmonkey4eva/Denizen/commit/88654ee4828ba4e9d35907dc5ae67248aea4a052

**Comment by BlackCoyote** [comment]
5/7

**Comment by Fortifier42** [comment]
https://github.com/mcmonkey4eva/Denizen/commit/c02bb5adc8e926494a6b5e9226ab29f6dd8f3617

**Comment by BlackCoyote** [comment]
better than the dark night krises

**Comment by Fortifier42** [comment]
Implemented into Dev.
