### ISSUE TITLE
ActionBar command to display text in the player's action bar.

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1288]
I'll do this.. just putting down an issue so it's documented :)

`Commit MSG reminder: #fix`

**Comment by mcmonkey4eva** [comment]
(note to readers: There is already the *mechanism* `action_bar` to accomplish this, we just want a command form of it)

**Comment by Fortifier42** [comment]
Implemented into Dev.
