### ISSUE TITLE
Finish converting events to ScriptEvent format.

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1294]
A fair few events, still need to be converted to ScriptEvent format, as some (such as `on command (in <area>):`) don't accept the cuboid name on it's own, but still require identifiers.
- [x] Player Edits Book bad79fd
- [ ] Player Clicks Block
- [ ] Player Clicks in Inventory
- [ ] Time Changes (in <world>) `Not even sure if this one is possible as it isn't a normal event.`

**Comment by mcmonkey4eva** [comment]
Smart Event is what we call the old system. Well what auf called them at least. Modern style is `ScriptEvent`

**Comment by mcmonkey4eva** [comment]
there's only a few old-style events left... would be good to update them but not super terrible that they're still old
