### ISSUE TITLE
Multiple symbols in one tag

### ISSUE THREAD

**Issue by XWildFlowerX** [DenizenScript/Denizen-For-Bukkit#1295]
Hello

Recently I have been using symbol tags such as <&nl> and <&sp>. What I have noticed is that there is no way to print multiple tags without calling the tag multiple times. For example to print 4 spaces I would have to do: "<&sp><&sp><&sp><&sp>".  This can make scripts look very messy. 

Here is what I suggest:
<&sp[X]> where X is the number of spaces the script should print. For example <&sp[3]> would print 3 spaces.

**Comment by Morphan1** [comment]
You can use padding tags. 
For example, if you want to `narrate "    hello"` you could instead do `narrate <el@val[hello].pad_left[4]>`
If you want to `narrate "....hello"` you can do `narrate <el@val[hello].pad_left[4].with[.]>`

**Comment by Fortifier42** [comment]
Also elements are automatically trimmed due to stupid

**Comment by mcmonkey4eva** [comment]
@Fortifier42 that was fixed

**Comment by XWildFlowerX** [comment]
@Morphan1 Does this online work with the narrate cmd? Can I use this to change the server's motd?

**Comment by Morphan1** [comment]
How are you using it?

**Comment by XWildFlowerX** [comment]
@Morphan1 
"ex narrate <el@val[hello].pad_left[4].with[.]>"

**Comment by Morphan1** [comment]
Can you record the debug? `/denizen debug -r`, run the `/ex`, then `/denizen submit` and paste the link back here

**Comment by XWildFlowerX** [comment]
@Morphan1 
Here is my debug: http://mcmonkey.org/paste/29525

**Comment by mcmonkey4eva** [comment]
Your debug is at http://mcmonkey.org/paste/29524 please do not re-paste to edit data :(

- Why are you in offline mode?
- Are you sure it narrates /your player name/ ? The debug says it's doing different...

**Comment by XWildFlowerX** [comment]
@mcmonkey4eva  I am in offline mode because I have just installed Bungee. Oppps sorry yes its supposed to narrate my player name:  I still get the name on its own without the ".".

**Comment by mcmonkey4eva** [comment]
... so, we're going to pretend "hello" is your playername?
Oooookay.

Uhm. Hello is 5 letters long. If you want 4 dots padded onto it, you need to pad at length of 4+5=9

**Comment by XWildFlowerX** [comment]
Ah I see thanks for the clarification.  It now works :) Your the man.
