### ISSUE TITLE
Tag location.attached_to always returns null

### ISSUE THREAD

**Issue by Berufeng** [DenizenScript/Denizen-For-Bukkit#1297]
mcmonkey made a new tag for the block that buttons/levers are attached to, but it is returning null.

Debug: http://mcmonkey.org/haste/29380

mcmonkey says perhaps Spigot is returning a bad location?

**Comment by mcmonkey4eva** [comment]
No fak off.

**Comment by Morphan1** [comment]
im also having problem with commit that happen 2 minute ago and only been used by me who do i even report to idk help

**Comment by Berufeng** [comment]
how do i dscript halp
