### ISSUE TITLE
denizen save file 

### ISSUE THREAD

**Issue by silentspectr** [DenizenScript/Denizen-For-Bukkit#1298]
hello
in my save file i have ID's instead of player names, is it possible to change it ?
or have UUID's instead of these weird ID's ? 

thank you

**Comment by Talamar1** [comment]
That would be silly because players can change their names.  You could put a players name in the save  under the UUID and update it as needed if you want visual reference.

**Comment by silentspectr** [comment]
yeah but the ID's in the file are not the UUID's given by mojang 
i have diferent ID's

**Comment by Talamar1** [comment]
If you use <player> you will get UUID, <player.name> will give you a name.  I'm not sure how are doing your IDs.

**Comment by silentspectr** [comment]
o my bad 
they are in fact UUID's 
didn't realize 
sorry ^^'

**Comment by silentspectr** [comment]
thanks
