### ISSUE TITLE
denizen throwing error on startup

### ISSUE THREAD

**Issue by zozer** [DenizenScript/Denizen-For-Bukkit#1300]
I just got everything up to date and denizen is throwing an error on start up.
 here is the error: http://mcmonkey.org/paste/29707

**Comment by mcmonkey4eva** [comment]
Update Spigot. **Spigot**.

**Comment by zozer** [comment]
I just downloaded the latest buildtools...

**Comment by Fortifier42** [comment]
And ran it with `java -jar buildTools.jar --rev latest` ?

**Comment by zozer** [comment]
not the --rev lataset...
lets see if that works

**Comment by zozer** [comment]
ok, that didn't seem to work... still has same error

**Comment by Fortifier42** [comment]
[craftbukkit.jar:git-Bukkit-039621d]

**SPIGOT**

**Comment by zozer** [comment]
oh.. use spigot instead?

**Comment by Fortifier42** [comment]
We have been building against spigot for over 12 months :stuck_out_tongue:

**Comment by zozer** [comment]
oh... (how come no one tells me these things?)
case closed
