### ISSUE TITLE
element to secret colour string and back

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1303]
Being able to store info with colour codes in item names or lore, or mob names, can be pretty useful in minecraft, so lets add a tag for element.to_colors or whatever you want to call it which would turn a string such as "peanuts are not bananas" into a list of colour codes like `<&b><&a><&1><&8><&b><&c><&f><&7>`,  and a second tag which could reverse the list of those colour codes back into the original element

**Comment by Devotedworker** [comment]
I would also See Great use for this
