### ISSUE TITLE
Sending http requests

### ISSUE THREAD

**Issue by sander758** [DenizenScript/Denizen-For-Bukkit#1305]
Add an command or something to send an http request to an website and retrieve the data in a variable to be able to use online API's such as https://api.mojang.com/users/profiles/minecraft/sander758

**Comment by BlackCoyote** [comment]
i want this. not only can you use online API's but you can use webizen to connect servers that do not share the same network

**Comment by CorporalBruno** [comment]
Yes please! Can we have this feature please?

**Comment by BlackCoyote** [comment]
this is added now
