### ISSUE TITLE
Jump Event doesn't work

### ISSUE THREAD

**Issue by Devotedworker** [DenizenScript/Denizen-For-Bukkit#1307]
Read Title

And if you ask if I'm not on current I will punch you :facepunch:

**Comment by mcmonkey4eva** [comment]
How about /the slightest bit of detail/?

**Comment by Devotedworker** [comment]
It doesn't work. It never triggers, ever

**Comment by mcmonkey4eva** [comment]
Where's the script?
Where's the debug, that includes `/denizen reload scripts` followed by some jumping?

**Comment by Devotedworker** [comment]
I hate myself
( After a Server Restart it resumed functioning )

**Comment by Morphan1** [comment]
r u not on curent
