### ISSUE TITLE
Allow the Creation of Custom Recipes for any Item

### ISSUE THREAD

**Issue by Devotedworker** [DenizenScript/Denizen-For-Bukkit#1309]
I've noted that Denizen only supports Custom Crafting Recipes through Items created with Denizen Item Scripts. I would like it to create Recipes for Items not created with Denizens, such as HeroCodex's, or maybe some Custom stuff. Idk.

I've checked the Code, its possible ( Add the Recipe to the List you guys are using ) and I think it would be awesome if it worked.

Maybe a Command
- CreateRecipe <player.item_in_hand> shaped_recipe:<i@air>|<i@air>|<i@air>|<i@air>|<i@air>|<i@air>|<i@air>|<i@air>|<i@air>|<i@air>| unshaped_recipie:<i@stone>|<i@stone> savedname:Name

**Comment by Morphan1** [comment]
How would this be better than just using an item script with `no_id: true`?

**Comment by Devotedworker** [comment]
Allow for items to have Multiple Recipes :smile:

**Comment by BlackCoyote** [comment]
a command for this seems odd, just allow a way to list multiple recipes inside the itemscript plox

**Comment by Fortifier42** [comment]
@BlackCoyote they want to be able to make recipes for NON-Denizen items... 
:+1:

**Comment by BlackCoyote** [comment]
> How would this be better than just using an item script with no_id: true?

**Comment by Fortifier42** [comment]
@BlackCoyote Your suggestion isn't related to this issue tho? :o

**Comment by BlackCoyote** [comment]
devotedworker > i want recipes for items not created by denizen, maybe add command to make recipe
morphan > how is that better than using an item script with no_id: true?
devotedworker > it would allow to have mutliple recipes per item
BlackCoyote > Maybe it would be better to just allow us to list multiple recipes in an item script then
fortifier > im drunk hurr durr

**Comment by Devotedworker** [comment]
Because sometimes Denizen can't recreate items, where special NBT has been added that makes it impossible to do script per say, but having a plugin read and compare it is just ok. Plus, what is easier, to copy EVERY SINGLE COLOR CODE IN THE WORLD or just registering it with a Command or something. Plus you could have NPC's add recipies on the fly, or something cool like that

**Comment by Fortifier42** [comment]
@Devotedworker That'd very likely require a hook into the plugin itself (Depenizen). We can't keep track of every aspect of items for all those plugins (in an easy manner). I think maybe specific hooks into plugins would be a good idea here, but that's just my personal opinion :)

**Comment by BlackCoyote** [comment]
Aside from automating the creation of new item recipes, how would using the command saying "this recipe matches this item" be any bit more benifitial than having an itemscript say "this item has this recipe"?

**Comment by mcmonkey4eva** [comment]
I agree with @BlackCoyote - what we need here is multiple recipes per item script

**Comment by BlackCoyote** [comment]
And when it comes to automaticly creating new recipes, perhaps you guys can add some new event that triggers every time the contents of any crafting slot gets changed, that would allow you to determine the result item based on the crafting matrix' contents, as well as to determine what items will be removed from it when this item is crafted.

doing both with just an on inventory click event would be even more tedious than what we had to do before 'on player crafts item' was added

**Comment by mcmonkey4eva** [comment]
Considering a duplicate https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1306
