### ISSUE TITLE
Fishing listener issues

### ISSUE THREAD

**Issue by robgob** [DenizenScript/Denizen-For-Bukkit#1310]
- listen item type:fish item:raw_fish qty:1 script:onRawFishEvent
this fires the task script for no matter what i catch? even if "item:fish" is set.
What would be the best possible way to handle fishing listeners upon catching an item based on name/ID

**Comment by mcmonkey4eva** [comment]
Step one: Don't use a listener for that, or anything.
Step two: Follow the modern tutorials not ancient information.
http://mcmonkey.org/denizen/vids
Step three: ???
Step four: profit!

**Comment by robgob** [comment]
profit it is, then! xD

**Comment by Morphan1** [comment]
Assuming this can be closed...
