### ISSUE TITLE
(block) location flags

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1312]
`- flag <context.location> myspecialblock`
`- flag <player.location> trespassers:++`

the input location would always be converted to the block location, as this flag system is really only for keeping block data

breaking the block would erase the flags, just like removing an entity erases their flags

not a necessity, but just like entity flags, despite being replacable by server flags, it would make things a whole lot easier for newer scripters

**Comment by mcmonkey4eva** [comment]
This will be added as part of #1970
