### ISSUE TITLE
1.9 probably boss bar issue

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1314]
See this error 

http://mcmonkey.org/paste/31039

**Comment by Morphan1** [comment]
A lot of packet magic stuff has not been updated yet. Please be patient, as it's a tedious process and unless @mcmonkey4eva wants to finish it up, I won't be able to until later today.

**Comment by Morphan1** [comment]
This was fixed, and also we have a new BossBar command to use the full functionality introduced by 1.9.
