### ISSUE TITLE
Denizen is broken in 1.9

### ISSUE THREAD

**Issue by Culvanen** [DenizenScript/Denizen-For-Bukkit#1315]
The Denizen plugin does not work on 1.9 Spigot.

Denizen version I use: 0.9.7

Sentry does not work

**Comment by mcmonkey4eva** [comment]
Sentry is updated at: http://ci.citizensnpcs.co/job/Sentry/lastSuccessfulBuild/
Dev is half-updated at : http://ci.mineconomy.org/job/Denizen_Developmental/lastSuccessfulBuild/
