### ISSUE TITLE
Err: NoteCommandObjectReflection  

### ISSUE THREAD

**Issue by CorporalBruno** [DenizenScript/Denizen-For-Bukkit#1316]
http://mcmonkey.org/paste/31074

**Comment by mcmonkey4eva** [comment]
Need to see the script that caused this

**Comment by CorporalBruno** [comment]
http://mcmonkey.org/haste/31075 for /survival

http://mcmonkey.org/haste/31076 for /creative

**Comment by CorporalBruno** [comment]
latest update didnt fix this

**Comment by GravityX** [comment]
Same issue, was about to post it but saw this. I think it's due to the off-hand slot but could be wrong, here's my script:
http://mcmonkey.org/haste/31105

and error:
http://mcmonkey.org/paste/31104

**Comment by Morphan1** [comment]
Should be fixed with the latest Spigot builds
