### ISSUE TITLE
The Shield

### ISSUE THREAD

**Issue by CorporalBruno** [DenizenScript/Denizen-For-Bukkit#1317]
Please add an event to detect when the player blocks with shield.
Also would love to know the stuff that happens with projectiles after it hits the shield. Noticed it ricochets into close by targets and does damage.

The shield can also be modified with banners. (mech?)

**Comment by BlackCoyote** [comment]
the blocking with shield part would just be on entity damaged with a newly required player.is_blocking tag

**Comment by Morphan1** [comment]
BC is right, the damaged event + `<player.is_blocking>` (which works perfectly for shields) is the way to go for the first thing. As for ricocheting, that should still be handled by separate hit events etc.

That last part is added into Denizen (06a48d6), currently waiting on spigot for it to be 100% functional though.

**Comment by mcmonkey4eva** [comment]
@Morphan1 what exactly is still needed from Spigot here?

**Comment by Morphan1** [comment]
@mcmonkey4eva although there's no error (with the latest builds at least), it doesn't actually properly update the apparently fake BlockState because it's not a placed block

**Comment by Morphan1** [comment]
Latest Spigot + latest Denizen dev build fixes editing shield pattern editing!
It's the same mechs/tags as banners:
```
<i@item.patterns>
<i@item.base_color>
```
