### ISSUE TITLE
Arrows Of All Kinds!

### ISSUE THREAD

**Issue by CorporalBruno** [DenizenScript/Denizen-For-Bukkit#1318]
(...)
http://minecraft.gamepedia.com/Arrow
(...)

**Comment by mcmonkey4eva** [comment]
` If a bow is enchanted with Infinity, tipped arrows will still be consumed.`
for some stupid reason, also consumed in creative mode.

**Comment by mcmonkey4eva** [comment]
So what do we actually need to support here?
