### ISSUE TITLE
Could not pass event InventoryClickEvent to Denizen v0.9.8-SNAPSHOT (build 502)

### ISSUE THREAD

**Issue by Culvanen** [DenizenScript/Denizen-For-Bukkit#1320]
03.03 16:45:36 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
03.03 16:45:36 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-stb19.jar:git-Spigot-604e046-69e196f]
03.03 16:45:36 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [Spigot-stb19.jar:git-Spigot-604e046-69e196f]
03.03 16:45:36 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [Spigot-stb19.jar:git-Spigot-604e046-69e196f]
03.03 16:45:36 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1804) [Spigot-stb19.jar:git-Spigot-604e046-69e196f]
03.03 16:45:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-stb19.jar:git-Spigot-604e046-69e196f]
03.03 16:45:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-stb19.jar:git-Spigot-604e046-69e196f]
03.03 16:45:36 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-stb19.jar:git-Spigot-604e046-69e196f]
03.03 16:45:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot-stb19.jar:git-Spigot-604e046-69e196f]
03.03 16:45:36 [Server] INFO org.bukkit.event.EventException
03.03 16:45:36 [Server] ERROR Could not pass event InventoryClickEvent to Denizen v0.9.8-SNAPSHOT (build 502)

**Comment by mcmonkey4eva** [comment]
Could you please open your logs and locate the **full** error message, in its original logged form?

**Comment by Culvanen** [comment]
This error message is always here

The command /npc look don't work properly

**Comment by mcmonkey4eva** [comment]
I'll say again...

Could you please open your logs and locate the **full** error message, in its original logged form?

**Comment by Morphan1** [comment]
Update everything and if the problem persists comment when you can provide more information.
