### ISSUE TITLE
problem with potions

### ISSUE THREAD

**Issue by silentspectr** [DenizenScript/Denizen-For-Bukkit#1321]
Hi 

i made an item script with some items and the potion don't work when i ask a npc to take it from my inventory.

all the othe items work with a "- take i@Item qty:1" but with the lored potion, the console return this:

`
Inventory does not contain at least 1 of 
                   i@potion,8234[display_name=Potion de purification;lore=Cette 
                   potion contre les effets malefiques de la 
                   statuette;potion=SLOWNESS,2,false,false]... Taking as much as 
                   possible... `

why does the command recognize other items and not potions ? (when i input a "- take i@Potion qty:1", it works so only the "take" command don't 

thanks

**Comment by mcmonkey4eva** [comment]
could you empty your inventory to just the potion in the hotbar, post the results of: `/ex narrate <player.inventory.list_contents>` for comparison the output above?

**Comment by silentspectr** [comment]
got that :

`silentspectr issued server command: /ex narrate ‹player.inventory.list_contents›
[11:35:36 INFO]:  Starting InstantQueue 'EXCOMMAND_SiemensSchoolVampire'... 
[11:35:36 INFO]:  Queue 'EXCOMMAND_SiemensSchoolVampire' Executing: NARRATE 
                   "‹player.inventory.list_contents›" 
[11:35:36 INFO]: +- Executing dCommand: NARRATE/p@silentspectr ---------+ 
[11:35:36 INFO]:  Filled tag ‹player.inventory.list_contents› with 
                   'li@i@potion,8234[display_name=Potion de 
                   purification;lore=Cette potion contre les effets malefiques de 
                   la statuette;potion=SLOWNESS,2,false,false]'. 
[11:35:36 INFO]: +› Executing 'NARRATE': 
                   Narrating='li@i@potion,8234[display_name=Potion de 
                   purification;lore=Cette potion contre les effets malefiques de 
                   la statuette;potion=SLOWNESS,2,false,false]'  
                   Targets='[p@silentspectr]' 
[11:35:36 INFO]:  Completing queue 'EXCOMMAND_SiemensSchoolVampire' in 1ms.`

why there is a "li@" in front of the item ? 

thanks

**Comment by zozer** [comment]
li@ denotes a list (just like i@ denotes an item)
http://mcmonkey.org/denizen/lngs/dobjects is a list of all dobjects
I had a similar problem with the take, until i realized that the item in your cursor is not in your inventory so make sure its actually in you inventory and not some other at the time of taking

**Comment by silentspectr** [comment]
what do you mean by "in your cursor" ? 
when i have the item in my hand ? 
if so, it doesn't work even if i don't have it in hand

**Comment by zozer** [comment]
does '/ex take' Item work?

**Comment by silentspectr** [comment]
yes that's the command o do 
the `/ex give Potion` works

**Comment by zozer** [comment]
well all i can say is that you should make sure that the item is in your inventory at the time the command is executed (maybe posting the script will help pin point the problem)

**Comment by silentspectr** [comment]
well yeah the potion is in my inventory 
it works with every other items, lored or normal 
here is the item script 

`Potion:
    type: item
    no_id: true
    material: 373:8234
    display name: Potion de purification
    lore:
    - Cette potion contre les effets malefiques de la statuette`

the only diference with this one is that the potion has a special ID 

the others like this one : 

`Planches:
    type: item
    no_id: true
    material: 5
    display name: Planche
    lore:
    - Une simple planche de bois`

works just fine 

thanks

**Comment by zozer** [comment]
ok, i figured it out. the special id is not included in the normal item therefor, when trying to take it its comparing a less specific item to a more specific item.
to fix this just say `- take <i@potion.full>`
the `.full` makes sure in include absolutely everything

**Comment by silentspectr** [comment]
Niiiiice
it worked 
thank you zozer, you rock 
=)
