### ISSUE TITLE
On player logs in for the first time doesn't fire anymore

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1322]
The event "On player logs in for the first time" does not fire anymore.

Using the latest builds of all plugins.

**Comment by mcmonkey4eva** [comment]
I see no reason that would fail to function, unless the players joining newly aren't as new as you think 0.o

**Comment by GomaTerzu** [comment]
You are completely right, That player was online almost a year ago..
