### ISSUE TITLE
PlayerInteractEntityEvent (and PlayerInteractEvent?) doesn't have its hand checked

### ISSUE THREAD

**Issue by fullwall** [DenizenScript/Denizen-For-Bukkit#1324]
PlayerInteractEntityEvent now requires you to use event.getHand() otherwise you will process it twice for each right click. Up to you how to handle it but Citizens just ignores the offhand right click.

**Comment by Morphan1** [comment]
...was this actually an intended change? Because that seems really dumb considering you can just manually check both hands if you really even care to.
@mcmonkey4eva what do you want to do about this?

**Comment by mcmonkey4eva** [comment]
@Morphan1 I just blocked it, same as was done in Citizens, as it seems to be a useless duplicate. Possibly not well thought out by the Spigot team? They might have a reason for it we're not thinking of though 0.o

**Comment by Xenmai** [comment]
Is this error when placing blocks related? http://mcmonkey.org/paste/31403 "Could not pass event PlayerInteractEvent..."

**Comment by mcmonkey4eva** [comment]
@Xenmai update Spigot

**Comment by uledrith** [comment]
I'm also getting a PlayerInteractEvent error every time i right click an NPC with a click trigger.

![image](https://cloud.githubusercontent.com/assets/4096231/13657643/72b89734-e636-11e5-987e-71e956b10210.png)

**Comment by mcmonkey4eva** [comment]
@uledrith same error = same response -> update spigot

**Comment by GomaTerzu** [comment]
works

**Comment by BlackCoyote** [comment]
this duplicate event issue is fixed now you can close it guis

**Comment by fullwall** [comment]
@mcmonkey4eva their reason was that the client was sending two click events so it should be fired twice.
