### ISSUE TITLE
on entity despawns:

### ISSUE THREAD

**Issue by tribness** [DenizenScript/Denizen-For-Bukkit#1325]
<context.entity> is returning e@Zombie instead of the uuid. Its a normal minecraft mob, all i did was changing is health with the health_Data mechanism.

**Comment by mcmonkey4eva** [comment]
Morph got you ^

**Comment by tribness** [comment]
yep, its working as it should now. you can close it, thanks :)

**Comment by BlackCoyote** [comment]
OR YOU CAN CLOSE IT YOURSELF
