### ISSUE TITLE
<def[hit_entities]> in shoot command returns null with ITEM_PROJECTILE[item=magma_cream] 

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1326]
Seems like ITEM_PROJECTILE[item=magma_cream] is not recognizes as an projectile anymore in the shoot command. It won't return hit entities. Works fine with arrows instead

**Comment by mcmonkey4eva** [comment]
Morph appears to have fixed it ^ - can you please confirm the fix?

**Comment by GomaTerzu** [comment]
Solved
