### ISSUE TITLE
Add new 1.9 Particle Effect Types

### ISSUE THREAD

**Issue by Xenmai** [DenizenScript/Denizen-For-Bukkit#1327]
With the 1.9 release, Mojang added some new particles: endRod, dragonbreath, damageIndicator and sweepAttack, as seen in http://minecraft.gamepedia.com/Particles. I hope it's an easy addition to make, and thanks for your time ^^

**Comment by mcmonkey4eva** [comment]
Fixed.

**Comment by Xenmai** [comment]
Can you also add them to the documentation? http://mcmonkey.org/denizen/lngs/effect

**Comment by mcmonkey4eva** [comment]
Is already there, just wasn't reloaded

**Comment by Xenmai** [comment]
Thanks :) I just tested the effects and it works fine.
