### ISSUE TITLE
"On player swaps hands:" Event

### ISSUE THREAD

**Issue by Xenmai** [DenizenScript/Denizen-For-Bukkit#1329]
As of 1.9, you can swap items in the main and offhand slots with a key (F by default). Is it possible to detect when this happens and run a script? Thanks beforehand.

**Comment by Fortifier42** [comment]
Have you tried the "on player scrolls their hotbar:" event, there's currently nothing in spigot about it. and I feel that it _may on off chance_ work

**Comment by Xenmai** [comment]
Thanks for the suggestion. I've now tried and nope, swapping hands doesn't trigger that event =/

**Comment by Morphan1** [comment]
Try out the newest developmental Denizen build.
```
WorldScript:
  type: world
  events:
    on player swaps item:
    - announce "SWAPPER NO SWAPPING"
    - announce "(<player.item_in_hand> and <player.item_in_offhand>)"
    - determine cancelled

**Comment by Xenmai** [comment]
Thanks a lot! Just in case somebody copy-pasted and is wondering why it won't work, there's an S missing in "item". So... "on player swaps item:"

**Comment by Morphan1** [comment]
Oh oops. Yeah sorry, I had changed that just before I committed it. I guess I forgot to edit my script for it

**Comment by BlackCoyote** [comment]
lol loser

**Comment by Morphan1** [comment]
```
<monkeybot>  on player swaps items: 
<monkeybot>   Triggered: when a player swaps the items in their main and off hands. 
<monkeybot>   This event can be cancelled. This adds 'context.cancelled', and determines 'CANCELLED' and 'CANCELLED:FALSE'
<monkeybot>   Context: <context.main> returns the dItem switched to the main hand.
<monkeybot>   Context: <context.offhand> returns the dItem switched to the off hand.
<monkeybot>   Determine: "MAIN:" + dItem to set the item in the main hand.
<monkeybot>   Determine: "OFFHAND:" + dItem to set the item in the off hand.
```
