### ISSUE TITLE
source:<player> in hurt command results in 0 damage

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1330]
If I use the hurt command like this

`- hurt 1 <player.location.find.entities.within[10]> source:<player>`

the entities within the radius won't get any damage.

**Comment by mcmonkey4eva** [comment]
That might be a Bukkit/Mojang limitation - players generally aren't allowed to magically damage things.\

Might also help to specify a `cause:`

**Comment by Morphan1** [comment]
There's a lot of weird issues with damaging entities I think. For example, you apparently can't use Hurt on an ender dragon at all.

**Comment by nurfuis** [comment]
What about .

- foreach <player.location.find.entities.within[10]> {
   - hurt 1 %value% source:<player>
   }

I know hurt should hit a list but this could get you by.

**Comment by GomaTerzu** [comment]
Maybe to make it clear, it worked perfectly fine with 1.8 and I am actually using a cause:projectile, too

**Comment by mcmonkey4eva** [comment]
Can you try aiming at an entity and doing: `/ex hurt 5 <player.target> source:<player> cause:projectile`?

**Comment by GomaTerzu** [comment]
Only works one time and then stops working and only after I hit the entity first with a real hit first.

**Comment by GomaTerzu** [comment]
Dunno why, but it seems to work again.
