### ISSUE TITLE
Question: Return block material when clicked

### ISSUE THREAD

**Issue by vicknyaz112** [DenizenScript/Denizen-For-Bukkit#1332]
How do you get the material of the block that has been clicked when using "	on player clicks block" event? There are no <context.material> or <context.block> tags.

P.S.: Sorry for the dumb question, it's probably mentioned somewhere, i just couldn't find it.

**Comment by Xenmai** [comment]
You can try "<context.location.material>". <context.location> returns the block that has been clicked, so adding a .material should return the material if it all goes well :)

**Comment by vicknyaz112** [comment]
Thanks!
But I don't quite get it. Could you give me an actual code line please?

**Comment by Morphan1** [comment]
```
WorldScript:
  type: world
  events:
    on player clicks block:
    - announce <context.location.material>
```

**Comment by mcmonkey4eva** [comment]
Be sure to check out http://mcmonkey.org/denizen/vids for some tutorials on how to do cool things like that!
