### ISSUE TITLE
Need 'offhand' for the Equip command

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1334]
Is it possible to add 'offhand:' when issuing 'equip' command for NPCs?

Thanks!
Uledrith

**Comment by uledrith** [comment]
Forgot to say PLEASE!! :)

**Comment by Morphan1** [comment]
Added in the latest dev build

**Comment by uledrith** [comment]
I'm guessing this error when i try '/ex equip <npc> offhand:i@shield

http://mcmonkey.org/paste/31486

**Comment by Morphan1** [comment]
Try updating Citizens

**Comment by uledrith** [comment]
I just did and am getting same error.
