### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by adexgold** [DenizenScript/Denizen-For-Bukkit#1335]
Ok when i came across this error I started a new fresh server with just the Denizen plugin, in order to make sure it was not because of a corrupt world or other plugin. Also i only have the single item script loaded.

What seems to be happening is an error when removing items from the crafting window, the recipe works fine and i am able to get my first item out correctly, but then the remaining items that are in the crafting window start to act funny, it don't subtract one from each like it should, instead it throws them into negative numbers and then back, if i keep clicking the result window/slot then i can pull an unlimited amount of the item out.

I have included link to the rar of the server i used to test it, as well as the paste of the latest log
the error starts on line 183.

Server.rar - https://drive.google.com/file/d/0Bz7UMDYkYtagdlp5VjlNbWZ6eWM/view?usp=sharing
Paste of Log - http://pastebin.com/Pgn0Sf5U

**Comment by Morphan1** [comment]
Update Spigot.

**Comment by adexgold** [comment]
I done that shortly after posting. Same problem. Currently using the "Version" command it tells me im 4 versions behind, seems they do update that quite often lol, I will work on updating now, im using 'BuildToolsGUI' to get my 1.9 versions of Spigot.

**Comment by Morphan1** [comment]
"still same problem" if you're getting the same error, then you're not using the latest spigot version.

**Comment by adexgold** [comment]
This is what i'm getting now as far as error goes, i'm still getting the same inventory glitch in the game.

Error - http://pastebin.com/it0JLdeH

Version - http://pastebin.com/12vbMBp5

**Comment by Morphan1** [comment]
Actually, I misread. Try updating to the latest development build http://ci.mineconomy.org/job/Denizen_Developmental/lastSuccessfulBuild/

**Comment by adexgold** [comment]
Very nice, I could have sworn I was on the latest Denizen build.

That seems to have fixed the problem, thank you very much.

**Comment by adexgold** [comment]
Found another issue with the crafting. If I disable crafting of lets say iron pickaxe, it does stop me from crafting it, but after the first try it also stops me from crafting anything else until i restart the server.
