### ISSUE TITLE
"on player stands on stone_plate" does not fire anymore

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1337]
```
"PressureRespawn":
  type: world
  debug: true
  events:
    on player stands on stone_plate:
    - announce "lol"
```

worked in 1.8 does not work in 1.9 anymore

**Comment by Morphan1** [comment]
That specific format actually never worked. The event is still in a really old format (we haven't updated it to ScriptEvent status yet) and it seems to still require m@.
```
on player stands on m@stone_plate:
- announce "lol"
```
Instead of changing that right now, I'm just gonna link this to #1294

**Comment by GomaTerzu** [comment]
Why is your first answer always "that never worked. That can't be possible". Please stop it. It did work and several hundred people used these stone plates Morphan.

I am only reporting stuff that worked without me changing anything in my scripts with 1.8 and now does not work anymore.

And it does not work with m@stone_plate, too

**Comment by mcmonkey4eva** [comment]
@Morphan1 our old code is weird... object notation was included, but then automatically stripped later down the line. I see a potential flaw that might cause it and have sent in a fix.

**Comment by GomaTerzu** [comment]
Works, thank you! (closing it now)
