### ISSUE TITLE
Player data storage problem.

### ISSUE THREAD

**Issue by vicknyaz112** [DenizenScript/Denizen-For-Bukkit#1338]
I have a very serious problem with player data storage.

I'm using Denizen 0.9.6, and it stores player data using UUIDs.
For example, I have two players stored: "bob" and "Bob". They have different UUIDs. And I also have a command: /assignflag <playername>, which assigns the flag "Test" to the player using the "flag p@<context.args.get[1]> TestFlag:true" command.

But when I perform the command on "Bob", the flag is being assigned to "bob" with his UUID. The same happens when I return the UUID of "Bob" using the uuid tag, it just returns the UUID of "bob". How do I fix this?

Thanks for the help!

**Comment by vicknyaz112** [comment]
I have an idea of storing all the player data in lowercase, but I think there's a better solution for this. I would be really grateful if someone gives me a hint!

**Comment by Morphan1** [comment]
I'm confused. You have 2 players with identical names?..

**Comment by vicknyaz112** [comment]
That's not it. Player may misspell their name and log in with all lowercase. This leads to creation of another profile in saves.yml and to the said issue.

**Comment by Morphan1** [comment]
Oh okay. Try this http://mcmonkey.org/haste/31508

**Comment by Fortifier42** [comment]
topkek @Morphan1
