### ISSUE TITLE
Crafting disabled

### ISSUE THREAD

**Issue by adexgold** [DenizenScript/Denizen-For-Bukkit#1339]
I posted this in the reply of my Duplication glitch post but I closed that because the duplication was fixed by the latest Dev build.

The event 'on player crafts' fires perfectly, I have set to where it determines cancelled when you try to craft an iron pickaxe, now here is the problem, once i try to make a pickaxe and it stops me it also stops all future crafting attempts, be it an axe, ladder, or any other item.

Denizen Build - 514

Spigot Version - (Latest as of this posting)
git-Spigot-6f291ea-6026dad (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**Comment by Morphan1** [comment]
Can you test this using the latest Denizen dev build?

**Comment by adexgold** [comment]
Tested using Denizen build 515

Same result, even tried disconnecting via the client and restarting the client. 

The problem seems to be something hanging in the server. Odd tho that we get no errors, just simply not able to craft.

**Comment by adexgold** [comment]
Any luck on this? Just tried with latest Spigot and Denizen Dev-Build and same results.

**Comment by adexgold** [comment]
Tested with latest version of Spigot plus Dev build of Denizen. Same issue. Latest version I can get working is 1.8.8

**Comment by mcmonkey4eva** [comment]
Issues have been mismanaged a bit, sorry for this getting ignored. I believe this should not still be an issue on latest builds - if it is, please reply below and we'll open it and investigate it more properly.
