### ISSUE TITLE
Error when /equip with offhand

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1341]
If you type /ex equip <npc> offhand:i@shield, you get the following error in console.

http://mcmonkey.org/haste/31573

Yes, I'm latest version of everything.

**Comment by mcmonkey4eva** [comment]
Can you try with latest Citizens build (as of this reply's date)?

**Comment by uledrith** [comment]
this appears to be working now.  Thanks!
