### ISSUE TITLE
The light formed by fires with explode command don't disappear

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#1344]
All is in the title :)
The light don't disappear even over server reboots and load/unload of the map.

Using both latest Denizen and Spigot

**Comment by mcmonkey4eva** [comment]
... `/explode`?

**Comment by MrMaleficus** [comment]
Hum, the /ex explode command i mean. This command : http://mcmonkey.org/denizen/cmds/explode

By script, or directly by command In Game, the light formed by fires don't fade.

**Comment by MrMaleficus** [comment]
It's a real issue : 
![2016-03-23_21 04 15](https://cloud.githubusercontent.com/assets/5609863/13999082/e623b898-f13a-11e5-8a66-b4b258516a13.png)

**Comment by mcmonkey4eva** [comment]
Can't replicate. Can you please update everything to latest dev builds + give exact replication sample commands and steps?

**Comment by MrMaleficus** [comment]
Tested with all latest builds on a test 1.9 test server (my server is 1.8.8) and the light bug is not present.
Just waiting for the Heroes update to update my server !
Thank you and sorry for this false issue :8ball: 
I close
