### ISSUE TITLE
fireworkexplodevent

### ISSUE THREAD

**Issue by insanesquirle** [DenizenScript/Denizen-For-Bukkit#1345]
Upon doing /denizen reload scripts

Please report this error:[See console]
java.lang.noclassdeffounderror:
org/bukkit/event/entity/fireworkexplodevent

Console reads:
WARN java.lang.NoClassDefFoundError: org/bukkit/event/entity/FireworkExplodeEvent

**Comment by Morphan1** [comment]
Update Spigot

**Comment by mcmonkey4eva** [comment]
Make sure you are running _SPIGOT_ not "Craftbukkit" or "Bukkit" or any other variation of Spigot.
