### ISSUE TITLE
PrepareItemCraftEvent error

### ISSUE THREAD

**Issue by BlackRavenMC** [DenizenScript/Denizen-For-Bukkit#1347]
Denizen error for build 530:
http://pastebin.com/nUjMAGuv

**Comment by Morphan1** [comment]
Should be fixed in the latest developmental build

**Comment by mcmonkey4eva** [comment]
@BlackRavenMC can you confirm the fix?

**Comment by BlackRavenMC** [comment]
@mcmonkey4eva yes, fixed
