### ISSUE TITLE
Shoot command buggy

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1349]
Is shoot supposed to be able to work with all entities?

```/ex shoot e@slime_ball```

I get this error on many entities - i tried e@snow_ball, e@bone and many others..

Others like e@fireball work fine or e@skeleton.

e@slime does not produce an error, but does nothing.

http://mcmonkey.org/paste/31857

**Comment by Morphan1** [comment]
Well that specific error doesn't help us because "slime_ball" does not exist (unless it's an entity script?)
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html

**Comment by Morphan1** [comment]
Oh yeah. Snow_ball and bone are also invalid.

**Comment by mcmonkey4eva** [comment]
He seems to be attempting to shoot items. If you do want an actual item, not an entity:
```
- shoot e@dropped_item[item=i@snow_ball]
```

**Comment by uledrith** [comment]
the e@dropped_item worked for what I was trying to do.  Thanks!! :)
