### ISSUE TITLE
null tag results on health.percentage & .formatted

### ISSUE THREAD

**Issue by CorporalBruno** [DenizenScript/Denizen-For-Bukkit#1351]
health.perectage and .formatted return null latest everything.

**Comment by Morphan1** [comment]
Can you please provide the full tags you are using?..

**Comment by mcmonkey4eva** [comment]
@Morphan1 `<player.health.percentage>` and `<player.health.formatted>`

**Comment by mcmonkey4eva** [comment]
Fixed for dev build 535
