### ISSUE TITLE
Potion effects property

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Denizen-For-Bukkit#1352]
We need an entity property that handles potion effects lists.

**Comment by Fortifier42** [comment]
Is this meant to be the list_effects tag as a property?

**Comment by mcmonkey4eva** [comment]
Yup.

**Comment by Fortifier42** [comment]
That shouldn't be hard then

**Comment by mcmonkey4eva** [comment]
This was added at some point forever ago
