### ISSUE TITLE
Request: Cuboid related tags

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#1353]
Tags to return volumes of cuboids
- [x] `<cuboid.volume[index]>`
- [x] `<cuboid.overlaps>`
- [x] `<cuboid.total_volume>`
- [x] `<cuboid.shell>`

**Comment by BlackCoyote** [comment]
https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1129

add this to your list so i can remove that issue

**Comment by AnthonyAMC** [comment]
@BlackCoyote how about a hollow cuboid.

These tags could all be generalized to include ellipsoids. Maybe the root of the tag could be `area` or some such.

**Comment by mcmonkey4eva** [comment]
- Added `cuboid.volume`
- I believe overlaps is just the existing `cuboid.intersects` tag?
- Added list_members, so if you want the total volume, use `cuboid.list_members.parse[volume].sum`
- Added `cuboid.shell`
