### ISSUE TITLE
on player equips armor - bug

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1355]
```
EquipTest:
  type: world
  debug: true
  events:
    on player equips armor:
    - determine cancelled
```

When the determine cancelled fires, it removes the item completely from the game.  That seems like a bug to me.  I would think it would simply remain on the players cursor or go back to `<player.inventory>`.  Am I wrong?

Thanks, Uledrith

**Comment by Morphan1** [comment]
Can test this? 
```
- determine passively cancelled
- wait 1t
- inventory update
```

**Comment by uledrith** [comment]
I tested that with your code; it still removes the item.

**Comment by mcmonkey4eva** [comment]
Equips events are just considered to be 'borked' for the most part, particularly determinations.

They're custom events janked into the system that don't work well, in large part due to reliance on too many different things at once.
