### ISSUE TITLE
Take command error.

### ISSUE THREAD

**Issue by vicknyaz112** [DenizenScript/Denizen-For-Bukkit#1356]
Getting errors when applying take command. The error seems to happen when the player has a player head in their inventory in the slot before the taken item.
This error is almost fatal for my server, please help me fix it!
The error: http://pastebin.com/LhCt5Zx4

**Comment by vicknyaz112** [comment]
The error only seems to happen when the player has a specific player head in their inventory.

**Comment by vicknyaz112** [comment]
OK, I've updated my Denizen version, and the error seems to be gone now, but the server still lags a bit, when executing take command and a player has a head in his inventory, and Denizen can't reach Mojang auth servers. Can I somehow tell Denizen not to do that?

**Comment by mcmonkey4eva** [comment]
This shouldn't be an issue anymore I think
