### ISSUE TITLE
add ratio to the random command

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#1358]
Say I have two commands to choose randomly:

"- random {
- narrate 'You are lucky!'
- narrate 'You seem quite unlucky...'
  }"

but this is a 50% chance for each command. Here is my example of how I think it should be:

" - random {
- ratio 1 {
  - narrate 'You are lucky!'
    }
- ratio 9 {
  - narrate 'You seem quite unlucky...'
    }
    }"

This should then create the ratio 1:9 meaning 10% to choose "lucky" and 90% for "unlucky" (if I understand ratios correctly)

**Comment by MrMaleficus** [comment]
the `<util.random.int[#].to[#]>` already do a such thing :8ball: but i approve this suggestion !

**Comment by BlackCoyote** [comment]
With list input in cases this could be done exactly like that. I suggest we add that instead!
example:
`- case 1|2|3:`

or in command handlers:

`- case remove|delete|del:`

**Comment by mcmonkey4eva** [comment]
Just do:
```
- define value <util.random.int[1].to[10]>
- if <def[value]> <= 1:
    - narrate "lucky"
- else:
    - narrate "nope!"
```
you can throw in `else if`s for larger sets

You might also check out the weighted random script @AnthonyAMC wrote for dUtilLib: https://github.com/BlackCoyote/dUtilLib/blob/master/WeightedRandomChoice.yml
