### ISSUE TITLE
Disable player pushing somehow

### ISSUE THREAD

**Issue by irbDylan** [DenizenScript/Denizen-For-Bukkit#1359]
In 1.9 it was made possible to push other players around and grapple them with fishing rods to move them around. Make a way to disable entities/players from pushing each other around maybe?

**Comment by mcmonkey4eva** [comment]
This will require a spigot update, at which point we can use `setCollidable`.

**Comment by mcmonkey4eva** [comment]
Collidable mechanism is available for dEntities
