### ISSUE TITLE
Item scripts with furnace component referring to yet unloaded item scripts fail.

### ISSUE THREAD

**Issue by Sparclen** [DenizenScript/Denizen-For-Bukkit#1360]
If you have item scripts A and B, and script A contains the B item as a recipe or furnace compoment, it will fail to load if it loads first.

Here's a **very** short item script portraying the issue clearly:

http://mcmonkey.org/paste/32104

If the script 'i@CobaltOre' loads first on server startup or reload, no errors.
If the script 'i@CobaltIngot' loads first on server startup or reload, there's an error saying that i@CobaltOre is invalid.

The only workaround I found is randomly changing the script names to affect load order. However, this load order changes everytime you add more scripts to your denizen folder, so this is not a great solution.

Load order shouldn't affect anything.

**Build:** 1612 (latest dev build)

**Comment by Morphan1** [comment]
I'm going to assume
> as a recipe or furnace (sic) compoment
is supposed to mean "as a furnace recipe component".
Both normal and shapeless recipes have a system for this case already; I guess whoever added furnace recipes was just lazy about it.

**Comment by Sparclen** [comment]
My mistake! This only started happening after I added furnace recipes, so you're right.

**Comment by Sparclen** [comment]
Any plans to adress this? It is **pretty** frustrating. Every time I add a new script, I have to change the names of the scripts containing furnace recipes hoping that they change their load order. Pretty stupid workaround!

**Comment by mcmonkey4eva** [comment]
Oh sorry, I either never saw this or thought morphan would fix it and ignored it because of that. Fixed. Furnaces recipes are still a bit problematic though - there doesn't appear to be a simple way to de-register a recipe after it's been added, short of restarting the server 0.o - could probably work around it, but I haven't done that at this time.

**Comment by mcmonkey4eva** [comment]
Thanks for the report, could you please confirm the fix on a 1.9.4 Spigot server with the developmental build available here: http://ci.mineconomy.org/job/Denizen_Developmental/ (number 583 or higher)
