### ISSUE TITLE
- inventory command trows nullpointer exeption

### ISSUE THREAD

**Issue by NLBlackEagle** [DenizenScript/Denizen-For-Bukkit#1361]
Since a couple of months I run a script on the server which has been working fine until about a month ago.

I have narrowed down the issue to the - inventory command. This issue does not occur when using /ex ingame, when using as_op "ex -inventory..." within a script the issue shows up again.

These are the original log & script:
Log: http://hastebin.com/radabovuja.xml 
Script: http://hastebin.com/iqedogonix.avrasm

Here is a simplified version that trows the same nullpointer:
http://mcmonkey.org/haste/32105

Denizen Build: 539
Paper-Spigot: git-paper-604

**Comment by mcmonkey4eva** [comment]
Should be fixed by https://github.com/mcmonkey4eva/Denizen/commit/1ed56bdc7fafa57ee24497c12c87e9a9863b0820
