### ISSUE TITLE
armor_scale mech (feature request)

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1362]
Now that we have armor_bonus mech (thank you!!!), was curious if you could add 'armor_scale' similar to the 'health_scale' option for health?

Thanks!
Uledrith

**Comment by Fortifier42** [comment]
Is this even possible?

**Comment by mcmonkey4eva** [comment]
Prooooooooooooobably not actually, not sure. @uledrith have you seen this done anywhere, or are you just hoping it'll be possible?

**Comment by uledrith** [comment]
just hoping.  I scale health on my server so it's easier to see for when the player gets extra hitpoints.  Would totally make sense to do the same with armor if possible.

**Comment by mcmonkey4eva** [comment]
It'd make sense, but I doubt Mojang allows it :/

**Comment by Fortifier42** [comment]
@mcmonkey4eva I actually looked through the code cause was going to implement it. Couldn't find anything related to armor scaling (Even checked attributes)
