### ISSUE TITLE
packet based "glowing" effect!

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1368]
I want to make specific clients render different potion effects on an entity than others,  mainly for the 'glowing' potion effect, which highlights the specified entity. If you can make certain entities glow to specific clients only, it can be used as a great way to indicating npcs to talk to and such for a player

**Comment by Xenmai** [comment]
I suggesed this :P Mcmonkey and Morphan1 talked about it, but I'm not sure if it's possible yet.

**Comment by BlackCoyote** [comment]
Did you make an issue post for it

**Comment by Xenmai** [comment]
I asked and was told not to

**Comment by mcmonkey4eva** [comment]
`I asked and was told not to` Please do not lie on the issues page :(

**Comment by mcmonkey4eva** [comment]
Anyway, this is a great idea and definitely worth trying for.
@Morphan1 You wanna try this?
