### ISSUE TITLE
Bug with spawn eggs

### ISSUE THREAD

**Issue by ghost** [DenizenScript/Denizen-For-Bukkit#1369]
When I do item_in_hand tag with spawn eggs equiped it says "i@monster_egg[spawn_egg=0]" for all spawn eggs and spawn_egg mech also does not work, it gives plain spawn egg.

**Comment by Morphan1** [comment]
Still waiting for spigot to add a working method for this. https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/pull-requests/148/overview

**Comment by mcmonkey4eva** [comment]
This was fixed.
