### ISSUE TITLE
<e@entity.scriptname> always returns null

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1372]
Not sure when this problem started, but I tested quite a few different entities(custom zombies, etc.) that I spawn from script containers.  They used to work, but now only return 'null'.

Thanks,
Uledrith

**Comment by uledrith** [comment]
Ok, I think this can be closed.  I was spawning entities from 'task' scripts and while the .scriptname tag did work on these, I'm guessing that is not by design.  I didn't know about actualy 'type: entity' script containers so I'm converting to those and they do work.  Sorry...

On a related note, I'm curious if there is a way to put an item in hands or offhand inside one of these entity script containers.  I know you can do ```equipment: li@i@boots|i@legs|i@chest|i@helmet```.  I'm trying to avoid using commands (i.e. - equip ...) after I spawn the e@entity.

Thanks! Uledrith

**Comment by mcmonkey4eva** [comment]
Equipment has new slot for offhand now. I believe hand is inventory contents?
