### ISSUE TITLE
notables.yml loads before any script can load worlds

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#1374]
It's a race condition folks. Any script that tries to act as a world manager runs too late. Any notable areas in the unloaded worlds are removed from the file and unless a script re-creates the notables on server start, you're screwed. But if a script has to recreate the notables, then wtf is the point of having noted areas be saved?

Heres a snippet from [server start log](http://mcmonkey.org/haste/32249)... i lol'd

**Comment by CorporalBruno** [comment]
I have tested prestart and integrated with my pex and grief prevention for a survival pvp world:
world_load:
  type: world
  debug: true
  events:
    on server prestart:
    - createworld world_wild worldtype:AMPLIFIED
    - wait 2s
    - execute as_server 'pex world world_wild inherit world'
    - wait 1t
    - execute as_server 'gamerule keepInventory true'
    - wait 1t
    - execute as_server 'gpreload'


this works.

**Comment by BlackCoyote** [comment]
this should be fixed now, right?
