### ISSUE TITLE
gamerules for worlds

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1381]
as we all know, in minecraft there are a bunch of gamerules which can be changed per world
http://minecraft.gamepedia.com/Commands#gamerule

I want to be able to change these from within denizen and I haven't really found a way to do this without listening for specific events and cancelling them

Maybe we could have a gamerule command for this?

**Comment by CorporalBruno** [comment]
as of right now i use
- excute as_server "gamerule option"

**Comment by BlackCoyote** [comment]
I haven't found a way to specify which world to apply that to

**Comment by BlackCoyote** [comment]
seems functional, thanks
