### ISSUE TITLE
Add wall signs to <location.attached_to> tag

### ISSUE THREAD

**Issue by irbDylan** [DenizenScript/Denizen-For-Bukkit#1383]
The location.attached_to tag currently only works for levers or buttons, but I feel having wall signs included in this would be beneficial.

**Comment by irbDylan** [comment]
Another addon similar to this could be a location.get_attached_items tag that would output a dList of the items attached to the block location, for example a sign, lever, button, or paintings/item frames.

**Comment by mcmonkey4eva** [comment]
Build that yourself with a procedure or task script :)
You'd be doing the same thing we'd do internally -> search the local area for relevant items.
it'd actually be easier in dScript that Java code.
