### ISSUE TITLE
<s@script.to_json> issues

### ISSUE THREAD

**Issue by ChemicalDatas** [DenizenScript/Denizen-For-Bukkit#1384]
Starts occurring after the vault version is bumped...
https://github.com/DenizenScript/Denizen-For-Bukkit/tree/924cfa0705db5c89602ceb29926c445278ea6c52

**Comment by mcmonkey4eva** [comment]
... what issues?

**Comment by ChemicalDatas** [comment]
The tag /<s@script.to_json/> fails to parse.

**Comment by mcmonkey4eva** [comment]
Fixed for latest dev build.

@Fortifier42 Brilliant commit there! Maven is funny sometimes.
