### ISSUE TITLE
n@npc.describe is kaput

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1387]
doesn't work for NPCs anymore, but still for regular entities

**Comment by mcmonkey4eva** [comment]
It's not really... meant to work for NPCs, beyond as coincidence because NPCs are entities, and thus have the entity tag for it when they're spawned.

**Comment by BlackCoyote** [comment]
Ah I see. could we have a tag like this for NPCs? something to list all the mechanics on the npc so we can store it as a string to then clone from even if the original npc is long gone?

**Comment by mcmonkey4eva** [comment]
Why? It's zero energy to store an NPC off-map and clone it as-needed.

**Comment by BlackCoyote** [comment]
For the instancing system I am working on, I'm creating a population config file to include in the world, which lists a bunch of entities/npcs to be cloned into the instanced clone of the original blueprint.

 It would be a lot more convenient to be able to do this without relying on having the npc still exist in the citizens save, not just for the sake of a more cleaner way to sort these save files and configs, but also gives the ability to manually edit these configs without messing with the entire citizens savefile

**Comment by BlackCoyote** [comment]
If it's difficult to add in denizen, I can just make a little procedure for it myself that keeps track of the mechanisms I really need saved, But if its not that big of a challenge, it would be nice to have it in denizen

**Comment by mcmonkey4eva** [comment]
Adding a describe means we have to rework the entire dNPC file into a series of properties, which is pretty non-trivial. We haven't even finished doing it for standard entities yet.

**Comment by BlackCoyote** [comment]
alright, I'll figure something out myself, thanks for the answer
