### ISSUE TITLE
Melee Critical Hit

### ISSUE THREAD

**Issue by CorporalBruno** [DenizenScript/Denizen-For-Bukkit#1389]
When a player jumps and hits a player in the head they deliver a critical blow in minecraft. Can we add an tag for this into the event:

on entity damages

And can we determine this damage separately?

**Comment by mcmonkey4eva** [comment]
Damage types Spigot considers separate:
```
        BASE,
        HARD_HAT,
        BLOCKING,
        ARMOR,
        RESISTANCE,
        MAGIC,
        ABSORPTION
```

**Comment by CorporalBruno** [comment]
tested these, critical hit doesnt affect any of these tags. If an attack+4 weapon is used and you critical hit all u see is the critical hit particles and you get damge returned and final damage returend (same value btw) of 5 or 6 depending.

**Comment by Xenmai** [comment]
You don't need to hit on the head in order to proc a crit, having negative vertical velocity is enough. You can probably use the "on player damages..." event normally, and add a check with - if <player.velocity.y> >= 0 { queue clear }
