### ISSUE TITLE
Skull ids bug

### ISSUE THREAD

**Issue by HeadlessJoey** [DenizenScript/Denizen-For-Bukkit#1390]
I was working with the skulls and when I have a skull in my hand and use `/ex narrate "<player.item_in_hand>"` it will return the proper ids like: i@creeper_skull, i@zombie_skull and for the dragon: i@skull_item,5

Now when I have a script with the event `"on player breaks blocks"` and then `"narrate <context.material.name>"` it will always return "skull" whether it was a dragonskull or creeperskull that was destroyed.

**Comment by mcmonkey4eva** [comment]
Because you used "`material.name`". Which returns the ... material name...

Everything is operating as expected here.
