### ISSUE TITLE
Map text

### ISSUE THREAD

**Issue by BlackRavenMC** [DenizenScript/Denizen-For-Bukkit#1391]
When i'm trying to do "/ex map 0 "text:Hello World!" x:35 y:60", it doesn't modify map.
Debug: http://mcmonkey.org/paste/32554

**Comment by Fortifier42** [comment]
Is anything going to be done about this, or will we just be relying on map scripts

**Comment by Morphan1** [comment]
It's all pretty screwed up at the moment, nothing about the map system is perfect and I don't know if it ever will be

**Comment by mcmonkey4eva** [comment]
map system has been adjusted a fair bit since then... open a new issue if there's still issues
