### ISSUE TITLE
on entity damages entity event 

### ISSUE THREAD

**Issue by tribness** [DenizenScript/Denizen-For-Bukkit#1392]
when using - determine Value , the damage dealt to the entity isnt the specified value.
I cleared all scripts and made a new test server just to be sure i wasnt having script conflict. so i made
a simple world event to test it. All updated too.
with the same script if the attacker is a player deals X damage, if its an entity deals Y damage, and none are the determined value.
the higher the value the bigger the diference from the aplied value and the one specified

heres some debugs of examples.
on player damages entity:
  - determine passively 15   < - only determines 13.8 - debug: http://mcmonkey.org/paste/32603
  - determine passively 3     < - only determines 2.76 - debug: http://mcmonkey.org/paste/32604
on entity damages player:  
  - determine passively 15   < - only determines 9.6 -   debug: http://mcmonkey.org/paste/32602
  - determine passively 3     < - only determines 1.92 -   debug: http://mcmonkey.org/paste/32605

**Comment by mcmonkey4eva** [comment]
This is a minecraft thing. Damage is modified by a variety of modifiers... If you need an exact result, you're probably best off cancelling the event and applying damage directly via `hurt` command.
