### ISSUE TITLE
New Preset available in 1.9 (THE VOID)

### ISSUE THREAD

**Issue by CorporalBruno** [DenizenScript/Denizen-For-Bukkit#1394]
Please add support for the void.

From Minecraft:

Superflat
New preset: The Void
Spawns the player on a stone platform. No other terrain generates.
The Void is now a biome with an ID of 127.

My idea is 
- createworld potatoVoid worldtype:SUPERFLAT environment:THE_VOID

But I have no real experience so just an idea. Hopefully can be done <3

**Comment by mcmonkey4eva** [comment]
Up to Spigot to add a thing for it

**Comment by MrMaleficus** [comment]
any news about this ?

**Comment by BlackCoyote** [comment]
was this added?

**Comment by mcmonkey4eva** [comment]
if it's available at all in Spigot, it's a generator or something... we have all current Spigot supported world creation options available
