### ISSUE TITLE
Entity Rotation Problems

### ISSUE THREAD

**Issue by Xenmai** [DenizenScript/Denizen-For-Bukkit#1397]
I've noticed that spawned entities don't behave correctly when rotating them, either with - rotate or with -teleport to a location.with_pose.
- Yaw doesn't work too well. Their body faces the correct yaw, but their head always face the same direction (North, slightly West). Barely a second after adjusting the entity's yaw, their body rotates back to match their fixed head yaw.
- Pitch seems to work properly, although I've noticed rotating it by 18 makes their head complete the full range of movement. That surprised me a bit, because I thought the pitch range was 180 (-90 to +90), not 18. A "0" might be missing somewhere?
- I think as well that the meta documentation regarding the rotate command could use an update. It says "yaw:< value >", when most documentations use #.# or # for values as of now. I'd suggest also adding some information about which units is the command using, so we know if it expects a value in º or in radians.

Hope to have explained myself well enough. Thanks beforehand ^^

**Comment by Xenmai** [comment]
Update:

- Rotate command seems fixed, thanks a lot! Both pitch and yaw work properly.

- Teleport command still the same. Pitch works but yaw doesn't.

- Meta documentation still the same.

Also I've noticed an interesting detail. Teleport command adjusts pitch from -90 to 90 (range of 180 degrees, half-turn), while the rotate command actually allows you to adjust pitch in a 360 range, so your head makes a full turn.

Thanks again ^^

**Comment by mcmonkey4eva** [comment]
`Teleport command still the same. Pitch works but yaw doesn't.` can't replicate.
