### ISSUE TITLE
Mount command problem

### ISSUE THREAD

**Issue by BlackRavenMC** [DenizenScript/Denizen-For-Bukkit#1398]
When entity is mounted with mount command it doesn't show mounted entity.

**Comment by mcmonkey4eva** [comment]
What versions are you on? Denizen and Spigot

**Comment by Xenmai** [comment]
If you're trying to mount that entity on a **player**, then it is a known **Spigot** issue.

**Comment by BlackRavenMC** [comment]
Denizen: build 565
Spigot: git-Spigot-5a40365-f631379

**Comment by mcmonkey4eva** [comment]
Do you mean just any two random entities, or specifically an entity on a player?

**Comment by BlackRavenMC** [comment]
Entity on a player, I didn't try entity on another entity before.

**Comment by mcmonkey4eva** [comment]
That's a Spigot/minecraft issue as Xenmai said then.
