### ISSUE TITLE
schematic load

### ISSUE THREAD

**Issue by CorporalBruno** [DenizenScript/Denizen-For-Bukkit#1399]
schematic load name:CLAIM_4523

produces:
http://mcmonkey.org/paste/32798

schematic load name:CLAIM_4523 filename:CLAIM_4523.schematic

produces no errors like above but says schematic doesnt exist make sure its in the proper folder yadayada, upon checking it is in the right folder and exists.

**Comment by mcmonkey4eva** [comment]
Corrupt schematic.

**Comment by BlackCoyote** [comment]
Is this issue resolved?

**Comment by mcmonkey4eva** [comment]
Probably.
