### ISSUE TITLE
API access to average cost of item in globalchestshop

### ISSUE THREAD

**Issue by CorporalBruno** [DenizenScript/Denizen-For-Bukkit#1401]
API access to average cost of item in globalchestshop

https://www.spigotmc.org/resources/globalchestshop-%C2%B8-%E2%80%A2-%E2%80%A2-%C2%B8-gui-shop-auction-house.6145/

https://www.spigotmc.org/members/edman93.4166/ is the author

**Comment by mcmonkey4eva** [comment]
Meant to post a Depenizen issue, maybe?
That's outside the realm of Denizen-For-Bukkit.
