### ISSUE TITLE
Give command/slot bug

### ISSUE THREAD

**Issue by Rickytehduck** [DenizenScript/Denizen-For-Bukkit#1402]
Denizen Build: 1614
Spigot Version: git-Spigot-5a40365-f631379 (MC: 1.9.2)

The slot option seems a little wonky? Like it won't always put the item in the correct slot.
When using for example:
- give i@item slot:11
The item will appear in slot 11 in the inventory. 
When running it at slot:12 next however, it sometimes will put the item at slot 11 instead, stacking with the previous item. This can happen regardless of what slot you specify. 
It seems like the first item placed attracts other items that come after or something? 

I gave this a shot on my own personal testing server to make sure it wasn't just one side, but it bugged out this way on both servers.

**Comment by Morphan1** [comment]
If you want more specific editing than that, use
`- inventory set slot:11 o:i@item`

**Comment by Rickytehduck** [comment]
Thanks!
Is it possible to set the quantity with inventory?

**Comment by Morphan1** [comment]
`i@item[quantity=3]`

**Comment by Rickytehduck** [comment]
Cheers!
