### ISSUE TITLE
Createworld & grief prevention

### ISSUE THREAD

**Issue by CorporalBruno** [DenizenScript/Denizen-For-Bukkit#1403]
When creating /loading world with denizen, grief prevention does not hook into them even upon the soft reload feature they have built in with their plugin (as by design apparently).

Please help get denizen to load the claims from girefprevention when denizen opens a new world.

Thanks <3

**Comment by Morphan1** [comment]
Uh... Isn't this their problem? Bukkit provides everything necessary for them to listen for when a new world is created

**Comment by CorporalBruno** [comment]
they coded it this way on purpose to "deter lag spikes"

**Comment by mcmonkey4eva** [comment]
Well... they coded it wrong :(
