### ISSUE TITLE
NBT spam

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1407]
items with NBT inside item container scripts produce spam in console even when debug is set to false.

```
FeebleBlade:
  type: item
  debug: false
  material: m@iron_sword[flags=hide_attributes;nbt=price_buy/6.80|price_sell/4.25|dmg_min/2|dmg_max/4]
  display name: <&7>Feeble Blade
  lore:
  - <&f>One Handed                Sword
  - <&f>2-4
  - <&7><&o>trash
```
/ex give i@feebleblade

http://mcmonkey.org/paste/32907

Thanks, Uledrith

**Comment by Morphan1** [comment]
Welp. I guess since people are already using the mech like that, might as well document it. I'm pretty sure there was a reason I didn't want people using it but I don't even remember so wee

**Comment by BlackCoyote** [comment]
maybe you didn't want people using it because you were too lazy to remove the debug yolo swaghetti 420 blaze it
