### ISSUE TITLE
accessor bug

### ISSUE THREAD

**Issue by ChemicalDatas** [DenizenScript/Denizen-For-Bukkit#1410]
There is issues with doing object access. `%accessor% `isnt parsed correctly and misses the final "]" when the accessor is `"parse[name]".`

```
accessor bug:
    type: task
    definitions: accessor
    script:
    - announce "%accessor%"
    - define list <server.list_online_players>
    - announce "<def[list].%accessor%>"
```

http://mcmonkey.org/paste/33023

**Comment by mcmonkey4eva** [comment]
Why in god's black space are you even trying that?

**Comment by ChemicalDatas** [comment]
Not sure, just going through some older debug logs and looking at some scripts that should be working still. I think the idea was having some object in a working queue that could be access different ways to produce data based upon request.

**Comment by ChemicalDatas** [comment]
It looks like it should work.

**Comment by ChemicalDatas** [comment]
It seems that code missed some tags that should be in there....

**Comment by mcmonkey4eva** [comment]
It won't have worked for the past few years after an ancient update to how tags are parsed... and it's not going to be made functional, as that would slow down tag parsing...

**Comment by ChemicalDatas** [comment]
Could you point me to where that part of the code is?

**Comment by mcmonkey4eva** [comment]
.. which part of the code, and what do you want to gain from reading it?

**Comment by ChemicalDatas** [comment]
The part of the code where that parsing occurs.

**Comment by mcmonkey4eva** [comment]
This is ancient code that's been rewritten already (Though the rewrite is not yet in use, and will be for Denizen 2.0) ... but here ya go: https://github.com/mcmonkey4eva/Denizen-Core/blob/master/src/main/java/net/aufdemrand/denizencore/tags/TagManager.java#L311

**Comment by ChemicalDatas** [comment]
Thanks for the help.
