### ISSUE TITLE
midi command to support .nbs files

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#1411]
NBS files are files created from a program called Minecraft Note Block Studio which has an interface of creating noteblock songs and then save as .nbs or export as .mid
You can find more information about it here: http://www.stuffbydavid.com/mcnbs

The problem is that "Denizen's player" is out of tune if I play an exported .mid file (it sounds horrible).
Therefore, by reading from a .nbs file, it should be much better to listen to in-game with the right tunes as well.

**Comment by Mwthorn** [comment]
After further investigation, its not much about the tunes but its actually the beat types.
Denizen only seems to support Piano / Double Bass. It is missing the Bass Drum, Snare Drum and Click. 
I would be okay if this was fixed instead.

**Comment by zozer** [comment]
I recently tried doing the midi command on the example file given (in a 1.10 server) and it sounds like someone attempted to redo the song only using clicks.

**Comment by Mwthorn** [comment]
Will this ever be a thing? Or maybe its for Depenizen instead?

**Comment by mcmonkey4eva** [comment]
Oh what how'd this slip by - the midi command may be fixed (hopefully), but .nbs support is pointless.
