### ISSUE TITLE
Tags throwing errors before able to check whether valid tag.

### ISSUE THREAD

**Issue by ChemicalDatas** [DenizenScript/Denizen-For-Bukkit#1413]
These tags throw errors before you can check if its a valid tag. Even if you provide a default fallback.
It will also throw the same error twice.
    - co\Color
    - cu\Cuboid
    - in\Inventory
    - w\World

Debug Output:
http://mcmonkey.org/paste/33353

Example Script:
http://mcmonkey.org/paste/33355

**Comment by mcmonkey4eva** [comment]
fallbacks are magic in modern version, as debug shuts up more often when a fallback is available
