### ISSUE TITLE
more task script speed control!

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1422]
I would love an `instant: true` option for task scripts,  so i don't have to do `- run scriptname instantly` everywhere.

I would also love a `speed:#`argument for the run command, to determine the delay in between commands from a variable from outside the script, rather than a hardscripted config value.

**Comment by Fortifier42** [comment]
In my latest PR. https://github.com/mcmonkey4eva/Denizen/pull/70

**Comment by BlackCoyote** [comment]
halfway there! :)

**Comment by Morphan1** [comment]
50eb4a0

**Comment by BlackCoyote** [comment]
:)))))
