### ISSUE TITLE
on player clicks in inventory bug

### ISSUE THREAD

**Issue by MarkLyck** [DenizenScript/Denizen-For-Bukkit#1425]
When running the following event:

on player clicks i@item1 in inventory with i@item2:

If you have a give command, and you use - determine cancelled to cancel the event.

It will give you 5 items instead of 1.

Here's the script causing the bug:

    on player clicks i@item1 in inventory with i@item2:
    - give "i@item1[display_name=Key;lore=<context.item.lore.formatted>]"
    - determine cancelled

**Comment by mcmonkey4eva** [comment]
try changing that script to:
```
on player clicks item1 in inventory with item2:
- determine passively cancelled
- wait 1t
- give "i@item1[display_name=Key;lore=<context.item.lore.formatted>]"
```

**Comment by MarkLyck** [comment]
That seemed to work perfect. Thanks!
