### ISSUE TITLE
Denizen save error

### ISSUE THREAD

**Issue by Carisus** [DenizenScript/Denizen-For-Bukkit#1426]
We noticed that our notables and flags were not saving on server restart. We ran /denizen save and got [this](http://mcmonkey.org/haste/33793) error. This is specific to this server, same builds on other servers do not throw it.

**Comment by Carisus** [comment]
I had some notable cuboids that were in unloaded worlds. I commented out those notables and the command runs fine. Shouldn't Denizen just ignore those instead of throwing an error?

**Comment by mcmonkey4eva** [comment]
Fix submitted to mineco dev build 590. (Catches the errors and safely 'ignores' the bad notables with a warning message)
Thanks for the report!
