### ISSUE TITLE
Map command doesn't work

### ISSUE THREAD

**Issue by MarkLyck** [DenizenScript/Denizen-For-Bukkit#1428]
The map command doens't seem to work. With the exception of resetting the map to a new position.

nothing shows up if you try to add text to a map.

and trying to add an image causes an internal server error and kicks you.

**Comment by Fortifier42** [comment]
Setting the map to an image works for me. It appears there is no code for the text based addition? @mcmonkey4eva @Morphan1 

Tested on:
![capture](https://cloud.githubusercontent.com/assets/598503/15775622/33ad4228-29c6-11e6-8b5d-d383aa069a7b.PNG)

**Comment by BlackCoyote** [comment]
We talked about it in the IRC a bit. Map scripts are now the prefered way to do this, as marklyck will probably already know.

Here's an example for anyone else: http://mcmonkey.org/haste/33978

**Comment by Fortifier42** [comment]
Main point of concern from my previous post: The map command doesn't have any code to render text.
in particular, this piece of meta is invalid.
````
/text:<text>
<monkeybot> Usage: Use to add some text to map 0
<monkeybot>   - map 0 "text:Hello World!" x:35 y:60
````

**Comment by Morphan1** [comment]
Basically all of the map command's meta is invalid, I need to get around to updating it. It's so sad to do though when map scripts themselves are so jittery

**Comment by BlackRavenMC** [comment]
I reported this long time ago. #1391

**Comment by Fortifier42** [comment]
pls?
