### ISSUE TITLE
insanely high (and wrong) measure of <pl.ping>

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#1430]
Hello,

When i joins my server, my pl.ping tag indicates this : 

<img width="821" alt="capture d ecran 2016-06-04 a 17 19 11" src="https://cloud.githubusercontent.com/assets/5609863/15800447/328fe33c-2a7a-11e6-8c7b-7fe2e1f3a1d2.png">

This measure is wrong, but becomes correct after 2 minutes : 

<img width="793" alt="capture d ecran 2016-06-04 a 17 21 08" src="https://cloud.githubusercontent.com/assets/5609863/15800453/4d7fa2cc-2a7a-11e6-9548-e27c6d06467b.png">

Using latest spigot and denizen_dev.

Thank you !
MM

**Comment by mcmonkey4eva** [comment]
Yup, this is a known issue, believed to be something wrong with Mojang's own internal ping tracking.

I've seen ping go both really high and far negative, in both cases the ping tracker in the tab menu goes red, leading me to believe Mojang's ping tracking is the internal fault here (as it appears to have the same numbers we do)

**Comment by Fortifier42** [comment]
pls
