### ISSUE TITLE
resource_pack mechanism NPE

### ISSUE THREAD

**Issue by Mickket** [DenizenScript/Denizen-For-Bukkit#1437]
Using the resource_pack mechanism throws a NPE.
[Debug Paste](http://mcmonkey.org/paste/34401)

**Comment by Morphan1** [comment]
Update to the latest developmental build
http://ci.mineconomy.org/job/Denizen_Developmental/lastSuccessfulBuild/

**Comment by Mickket** [comment]
Updating fixed this issue and the resource pack event.
