### ISSUE TITLE
Denizen Adjust Skin Blob

### ISSUE THREAD

**Issue by ryanboerner** [DenizenScript/Denizen-For-Bukkit#1439]
I am trying to adjust the skin blob of an npc on assignment, and the reason I cannot get a skin to appear seems to be a bug. This is me giving an assignment to an NPC. [http://mcmonkey.org/paste/34403](http://mcmonkey.org/paste/34403)

**Comment by BlackCoyote** [comment]
i can confirm it does not work, and so can @Morphan1

**Comment by Morphan1** [comment]
@BlackCoyote no, this is for NPCs.
Anyway, we set the data using Citizens2's way of doing it, so this particular bug is C2 I believe?

**Comment by BlackCoyote** [comment]
@Morphan1 i can confirm it doesn't work on npcs either D:<

**Comment by mcmonkey4eva** [comment]
Doesn't it require you set the skin name THEN the skin blob? or something like that...

**Comment by BlackCoyote** [comment]
can't get it to work for npcs nor players even when using the skin mechanism to set the skin to the username the blob was taken from, before setting the blob

**Comment by Morphan1** [comment]
@BlackCoyote but it's 2 different systems is what I'm saying

**Comment by BlackCoyote** [comment]
@Morphan1 and they're both equally broken is what I'm saying D:<

**Comment by mcmonkey4eva** [comment]
This was patched
