### ISSUE TITLE
"on item recipe formed" not resetting when cancelled

### ISSUE THREAD

**Issue by Mickket** [DenizenScript/Denizen-For-Bukkit#1444]
This event is not resetting properly when it is cancelled.

```
        on gold_helmet recipe formed:
         - determine cancelled
```

You can craft items until you attempt to form a gold_helmet recipe. After that point all recipes break.

**Comment by KeangDavid** [comment]
Try '- determine i@air' in the mean time.

**Comment by mcmonkey4eva** [comment]
I believe this was fixed
