### ISSUE TITLE
Location.base_color Error for banners.

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Denizen-For-Bukkit#1447]
http://mcmonkey.org/paste/34663

Returns invalid tag for a location's banner base_color.
Appears to do the same thing for location.patterns as well.

**Comment by mcmonkey4eva** [comment]
@Morphan1 https://github.com/DenizenScript/Denizen-For-Bukkit/commit/57d2a5b0534fba2adf165287842e6c5fb37b25d2 that... bad morphan :(

Should be more functional in the new dev build, as I fixed the error at hand. No promises there isn't another error somewhere else in that same code though.

**Comment by KeangDavid** [comment]
Tested, and fixed.
