### ISSUE TITLE
Recipe events trunning banners black.

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Denizen-For-Bukkit#1449]
Some failed determination of some sort? http://mcmonkey.org/paste/34671
This also happens in the second double firing of the, On player crafts item event.

**Comment by KeangDavid** [comment]
http://mcmonkey.org/paste/34676
Manually duplicate the craft event.
Same technique does not seam to work on recipe formed.

**Comment by mcmonkey4eva** [comment]
Likely can merge into #1817 or #1678
