### ISSUE TITLE
item_in_hand mechanisim

### ISSUE THREAD

**Issue by zozer** [DenizenScript/Denizen-For-Bukkit#1450]
adding a mechanism to adjust an entities item in hand

**Comment by BlackCoyote** [comment]
what's wrong with `- equip <entity> hand:<item>`?

**Comment by zozer** [comment]
well, i was making an entity script where I wanted the entity to have a weapon and armor. There is an equipment mech.. but no mech for item in hand. and while yes you could save the entity and then equip the item in hand, i just think it would be more convenient in cases like this.

**Comment by mcmonkey4eva** [comment]
added
