### ISSUE TITLE
on entity dies cant find the script attached to the entity

### ISSUE THREAD

**Issue by zozer** [DenizenScript/Denizen-For-Bukkit#1451]
on player kills entity can find the script, but on entity dies can not
http://mcmonkey.org/paste/34765
(line 148 and 194)
(also on a side note maybe add a mech to define what the entity will drop on death?)

**Comment by mcmonkey4eva** [comment]
This is an unfortunate limitation of the current system.

Entities are deleted, THEN the dies event fires within Spigot. You'll have to find an alternate method to track the entity if you MUST use the dies event. A quick server flag would generally world.

We may be able to use NBT magic to fix this in the future though...
