### ISSUE TITLE
Step on loop

### ISSUE THREAD

**Issue by Mormaii** [DenizenScript/Denizen-For-Bukkit#1456]
I've got this script:

```
TestScript: 
    type: world 
    events: 
        on player steps on iron_block in Hub: 
        - shoot <player> height:4 gravity:0.3 save:TEST 
        - foreach <entry[TEST].shot_entities>: 
            - flag <def[value]> no_damage 
        on player damaged by FALL in Hub: 
        - if <context.entity.has_flag[no_damage]> { 
            - determine passively cancelled 
        } 

```

Version: `[04:03:51 INFO]: version: 0.9.8-SNAPSHOT (build 595), core version: 1.10 (Build ${build.number})`
And this is the issue I'm getting: https://imgur.com/a/4CvId

It apparently looks like the event to step on "heavy_weighted_pressure_plate" doesn't work either.

**Comment by mcmonkey4eva** [comment]
`- shoot <player> height:4 gravity:0.3 save:TEST `
You're using the shoot command entirely wrong, first off.

Also, what's the error message in console?

**Comment by Mormaii** [comment]
How would I use it then? There's no error message but the script goes on a constant loop and then it crashes the server.
I added a cooldown to get it to work without crashing

```
TestScript:
    type: world
    events:
        on player steps on IRON_BLOCK in Hub:
        - if <player.has_flag[booster_cooldown]> queue clear
        - flag <player> booster_cooldown duration:2s
        - shoot <player> destination:<l@location.precise_cursor_on> height:4 gravity:0.3 save:TEST
        - foreach <entry[TEST].shot_entities>:
            - flag <def[value]> no_damage
        on player damaged by FALL in Hub:
        - if <context.entity.has_flag[no_damage]> {
            - determine passively cancelled
        }
```

**Comment by mcmonkey4eva** [comment]
The best way to do it is to not use shoot at all actually.
```
- adjust <player> velocity:<player.velocity.add[0,2,0]>
- flag <player> no_damage
```

Also, the item you're looking for is either `gold_plate` or `iron_plate`. and the event `on player stands on <pressure plate>:`

**Comment by Fortifier42** [comment]
@mcmonkey4eva actually an issue?
