### ISSUE TITLE
Cuboid tag

### ISSUE THREAD

**Issue by mawej1** [DenizenScript/Denizen-For-Bukkit#1457]
`<cu@cuboid_name.list_npcs>` gives off http://mcmonkey.org/paste/35165

**Comment by mcmonkey4eva** [comment]
What exactly does `cu@graveyard` represent?

**Comment by mawej1** [comment]
`graveyard: -50,70,5,Tristram|-6,76,39,Tristram`

Yes, there are a few old/non-used npcs inside non-loaded worlds - should they be deleted?

**Comment by mcmonkey4eva** [comment]
Definitely delete or move those, they're probably the source of the error, I think.

**Comment by mawej1** [comment]
Deleted unused NPCs, got the same result http://mcmonkey.org/paste/35301

**Comment by mcmonkey4eva** [comment]
You somehow still have NPCs with null locations :/

**Comment by mawej1** [comment]
My apologies, two fuckers slipped away. Thanks for help.
