### ISSUE TITLE
Create command in WG regions

### ISSUE THREAD

**Issue by mawej1** [DenizenScript/Denizen-For-Bukkit#1460]
When executing `create n@18 Skeleton <player.location>` inside a WorldGuard region that has a flag deny-spawn: skeleton, the npc gets spawned (I can do /npc sel), but it is invisible. n@18 has a sentinel trait and has type skeleton. When I go outside of this region, the command works as expected.

However, when I try `/npc create Skeleton --type skeleton --trait sentinel` in the same region, it works perfectly.

This happened a day ago when I updated to the newest versions of Denizen, Sentinel & Citizens, but I can't tell the exact version I was using before, because I removed the older versions.

**Comment by mcmonkey4eva** [comment]
Denizen tries where possible to do things "properly", meaning allowing other plugins to interfere as needed. In this case, Denizen is allowing WorldGuard to do its job, and Citizens is overriding the correct functionality with its own.

That aside, you're doing two different commands.
On the Citizens command, you're spawning a /new skeleton NPC/ whereas in the Denizen command, you're /cloning and then teleporting/ an existing NPC.

**Comment by mawej1** [comment]
So with that said, is there a way to achieve desired result with current configuration? In other words, how to prevent the spawning of entity skeletons but allow npc skeletons? 

Also, curiosity won't stop me from asking, why was this not a problem with previous versions released over past month? Of course I don't want to interviere into the development process, I am simply curios.

Thanks

**Comment by mcmonkey4eva** [comment]
Haven't touched that code in Denizen in forever, so not our doing~

Might be the Citizens redesign.

**Comment by BlackCoyote** [comment]
just gonna leave this here:

it's extremely simple to just make a denizen cuboid over the region and cancel non npc mob spawning in there

**Comment by mawej1** [comment]
@BlackCoyote That sounds like a simple solution, but I think that this might be a problem in the future for new Denizen users, as this might influence other entity types too.

@mcmonkey I see, so should I then redirect the issue to the Citizens corner?

**Comment by mcmonkey4eva** [comment]
I guess, but you'll probably just be told to configure WorldGuard better - it's not Citizens' fault that WorldGuard blocks entities teleporting in /when you tell it to do exactly that/.

**Comment by mawej1** [comment]
Ok, I will try, but the interesting thing is that you can still do /npc select and edit the npc - it is just invisible. 

Thanks
