### ISSUE TITLE
add player Exhaustion tag and mechanism

### ISSUE THREAD

**Issue by DNx5** [DenizenScript/Denizen-For-Bukkit#1464]
[org.bukkit.entity.Player#setExhaustion(float)](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#setExhaustion(float))
[org.bukkit.entity.Player#getExhaustion()](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#getExhaustion())

**Comment by mcmonkey4eva** [comment]
Added to dev build 5

**Comment by DNx5** [comment]
Thanks
