### ISSUE TITLE
Exception when trying to query player flag

### ISSUE THREAD

**Issue by Armin79** [DenizenScript/Denizen-For-Bukkit#1466]
Hi!

I'm new with denizen scripts, and read several example scripts and manuals, so it could be I do something wrong, but I think the mod anyway should not crash :) but it does, when I try to access a player's flag.
Then it comes with an IndexOutOfBoundException.

In my script I try to set up a first experimental dialogue script, currently mor for testing how the system works. What I try to do is when the player is in range say some random message and set the player's flag "VisitedMissSally" to 1. If the player comes in range again check this players flag, and if it is set to 1, say another message (like he visited already). Sure I will add a cooldown later on.
No matter what code sample and syntax from the documentation I try, like `<player.flag[VisitedMissSally]>`, `<@p.player.flag[VisitidMissSally]>` or whatever I try, it doesn't seem to work and even crashes, like you can see in my attached log file. 

So I hope I'm right considering it as a bug, because I think there should be no internal exception when querying flags.
If I did something wrong which cause this problem already want to apologize :)

Attached you also can find the script I'm using.
The denizen mod I'm using is the latest one I have downloaded from this link:
https://dev.bukkit.org/bukkit-plugins/denizen/files/32-denizen-0-9-8-mc-1-10/

I also have the citizen 2 mod installed 2.0.16.
Using SpigotMC 1.10.2

Thank you for your attention!
[miss_sally.txt](https://github.com/DenizenScript/Denizen-For-Bukkit/files/484447/miss_sally.txt)
[miss_sally_logpiece.txt](https://github.com/DenizenScript/Denizen-For-Bukkit/files/484448/miss_sally_logpiece.txt)

**Comment by mcmonkey4eva** [comment]
The error isn't from the flag.

Your script is very misformatted. Check the tutorial videos here: http://mcmonkey.org/denizen/vids
In particular the one on the `if` command, which shows how to format it.

In more specifics:
spacing matters... a fair bit.
You have something like:
```
- if x {
  - do whatever
  }
else {
- do whatever
  }
```
which doesn't work.
The correct formatting of that example would be:
```
- if x {
  - do whatever
  }
  else {
  - do whatever
  }
```

The basic rule is that everything inside a `{ braced }` block must be spaced out beneath it.
(Note that on modern versions, `else` and `}` can be spaced even with the `- if` optionally, if you prefer that format)


ALSO fair warning:
You downloaded a build from June - specifically the first functional 1.10 version
More recent versions are available at: http://ci.citizensnpcs.co/job/Denizen/
