### ISSUE TITLE
Trading

### ISSUE THREAD

**Issue by KernalMage** [DenizenScript/Denizen-For-Bukkit#1469]
I have made 3 scripts, and each one of them, the first two inventory slots don't work. The others do. It gives me the item but doesn't take anything.

http://one.denizenscript.com/haste/36425

http://mcmonkey.org/paste/36426

**Comment by BlackCoyote** [comment]
The first one doesn't work because 

```        - if <player.inventory.contains[i@iron_ingot].quantity[2]> { 
            - take i@gold_ingot quantity:2 ```

You're checking if they have iron, then trying to take gold

the second one doesn't work because

```- take i@i@iron_ingot_ingot quantity:1```` 

i@i@iron_iron_ingot does not happen to be a valid item
