### ISSUE TITLE
Bug report crash server

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1474]
Denizen Version : Devbuild 22 (25/09/2016 - 10:39)
When a player try to connect it said "Building terrain" and then after a certain time "time out" and then the server crash
bug report : http://pastebin.com/wRnvyuUF

**Comment by mcmonkey4eva** [comment]
No idea what that error is or why it might be Denizen related, tbh.

**Comment by Vellric** [comment]
@mcmonkey4eva it happens with the Message Constructor Library script, only with Denizen 1.0.0. I had exactly this problem and going back to the dev build before the d1.0.0 fix the problem. 

I tested it on a server with no plugins except Denizen, and with Message Constructor Library as the only script. When you put that script out, it works fine.

**Comment by Morphan1** [comment]
http://ci.citizensnpcs.co/job/Denizen_Developmental/lastSuccessfulBuild/

**Comment by Noiknez** [comment]
Latest developmental build work fine, thank you
