### ISSUE TITLE
Entity Dies Event Error

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#1476]
In minecraft 1.8.8 When an entity dies it causes an error
Debug: http://one.denizenscript.com/paste/36424

**Comment by mcmonkey4eva** [comment]
:o @Morphan1 didn't modulize potions right

**Comment by mcmonkey4eva** [comment]
Try the new dev build, ^ that might help?

**Comment by Mwthorn** [comment]
The errors seems to have been fixed with the new build. Thanks ^^

**Comment by Morphan1** [comment]
I'm... Not sure how that could've fixed your errors. Are you sure that the errors you were receiving on the build before the latest one were the same as that log you gave from build 19?
