### ISSUE TITLE
Event equip item

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1477]
Greeting,
i created this issue because the event
`"on player equips <item>:"` does not work,
but the event
`"on player unequips <item>:" `work

I tried this with Elytra, and gold_chestplate
When using a more general event like "on player equip armor" it work, but not when using specific minecraft chest item
Tried with =
Denizen 1.0.0r2
Denizen dev #29

**Comment by Morphan1** [comment]
Try the latest Denizen developmental build
http://ci.citizensnpcs.co/job/Denizen_Developmental/lastSuccessfulBuild/

**Comment by Noiknez** [comment]
It work now ! Thank you
