### ISSUE TITLE
Notables saved twice

### ISSUE THREAD

**Issue by DNx5** [DenizenScript/Denizen-For-Bukkit#1479]
I think this line shouldn't exist. because the method already called inside ``saveSaves()``.
https://github.com/DenizenScript/Denizen-For-Bukkit/blob/master/plugin/src/main/java/net/aufdemrand/denizen/DenizenCommandHandler.java#L304

Also, is it okay if denizen save process running outside main thread? would be good to reduce lag spike.

**Comment by mcmonkey4eva** [comment]
... how many notables do you have that you lag from saving them 0.0

**Comment by DNx5** [comment]
@mcmonkey4eva I mean, for the saves.yml

**Comment by mcmonkey4eva** [comment]
... how much general disorganized save data do you have that you lag from saving it?

**Comment by DNx5** [comment]
It's not me, 
https://one.denizenscript.com/denizen/logs/denizen-dev#2016/10/04-06:01:16

**Comment by mcmonkey4eva** [comment]
lol big servers with poorly optimized scripts lag... I mean we can only async the saving so far. We can asynchronize the copy from RAM to disk, but it still has to do a lot of sync calculations to ready the save data...

Denizen2 is a lot nicer on save data in theory (it operates within Minecraft's own save data, not in separate YML's)... as far as Denizen1: the trick is to use SQL and YAML commands to optimize things in your scripts, the built in saves are really old and weak :/

**Comment by DNx5** [comment]
yeah, I understand that async isn't always good. 
I will close this as the problem is fixed.
Denizen2 looks promising, can't wait for it to ready!
