### ISSUE TITLE
PlayEffect Issues/Doubts

### ISSUE THREAD

**Issue by Xenmai** [DenizenScript/Denizen-For-Bukkit#1480]
I've noticed some errors as of lately with this command, and I'd like to ask a couple things.

First, the _blockcrack_id_ and _blockdust_id_ throw an exception, probably not being recognized as effects. I've seen 2 new effects, _tile_break_ and _tile_dust_, that could have replaced those, but then the meta shoould be updated.

Some effects seem duplicated, like _magic_crit/crit_magic_ and _spell_instant/instant_spell_. Is this intended for some sort of backwards compatibility? Then _red_dust_ could be added to the list, because it works just like the new _redstone_.

Also, is _color.to_particle_offset_ only used in _red_dust/redstone_. I can't get it to work with _potion_swirl_, as setting quantity to 0 results in no particles being shown. The colours seem random with this one.

Last but not least, the particle effect list needs some cleaning :o

**Comment by Morphan1** [comment]
It's all a mix of Bukkit code and NMS code. For some stupid reason, Bukkit decided that reversing  and/or entirely screwing up all the names was the best course of action when making their enums. I haven't seen an exception for blockcrack and the like, could you provide that? 
Also, yes, color is only for certain particles in very specific cases

**Comment by BlackCoyote** [comment]
those 'potion' effects that take colors are some of these maybe ` SPELL, SPELL_INSTANT, SPELL_MOB, SPELL_MOB_AMBIENT,  SPELL_WITCH`

**Comment by Xenmai** [comment]
`16:56:59 [INFO]  Starting InstantQueue 'EXCOMMAND_TrademarkLockGuru'...  
16:56:59 [INFO]  Queue 'EXCOMMAND_TrademarkLockGuru' Executing: PLAYEFFECT  
                   "<player.eye_location>" "effect:blockdust_174" "data:0.0"  
                   "quantity:1" "visibility:16"  
16:56:59 [INFO] +- Executing dCommand: PLAYEFFECT/p@xenmai ---------+  
16:56:59 [INFO]  Filled tag <player.eye_location> with  
                   'l@10003.419565381058,70.62,9973.42460310736,50.46556,-320.08792,world'.  
16:56:59 [INFO] +> Executing 'PLAYEFFECT': iconcrack_type='blockdust'   
                   iconcrack='174'   
                   locations='[l@10003.419565381058,70.62,9973.42460310736,50.46556,-320.08792,world]'  
                    radius='16'  data='0.0'  qty='1'  offset='l@0.5,0.5,0.5'  
16:56:59 [INFO]  ERROR! Woah!! An exception has been called with this command!  
16:56:59 [INFO]  ERROR! Internal exception was thrown!  
16:56:59 [SEVERE] java.lang.NullPointerException 
16:56:59 [SEVERE] net.aufdemrand.denizen.scripts.commands.world.PlayEffectCommand.execute(PlayEffectCommand.java:316) 
16:56:59 [SEVERE] net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:248) 
16:56:59 [SEVERE] net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54) 
16:56:59 [SEVERE] net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:678) 
16:56:59 [SEVERE] net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:61) 
16:56:59 [SEVERE] net.aufdemrand.denizencore.scripts.queues.ScriptQueue$1.run(ScriptQueue.java:509) 
16:56:59 [SEVERE] net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:528) 
16:56:59 [SEVERE] net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1228) 
16:56:59 [SEVERE] org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) 
16:56:59 [SEVERE] org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) 
16:56:59 [SEVERE] org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) 
16:56:59 [SEVERE] net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) 
16:56:59 [SEVERE] net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) 
16:56:59 [SEVERE] net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) 
16:56:59 [SEVERE] net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) 
16:56:59 [SEVERE] net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) 
16:56:59 [SEVERE] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
16:56:59 [SEVERE] java.util.concurrent.FutureTask.run(FutureTask.java:266) 
16:56:59 [SEVERE] net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) 
16:56:59 [SEVERE] net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) 
16:56:59 [SEVERE] net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) 
16:56:59 [SEVERE] net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) 
16:56:59 [SEVERE] net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) 
16:56:59 [SEVERE] java.lang.Thread.run(Thread.java:745) 
16:56:59 [INFO] +> [Denizen] (Attempted: PLAYEFFECT "<player.eye_location>"  
                   "effect:blockdust_174" "data:0.0" "quantity:1"  
                   "visibility:16")  
16:56:59 [INFO] +---------------------+  
16:56:59 [INFO]  Completing queue 'EXCOMMAND_TrademarkLockGuru' in 2ms.  `

**Comment by Xenmai** [comment]
Just checked and the same combination that works for setting colour to _red_dust/redstone_ effects (q:0, offset:color to offset...) doesn't seem to change the colour of spell effetcs. Setting quantity to 0 does indeed show 1 particle, but the colour stays always the same. Might be a bug?

**Comment by Morphan1** [comment]
Blockcrack etc should be fixed in the latest build.
We don't control what works with color and what doesn't, #blamemojang
