### ISSUE TITLE
Item Script Recipes With Quantities

### ISSUE THREAD

**Issue by Morphan1** [DenizenScript/Denizen-For-Bukkit#1482]
Item script recipes should use special handlers to allow things like

```
recipe:
- air|air|air
- air|air|air
- charcoal|iron_ore[quantity=5]|charcoal
```

(note the quantity)
The system needs to be generally improved, really, and should probably support any kind of properties

**Comment by mcmonkey4eva** [comment]
Redirecting to #1851

**Comment by mcmonkey4eva** [comment]
Handled via resolution to #1851
