### ISSUE TITLE
Item Recipe Event

### ISSUE THREAD

**Issue by HeadlessJoey** [DenizenScript/Denizen-For-Bukkit#1484]
Sorry again a small issue with this event `on item recipe formed`

```
ChangeRecipeItems4:
  type: world
  events:
    on torch recipe formed:
    - determine i@stone
```

```
ChangeRecipeItems2:
  type: world
  events:
    on SteelIngot2 recipe formed:
    - determine i@stone
```

Recipe for the SteelIngot2:

```
  recipe:
  - air|air|air
  - charcoal|iron_ore|charcoal
  - air|air|air
```

These are both working (so SteelIngot2 is a custom item).
HOWEVER if you shift click the item, so let's say we put in 5 charcoal, 5 iron_ore and 5 more charcoal, then it will not give you 5 stone but 5 SteelIngot2.
So the determine here doesn't work if you shift click for multiple items, instead of getting 5 stone it gives you the 5 SteelIngot2.

Weird part, this does work for the torch one, so if you put in 5 coal and 5 sticks and then shift click you'll get 5 stone.
It just doesn't work for custom items.

**Comment by Morphan1** [comment]
@mcmonkey4eva this sounds like an issue with tryItem or whatever it's named? Probably checks for quantities which... It probably shouldn't

**Comment by mcmonkey4eva** [comment]
I dunno about any of that inventory stuff. All I've done in it is minor tweaks.

**Comment by Fortifier42** [comment]
@Morphan1 doesn't tryItem set the quantity to 1 regardless?

**Comment by mcmonkey4eva** [comment]
Redirecting to #1851

**Comment by mcmonkey4eva** [comment]
Probably better now thanks to the resolution to #1851
