### ISSUE TITLE
Location.Facing.Degrees Pitch Request

### ISSUE THREAD

**Issue by Xenmai** [DenizenScript/Denizen-For-Bukkit#1485]
Hi there. Right now, `location.facing[].degrees[#]` accepts a yaw value. Would it be possible to turn it into `location.facing[].degrees[#,#]` so you can also specify a pitch range to check? It'd help me a lot. Thanks in advance for your time.

**Comment by mcmonkey4eva** [comment]
Added in DEV-474+
