### ISSUE TITLE
Update Damage Cause Meta

### ISSUE THREAD

**Issue by Xenmai** [DenizenScript/Denizen-For-Bukkit#1486]
Hi there. I was testing around ingame, and noticed narrating the damage cause when you glide into a block returns _fly_into_wall_. The damage cause list at http://one.denizenscript.com/denizen/lngs/damage%20cause is missing this one, so it should be easy to update ^^ Thanks in advance.

**Comment by Morphan1** [comment]
Why do we even maintain lists of things we don't have to 
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html

**Comment by mcmonkey4eva** [comment]
Done (per @Morphan1 's suggestion)
