### ISSUE TITLE
Achievements - Tag

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Denizen-For-Bukkit#1487]
Can find a tag to results player achievements. 

Thanks.

**Comment by Oruss7** [comment]
Any news ?

**Comment by mcmonkey4eva** [comment]
@Oruss7 thanks for the suggestion! And sorry for the delay!
The option wasn't available at the time, but it is now!
It's available in the latest dev build :) (`DEV-99`)
`<player.has_achievement[ACHIEVEMENT_GOES_HERE]>`

**Comment by Oruss7** [comment]
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Achievement.html ? is this list or mojang list ?

**Comment by mcmonkey4eva** [comment]
Yup, that one
