### ISSUE TITLE
Inventory command/conditions issues

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1489]
I've seen to have gotten in a pinch.

I'm currently using Spigot 1.10.2 (version git-Spigot-90f61bc-6053c5c), and when I use commands that search for and deal with items in the inventory, I encountered a few problems. One I've already made aware to BlackCoyote and Morphan1, that the "on player (un)equips armor" event doesn't really work.

In addition to such, I have found the following issues:
- the "on player clicks in inventory" event doesn't properly register shift clicks.
- when using "if" commands to detect the items in the armor slots, it appears that if I order my commands like this: http://pastebin.com/8jPvrWS4 , the head armor slot _must_ be empty before the other slots are registered by the script.
- if I reverse the order of the same script (that is, detect the head armor first, then the chestplate, then the leggings, then the boots), then only the head armor slot is affected by the script.
- clicking on one item consecutively makes scripts ignore it (or, according to the debugger, makes the scriptname return as null). Clicking on the item, then another item seems to work fine, but clicking on the same item twice in a row appears to break the scripts. This can be replicated by using the same above script and trying to click on the Structure Void blocks with no cursor item.

EDIT: On the IRC, I use the nickname "suspic", just in case you're wondering about my comment on how I already told BlackCoyote and Morphan1 about the event.

EDIT 2: Even without the async's in the script, the issue persists.

**Comment by mcmonkey4eva** [comment]
Please remove the line `- async:` from each script, that really really really does not belong.

**Comment by MusicScore** [comment]
Even without async, the issue persists. I added the async as a test, I should have noted that you could remove the async's and the issue still exists. My apologies.

**Comment by mcmonkey4eva** [comment]
Can you post a debug report from the script?

**Comment by MusicScore** [comment]
http://one.denizenscript.com/paste/36902

That's the debug when I'm clicking on the same item consecutively (the Structure Voids). When I click on one of them, the script does as it should. When I click on the same Structure Void again, the script doesn't seem to be able to catch that particular instance. Clicking on other items "fixes" the issue, but it allows for many loopholes.

https://youtu.be/rpLW8Zdtj2Q

The above video shows what happens on the user's end when they click on the same item consecutively. It's hard to determine if I'm just single clicking or double clicking, but I assure you that when the items seem to disappear, I am double clicking.

I could replicate the issue with at least 1 of each Structure Void in each armor slot (instead of 0 in each slot), but since the result would be the same (me being able to drag the Structure Void out, even if the script is set to cancel the click event), I didn't feel the need to.

Although there is an issue with a user being able to duplicate the items, even if I set the scripts to cancel the click event. The debug would be almost the same (registering on the first click, not registering on the second), and if the user puts the item in a different slot, then there's a high chance of the item duplicating. If you want, I can provide video evidence of this tomorrow night (timezone: EST).

P.S., on a near unrelated note, if you want video and console evidence of shift clicks not working, I can also do that tomorrow night.

**Comment by mcmonkey4eva** [comment]
You're in creative mode in that video; inventory control is minimal in creative mode due to Minecraft code oddities.
Please reattempt in survival mode.

**Comment by MusicScore** [comment]
In survival mode, just clicking does nothing. The script works as it should. When I shift+click, though, the Structure Voids disappear.

I would like to provide another video of what happened while I was in Survival, but my schedule won't permit me enough time to do so. If needed, I can provide the evidence tomorrow night.

**Comment by mcmonkey4eva** [comment]
`is_shift_click` is a direct read from an underlying Bukkit event. For that to fail, something went wrong on Bukkit or Minecraft's end :/
Also use `||null` in your tags to prevent them from erroring when they give back null.
