### ISSUE TITLE
Item Recipe Event

### ISSUE THREAD

**Issue by HeadlessJoey** [DenizenScript/Denizen-For-Bukkit#1490]
Again with this same event a weird problem:

Take any script using the "on item recipe formed" event:

```
ChangeRecipeItems3: 
  type: world 
  events: 
    on torch recipe formed: 
    - determine stone 
```

That one for example, now take out 1 color dye and a piece of leather armor. When you try and dye the armor it won't work. Same for banners.
http://prnt.sc/cxipbi
http://prnt.sc/cxipgg

Now when I remove all my scripts using the "on item recipe formed" event then I can color all my armors like normal.

Using build 49, latest version of Spigot.

Might aswell link this issue to my other issue involving this event (not sure if I can do that myself). That is the issue involving this event not working when you add the "determine item" and someone were to shift click a big quantity of them. 
(In our case using that code from before, if someone would add 4 sticks and 4 coal then they will see stone as the result item but if they shift click the stone then instead they get the 16 torches, so the "determine stone" never happened)

**Comment by mcmonkey4eva** [comment]
@Morphan1

**Comment by GomaTerzu** [comment]
Can confirm, can't use dye with banner and leather armor, too. No idea why.

**Comment by GomaTerzu** [comment]
@Morphan1 pls  - even the old "On player crafts" works better atm. But it makes the result visible.

**Comment by mcmonkey4eva** [comment]
Can this be confirmed as fixed in the latest version?

**Comment by GomaTerzu** [comment]
One issue is fixxed. I can dye leather armor and banner again. BUT now every custom recipe does not work anymore. You place the items but you see no result in the result slot. If you click on the result slot the items on the crafting table are gone and you have nothing on your cursor.

**Comment by GomaTerzu** [comment]
One addition...if you shift click the seemingly empty result slot you actually get the item you wanted to craft without seeing it in the result slot beforehand - but it only works if you craft more than one custom item at once.

**Comment by mcmonkey4eva** [comment]
Er... build 80 oughtta fix that one!
