### ISSUE TITLE
Written Books

### ISSUE THREAD

**Issue by HeadlessJoey** [DenizenScript/Denizen-For-Bukkit#1491]
Build 49 seems to have broken books.
Now when you right click them, nothing happens.
The book and quil works fine but as soon as you finish it and then you get the written book then you can't open it.

**Comment by mcmonkey4eva** [comment]
Can you narrow it down to a specific dev build? 49 doesn't seem likely to cause that issue.

**Comment by HeadlessJoey** [comment]
Build #47 (16-okt-2016 20:38:45) caused it.
The build before that, #46 the books are still working.

**Comment by mcmonkey4eva** [comment]
Odd... in that update @Morphan1 rewrote the trade item networking. Shouldn't affect regular item usage in theory... except that uses some generic code that could mess with a lot of things.

I am able to replicate the bug, but don't have time right this moment to look into /why/ it happens more closely.
It'd be nice if @Morphan1 could take a look at it...

**Comment by Morphan1** [comment]
This is fixed in the latest developmental build.
