### ISSUE TITLE
Denizen says valid tag: <context.entity.location.tc_biome.name> is invalid.

### ISSUE THREAD

**Issue by NLBlackEagle** [DenizenScript/Denizen-For-Bukkit#1493]
Hello,

I've written a script that uses on 'entity despawns:' this is how it looks:

```
NaturalMobSpawningScript:
  type: world
  debug: true
  events:
    on entity despawns:
    - define 1 <context.entity.location.tc_biome.name>
    - if <server.flag[<def[1]>ZOMBIEMaxSpawnedEntities]||false> > 0 {
      - flag server <context.location.tc_biome.name>ZOMBIEMaxSpawnedEntities:-:1
      }
```

Script hastebin: http://one.denizenscript.com/haste/37360

When I start up the server it gives a bunch of errors saying:
ERROR in script 'NATURALMOBSPAWNINGSCRIPT'! Tag <context.entity.location.tc_biome.name> is invalid!

While it says the following when I'm logged in and everything is started up:
Filled tag <context.entity.location.tc_biome.name> with 'TemperateFrozenPlains'. 

I think that denizen currently is missing a validation for this tag as it works perfectly, it's just the startup error.

Here are the sources:
http://one.denizenscript.com/haste/37356  
http://one.denizenscript.com/paste/37357  

Thanks for reviewing this issue in advance!

**Comment by NLBlackEagle** [comment]
Also, I'd like to note that this tag causes a error on startup:

http://one.denizenscript.com/haste/37447

**Comment by NLBlackEagle** [comment]
![2016-11-08_23 34 12](https://cloud.githubusercontent.com/assets/4073584/20121681/2a682600-a613-11e6-847a-94da4827fd37.png)

**Comment by Morphan1** [comment]
What is `<context.entity.location>` returning in these cases?

**Comment by NLBlackEagle** [comment]
Also, I'd like to note that this tag causes a error on startup:

http://one.denizenscript.com/haste/37447

**Comment by Morphan1** [comment]
...I'm confused. You didn't try the tag I asked you to, but the tag you're reporting an issue with is working just fine in that log?
