### ISSUE TITLE
Spawn Husk Says: <e@entity.profession> normal Instead of HUSK

### ISSUE THREAD

**Issue by NLBlackEagle** [DenizenScript/Denizen-For-Bukkit#1494]
Hello,

When using the following tag under On Entity Spawns:
- announce <context.entity.profession> It announces 'normal'

I think this is a bug as there is no other way of determining whenever a zombie is a husk or not.

LOG: http://one.denizenscript.com/paste/37387

**Comment by mcmonkey4eva** [comment]
Wait 1t before reading too much into an entity's details in the spawn event...
