### ISSUE TITLE
Adjust banners not working properly with <player.item_in_hand.patterns>

### ISSUE THREAD

**Issue by Syraleaf** [DenizenScript/Denizen-For-Bukkit#1496]
Okey, so I tried to change a blue banner, standing at the location 242,4,-1643,templates into a blue banner with a white bottom using the -adjust function. Sadly enough this turned out not to work.

Here's the code I used: 
```
BANNERISSUE:
    type: world
    events:
        on player clicks in inventory:
            - adjust l@242,4,-1643,templates patterns:<player.item_in_hand.patterns>
            - narrate "test"
```

When using this, hold a banner in your hand with a pattern and click on a random other item in your inventory to see the result. 
(Spoiler, the banner will change to a black banner instead of a blue one with a white bottom!)

Here's a debug of the code in action:
http://pastebin.com/H0eL4bkK

If you need any help reproducing this bug, feel free to send me a message :)
-Syra

**Comment by mcmonkey4eva** [comment]
You want to use the cursor_item rather than player.item_in_hand I think?
Also, you need the base color too.
