### ISSUE TITLE
horse[color=BLACK|DOTS|SKELETON_HORSE] Wont work anymore.

### ISSUE THREAD

**Issue by NLBlackEagle** [DenizenScript/Denizen-For-Bukkit#1499]
As the title says, the mechanism for variant doesnt works anymore. I've tried serval things including - adjust I'm using build 1630 for the latest spigot version.

Here's the spawn tag I've been using:

/ex mount skeleton|horse[age=adult;tame=true;color=BLACK|DOTS|SKELETON_HORSE] <player.location>

**Comment by mcmonkey4eva** [comment]
1.11 changed how that works for no apparent reason.
Gotta spawn a `SKELETON_HORSE` now, where you just have `horse`.
