### ISSUE TITLE
Better item recipes?

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1500]
So yea, I brought this suggestion up on the IRC but I might as well make it again ;D

All I really want is multiple crafting recipes support for one item (i.e. make a custom item craftable with more than one recipe), although dynamic crafting recipes (kind of like how you craft slabs, swords, tools, etc.? How you can place the materials relative to each other and it still works? I can't explain well lol) would be a nice bonus.

I *could* use an external plugin to handle crafting recipes, but being wholly honest here I like keeping the number of plugins I'm using to a minimum, and I'm fairly unwilling to sacrifice Denizen from my plugins list.

**Comment by mcmonkey4eva** [comment]
goes in https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1851 tbh

**Comment by mcmonkey4eva** [comment]
Added during the resolution to #1851
