### ISSUE TITLE
Suggestion: Dragon flies to portal mechanism

### ISSUE THREAD

**Issue by NLBlackEagle** [DenizenScript/Denizen-For-Bukkit#1504]
I've experimented with the new tag/mech dragon_phase and as it turns out the dragon will fly towards 0,99,0 no matter what after a couple of seconds.

So, my question is if it's possibile to give 'false' information to the dragon tricking it into thinking that the location 0,99,0 is <player.location>

Here's how I would imagine the tag:
- adjust <entry[dragon].spawned_entities> portal_location:<player.location>

Also, when this is possibile and can be implemented could an listener be added aswell so the LAND_ON_PORTAL phase doesnt cause any issues as the dragon would land on the player thinking it is the portal.

Thanks for reading this suggestion!

I'll look forward to any anwser!

**Comment by mcmonkey4eva** [comment]
As best I can tell from the internal code, the dragon simply flies to a high up location at the world center... it's not a hardcoded location, it's programmed to fly away from its own location (ie towards true zero).
You'd probably be better off using the fly or push commands.
