### ISSUE TITLE
Unbreakable flag not working with notable shields

### ISSUE THREAD

**Issue by Mickket** [DenizenScript/Denizen-For-Bukkit#1505]
On the more recent builds of Denizen (tested with latest developmental and stable builds) my notable shield items are not having the unbreakable flag applied to them.

```
ITEM_EVOCATION_SHIELD_MAGI:
  type: item
  material: shield,5[base_color=WHITE;unbreakable=true;flags=li@HIDE_ENCHANTS|HIDE_UNBREAKABLE|HIDE_POTION_EFFECTS]
  display name: <&b>Evocation Shield
  lore:
  - <&7>Durability: 3
  bound: true
  unbreakable: true
```

I generally put the unbreakable flag in with the material but now it doesn't seem to work. I tried adding "unbreakable: true" separately and that doesn't seem to work either. I can however get a unbreakable shield if I use /ex give shield[unbreakable=true] in-game but giving myself the notable item gives me the shield without it being unbreakable. The shield is the only durability item that is experiencing this issue.

**Comment by GomaTerzu** [comment]
You have to write it like this in order to work atm

shield[durability=5;unbreakable=true;flags=li@HIDE_ENCHANTS|HIDE_UNBREAKABLE|HIDE_POTION_EFFECTS;base_color=WHITE;]
