### ISSUE TITLE
Biome Tags non functional on 1.11

### ISSUE THREAD

**Issue by Ditronian** [DenizenScript/Denizen-For-Bukkit#1509]
Hey guys,

Was messing around with biome tags and have found that the only one that appears to be working on 1.11 is <l@location.biome.formatted>, with any other tag throwing a lengthy internal exception error.  Oddly enough the above command works, but take off that .formatted and its errors for days.

[Error.txt](https://github.com/DenizenScript/Denizen-For-Bukkit/files/647943/Error.txt)

**Comment by mcmonkey4eva** [comment]
Can you look in your logs for the original error? it should give a different error the first time you try to use the tag, this error is merely the one that shows for any followup usages of the tags, after confirming it as unable to load.

**Comment by Ditronian** [comment]
I have done so, and it appears to be saying that every biome tag is invalid (except for the .formatted one).

[Error.txt](https://github.com/DenizenScript/Denizen-For-Bukkit/files/647962/Error.txt)

**Comment by mcmonkey4eva** [comment]
Try build 91, should fix it.

**Comment by Ditronian** [comment]
Cheers man!

All the tags appear to be functioning now.

Thanks for the code sorcery!
