### ISSUE TITLE
dChunks throw errors when used.

### ISSUE THREAD

**Issue by Mickket** [DenizenScript/Denizen-For-Bukkit#1511]
http://one.denizenscript.com/paste/38373

Error - [Pastebin](http://pastebin.com/NKU3fXRv)

edit*
The errors appear to occur on PaperSpigot. I don't encounter them in the console when using standard Spigot. However,` <ch@.is_loaded>` still returns true for any chunk that is not loaded for both Spigots.

**Comment by mcmonkey4eva** [comment]
the tag will load a chunk just to process the tag, so... yeah, that happens. Not the best method.


Anyway, the error is Paper spigot disobeying the standard Spigot setting to allow valid "async" calls that aren't actually even async. Go yell at paper, or just don't use paper, if that's a problem.
