### ISSUE TITLE
Feature Request: Armor Stand Item EntityTags

### ISSUE THREAD

**Issue by jayhopkins219** [DenizenScript/Denizen-For-Bukkit#1513]
Hello! I am trying to add some custom crafting recipes to my server that will allow players to craft and place  armor stands with arms, no base plate, various poses, etc - However, because these are all dEntity mechanisms, they do not work when given to the item (ex - i@armor_stand[arms=true] will spawn a regular armor stand). 

Vanilla Minecraft has the ability to set EntityTags however, which determine a mob's entitydata when spawned. An example would be /give @p armor_stand 1 0 {EntityTag:{ShowArms:1,NoBasePlate:1}}. My request is for a similar feature in denizen.

Thanks in advance, hope this is considered :)

**Comment by mcmonkey4eva** [comment]
I don't think Spigot has anything for this for some reason

**Comment by mergu** [comment]
There isn't, and this can be replicated anyways
