### ISSUE TITLE
Suggestion: Install files from direct urls

### ISSUE THREAD

**Issue by jayhopkins219** [DenizenScript/Denizen-For-Bukkit#1516]
Heya, asked over on the IRC and was told it may be possible and to make an issue. Goal is to download files into a specific location from a direct url through Denizen.

I'd like select individuals to be able to run commands such as /install midi *direct url*, /install script *direct url*, etc.

Thanks :)

**Comment by mcmonkey4eva** [comment]
Script installation won't be possible because that's a ridiculous massive security risk.
Midi install, however, can be done.

**Comment by jayhopkins219** [comment]
Possibly schematics as well? Would be helpful to give a builder rank the ability to install resources like trees/buildings on their own.

**Comment by mcmonkey4eva** [comment]
Schematics will be quite doable as well.

**Comment by Mwthorn** [comment]
Could it also be possible to download a whole world as a zip file?
It might be more complex to do since you would have to unzip afterwards.

This can help builders import their own custom generated worlds.

**Comment by mcmonkey4eva** [comment]
that's getting to the point of ... get a separate program handling that.
