### ISSUE TITLE
on player damages minecart: broken context tags

### ISSUE THREAD

**Issue by Mickket** [DenizenScript/Denizen-For-Bukkit#1519]
The <context.damager> and <context.entity> tags for this event do not return the correct information when used with minecarts.

<context.damager> returns null
<context.entity> returns the player damaging the minecart

**Comment by mcmonkey4eva** [comment]
You're probably catching `on player damages vehicle`, which for some odd reason is its own overlapping event :/
http://one.denizenscript.com/denizen/evts/damages%20ve

**Comment by Mickket** [comment]
Found the issue. <context.final_damage> was returning null as well, which turned my determine into a null value for the damage. I'll keep that other event in mind for future scripts.
