### ISSUE TITLE
Action: On Kill firing too early

### ISSUE THREAD

**Issue by Ditronian** [DenizenScript/Denizen-For-Bukkit#1520]
Denizen: Latest Dev Build
Server: Spigot 1.11

This is just a quick bug I'm reporting, I've already coded a work around to it so I'm not too phased about it.

When a NPC is given the On Kill: action, the action is firing twice for us.  The first time it fires is around 1-2 hearts for the being killed player, so he is not actually did yet and can survive.

On actually dieing, the action fires again.

Our work around was to just add the following to the begining of the action.
 - wait 3t
- if <player.is_spawned> queue clear

**Comment by mcmonkey4eva** [comment]
Woops, that code got missed in an update somewhere.
Thanks for the report!

**Comment by Rickytehduck** [comment]
Sorry for posting in this issue, but I'm finding the dev build 1633 doesn't fix this issue for me. The kill messages begin slightly before death, as mentioned, and also spam a lot on the actual death event.
My particular config is:
`    on player killed by lava in cu@553,2,1033,build_world|840,203,1225,build_world:
    - wait 3t
    - if <player.is_spawned> queue clear
    - announce "<context.entity> tried swimming in molten metal"`
And it results in:
[18:43:35 INFO]: p@d9ac7000-7bc0-31ce-95bc-0b69fbd89437 tried swimming in molten metal
[18:43:35 INFO]: p@d9ac7000-7bc0-31ce-95bc-0b69fbd89437 tried swimming in molten metal
[18:43:35 INFO]: p@d9ac7000-7bc0-31ce-95bc-0b69fbd89437 tried swimming in molten metal
[18:43:35 INFO]: p@d9ac7000-7bc0-31ce-95bc-0b69fbd89437 tried swimming in molten metal
[18:43:35 INFO]: Rickyling tried to swim in lava
It's a bit longer than that but yeah.

**Comment by mcmonkey4eva** [comment]
`1633` is the latest mainline build, not a dev build.
Also, you said:
`When a NPC is given the On Kill: action,`
your code does not match this.

Anyway, the only reason that **world event** would/should fire repeatedly is if you have a plugin or script modifying the damage being applied in the event. There's not much we can do about this if it's the case :/

You'd probably be better off using the `on entity death` event, which is guaranteed to fire only once per actual death. The killed event is calculated from damage applied, and thus can be tricked by plugins.

**Comment by Rickytehduck** [comment]
Ah, my mistake. 
Thanks for your quick reply, I'll try and figure out what's causing it to fire repeatedly.
