### ISSUE TITLE
item slot changes event

### ISSUE THREAD

**Issue by XonePlay** [DenizenScript/Denizen-For-Bukkit#1521]
Could you add this event?

on item in slot changes in inventory

Tags:
<context.slot>
<context.new_item>
<context.previous_item>
<context.cause>

Example script:
http://one.denizenscript.com/paste/38838

**Comment by mcmonkey4eva** [comment]
What would that... be triggered by?

**Comment by XonePlay** [comment]
It triggers when an item in a slot changes.
For Example:
If you have air in slot 1 and through an adjust command, by player or through pickup there is then another item in the slot 1. It is easier to handle and you don't have this whole click types etc.

**Comment by mcmonkey4eva** [comment]
There is no way to listen for plugin-induced inventory modification in a reasonably generic way.
Pickup and click both have events - in fact, using the event command, you could make your own custom event to handle those two in one if you wished - though why would you, considering they have such different data associated with them?

**Comment by XonePlay** [comment]
Well, I have an Item with stats like strength in the lore and i want it to change a flag when it is assigned to slot 1. The way it gets there not matters.

**Comment by mcmonkey4eva** [comment]
Well, `using the event command, you could make your own custom event to handle those two in one if you wished`
Check here: http://one.denizenscript.com/denizen/cmds/event
It'd be only a few short lines of script work to accomplish! :D

**Comment by XonePlay** [comment]
Ah okay. That could work for me. Sometimes I get stuck in that many lines of script.. haha. :D
Thanks for the support.  :)

**Comment by XonePlay** [comment]
Wait a second.. Is there a way to find out in which slot the item gets when it is picked up?

**Comment by XonePlay** [comment]
There is no <context.slot> or something.

**Comment by mcmonkey4eva** [comment]
Not within the event itself... but you can safely assume it'll go into the first free slot.

If you don't like that, you can instead add a `wait 1t` to and check recalculate based on where the item ended up.

**Comment by XonePlay** [comment]
That works for me, thanks :)
