### ISSUE TITLE
Book Scripts

### ISSUE THREAD

**Issue by XonePlay** [DenizenScript/Denizen-For-Bukkit#1525]
Whats up with book scripts?
Maybe you can add some more nbt stuff like click and hover events.
Maybe a command to open those without having them in your inventory. :)

**Comment by mcmonkey4eva** [comment]
Mechanisms fake_equipment and open_book work excellently together for the second question

**Comment by mcmonkey4eva** [comment]
`show_book` mechanism is actually better (semi-recent feature) for the command request.

Click/hover events are part of the general 'raw text' support situation, which is being redirected into #1968
