### ISSUE TITLE
follow command broken

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1526]
Hey, the follow command isn't really working for me, and it's creating error messages.
Errors: http://www.bilder-upload.eu/show.php?file=71498a-1484084710.png
Debug(isn't catching the error) http://one.denizenscript.com/paste/38895

**Comment by mcmonkey4eva** [comment]
What version of Spigot?

**Comment by BloodEko** [comment]
Spigot 1.8 ,but in some earlier builds of denizen the command worked fine.

**Comment by mcmonkey4eva** [comment]
I imagine it's just an incompatibility between modern modulized Denizen setup and old Citizens.

**Comment by BloodEko** [comment]
despawn cmd module errors:
http://www.bilder-upload.eu/show.php?file=638d8c-1484096993.png

**Comment by BloodEko** [comment]
May not exist anymore.
