### ISSUE TITLE
EntityDeathEvent Issue ( Citizens B1465 )

### ISSUE THREAD

**Issue by NLBlackEagle** [DenizenScript/Denizen-For-Bukkit#1527]
Hello, as I dont have a clue where to post issues for Citizens I took my chances and placed it here. ( I hope I did correct by this action )

Anyway, right after I start up the server this error takes place ( Without even logging in )

Error:
http://one.denizenscript.com/haste/38973

Citizens Build: 1465
Spigot Build: (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by mcmonkey4eva** [comment]
Did you potentially delete/remove an entity in the death event?

**Comment by NLBlackEagle** [comment]
The issue was solved by adding a delay on the - remove on the death event. Thanks for the info!
