### ISSUE TITLE
[Bug?] player unequip armor event inconsistent

### ISSUE THREAD

**Issue by Rickytehduck** [DenizenScript/Denizen-For-Bukkit#1530]
This issue is just puzzling me right now, as the player unequip armor armor event works fine on one of my test servers. but won't on another.

Both servers are running the same files, and same plugin jars, etc. I even copied across the same folders just to make sure. 
Denizen Dev Build: 117 (I made sure it actually was a dev build this time >_>)
Citizens Build: 1465
Spigot: 1.11.2 

> TestEvent:
>   type: world
>   Events:
>     on player equips armor:
>     - narrate <context.armor>
>     on player unequips armor:
>     - narrate <context.armor>
> 

On testing server #1, everything runs as expected. When armor is equipped/unequipped, it displays the item.

However, on test server #2, the equip event works fine, but the unequip event straight up doesn't trigger at all. 
When reloading, both servers claim to find event matches for 'player unequips armor', so I have no clue where the issue is occurring.

Do you guys have any idea what's going on and how I might fix it?

EDIT: It's working again on server 2, which is incredibly odd. 
I definitely did restart both servers multiple times to see if that was the cause, so I have no clue why it's decided to start working now.

EDIT 2: 
It stopped working again. I have no clue what's changing.

**Comment by mcmonkey4eva** [comment]
You might want to build the event yourself from relevant events, as the event itself is a bit borko
