### ISSUE TITLE
blockdust/blockcrack/iconcrack particles not working?

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1533]
I'm unsure if this is just me being stupid, but I've been trying to make colored particle effects via ```iconcrack```/```blockcrack```/```blockdust```. However, when I try to use stained clay to achieve an effect, all I get is White Stained Clay particles from ```iconcrack```, and errors for ```blockcrack``` and ```blockdust```.

The commands I've used to test this out are:
```
- playeffect <player.location.cursor_on.center> 'effect:blockcrack_45215' data:0.3 quantity:10 offset:0,0,0
- playeffect <player.location.cursor_on.center> 'effect:blockdust_45215' data:0.3 quantity:10 offset:0,0,0
- playeffect <player.location.cursor_on.center> 'effect:iconcrack_159,11' data:0.3 quantity:10 offset:0,0,0
```

**Comment by mcmonkey4eva** [comment]
`45215`?
What is that supposed to represent?

**Comment by MusicScore** [comment]
It's supposed to be the ID that identifies what particle I want to use. In vanilla MC, ```blockcrack``` and ```blockdust``` rely on only one number, which is calculated by ```<item ID> + (<item metadata> * 4096)```. For example, if I wanted to use stone (ID of 1), I would use ```1``` as the number to specify that the ```blockdust```/```blockcrack``` particle I want is just stone. However, if I wanted to use diorite, I would use the formula to calculate what number I need to use. Since its metadata is ```3```, I need to multiply it by 4096, then add it to the ID. This would produce  ```12289```, which is the number I would use to produce ```blockcrack```/```blockdust``` particles that used diorite.

**Comment by mcmonkey4eva** [comment]
Oh woops, somebody half-coded that but then cut it off. I exposed the options for that.
It'd be `effect:blockcrack_1,3` or `159,11`

Dev build 126+ on http://ci.citizensnpcs.co/job/Denizen_Developmental/ has the fix.

**Comment by MusicScore** [comment]
It appears to be fixed. I'm hesitant to close this issue in case this sort of problem crops up again (and I'll be honest, I've had more issues with the ```playeffect``` command than most other commands), but I'm more than willing to believe that there's nothing else regarding the ```blockdust```, ```blockcrack```, and ```iconcrack``` particle effects.

Thank you for helping out!

**Comment by MusicScore** [comment]
Okay, nevermind. Either I'm drunk, or ```iconcrack``` still doesn't work for some reason. It does the same thing that it did before, it just returned White Stained Clay particles.

**Comment by mcmonkey4eva** [comment]
But the other two work fine with colors, right?

**Comment by MusicScore** [comment]
I believe so, yes. I've tried out both ```blockdust``` and ```blockcrack``` with various colored blocks.

**Comment by mcmonkey4eva** [comment]
Lol, uh, build 127+ actually :P there was a typo in the pre-existing code there too

**Comment by MusicScore** [comment]
Confirmed that the current build works. Thank you!
