### ISSUE TITLE
Error occured while enabling Devizen

### ISSUE THREAD

**Issue by Sebbertoa** [DenizenScript/Denizen-For-Bukkit#1536]
Hi,

I believe I might be getting an unusual error. Citizens is loading fine on my server, however Denizen appears not to. I've made sure I downloaded the correct versions of each plugin required, I also believe i'm on the most up-to-date version of Minecraft as well as CraftBukkit, but Denizen doesn't want to work.

I looked up the server logs and it indicates that an error occured while enabling Devizen, and the server by default assumes the version is out of date.

I've posted the entire logs of the server launch here: http://pastebin.com/PUYhLGWw

I sure hope someone can help.

-Alex

**Comment by Morphan1** [comment]
Use Spigot, not CraftBukkit.

**Comment by Sebbertoa** [comment]
Took me a while to understand, but I had to install gitbash, use BuildTools.jar to compile a spigot jar of the latest version, then everything became peachy. Thanks.

Any particular reason why CraftBukkit might be having difficulty working with Denizen?

**Comment by Morphan1** [comment]
Because we link to Spigot, as it has some features we use and there's no reason for server owners not to use it since CraftBukkit is a dead project.

**Comment by Sebbertoa** [comment]
Okay, that makes sense. Thank you for answering!

Case closed ;)
