### ISSUE TITLE
Script bug

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#1537]
- foreach <server.flag[rpg.mine.rank]>:
      - define item i@human_skull[skull_skin=<def[value].name>;lore=<&f><def[loop_index]>|<&f><def[value]>]
      - define list <def[list].include[<def[item]>]>
    - determine <def[list]>

I found a bug.
In the above code, the second lore <def[value]> does not seem to work properly.

**Comment by Mwthorn** [comment]
Try replace <server.flag[rpg.mine.rank]> with <server.flag[rpg.mine.rank].as_list>
You might want to paste your script [here](http://one.denizenscript.com/haste) next time for better reading.
Also I strongly recommend to use [the live irc-webchat](https://one.denizenscript.com/ircchat_denizen)

**Comment by wolfwork** [comment]
http://one.denizenscript.com/paste/39745
http://one.denizenscript.com/haste/39746

**Comment by BlackCoyote** [comment]
put quotes around your definition input argument like so: 
```- define item "i@human_skull[skull_skin=<def[value].name>;lore=<&f><def[loop_index]>|<&f><def[value]>]"

**Comment by wolfwork** [comment]
thanks blackcoyote
