### ISSUE TITLE
could not pass craft event

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#1540]
RPG_Item_Light_Helmet:
  type: item
  material: i@leather_helmet
  display name: <&f>Mining Helmet
  lore:
    - 'This is Mining Helmet'
  recipe:
    - i@leather|i@leather|i@leather
    - i@leather|i@air|i@leather
    - i@air|i@air|i@air

http://one.denizenscript.com/paste/39847

I craft custom item, this error caused

mc version 1.8

**Comment by mcmonkey4eva** [comment]
Should be fixed in build dev-129.
