### ISSUE TITLE
on mythicmob death event

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#1542]
on mythicmob <name> death:

determine command working but in console show unknown determination error

so i hope hide this error

mc ver 1.8
mythic mob version 2.5.11
depenizen build 379

**Comment by mcmonkey4eva** [comment]
What error /exactly/ and what determination are you inputting?

**Comment by wolfwork** [comment]
on mythicmob SkeletonKing death by player:
      - determine i@sand

**Comment by mcmonkey4eva** [comment]
That's not a valid determination is why it says that. Give a valid one instead!
Actually for that matter there aren't any valid determinations for that event :/

**Comment by wolfwork** [comment]
so you aren't make determine command on mythicmob death event?
