### ISSUE TITLE
Shapeless recipe bug and question

### ISSUE THREAD

**Issue by Al3xCalibur** [DenizenScript/Denizen-For-Bukkit#1544]
`shapeless_recipe: i@slime_ball|i@slime_ball` isn't working as expected (the need of 2 slime ball in 2 different slot, i don't want `shapeless_recipe: i@slime_ball[quantity=2]`) because it works like `shapeless_recipe: i@slime_ball` and 
Moreover i didn't find the equivalent of 4 stone which give 4 stone bricks
Thanks for your help and your beautiful plugin

**Comment by mcmonkey4eva** [comment]
Honestly I'm not 100% sure that's possible in base minecraft, without hacking it in...

**Comment by mcmonkey4eva** [comment]
Redirecting to #1851

**Comment by mcmonkey4eva** [comment]
Assuming it is possible in minecraft, it's been fixed by the resolution to #1851
