### ISSUE TITLE
question about error logs

### ISSUE THREAD

**Issue by econowill** [DenizenScript/Denizen-For-Bukkit#1546]
https://one.denizenscript.com/haste/40206
i got some error logs,

Already I know the script cmd, listener was depreciated, but by so many old scripts, having a trouble to update them.
Anyway, this errors was happened by 'listener cmd?' or is there any other reason?

thanks!

**Comment by mcmonkey4eva** [comment]
Stop using the listen command.
It is deprecated. Has been since before you were born, boyo!
