### ISSUE TITLE
/ex narrate <w@world.loaded_chunks> kicks player

### ISSUE THREAD

**Issue by Xericore** [DenizenScript/Denizen-For-Bukkit#1547]
Simple execute this command in console as op having all permissions:

/ex narrate <w@world.loaded_chunks>

Result:
Player is kicked. Screen shows:

Connection Lost
Internal Exception: io.netty.handler.codec.DecoderException:
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 1).

Tested with Denizen version: 1.0.1 #1630 and #1634.
Spigot version 1.11.2.

**Comment by mcmonkey4eva** [comment]
That's the funny thing about sending ten billion lines of text to a client's chat... it crashes things.
