### ISSUE TITLE
denizen recipe script works strange.

### ISSUE THREAD

**Issue by econowill** [DenizenScript/Denizen-For-Bukkit#1549]
https://youtu.be/A6gmbftBhYA
1. strange numbers are shows
2. shift-click making(making all at once) use remained ingredients

**Comment by econowill** [comment]
https://one.denizenscript.com/haste/40358
here is the recipe script i used.

I used other recipe scripts, these are shows same issues

**Comment by Oruss7** [comment]
nice video =)

**Comment by GomaTerzu** [comment]
Crafting recipes containing only custom items sometimes won#t show up in the result field but are stil clickable and you don't get anything

**Comment by GomaTerzu** [comment]
Using for example the paper item as a custom item (a bandage) makes the resulting custom item still usable in scripts were you need paper

**Comment by mcmonkey4eva** [comment]
Redirecting to #1851

**Comment by mcmonkey4eva** [comment]
Fixed by the resolution to #1851
