### ISSUE TITLE
"on player unequips armor" doesn't fire while in survival mode?

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1550]
Using Denizen Developmental build 135, Spigot 1.11.2 (git-Spigot-d4f98a3-cb61ac0).

When I use the ```on player unequips <helmet/chestplate/leggings/boots>``` event, it does not fire while I was in Survival/Adventure mode. When I tried out the event while in Creative mode, it fired immediately.

I don't believe I can provide relevant debug, since the event treated Survival/Adventure unequip as if it never occurred.

**Comment by Rickytehduck** [comment]
Yeah, I had a similar bug a while ago. It's very inconsistent in how it fires, and sometimes just straight out won't work.
#1530

**Comment by mcmonkey4eva** [comment]
That event was @Morphan1 attempting to create a new event out of pre-existing events, and struggling. He seems to be openly refusing to maintain it at this point :/

**Comment by MusicScore** [comment]
Ah, darn. I suppose I'll have to use an elaborate amount of inventory checks to see when the player tries to unequip stuff.
