### ISSUE TITLE
Nbt Attributes issues

### ISSUE THREAD

**Issue by Rickytehduck** [DenizenScript/Denizen-For-Bukkit#1551]
Dev Build: 139 , but it's been like this since at least official build 1605

For a little while now, nbt attributes have been a bit funky.
One thing I've noticed is that the item.nbt_attributes tag straight up doesn't seem to work anymore. It always returns null, even if using <pl.item_in_hand> displays the nbt_attributes=li@etc stuff.

The second thing is, when you generate a copy of an item with nbt_attributes, the new saved/created item has duplicates (I find usually two) duplicates of those nbt_attributes.
Here's some screenshots of the same sword, saved and duplicated through the give command. (This also happens if you modify nbt, or adjust the item, or move the item via the inventory command, etc. Any form of Denizens inventory management really)

Here's an example item:

`TestSword:
  type: item
  material: diamond_sword[unbreakable=true;flags=li@HIDE_UNBREAKABLE;nbt=li@Element/None|Slot/2;nbt_attributes=li@generic&dotattackDamage/mainhand/0/12.0|generic&dotattackSpeed/mainhand/0/-2.9]
  bound: true
  display name: <&f>Test Sword`
It displays as so:
http://imgur.com/bhHYQSw

After you copy it:
http://imgur.com/Fdb1yss

Any idea why this is happening? It wouldn't be as bad if you could return the nbt_attributes using the tag, because I could just deduplicate it and adjust it, but since the tag is also broken it's gotten to the point where I can't figure out how to work around it.

Thanks for your time as always, I know I've been making a lot of bug reports.

**Comment by mcmonkey4eva** [comment]
Can you paste a debug log of the item being duplicated?

**Comment by Rickytehduck** [comment]
Sure, what do you need me to do?
If you mean with /denizen debug, is there a way to output debug info without formatting? 
It looks incredibly weird in my .log files.

**Comment by mcmonkey4eva** [comment]
`denizen debug -r`
duplicate the item
`denizen submit`

**Comment by Rickytehduck** [comment]
Ok, submitted:
http://old.mcmonkey.org/paste/40365

I just simplified it by using the nbt command on some nonsense value.

**Comment by mcmonkey4eva** [comment]
I... don't honestly know why that would ever happen. Something is somehow running twice, and the closest 'solution' to that, short of figuring out what's running twice somehow, is to give each attribute a script-defined UUID. Not impossible, but takes a bit of clever refactoring...
`ITEM.nbt_attributes` should almost definition work fine... it's defined the same as any other given property tag...

**Comment by Rickytehduck** [comment]
What's weird is that it sometimes runs THREE times too, I'm not sure what decides that haha.
<player.item_in_hand.nbt_attributes> should work, right?

**Comment by mcmonkey4eva** [comment]
agsgslakklasg nbt_attributes was broken due to read order. It misinterprets `nbt_attributes` as `nbt`.
That's patched in the currently processing dev build.

As to duplication: I can't replicate that on my server :/

**Comment by Rickytehduck** [comment]
Welllllp, that's pretty darn weird. I've got two seperate servers, one running the latest official build, that have the same issue. This is really odd.

**Comment by mcmonkey4eva** [comment]
It's possible a separate plugin is causing it by some mistake, or just some coincidence of difference between how you tested and how I did...

**Comment by Rickytehduck** [comment]
Right, all I did was use the nbt command as so:
- nbt <pl.item_in_hand> "Test:1", and the debug returned it as doubled for some reason...
I can try stripping out all other plugins but Denizens and see what happens?
I'll report back in a second.

**Comment by Rickytehduck** [comment]
Here's my new debug.
http://old.mcmonkey.org/paste/40370
I stripped it down, and it's still happening. It happened on older Denizens builds for me too.

I just tried it with literally nothing but the latest Citizens and the latest dev build for Denizen (the one you just loaded), and while nbt_attributes works, still getting the same problem.

**Comment by mcmonkey4eva** [comment]
Does it work with commands other than `nbt`?



BTW: Denizen. No "s". Just Denizen.  .-.

**Comment by Rickytehduck** [comment]
Force of habit, haha. I dunno why I always type denizens. 
I recall it causing issues with the inventory command, but I'm not running into that anymore now. Let me try and figure out if it's a specific inventory option that's doing it.

**Comment by Rickytehduck** [comment]
...huh.
It looks like another instance where nbt_attributes duplicate, is on when the server loads.
I'm storing the inventories in notables inventories, and they duplicate when the server restarts/loads up.

It seems like it specifically happens when the server is saving notables to the disk?

**Comment by Rickytehduck** [comment]
Here's another thing that causes this issue:
http://old.mcmonkey.org/paste/40434

**Comment by Rickytehduck** [comment]
Any word on this?
I've made a sort of work-around, but it's ungodly clunky.

**Comment by mcmonkey4eva** [comment]
Fixed in latest dev build! (DEV-193+)
