### ISSUE TITLE
Errors on breaking and placing skulls using <l@location.skull_skin.full||null> tag

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1552]
I'm using Denizen Developmental build 136, Spigot 1.11.2, and EssentialsX version 2.0.1-b439. I tried out a script using player skulls and got a lot of errors when placing down an empty human skull and using an apparently invalid skull produced from the EssentialsX command ```playerskull```.

The full error stacktrace can be found at this link:
http://pastebin.com/bL96sEPZ

The only scripts that uses the ```<context.location.skull_skin.full||null>``` tag can be found at these links:
brown_candle: http://pastebin.com/0x9sw3N7
white_candle: http://pastebin.com/9kvm7utr
medieval_lantern: http://pastebin.com/K5idDvsM

**Comment by Oruss7** [comment]
Heads are not fully fonctional with offline server. Because mcmonkey loves mojang.

**Comment by mcmonkey4eva** [comment]
@Oruss7 please don't troll on the issues page.

@MusicScore looks like the playerskull object doesn't have a name associated with it?

**Comment by Oruss7** [comment]
Sorry.

**Comment by MusicScore** [comment]
@mcmonkey4eva I was wondering if there was a way to detect a playerskull's name without having Denizen throw an error. Does ```||null``` not work in this instance?
