### ISSUE TITLE
Experience Command point bug

### ISSUE THREAD

**Issue by Mickket** [DenizenScript/Denizen-For-Bukkit#1554]
Using dev build #136.
PaperSpigot build #1060.
Tested with essentials' experience command which is able to remove/add 1 and up of experience points at precise amounts.

The amount of experience taken from players is inconsistent. It seems to be taking much more than 1 at random amounts.
A level 13 player with 278exp ends up with 245exp when taking 1 point away.
A level 13 player with 245exp ends up with 246exp when giving 1 point.

A level 14 player 261exp ends up with 2147483647exp when taking 100 points away. The resulting experience is invalid. The experience needed to level to 15 in the negatives of several thousand.

**Comment by mcmonkey4eva** [comment]
DEV-473+ on http://ci.citizensnpcs.co/job/Denizen_Developmental/ has a fix for the experience command (changed to rely on Spigot API calls, not the old custom code)
