### ISSUE TITLE
Is this issue?

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#1555]
https://one.denizenscript.com/paste/40511

        - flag "%player%" "inftower.quest.%quest%:true"
        - flag "%player%" "inftower.quest.%quest%.kill:0"

**Comment by mcmonkey4eva** [comment]
The fault is in the server being "offline mode" or having previously been "offline mode".
Please turn the server online and delete old player data to repair this and many other potential issues.

**Comment by wolfwork** [comment]
I switched to online mode and removed the player data and the denizen data, but the symptoms are the same.

**Comment by mcmonkey4eva** [comment]
Please post a fresh debug log for that

**Comment by wolfwork** [comment]
https://one.denizenscript.com/paste/40519

**Comment by mcmonkey4eva** [comment]
Er... can you maybe record a full and generally readable debug:
`/denizen debug -r`
(Run the script)
`/denizen submit`

**Comment by wolfwork** [comment]
http://old.mcmonkey.org/paste/40520

**Comment by mcmonkey4eva** [comment]
This took me far longer than it should have to figure out.
You have a flag of the structure `x.y`... you also have a flag of the structure `x.y.z` -> Setting either one inherently deletes the other, due to the YAML flag structure.
