### ISSUE TITLE
cuboid.outline tag bug

### ISSUE THREAD

**Issue by econowill** [DenizenScript/Denizen-For-Bukkit#1556]
currently, in outline tag, one of the top corner is empty.

screenshot
http://imgur.com/a/Ucpkw

test code
http://old.mcmonkey.org/paste/40550
logs
http://old.mcmonkey.org/paste/40549

**Comment by mcmonkey4eva** [comment]
0.o...

**Comment by Fortifier42** [comment]
Turns out this is the `pair.high` of each pair.

**Comment by mcmonkey4eva** [comment]
Fixed in latest build thanks to @Fortifier42
