### ISSUE TITLE
<i@myItem.json> broken for summon command

### ISSUE THREAD

**Issue by Xericore** [DenizenScript/Denizen-For-Bukkit#1558]
Denizen for MC 1.11.2 adds backslashes to double quotes when using the tag <*.json>. This causes it to be incompatible with the summon command (can't use -spawn). Denizen for MC 1.8 didn't do so.

I can work around the issue by calling <i@myItem.json.replace[\].with[]> in MC 1.11.2.

Please see this script. It shows the problem with a minimum example: https://one.denizenscript.com/haste/39401

**Comment by mcmonkey4eva** [comment]
That tag is nonsense at this point, every situation requires a different level of quotes and backslashes and I Half regret ever adding it. I would recommend finding cleaner ways to deal with it for things like summon.
It's use that remains is for tellraw, and that's it.
