### ISSUE TITLE
- take cmd not working or I'm being dumb again

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1561]
I'm running Spigot 1.11.2 (latest build, git-Spigot-96235ab-2aa5ac6) and Denizen_Developmental build 139.

In one of my scripts, I'm checking a player's inventory for items that have the scriptname ```repair_kit_item``` using a ```foreach``` loop. The item can be found, but the script doesn't take the item from the player's inventory.

Here's the relevant script: http://pastebin.com/jmit1pHw
Section of concern is between lines 280 and 287.
The script for ```repair_kit_item``` is here: http://pastebin.com/4G34WSD1

I should note that when I use the line that's been commented out, the script is able to take the item from the player's inventory. What I don't understand is why the first (uncommented) version doesn't work.

**Comment by mcmonkey4eva** [comment]
Inventory code is a bit weird... it's hard to entirely accurate identify an item in a consistent way sometimes :/
You can take by slot since you're already doing some amount of searching yourself.

**Comment by GershonR** [comment]
Same issue, just tested it and it happens if the item is not in the hotbar.

**Comment by mcmonkey4eva** [comment]
In the case of OP or similar, take by slot!
