### ISSUE TITLE
Scoreboards and colors

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Denizen-For-Bukkit#1562]
Hello,

I had an `<red>` to colorize a score.

Works fine... but not really. scoreboards.yml are not correctly serialized :'(
That's made a lot of error when trying to remove a score.

![image](https://cloud.githubusercontent.com/assets/4788317/24083858/7a2b3f64-0cdf-11e7-92a1-69f602838330.png)

**Comment by Oruss7** [comment]
Oruss7 is blue and ======== in red

**Comment by mcmonkey4eva** [comment]
You know there's a `sidebar` command to reduce scoreboard trouble, right?

**Comment by Oruss7** [comment]
Oo no i don't !
