### ISSUE TITLE
a bugs on mech enchantments

### ISSUE THREAD

**Issue by econowill** [DenizenScript/Denizen-For-Bukkit#1563]
some errors on enchantments mech, it does not work properly.

there is no way to make remove enchantment. below code shows whole enchantments even enchantments are removed.
> enchantment_remove_test:
>     type: task
>     script:
>     - adjust <player.item_in_hand> enchantments:li@ save:item
>     - narrate <entry[item].result.enchantments.with_levels>
>     - give <entry[item].result>

also set level 0 makes dummy enchantment list, follow this
> enchantment_remove_test:
>     type: task
>     script:
>     - adjust <player.item_in_hand> enchantments:li@dig_speed,0 save:item
>     - narrate <entry[item].result.enchantments.with_levels>
>     - give <entry[item].result>

in this case. the result shows 'efficiency enchantment.level.0'
![image](https://cloud.githubusercontent.com/assets/7900163/24129201/4cda0edc-0e24-11e7-8da3-fb4dd44a47fd.png)

does this code remove enchant from the tools?

**Comment by mcmonkey4eva** [comment]
I've added a new mechanism to the upcoming new dev-build.
`remove_enchantments` can now be used to clear away enchants!

**Comment by econowill** [comment]
when stable update would be ready?

**Comment by econowill** [comment]
About second topic. would be fixed?
remove enchant mech is not enough. if i want remove one of the them, enchant level 0 must be removed.

**Comment by mcmonkey4eva** [comment]
... the dev build is available; use that.

And how is the mech not enough?

**Comment by econowill** [comment]
when if the tools needed to remove some of the enchantments.

**Comment by mcmonkey4eva** [comment]
... remove the enchants, and re-apply any you wanted to keep?

**Comment by econowill** [comment]
ok...
