### ISSUE TITLE
Mounted armorstands on NPCs get removed with server restart

### ISSUE THREAD

**Issue by mpivchev** [DenizenScript/Denizen-For-Bukkit#1564]
I want to hide the nametags off the NPCs so I am making them mount an armorstand with the command
`/ex mount e@armor_stand[visible=false]|<pl.target> <pl.target.location>`,however when I restart the server the armorstands are gone (visible armorstands too). Can this be fixed in some way? And if not, can I remake that command so it selects all NPCs and gives them the armorstand, because as of now the only way I know how to do this is for each NPC with their number `('/ex mount e@armor_stand[visible=false]|<n@12> <pl.target.location>'.`

Thanks in advance.

**Comment by mcmonkey4eva** [comment]
Make the armor stands be NPCs themselves... might have to use the `npc mount` system.

**Comment by mpivchev** [comment]
But don't I need to make the NPCs invisible first? How can I do that?

**Comment by mpivchev** [comment]
Found it: `ex invisible <pl.target>`. It works perfectly now. Thanks for the help!
