### ISSUE TITLE
Baby Pig Zombie Mech

### ISSUE THREAD

**Issue by HeadlessJoey** [DenizenScript/Denizen-For-Bukkit#1565]
Seems like the mech 'age' doesn't work on pig_zombie although it should.

Both these commands just spawn adults:
/ex spawn pig_zombie[age=baby] <pl.location>
/ex spawn pig_zombie[age=0] <pl.location>

But then with just a zombie an actual baby spawn:
/ex spawn zombie[age=baby] <pl.location>
/ex spawn zombie[age=0] <pl.location>

When randomly spawning pig zombies I sometimes get a baby one so it is possible.

Maybe something went wrong after those name changes? (Now it's 'pig_zombie').

**Comment by mcmonkey4eva** [comment]
Should be fixed in latest dev build?
