### ISSUE TITLE
Tags custom items

### ISSUE THREAD

**Issue by HeadlessJoey** [DenizenScript/Denizen-For-Bukkit#1566]
Using this item script:
```
GhostDagger:
  type: item
  material: iron_hoe
  durability: 14
  display name: <&8>Cursed Dagger
  lore:
  - <&7>Rare
```

Then using this command: /ex give GhostDagger[unbreakable=true]
This used to give me an unbreakable weapon. But now when using build 142 (denizen dev builds) it no longer works.

I have to make the item like this:
```
GhostDagger:
  type: item
  material: iron_hoe[unbreakable=true]
  durability: 14
  display name: <&8>Cursed Dagger
  lore:
  - <&7>Rare
```
And then use /ex give GhostDagger
This one works, so you now have to put the unbreakable tag inside the item script and not in the give/drop command.

I know it's a minor problem and I started doing the second method for a long time now but I still have 25-50 items that are made using the first method (putting the unbreakable tag only in the give command and not in the item script).

Can you fix it so the unbreakable tag works in the give (and drop) command again or is that no longer a valid way to script things?

**Comment by mcmonkey4eva** [comment]
Can you narrow down when the way you were doing it stopped working?

**Comment by HeadlessJoey** [comment]
Ah.. uhhm..
Kill me with fire please. Also close this issue please.

I went back in time like you told me to and checked in which build my first method worked.
Seems I had to go all the way back to 1.10 builds (Oktober 2016) and even in those builds it still doesn't work.

Sorry about that. Must've been somewhere between 1.9 and 1.10 when I was using that method and I never realized it stopped working.
