### ISSUE TITLE
Skin mechanism can crash client

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#1572]
This is more like an idiot-proof issue.

When I change to some skin names that doesn't exists, the client crashes.
The crash can be recreated using:
/ex adjust p@Mwthorn skin:asfgo
The client crashes with this error message:
[http://image.prntscr.com/image/be488ec545a14cca80e7ab5e06cc5bb6.png](url)
I've also tested this with Citizen's NPC's simply using /npc rename asfgo
This just changes the skin either into steve or alex. Maybe the skin mechanism could do the same?

Using MC 1.8.8 and Denizen 1.0.1 (Build 121)
I do understand that 1.8 is not entirely supported so it is understandable if the issue can be closed.

**Comment by jayhopkins219** [comment]
#1514
