### ISSUE TITLE
Open Inventory Action

### ISSUE THREAD

**Issue by Arctomium** [DenizenScript/Denizen-For-Bukkit#1573]
So I was having a look at the inventory actions and noticed one for everything except when the player goes to open their inventory, I was wondering how I can detect this action, deny it and run a command? So essentially running a command when the inventory is opened without actually opening it.

**Comment by BloodEko** [comment]
Hello,

seems like there is no possibility to detect when a player opens their main inventory.
You can only detect when they open other inventories, like chests, furnaces, ...

BloodEko

**Comment by Oruss7** [comment]
You only can detect when items are clicked on an inventory

**Comment by mcmonkey4eva** [comment]
There is in fact a `on players open <inventory>:` event... this does not, however, apply to the main inventory due to minecraft limitations, as BloodEko said.

**Comment by Arctomium** [comment]
So could I say do determined cancelled or whatever it is when the player tries to open their inventory but cancel it correct?

**Comment by mcmonkey4eva** [comment]
... As I _just said_, and BloodEko said as well, the event does not apply to the player's own main inventory.
