### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1574]
Hey,

after working a bit with denizen and schematics , i came to the idea to suggest this feature, to make the handling a bit easier:

-new-denizen-config-option-
//default on false
use-worldedit-schematic-folder: false

If set to true, denizen uses the world-edit schematic folder instead of the normal denizen schematic folder. 
To have all schematic on one place, and the possibility to edit them directly through world-edit would me a (nice) improvement.

BloodEko

**Comment by mcmonkey4eva** [comment]
Use your operating system to link the folders. (create a symlink)
We do not have any reason to arbitrarily share a folder with another highly specific plugin.
