### ISSUE TITLE
Items unable to be stacked due to inconsistent UUIDMost and UUIDLeast values when using the "nbt_attributes" mech

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1577]
I'm using Denizen Developmental build 146 on Spigot 1.8.8 (git-Spigot-21fe707-e1ebe52), and I noticed that when I run the `give` command for one item multiple times, each copy of the item will not stack with its supposedly identical item. This seems to only apply to items that are created using the `nbt_attributes` mechanism.

For example, I am able to stack dirt produced by `give i@dirt`, `give i@dirt[display_name=test]`, etc. However, when I add the `nbt_attributes` mech to it, the dirt becomes unstackable when I run `give i@dirt[display_name=test;nbt_attributes=generic&dotattackDamage/mainhand/0/1]` multiple times. I can gain the items in a stack if I use the `quantity` argument in the command, but each time I run the `give` command it treats each item stack as completely different item stacks.

**Comment by MusicScore** [comment]
I noticed this just now, but maybe the reason for this is because something inside of the `nbt_attributes` mech changes the item's ID? I know that NBT attributes have `UUIDMost` and `UUIDLeast` tags. Perhaps those values are generated randomly or changed each time I try to use the `give` command for an item with the `nbt_attributes` mechanism?

**Comment by mcmonkey4eva** [comment]
Well, that was a mistake from long ago >.>

As a semisufficient quickfix, I've made it so it applies a trustworthy UUID: the current number of active attributes is used. So first attrib will be 0, next 1, next 2, etc. So long as attribs are applied in the same order, it oughtta produce the same internal stack data.
This will also produce a lot of 0's if rendered as an actual UUID.

**Comment by MusicScore** [comment]
Right, so this issue is fixed, but gave rise to another lol
