### ISSUE TITLE
"nbt_attributes" not applying to items

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1578]
I'm using Denizen Developmental version 147, on Spigot 1.8.8, and I seem to be unable to apply the `nbt_attributes` mech to any item.

For example, when I use `give 'i@dirt[nbt_attributes=generic&dotattackDamage/mainhand/0/1]'`, instead of giving me dirt with a +1 Attack Damage modifier, it just gives me regular dirt.

**Comment by mcmonkey4eva** [comment]
But it worked fine in 146?

**Comment by MusicScore** [comment]
Yes, it worked fine in build 146.

**Comment by mcmonkey4eva** [comment]
I wonder if it expects/demands unique UUIDs instead of just a linear series of numbers? 0.o

**Comment by mcmonkey4eva** [comment]
In case it just hates '0' and/or low-numbered UUIDs, new attempt: linear but high-numbered.

**Comment by MusicScore** [comment]
It appears to be working now. The attributes can be applied and the items can be stacked.

Many thanks!
