### ISSUE TITLE
Error while parsing choose command

### ISSUE THREAD

**Issue by SaitDev** [DenizenScript/Denizen-For-Bukkit#1580]
Got error _mapping values are not allowed here_ at _org.yaml.snakeyaml..._

Example to get error:
```
- if true {
  - choose "1":
    - case "1":
      - narrate abc
}
```
Save and reload scripts.

We cant use choose command inside a codeblock because of yml parsing?

**Comment by mcmonkey4eva** [comment]
cannot put `:` notation inside a `{}` notated section :/  Easiest copy-and-paste fix is to bring the choose/case block into a task subscript and inject it. Alternately, rework the logical ordering of the script at hand a bit...

**Comment by SaitDev** [comment]
Thank you very much
