### ISSUE TITLE
Proximity Trigger for NPCs

### ISSUE THREAD

**Issue by Arctomium** [DenizenScript/Denizen-For-Bukkit#1581]
I understand how the proximity trigger works when a player enters an NPCs proximity but I was wondering how I would detect when 2 NPCs are in each others proximity to make them talk to each other?

**Comment by mcmonkey4eva** [comment]
Sorry for slow reply, but you'd either have to spam a distance tag or have us upgrade the proximity engine...

**Comment by Arctomium** [comment]
Could you upgrade the proximity engine then and possibly add an event for it or something?

**Comment by mcmonkey4eva** [comment]
As of build DEV-239 ( http://ci.citizensnpcs.co/job/Denizen_Developmental/ )
You can use mobprox for any NPC type.
`/trait mobprox`
NPC has flags `mobprox_range`, `mobprox_acceptnpcs`, `mobprox_timer`.
in discord type `!act mob` to see the relevant actions to listen for :)
