### ISSUE TITLE
context for clicks event is not working

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1586]
Denizen version : dev build` #163`

The context for clicking in inventory is not working 
`on player (<click type>) clicks (<material>) (in <inventory>) (with <material>) `

`<context.is_shift_click> and <context.click>` is not recognised

i tried with these
     ` on player right clicks with Baton_annex_maitre_guilde:  `         
     ` - if <context.is_shift_click> == false {  ` 
      `  - narrate "test 1"  ` 
     `   } else { ` 
     `   - narrate "test 2"  `
     ` }  `
also it is not working like these
`on player SHIFT_RIGHT clicks with Baton_annex:`

**Comment by mcmonkey4eva** [comment]
you should probably specify `in inventory` to reduce trouble.

**Comment by Noiknez** [comment]
I tried, but it is not working (The action that i want to listen is not in inventory : it is when player left or right click with a stick in hand)

**Comment by mcmonkey4eva** [comment]
In which case you only have context available to you from the event `on player clicks block`, not the inventory event ...

**Comment by Noiknez** [comment]
Thank you for the help, it worked
