### ISSUE TITLE
Shoots Bow Event

### ISSUE THREAD

**Issue by jayhopkins219** [DenizenScript/Denizen-For-Bukkit#1587]
Hiya, getting back into Denizen now that summer is here. Noticed that bows don't take durability damage if you `- determine <projectile>`, which is a small issue. Also, because force is handled, can we have a determine added for it?

**Comment by mcmonkey4eva** [comment]
That event actually runs that determination by cancelling the event and manually launching the entities.
You can take this a step further, and manually apply any relevant adjustments such as bow durability yourself.

**Comment by jayhopkins219** [comment]
Good to know it cancels, I've worked around this now. Is it possible to get a determine for force though? That way I could do something along the lines of - 
`- determine force:<context.force.div[2]>`

**Comment by mcmonkey4eva** [comment]
The event doesn't support and would require a manual shooting as well 0.o

**Comment by jayhopkins219** [comment]
Gotcha, found the event's code. I'll just cancel and handle the event myself as it doesn't seem as bad as I figured
