### ISSUE TITLE
Recipes Undefined Behaviour

### ISSUE THREAD

**Issue by GershonR** [DenizenScript/Denizen-For-Bukkit#1589]
Video: http://imgur.com/jZ3tH0P

Script used: https://one.denizenscript.com/denizen/repo/entry/26

If any item is attempted to be made with a quantity greater than 1, it will cause undefined behavior and allow items to be duped.

For shapeless recipes, if a recipe is made with multiple of that item, it will only take 1 of those items to make it. i.e

shapeless-recipe: i@dirt|i@dirt|i@dirt -> expected to put 3 dirt in the crafting bench and get the item, but you can put 1 dirt and you will still get the item

**Comment by mcmonkey4eva** [comment]
As I said in IRC: this is not valid, and you can't do that.
Minecraft does not allow for that, for some reason.

**Comment by GershonR** [comment]
So are recipes deprecated then? If you try to make any recipe a person can break and abuse it

**Comment by mcmonkey4eva** [comment]
No, specifically recipes with high quantities are not permitted.

**Comment by mcmonkey4eva** [comment]
Unless this issue is entirely unrelated to what you said on IRC and I'm misunderstanding.
In which case, discuss on IRC first.

**Comment by GershonR** [comment]
The script that was tested was:
    recipe: 
    - i@air|i@bone|i@air 
    - i@bone|i@redstone_block|i@bone 
    - i@air|i@bone|i@air

**Comment by GershonR** [comment]
I have confirmed that this can be perfectly valid behavior in Minecraft.

Video: http://i.imgur.com/b9Se1VN.mp4
Plugin: https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-%E2%97%84%E2%97%84-remastered-create-your-own-recipes.36925/

Quantities of items should not matter

**Comment by mcmonkey4eva** [comment]
Does not demonstrate the flaw mentioned on IRC.
I say again: if you have something different here than what was mentioned on IRC by you a bit before you posted this... then discuss it on IRC first.
