### ISSUE TITLE
Server flag array

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Denizen-For-Bukkit#1590]
`/ex narrate <server.flag[games.Horserace.PLAYERSLIST].as_list>`
returns `li@value ...` but when they are no values (ie `PLAYERSLIST: []`) throw error tag is invalide !

Why it don't return an empty li@ ?? I'm misusing the flag system ?

Thanks.

**Comment by mcmonkey4eva** [comment]
An empty flag is a gone flag.
You can add a fallback to deal with this, `.as_list||li@>` at the end.
