### ISSUE TITLE
Load Custom Items from Resource Pack

### ISSUE THREAD

**Issue by Arctomium** [DenizenScript/Denizen-For-Bukkit#1592]
So I was looking over your custom items documentation and I was wondering if possible how I could create custom items and then load a custom texture from the resource pack, if this isn't possible could you possibly add it in as a feature?

**Comment by mcmonkey4eva** [comment]
That's a minecraft thing you're asking about that we're not very much able to control.
You can sorta do that via unbreakable+durability value.

**Comment by Arctomium** [comment]
You are able to control it, if you can create a custom item what is stopping you from loading an image file or texture from the resource pack like other plugins already do?

**Comment by mcmonkey4eva** [comment]
Please provide an example of a plugin that does that, I've not heard of one.
I've only seen ones that use durability tricks.

**Comment by Arctomium** [comment]
Straight away found 2 plugins that add new items and load custom textures from a resource pack:
https://dev.bukkit.org/projects/slimefun
https://www.spigotmc.org/resources/newitems-create-items-with-custom-textures-models-without-mods.22783/

**Comment by mcmonkey4eva** [comment]
One is paid (so I can't research it) the other has no outwardly visible signs of doing what you're asking for.

**Comment by Arctomium** [comment]
They both do pretty much the same thing, I've looked into both plugins and both add content that is loaded from a custom resource pack now if you want to look into the paid one I have a copy.

**Comment by BlackCoyote** [comment]
@Arctomium unless mojang very secretly added the modding API already without telling anyone but a few select plugin developers, the only way to give the illusion of an extended range of custom items is with durability trickery as mcmonkey described.

In resource packs, you can assign different textures to different durability values on the same item, this gives you a wide range of textures to use on the same item. 

You can change the texture the client sees by changing the durability of the item, and you can prevent the durability from changing naturally by using unbreaking.

Achieving this in denizen requires no new features to be added. Durability and unbreaking are already accessable from within denizen, and resource packs have to be prepared by yourself manually outside of denizen.

**Comment by Arctomium** [comment]
@BlackCoyote so how do they add all these custom items and textures then without modding or replacing any of the default textures? Also if you claim that's how you can do it then how would I do it without replacing any of the default textures?

**Comment by BlackCoyote** [comment]
As I said, you have the ability to assign a whole range of custom textures to a single item, and choose which one to show by changing its durability value.

When you have room for a large range of textures, it's not very hard to keep one of them looking like the default texture.

**Comment by Arctomium** [comment]
Okay so how would I do this then?

**Comment by BlackCoyote** [comment]
Here's a more detailed look on how to set up a resource pack to have durability specific textures: https://www.reddit.com/r/Minecraft/comments/3fbque/15w31a_snapshot_item_textures_changeable_by/

To change the durability of an item via denizen, you simply use the durability mechanism on it.
