### ISSUE TITLE
Can't Click Item Outside Inventory

### ISSUE THREAD

**Issue by Arctomium** [DenizenScript/Denizen-For-Bukkit#1594]
So I'm trying to create a basic server selector but I can only seem to get the script to run when I open my inventory then click it but I want to be able to click it straight from in-game, how do I do this?

My script so far: https://one.denizenscript.com/haste/42257

The way this script is written it doesn't do anything, it's only when I change it to `on player clicks ServerSelector in inventory` and add the `in inventory` to script does the script one when the item is clicked but I can't figure out how to make it work outside of the player inventory like just holding it in your hand and clicking it.

**Comment by mcmonkey4eva** [comment]
`on player right clicks with ServerSelector:` might do it.
Failing that, add a blocktype to be clicked, EG `on player right clicks air with serverselector:` where air can be 'block', 'air', or a specific block type.

**Comment by BlackCoyote** [comment]
"on player clicks with MyCustomItem" will work just fine with any kind of clicking that is not in an opened inventory.

Might I suggest for you to join our IRC channel, which offers a more convenient platform for direct questions & answers, as well as having a meta search bot?

**Comment by Arctomium** [comment]
Could you send me a link to it @BlackCoyote? Also I wanted to get in touch with you about buying a whole bunch of your songs in bulk.

**Comment by mcmonkey4eva** [comment]
Discord now rather than IRC, but it's at https://discord.gg/Q6pZGSR

**Comment by Arctomium** [comment]
Okay that script you gave me worked but it opens up what I think is a duplicate of my current inventory with the server selector inside instead of the desired item and there isn't even a title: http://prntscr.com/fcxy0q

**Comment by mcmonkey4eva** [comment]
that means the inventory you tried to open was misconfigured.
Check your log for error messages, and ensure your inv script matches https://one.denizenscript.com/denizen/lngs/inventory%20script%20containers effectively.

For like the third time today alone: Come on the Discord for general purpose help!
