### ISSUE TITLE
item craft bug

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#1603]
https://drive.google.com/open?id=0B0og2QY4BrgJeW02QnNhUWZoSkU

mc version 1.8
denizen bukkit latest
  recipe:
    - i@air|i@air|i@air
    - i@air|i@diamond|i@air
    - i@air|i@air|i@air

**Comment by mcmonkey4eva** [comment]
@Morphan1 send help!

**Comment by wolfwork** [comment]
When will you fix this?

**Comment by mcmonkey4eva** [comment]
Join us on Discord at https://discord.gg/Q6pZGSR and bug @Morphan1 'til he sends help :P

**Comment by mcmonkey4eva** [comment]
Redirecting to #1851

**Comment by mcmonkey4eva** [comment]
Fixed by the resolution to #1851
