### ISSUE TITLE
Weather Command does not work

### ISSUE THREAD

**Issue by applepower34** [DenizenScript/Denizen-For-Bukkit#1604]
Specifying a world in the command always sets the world name to "world" and ignores the world specified.

![weather](https://user-images.githubusercontent.com/28375751/27261557-6950e1f0-5413-11e7-9fc1-7a19ab7313c1.png)

**Comment by mcmonkey4eva** [comment]
Can you please post the command you input in exactum?

**Comment by mcmonkey4eva** [comment]
Fixed for build DEV-192+ http://ci.citizensnpcs.co/job/Denizen_Developmental/

**Comment by mcmonkey4eva** [comment]
Thanks for the report! :)
