### ISSUE TITLE
Large Number Calculations goes wrong

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#1605]
```
the tag '<el@9500000000000000000.as_int>' fills with '9223372036854775807'
and
the tag '<el@950000000000000000.round_to[2]>' fills with '9.223372036854776E16'
```

Tested on 1.0.1-SNAPSHOT (build 1634) via. the IRC Tag-Parser

**Comment by mcmonkey4eva** [comment]
wtf u expecting?
There's a limit to how much detail a computer can retain regarding a number...

**Comment by Mwthorn** [comment]
I expected it worked just like the other math tags. I know stuff gets unstable at those high numbers and there are ways around this. But since some of the math tags (.mul .add .div .sub) worked. I was wondering if it was simply some additional code that would do the trick :) Otherwise you can close this issue.

**Comment by mcmonkey4eva** [comment]
rounding doesn't support the hackish "big decimal" code logic so much
