### ISSUE TITLE
Citizens don't attack targetted mobs

### ISSUE THREAD

**Issue by Eredrim** [DenizenScript/Denizen-For-Bukkit#1606]
Hello,
I have a problem with the latest version of sentinel on Spigot 1.12 (latest). The sentinels don't attack mobs in the target. I currently tested with sentinel which had "monsters" and "horse" as target. There is no stack in the console and in the logs.

Regards,

**Comment by mcmonkey4eva** [comment]
You will need to reapply the targets list if you're running a dev build.

Also, this is the Denizen github page, lol.

**Comment by Eredrim** [comment]
Oh ! Sorry the for bad location. Just a final question, is there a way to reapply targets quickly ?

**Comment by mcmonkey4eva** [comment]
Run sentinel dev build 125+ it should compensate for data loss now

**Comment by Eredrim** [comment]
Ok, thank you very much.
