### ISSUE TITLE
Attack speed of dItems is broken

### ISSUE THREAD

**Issue by Zughy** [DenizenScript/Denizen-For-Bukkit#1611]
*result
![citizens](https://user-images.githubusercontent.com/4713500/27752860-67038eb4-5de3-11e7-96d6-693cbc7b0e46.png)

**Comment by mcmonkey4eva** [comment]
Denizen doesn't add nbt attribs to items on its own ... something's wrong on your end yo

**Comment by Zughy** [comment]
I've just tried in a server having only denizen loaded: same thing
This is one of the swords, I guess I missed something
```
training_sword:
    type: item
    material: stone_sword[unbreakable=true;nbt_attributes=li@generic&dotattackDamage/mainhand/0/5.0]
    display name: <&b>Training Sword
    lore:
    - <&8>Lv.: <&e>1
    - <&8>From: <&b>Training Sword Recipe
```

**Comment by mergu** [comment]
This is present in vanilla minecraft (it's not Denizen's fault!). Relevant post -
https://www.reddit.com/r/Minecraft/comments/4a9qkr/attribute_modifiers_break_attack_speed/

**Comment by Zughy** [comment]
Oh, I didn't know that, thanks a lot!
