### ISSUE TITLE
Issue with player.inventory.contains

### ISSUE THREAD

**Issue by MrSpomg** [DenizenScript/Denizen-For-Bukkit#1613]
Hi! I'm having an issue with if arg:
if <player.inventory.contains[277]> ==  true {
  //do something
}

It is working when I have a normal 277 item in the inventory, but when I have a 277 item whose name has been modified by another plugin, dont works! I would like to know how to fix this, and how to use the if arg when the players has a specific item with a specific ID.

Thank u! Sorry for my English, Im Spanish.

**Comment by BlackCoyote** [comment]
use contains.material

**Comment by MrSpomg** [comment]
Thank u! Also waiting for... "how to use the if arg when the players has a specific item with a specific ID."

**Comment by mcmonkey4eva** [comment]
Not sure what you mean by that last request?
