### ISSUE TITLE
Check for items with NBT in requirements

### ISSUE THREAD

**Issue by trisgnd** [DenizenScript/Denizen-For-Bukkit#1621]
I'm new to Denizen scripting, so this may be a silly question, but I can't find the answer anywhere.

I've made a quest that requires you to have ten of a special mob drop, which is a light blue dye, to finish it. The denizen won't recognize the dye in players' inventories because it's named, and I'm assuming the reason for this is that the NBT does not match that of a regular light blue dye.

I tried adding the special item as an item script, but the script version has the "Denizen Item Script":"" NBT on it (making it have two tags instead of just one - that, and the display name NBT), so it won't take that either.

Is there a way to make the denizen take any light blue dye, regardless of the NBT tags on it? Or perhaps a way to make him take any light blue dye with the specific name? Either one would work, I think, though the former probably would make more sense.

**Comment by Fortifier42** [comment]
```
<Fortifier> !t inventory.contains.material
<monkeybot> Found: <in@inventory.contains.material[<material>]>, which returns a Element(Boolean)
<monkeybot>   Returns whether the inventory contains an item with the specified material.
```

**Comment by mcmonkey4eva** [comment]
You'd probably want `inventory.find.material[...]` and take by slot...

**Comment by trisgnd** [comment]
@Fortifier42 That isn't the issue; I have no problem having it identify the item, but I can't get it to find the item with the specific NBT of the drop that it needs to take.

@mcmonkey4eva Right now, there's nothing forcing the item to be placed in any specific spot, so how would that work? It's dropped randomly from a monster, so where it goes into a player's inventory is totally random

**Comment by mcmonkey4eva** [comment]
... the tag I mentioned, find.material, returns the slot number of the item. You then take by slot, where the slot is the result of that tag...

Also, requirements are ancient...
Check the tutorial videos https://one.denizenscript.com/denizen/vids

**Comment by trisgnd** [comment]
I'm only about a week into learning how all of this works, so you'll have to forgive me on the slow pickup, but from what I understand, what you're suggesting doesn't solve the problem either. It still only looks for regular dyes, and not the named ones.

Side note: Would it be possible in the future, perhaps, to add a simple way to just look for and take items regardless of their NBT? If something like that existed (or exists? Maybe I just don't know about it), this problem wouldn't be plaguing me. I've been trying to solve it for hours now.

**Comment by mcmonkey4eva** [comment]
If you want the ones with a specific name, just use `bydisplay`

**Comment by trisgnd** [comment]
I tried to figure it out with what you suggested, but I don't really understand what you meant, due to my lack of experience with any of this. Per suggestion of the IRC chat, I tried using IF with various tags, but I'm struggling to understand what I'm doing. I watched a few videos, but they didn't help me figure out exactly what I'm trying to do.

If you have the free time, do you think you could maybe write a quick example?


I tried using `if <player.inventory.contains.scriptname[Silk].quantity[10]>` where I've written Silk as
```
Silk:
    Type: Item
    Material: item:351:12
    Display name: Spider Silk
```
and it can't find the item. I have no idea what I'm doing wrong.

**Comment by MusicScore** [comment]
For best results, most objects (e.g. entities and items) should be in Denizen notation. For light blue dye, for example, you can write `i@light_blue_dye` or `i@dye,12` (you can find more by running `!item <item name/ID>` in the Denizen Discord or IRC).

So for your item script, you'd might want to use:
```
Silk:
    type: item
    material: i@dye,12
    display name: Spider Silk
```
For your `take` command: `- take i@Silk qty:10`
Alternately: `- take 'bydisplay:Spider Silk' qty:10`

**Comment by trisgnd** [comment]
@MusicScore That makes taking the item a lot easier, so thank you!
However, I need to be able to check that the player has 10 on them before the script starts. Can I somehow use bydisplay in this context? I tried

```
   Script:
                - if <player.inventory.contains['bydisplay:Spider Silk'].quantity[10]> true {
                    - chat "&fSuccess!."
                    }
                else {
                    - chat "&fNope."
                    }
```
and it can't find it. I'm not sure how to fix it, but I have the feeling it's quite simple and I'm just missing it.

**Comment by MusicScore** [comment]
Aha, that's a problem.

You can use one of the newer inventory tags, `<in@inventory.contains.scriptname[<scriptname>].quantity[<#>]>`. For example, `<player.inventory.contains.scriptname[the item script's name].quantity[64]>`.

In your case, `<player.inventory.contains.scriptname[Silk].quantity[10]>`

**Comment by trisgnd** [comment]
@MusicScore I've tried doing this in several contexts and none of them seem to work...
`<in@inventory.contains.display[(strict:)"Spider Silk"].quantity[10]>`
`<in@inventory.contains.display[(strict:"Spider Silk")].quantity[10]>`
`<in@inventory.contains.display[("strict:Spider Silk")].quantity[10]>`
How close did I get? _sigh_

**Comment by MusicScore** [comment]
For the `(strict:)` part, you don't need the parentheses. If you wanted to read the display name literally (as in directly matching it), just do `'<player.inventory.contains.display[strict:Spider Silk].quantity[10]>'`. If you want the match to be a little lax (allowing color codes or seeing if part of the item's name matches, for example), consider removing the `strict:` part altogether.

**Comment by trisgnd** [comment]
It finally works! Thank you so much!! I've been trying to fix this for days!

**Comment by MusicScore** [comment]
No problem!

For Denizen, there are a lot of resources you can use. Try hopping on the IRC (https://one.denizenscript.com/ircchat_denizen) or Discord (https://discord.gg/Q6pZGSR) for more resources and help.
