### ISSUE TITLE
Recording player interactions

### ISSUE THREAD

**Issue by strudinox** [DenizenScript/Denizen-For-Bukkit#1622]
Currently running Spigot 1.12, Citizens2, latest build of Denizen.

I'm unable to find a way for to save a history of player interactions, so actions cannot be repeated. Our goal is to mark an interaction or quest in this case as completed using flags, and the script cannot be re-ran. Is there a way to accomplish this by having Denizen log an entry into a file or database?

**Comment by MusicScore** [comment]
The `flag` command helps.

If you're insistent on using a database of sorts, you can check out the `yaml` command. Details on it can be found here:
https://one.denizenscript.com/denizen/cmds/yaml

**Comment by Fortifier42** [comment]
Furthering on this, Denizen has SQL capability if you know how to manipulate a databse.
