### ISSUE TITLE
Don't know what this is, Just an FYI I guess

### ISSUE THREAD

**Issue by TheLastBlockbender** [DenizenScript/Denizen-For-Bukkit#1623]
This happened when I restarted my server. I don't think it affects the server in any way, but I thought I'd let you guys know.

17.07 10:21:45 [Server] WARN java.io.IOException: Server returned HTTP response code: 500 for URL: http://neo.mcmonkey.org/plugins/public_statslugin=Denizen&version=1.0.2-SNAPSHOT+%28build+1638%29
17.07 10:21:45 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
17.07 10:21:45 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon

**Comment by mcmonkey4eva** [comment]
Thanks for the report, it's a minor problem with the statistics server crashing for little apparent reason.
I've set it to autorestart daily so that should be less of a problem now!
