### ISSUE TITLE
experience command still a bit wonked

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1625]
Spigot 1.11.2, Denizen Developmental build 196.

When I run the experience command and attempt to use the `take` argument, nothing happens. Contrarily, I can `give` a negative value, but doing so does not change the player's level. The level gets bugged, even though the player's total XP does change.

**Comment by mcmonkey4eva** [comment]
Gonna lump this in with https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1554 - send in a message there?
