### ISSUE TITLE
"on player death" doesn't let me determine drops

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1626]
Spigot 1.11.2, Denizen Developmental build 196.

When I try to determine the drops in the `on player death` event, it just drops my entire inventory instead.
This is the part of the script I showed BlackCoyote on Discord:
```
- if '<def[al_inv.enable]>'
{
  - define 'player_inv' '<def[target].inventory.list_contents>'
  - define 'inv_loss_chance' '0'
  - define 'inv_lost' 'li@'
  - foreach '<def[target].inventory.list_contents>'
  {
    - define 'inv_loss_chance' '<util.random.decimal[<def[al_inv.min]>].to[<def[al_inv.max]>]>'
    - if '<def[al_inv.hotbar]>' && '<def[loop_index]>' <= '9'
    {
      - define 'inv_loss_chance' '<util.random.decimal[<def[al_inv.min].div[2]>].to[<def[al_inv.max].mul[0.8]>]>'
    }
    - if '<util.random.int[1].to[10000]>' <= '<def[inv_loss_chance].mul[10000]>'
    {
      - define 'player_inv' '<def[player_inv].set[i@air].at[<def[loop_index]>]>'
      - define 'inv_lost' '<def[inv_lost].as_list.include[<def[value]>]>'
    }
  }
  - wait '1t'
  - adjust '<def[target]>' 'inventory_contents:<def[player_inv]>'
}
else
{
  - define 'inv_lost' '<def[player_inv].exclude[i@air]>'
}
- narrate '<def[inv_lost]>' 'targets:<p@GrandPartyMask>'
- if '<def[al_inv.drop]>'
{
  - determine 'passively' '<def[inv_lost].exclude[i@air]>' 
}
else
{
  - determine 'passively' 'NO_DROPS'
}
```

**Comment by MusicScore** [comment]
Confirmed that `determine passively NO_DROPS` does not work either. I cannot determine item drops upon player death at all.

**Comment by BloodEko** [comment]
debug?

**Comment by MusicScore** [comment]
```
[13:53:11 INFO]: +- Executing dCommand: DETERMINE/p@GrandPartyMask ---------+
[13:53:11 INFO]:  Filled tag <def[inv_lost].exclude[i@air]> with
                   'li@i@stone|i@stone|i@stone'.
[13:53:11 INFO]: +> Executing 'DETERMINE': outcome='li@i@stone|i@stone|i@stone'
                    passively='true'
```
This was the debug for determining an item drop via `determine 'passively' 'dList(dItem)'`.
As for determining `NO_DROPS`, I haven't gotten the debug for it yet. I need to wait for my laptop to cool down before I boot up the local server I have stored.

**Comment by BloodEko** [comment]
Use /denizen debug -r and /denizen submit , as it also shows your denizen version and so on.

**Comment by MusicScore** [comment]
The debug with drops enabled in the script's respective config:
http://old.mcmonkey.org/paste/43204

The debug with drops disabled in the script's respective config:
http://old.mcmonkey.org/paste/43205

The script:
[http://github.com/MusicScore/ . . . /gpa_feverDeath_main.yml](https://github.com/MusicScore/Denizen-GrandPartyAddons/blob/master/feverDeath/gpa_feverDeath_main.yml)

**Comment by MusicScore** [comment]
Er, now the script won't drop anything lol

The updated script is still at the same link. I'll edit this comment with the debug in a moment.

**Comment by MusicScore** [comment]
So apparently if you pray to the magic gods of code bugs, your issues go away...
