### ISSUE TITLE
Item cooldown/reload

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Denizen-For-Bukkit#1630]
Hi,

Is a mech exist to add visuel effect for item cooldown (like enderpearl) ?

I saw on a mini game server, they use it with any item:

![item cooldown](https://user-images.githubusercontent.com/4788317/28743426-df08c1aa-7449-11e7-9622-98c257240b87.png)

Thanks

**Comment by mcmonkey4eva** [comment]
Do you have any idea how they accomplish that? 0.o

**Comment by mcmonkey4eva** [comment]
Appears to be a new minecraft feature which @mergu is hoping to make a PR for :o

**Comment by Oruss7** [comment]
// <--[command]
+        // @Name ItemCooldown
+        // @Syntax itemcooldown [<material>|...] (duration:<duration>)
+        // @Required 1
+        // @Stable stable
+        // @Short Places a cooldown on a material in a player's inventory.
+        // @Author Mergu
+        // @Group player
+        //
+        // @Description
+        // Places a cooldown on a material in a player's inventory.
+        //
+        // @Tags
+        // <p@player.item_cooldown[<material>]>
+        //
+        // @Usage
+        // Places a 1 second cooldown on using an ender pearl.
+        // - itemcooldown ender_pearl
+        //
+        // @Usage
+        // Places a 10 minute cooldown on using golden apples.
+        // - itemcooldown golden_apple d:10m
+        //
+        // -->

Thanks !

**Comment by Oruss7** [comment]
that's minecraft which limit to material and not item ? 
I made custom item with blaze powder, and that command apply well on it but also on blaze powder. That's logical, it take material as argument.

**Comment by mcmonkey4eva** [comment]
Yeah minecraft limit :/
