### ISSUE TITLE
Invulnerable mech

### ISSUE THREAD

**Issue by HeadlessJoey** [DenizenScript/Denizen-For-Bukkit#1631]
The invulnerable mech doesn't seem to be working on any entities except the armor stand.

Not sure if that's intended to only work for armor stands?

Spigot 1.12, dev build 196

**Comment by mergu** [comment]
Hi,
Invulnerable mec seems to be working. Players in creative ignore the invulnerable attribute, however (this is intended). Try setting yourself to a survival game mode and hurting the entities.

If you absolutely do not want them taking damage, regardless of game mode, you can cancel it using an event.

**Comment by HeadlessJoey** [comment]
Ah that makes sense.
I'll just use an event to cancel it, thanks!
