### ISSUE TITLE
<context.damager in "entity dies" and "entity killed" event

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1635]
If you kill a zombie with a bow and check the <context.damager> in the "on zombie dies" event it is null

if you check the death with "on zombie killed" you get the player in the context.damager correctly

In both cases the cause is PROJECTILE

is this a bug? I mean you should get the context.damager in "on zombies dies" properly too?

**Comment by mcmonkey4eva** [comment]
If it's null, then Bukkit has decided something else was the true killer. 0.o
I don't know what we can do about that.

**Comment by Fortifier42** [comment]
Check if it is killed by projectile, and check it's shooter?

**Comment by GomaTerzu** [comment]
Found the problem within a hurt command that is used in another death related script that I forgot about. Foxxed this mess, Now context.damager is the arrow and context.damager.shooter gives me the player. Thank you both
