### ISSUE TITLE
Chunk on login broken

### ISSUE THREAD

**Issue by HeadlessJoey** [DenizenScript/Denizen-For-Bukkit#1636]
Hi,

I've had this issue a few times before back in 1.11 aswell but I never got any errors with it. This time I got an error with denizen mentioned in it. No idea what it means but I hope it's linked to denizen and fixable.

What happens is a player logs in and no chunks are loading around him only the one he stands on and the ones connected to it.
He then relogs and when he logs back in there isn't any errors but when he checks his chests in those chunks that did load he sees that all his chests are empty: https://prnt.sc/g8mpg4
Those 2 double chests are half in the chunk that loaded and the other half were in the not loading chunk.
Half of the items from those double chests are gone and the other half remains.
His beacons also stopped working, the light was off and it gave no buffs. He had to place a block next to them to update them.

This has happened before with different versions of everything (denizen, depenizen, citizens, sentinel and spigot 1.11 whereas I am now in 1.12).

This is the error I got when the player first logged in but he could only see the chunk we was on and the ones connected to it: https://pastebin.com/NVGRCHPK
So those chunks, the ones he saw when he first logged in got cleared so to say. Chests inventories all gone, item frames gone, armorstands gone or cleared, ..

I'm not certain this is caused by denizen but it would make sense since I was using denizen in 1.11 aswell.
No clue but if you know what caused it even if it wasn't denizen it's always appreciated.

**Comment by mcmonkey4eva** [comment]
If you believe it's Denizen...
Post any scripts that use the `logs in` or `joins` events, or anything else that would fire in that time period.
