### ISSUE TITLE
Error with command on player login event

### ISSUE THREAD

**Issue by doitliketyler** [DenizenScript/Denizen-For-Bukkit#1640]
Not sure whats going on here but getting an error when trying to run a command on a players first join. I've tested the script with just the "on player join" event and it works just fine so it seems something is going wrong with the "on player login" event. Here is the error:

https://pastebin.com/bFTwyazL

Thoughts?

**Comment by BlackCoyote** [comment]
the login event fires before the player is fully connected to the server, so the player isn't online yet. add some delay before executing commands for the player

**Comment by doitliketyler** [comment]
Added a 1-second delay and it worked perfectly. Thanks so much.
