### ISSUE TITLE
bug: on item recipe formed

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1644]
Hey.
Wanted to let you know, when you use "on item recipe formed:" and you put i.e. 2 broken diamond axes into the workbench the event fires twice.

**Comment by Fortifier42** [comment]
Can you like, record a short gif or perhaps explain in a little more detail?

**Comment by BloodEko** [comment]
Sure!
https://youtu.be/uE0_57qgZD8

**Comment by mcmonkey4eva** [comment]
Does... this matter that it double fired?

**Comment by BloodEko** [comment]
For my use it shouln't be a big problem, but i made the report because it is redundant.

**Comment by mcmonkey4eva** [comment]
Considered an irrelevant Spigot issue.
