### ISSUE TITLE
Denizen breaks WorldGuard flags

### ISSUE THREAD

**Issue by TheOneTwelfth** [DenizenScript/Denizen-For-Bukkit#1647]
Denizen seems to break WorldGuard flags (such as use, block-break and others). When a player tries to open a door/break a block/etc, the blake smoke appears, indicating that WorldGuard has tried to interfere, but the event proceeds anyway. This only happens when the latest Denizen version is installed.

Spigot 1.8.8

**Comment by mcmonkey4eva** [comment]
Any errors in server logs?

**Comment by mcmonkey4eva** [comment]
Build DEV-225+ might fix it on http://ci.citizensnpcs.co/job/Denizen_Developmental/

**Comment by TheOneTwelfth** [comment]
No errors in logs. Will try out the dev build as soon as i can.

**Comment by mcmonkey4eva** [comment]
Did it help?

**Comment by TheOneTwelfth** [comment]
The problem seems to have gone. Thank you for the help!

**Comment by BloodEko** [comment]
Now as you say it, I seem to have the same error. Players can open fence-gates although they get the cancel message of worldGuard. While i am not 100% whether denizen making the problem.

**Comment by mcmonkey4eva** [comment]
@BloodEko if you can link it down to Denizen, and from there to "not a script"
AND YOU'RE ON LATEST VERSIONS
Post a new issue.
