### ISSUE TITLE
Error occurred while enabling Denizen v1.0.2-SNAPSHOT (build 1641)

### ISSUE THREAD

**Issue by meoso** [DenizenScript/Denizen-For-Bukkit#1649]
`This server is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)`

` [Server thread/INFO]: [Citizens] Loading Citizens v2.0.22-SNAPSHOT (build 1490)`

```
[Server thread/ERROR]: Error occurred while enabling Denizen v1.0.2-SNAPSHOT (build 1641) (Is it up to date?)
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState
```

**Comment by mcmonkey4eva** [comment]
Update spigot to latest 1.12.1

**Comment by meoso** [comment]
thank you
