### ISSUE TITLE
On drags event not working properly

### ISSUE THREAD

**Issue by Zughy** [DenizenScript/Denizen-For-Bukkit#1650]
https://one.denizenscript.com/haste/43919

Even if I cancel the drag event, I can still put an item into the crafting area (I'm on gm 0)

How to reproduce it:
- take an item with the cursor
- now click on an empty crafting slot and WITHOUT RELEASING THE MOUSE BUTTON drags the cursor on another one
- enjoy

In this case I recreated a situation with the crafting event, "solving" it adding a cancel when people click the result slot, but I can do this everywhere.

Also tried with 
``` 
- determine passively cancelled
- wait 1t
- inventory update
``` 
in the drag event, but nothing. The thing is, if I close my inventory without crafting anything, the items return in the "normal" area. Still, for the server, the items are there till I keep it open, so I could craft/bypass any kind of system

**Comment by mcmonkey4eva** [comment]
It helps to look at debug logs ocassionally .-.
```

        on player drags in inventory:
        - if <context.slot_type> == CRAFTING {
            - determine cancelled
            } 
```
That will throw errors, as slot_type is not available in drags event.

It's easy to cancel if you get rid of that check and replace it with something more logical...
