### ISSUE TITLE
on player kills player , fires multiple times

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1651]
Video: https://www.youtube.com/watch?v=a_EDPEtbj0M
Running Code for Video:
on player kills player in 173pre:
    - narrate kill!<context.entity>
    - announce <context.damager>
    - announce "globalkillMessage"

Screenshot: http://www.bilder-upload.eu/show.php?file=86cf8f-1504092287.png
Running Code for Screenshot:
on player kills player in 173pre:
    - announce <context.entity.health>
    - announce <context.final_damage>
    - announce "globalkillMessage"

**Comment by mcmonkey4eva** [comment]
Use player death and some logic.

Kills event is an assumption-driven event, and it stops working when a plugin or script modifies the damage values.
