### ISSUE TITLE
"on script generates error" - context missing script and queue

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#1653]
When the event "on script generates error" is called, some errors does not specify the script or any trace of where the error came from. Only <context.message> works, leading to <context.script> and <context.queue> being undefined.

The following error-messages does not show script or queue context:
- "Narrated to non-existent or offline player!"
- "'something' is an unknown argument!" (this it is usually followed up by a another error which shows the script and queue)
- "Entity referenced is null!"
- "Tag filling timed out!"

This is probably a problem in the internal code but I'll leave this issue here incase if it somehow could be fixed. It would help a lot through debugging.

**Comment by mcmonkey4eva** [comment]
That's an odd limitation of D1, is that the system that handles errors _doesn't know where it's at_ very often!
D2 fixes this inherently.
But D1, nothing will cure it :/
