### ISSUE TITLE
bug: on command in (region)

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1657]
The region argument (in < area > ) for on command doesn't seem to work.

**Comment by mcmonkey4eva** [comment]
Post script, and some explanation of why you think it doesn't work?

**Comment by BloodEko** [comment]
Still exists,
`on myCommand command:` <-- this runs
`on myCommand command in 172:` <-- this not

Maybe somewhere a minor typo in the event-parser ?

**Comment by mcmonkey4eva** [comment]
do you really have a cuboid named `172`

**Comment by BloodEko** [comment]
Its the name of my world.

**Comment by mcmonkey4eva** [comment]
That's a horrible world name. Also, patch in latest dev

**Comment by BloodEko** [comment]
Fix confirmed.
