### ISSUE TITLE
Make placed skull skins more flexible?

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1659]
I know that Denizen currently has it so that you can apply a specific skin texture on a head (dItem) via `UUID|skin-cache|username` format. I was wondering if this could also be applied to placed skulls (dLocation) for greater control over the displayed placed skull's skin.

For example,
```
- define skin_texture <some UUID>|<skin cache>
- adjust <player.item_in_hand> skull_skin:<def[skin_texture]>
- adjust <player.location> skull_skin:<def[skin_texture]>
```
And both `adjust` commands resulting in the held skull and a placed skull having exactly the same skin.

**Comment by mcmonkey4eva** [comment]
This was done at some point
