### ISSUE TITLE
Sometimes a chat overlay bug occurs.

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#1661]
Environment:
On chat events and determine using Format

Symptom:
When you type a chat, one player's chat is ignored and the other player's chat is displayed twice.

frequency:
As often as players are chatting

**Comment by mcmonkey4eva** [comment]
Disable async chat to fix this, in theory.

**Comment by wolfwork** [comment]
Now i think solved
