### ISSUE TITLE
Right-click bug in the inventory

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#1662]
On click-prohibited slots

Holding an item and right-clicking on an empty slot, the item is placed, even though it is forbidden.
I think the right click event does not seem to fire properly, When you holding items.

      - if <context.raw_slot> <= '45' {
          - determine cancelled
      }

**Comment by MusicScore** [comment]
Were you in Survival/Adventure mode when testing this?

**Comment by wolfwork** [comment]
I found its the drag event
