### ISSUE TITLE
Tipped Arrows don't have enough tags/mecs

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1665]
Denizen Developmental build 247, Spigot 1.12.1

Tipped arrows do not seem to have their own mechanisms/tags/etc. This makes it impossible to do direct copies of tipped arrows from one inventory to another without the tipped arrows reverting to an unusable state.

**Comment by mcmonkey4eva** [comment]
iirc it used to just be the durability... guess they changed it D:

**Comment by MusicScore** [comment]
Fixed in latest build. Cheers to quick and fast development lol

**Comment by mcmonkey4eva** [comment]
Beat THAT fix time, Insert Opposing Project Here!
