### ISSUE TITLE
Suggestion: list.average

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1666]
tag: `li@list.average`
returns: Element(Number)
descrip: Calculates the average of all numbers in the dList.

**Comment by Morphan1** [comment]
Should probably have 3 different tags for this (mean median mode)?

**Comment by mcmonkey4eva** [comment]
just average (mean) is needed realistically.
Median would be .numerical.get[length.div[2]]
Mode ... ehhhhhh.... sort by count, idk?

**Comment by Morphan1** [comment]
Median would be more like
```
- define list <def[list].numerical>
- define half <def[list].length.div[2]>
- if <def[list].length.mod[2]> == 0 {
  - define higher <def[list].get[<def[half].add[1]>]>
  - define lower <def[list].get[<def[half]>]>
  - define median <def[list].get[<def[higher].sub[<def[lower]>].div[2].add[<def[lower]>]>]>
  }
  else {
  - define median <def[list].get[<def[half].round_up>]>
  }
```

**Comment by BloodEko** [comment]
sort by ... ? This tag at least should return a Number.

**Comment by BloodEko** [comment]
Tag is added.

**Comment by Morphan1** [comment]
RIP the median and mode
