### ISSUE TITLE
Right click randomly stops working

### ISSUE THREAD

**Issue by doitliketyler** [DenizenScript/Denizen-For-Bukkit#1669]
Ran into a strange bug I can't decipher. So periodically right clicking just stops working and after some time it starts working again. If I run /denizen reload scripts it automatically fixes itself or if I relog it fixes itself. There are no bugs in console and nothing I can find to be causing this. I'm running on Paper Spigot 1.12.1 & Denizen: 1.02-Snapshot.

Thoughts?

**Comment by mcmonkey4eva** [comment]
What build # of Denizen? If not latest dev, update.

**Comment by doitliketyler** [comment]
Build 255

**Comment by mcmonkey4eva** [comment]
Updated enoughish I suppose.
What about scripts, what scripts do you have using that event?
