### ISSUE TITLE
Take command changing item stacks

### ISSUE THREAD

**Issue by doitliketyler** [DenizenScript/Denizen-For-Bukkit#1671]
Experiencing an issue with item stacks with some custom items/models I've set-up. They are using the diamond_hoe and if I have a stack of them and use the take command in a script it removes the texture. I'm guessing this has something to do with durability being changed for some reason. Here are some screenshots of before & after the take command was used.

Before: https://imgur.com/a/lN9CM
After:https://imgur.com/a/uIC6x

Thoughts?

**Comment by MusicScore** [comment]
To add to this:
When I noted an inventory and tried to `- inventory set` the noted inventory into my inventory, the shields became black shields. Spigot 1.12.1, Denizen Dev build 256

**Comment by mcmonkey4eva** [comment]
Fixed, confirmed fix via Discord.

@MusicScore your issue is unrelated to this.
