### ISSUE TITLE
Suggestion:  flagKeys

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1673]
Hello, i would like to suggest these tags as a analysis tool ( beside p@player.list_flags ) for flag structures.

tag: <p@player.list_flag_keys[section]>
returns: dList
descrip: Returns the entries in the specified section.

tag: <p@server.list_flag_keys[section]>
returns: dList
descrip: Returns the entries in the specified section.

Should be doable with "Configuration Section getKeys(boolean deep) - [LINK](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/configuration/ConfigurationSection.html) " , when deep is set to false

**Comment by mcmonkey4eva** [comment]
wtf is `p@server`

That's some young-morphania there

**Comment by mcmonkey4eva** [comment]
As I've said to you countless times, alongside every else on the Discord;
This feature idea is invalid.
- You're asking to enhance the power of a D1-local system that was available by chance.
- It would make more sense to remove the structuring entirely - it's only kept for back support for some scripts.
- There's a million better ways to do that if you need it... such as actually using YAML!
- You clearly have no knowledge of how Denizen is set up internally, so I don't know why you're linking irrelevant Bukkit code.
