### ISSUE TITLE
[suggestion] Player closes written_book | <written_book>

### ISSUE THREAD

**Issue by lmorgh** [DenizenScript/Denizen-For-Bukkit#1674]
Can we get an event that catches players closing a book? I don't think there's even a workaround for it, and it would be super useful in any case.

Thanks for considering it.

**Comment by mcmonkey4eva** [comment]
As best I'm aware, Spigot doesn't have an event for that :/
I don't think Minecraft sends that information over the network.


There IS a "sorta" workaround though.
- mark when the player has opened a book
- Listen to any reasonable action that they might perform. Command, Chat, Opens (inventory, book, anything), and steps would be my set for that.
- From all the events above, run this command:
```yml
- event "player closes book"
```
Boom, you got an event for it :P 
Can then listen to it with `on player closes book:`

**Comment by lmorgh** [comment]
Thanks for the info. Hopefully that's another thing that will be handled by sponge better.
