### ISSUE TITLE
[suggestion] <player.list_permissions>

### ISSUE THREAD

**Issue by lmorgh** [DenizenScript/Denizen-For-Bukkit#1675]
There is currently no way to get all player permissions listed, could this be implemented?

**Comment by mcmonkey4eva** [comment]
Different perm plugins list them in different formats, it might be difficult...

**Comment by Mwthorn** [comment]
Does Vault not have a general way of getting the permssions?

**Comment by lmorgh** [comment]
You can see the perms via Vault, but it would be useful if we could list them in Denizen and manipulate them as dList. I think the feature would improve the Denizen experience for sure.

**Comment by Morphan1** [comment]
This is more than likely not going to happen. Vault doesn't support it because not many permissions plugins support it, and a manual search through the underlying Bukkit system would be extremely slow from my experience.

What exactly is your use case?

**Comment by lmorgh** [comment]
I forgot the details, but I think I wanted to list all player perms and compare them to a dList of possible permission rewards, so I could give out "random" permissions for my server features. Surely I've had other ideas involving the tag in question, but those come and go as they please, so...

I'm not familiar with the methods you code wizards use for getting stuff done, but if you say it's not going to happen, I guess us users will have to deal with it. Thanks for looking into it.

**Comment by mcmonkey4eva** [comment]
put the list of possible rewards in a yaml data script, then remove one from a temp list at random, `if !<player.has_permission[chosen]> { - give perm[chosen] - queue clear }` and repeat that until the list is empty. When it's empty, you know they have all possible perms!
