### ISSUE TITLE
Shields becoming black from noted inventory after server restart

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1678]
Denizen Developmental 263, Spigot 1.12.1

After a server restart, any noted inventory will return black shields instead of patternless shields. I'm not entirely sure what the cause is, since no error is thrown in the console.

EDIT: Persists in developmental build 264

**Comment by mcmonkey4eva** [comment]
Is this still an issue?

**Comment by MusicScore** [comment]
Shields do not appear to turn black when placed in a notable inventory. The shield remains colorless after a restart.
