### ISSUE TITLE
Ellipsoid tags and functionality

### ISSUE THREAD

**Issue by blindcat97** [DenizenScript/Denizen-For-Bukkit#1680]
I'm not sure how much of ellipsoid functionality is complete, just that the Discord chat agrees that it's most likely still a WIP. I'm just here to suggest that it be finished, or at least that it have more support/functionality. Specifically, things like modifyblock, notables, and player.selected_region should be able to interface properly with ellipsoids. WorldEdit supports ellipsoid selection, but cuboid selection could also be used with the corners as defining points. Since ellipsoids seem to only be notable if the full "ellipsoid@x,y,z,world,radius-x,radius-y,radius-x as:notable_name" notation is used, some region selection or at least easier location tagging would be preferable.

**Comment by mcmonkey4eva** [comment]
Ellipsoid support is complete and functional last I checked, don't know who you were speaking to on Discord...
A WorldEdit tag would be a job for Depenizen, not Denizen-Bukkit!
