### ISSUE TITLE
On player clicks block doesn't fire when clicking air

### ISSUE THREAD

**Issue by lmorgh** [DenizenScript/Denizen-For-Bukkit#1681]
The event should fire when clicking air, it even says so in the meta, but it doesn't. Bug?

**Comment by lmorgh** [comment]
It turns out it just doesn't work when you do On player clicks air, but works if you just do On player clicks.

Maybe a quick meta update to note this little quirk is in order.

**Comment by Oruss7** [comment]
Air is technically a block, but not functionnall

**Comment by mcmonkey4eva** [comment]
I believe this shouldn't happen that way on latest version. If it does, please reply below.
