### ISSUE TITLE
Cannot adjust unbreakable mechanism on items

### ISSUE THREAD

**Issue by GershonR** [DenizenScript/Denizen-For-Bukkit#1682]
When using adjust on items, the unbreakable mech does not get saved, if using an adjust to change the unbreakable nothing happens.

**Comment by mcmonkey4eva** [comment]
Have you been able to use adjust with other item mechanisms?

**Comment by GershonR** [comment]
I can adjust the lore of the item, and when using adjust, enchants and flags get saved but unbreakable just dissapears

**Comment by mcmonkey4eva** [comment]
was fixed
