### ISSUE TITLE
New to ymal/denizens and in need of help to figure why a script does not work properly

### ISSUE THREAD

**Issue by iurirolho** [DenizenScript/Denizen-For-Bukkit#1683]
My script does not want to go past the part were i send a reply(it does not recognize it for some reason) i hope here somebody cant hint me up with a why its doing that. 

[my script.zip](https://github.com/DenizenScript/Denizen-For-Bukkit/files/1451174/my.script.zip)

**Comment by Mwthorn** [comment]
You can do the "click trigger" and "chat trigger" on the same step like so: https://one.denizenscript.com/haste/45391
Everything else looks good. I have not tested the script though.

For future script help, we have a Discord ^^
https://discord.gg/Q6pZGSR

**Comment by iurirolho** [comment]
i will probably go on discord and ask for help i did once try on same step and no luck

**Comment by iurirolho** [comment]
spacing was the issue went on discord and 2 people managed to help me figure it out
