### ISSUE TITLE
area_effect_cloud mechanisms

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1684]
I've noticed that the meta says nothing about mechanisms specific to the `area_effect_cloud` entity. I was wondering if there were any way to include `area_effect_cloud` mechanisms so I could do some manipulative magic with it, or if I have to resort to the good old `- execute` for area_effect_clouds.

**Comment by Rickytehduck** [comment]
I'm glad someone else brought this up, since my old post ages ago never got looked at. Thanks MusicScore!
