### ISSUE TITLE
Tags - Towny flags

### ISSUE THREAD

**Issue by WaterQuarks** [DenizenScript/Denizen-For-Bukkit#1685]
Requesting:

<player.town.has_explosions> -> true/false, does the Town has explosions enabled?
<player.town.has_mobs> -> true/false, does the Town has mobs enabled?
<player.town.has_pvp> -> true/false, does the Town has PvP enabled?
<player.town.has_firespread> -> true/false, does the Town has fire spread enabled?
<player.town.has_taxpercent> -> true/false, does the Town has taxing by percentage enabled?
<player.town.has_plottax> -> taxes collected from each resident daily, per plot that they own.
<player.town.has_plotprice> -> default cost of plot for the town.

also, if its possible, a tag that displays all Towns as a dList.

**Comment by mcmonkey4eva** [comment]
https://github.com/DenizenScript/Depenizen/issues
