### ISSUE TITLE
A proposal for a damage check

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#1686]
on entity damaged event occurs
I wish Denizen could detect the damage through another plug-in.

**Comment by mcmonkey4eva** [comment]
... huh?

**Comment by wolfwork** [comment]
rpgitems, myitems pugins modify the damage. I hope that denizen can get this modified damage.

**Comment by mcmonkey4eva** [comment]
We can't interop with other plugins automatically, any given plugin would need to be explicitly supported, EG through Depenizen.

**Comment by wolfwork** [comment]
I got it. Thank you for your support.
