### ISSUE TITLE
Color Update: dMaterial or a Tag ?

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1689]
Hey!
With 1.12 ShulkerBoxes and Beds can have colors. Can support for these maybe be added ?
Maybe directly in the dMaterial name, or as tag ?

I found this in the spigot docs: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/material/Colorable.html#getColor--

**Comment by MusicScore** [comment]
I believe `.material` supports `WHITE_SHULKER_BOX`, etc. Only beds seem to not have color support.

**Comment by BloodEko** [comment]
Closing this and making a more precise issue, for a possible bed color tag.
