### ISSUE TITLE
Update Gravity mechanism/tag

### ISSUE THREAD

**Issue by Rickytehduck** [DenizenScript/Denizen-For-Bukkit#1695]
Post 1.9, the gravity NBT tag works with all entities, not just armor stands.
It'd be pretty useful if we could have that updated to work.

**Comment by mergu** [comment]
Is there any difference between this, and the has_ai functionality currently implemented?

**Comment by Rickytehduck** [comment]
Oh yeah, has_ai only affects mobs, not all entities. 
For instance, the dropped_item and falling_block entities are not affected by it. There may be others as well, I assume the boat entity doesn't rely on AI.
