### ISSUE TITLE
denizen command(schematic paste) don't work after world regeneration(Multiverse-Core)

### ISSUE THREAD

**Issue by Wolf2323** [DenizenScript/Denizen-For-Bukkit#1696]
i found this strange bug while i wrote a complex script.

Introduction(only to get the context):
The Script should regenerate the Nether World and manage a custom unique NetherPortal, that is made of Schematics. When the Nether is regenerated, i call Multiverse-Core commands ("execute as_server "mv regen Nether -s") and when the regeneration is completed i paste a schematic in the Nether as a Spawn(this is all done withe the Nether_Regen task). When someone wants to leave the nether the method Nether_World_Portal is called to open a portal to the normal world.
My Script: https://pastebin.com/PsN3UuqM

The Problem:
The schematic that represets the Spawn is pasted perfect. But the schematics, that represents the portal are not pasted.

My guess:
when the world is regeneraterd the locations from the notables.yml are not mapped to the "new" world. But when a method like .add[0,67,0] is calles the location gets mapped. Because of this the spawn schematic is pasted(add and sub is called) and the Portal schematic is not pasted(no add,sub,.. is called).

My temporary solution:
when the world is regenerated i run "execute as_server "denizen reload Notables" this is no nice solution but it work.

**Comment by mcmonkey4eva** [comment]
Uh, that's really non-standard action to be taking and glitches are inevitable.
Other notable handling issues may be relevant here or helpful to your case... but as far as this issue: yeah that's going to bug a bit sometimes when you break a world on your server :/
