### ISSUE TITLE
<&quo> invalid tag ??

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Denizen-For-Bukkit#1697]
Hello, 

```
- narrate format:narration_format "- <white>/sign <&lt>ligne<&gt> <&quo><&lt>texte<&gt><&quo><gray> en regardant le panneau pour modifier la ligne."
```
with `<&lt>` and `<&gt>` working great, `<&quo>` invalid tag ... 

Thanks

**Comment by BloodEko** [comment]
Hey,
it's <&dq> for "

**Comment by Oruss7** [comment]
Oh thanks, the doc is not up-to-date ='(

**Comment by mcmonkey4eva** [comment]
That's not a doc flaw, that's you misreading the docs :P

**Comment by Oruss7** [comment]
here: https://one.denizenscript.com/denizen/lngs/Property%20Escaping
