### ISSUE TITLE
Written book mecs throwing errors

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1700]
Denizen Developmental build 268, Spigot 1.12.2. When I try to use or read the `book` mec, an error is returned.

This is from using `/ex narrate <player.item_in_hand>` on a written book: https://one.denizenscript.com/haste/46078
This is from using `/ex give 'i@written_book[book=author|test|title|tester|pages|testing]'`: https://one.denizenscript.com/haste/46079

**Comment by mergu** [comment]
Repeat of https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1693
Fixed in https://github.com/mcmonkey4eva/Denizen/pull/119
