### ISSUE TITLE
Anvils in inventory script containers

### ISSUE THREAD

**Issue by WaterQuarks** [DenizenScript/Denizen-For-Bukkit#1702]
Requesting added functionalities to inventory scripts that use `inventory: anvil`!
They "work" but you can't add any items on them. I've tried to fill them with procedural items, and using the slot list. I'm aware that we have anvil-specific events, but they aren't suitable for making, say, a chat prompt or anything GUI related.

Thanks in advance!

**Comment by mcmonkey4eva** [comment]
aren't anvils clientside?

**Comment by WaterQuarks** [comment]
I don't think so. Here's an example of what could be done:

![screenshot from 2017-12-30 21-29-08](https://user-images.githubusercontent.com/28162761/34458664-c8af1642-eda8-11e7-812f-72762d87d373.png)

**Comment by Morphan1** [comment]
I'm... gonna bulk this up with #1030, as I don't think an inventory script is the way to do this
