### ISSUE TITLE
Giving book error

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1703]
Hi, I got an new error after an update of the spigot.jar, I can't give anymore a book, it trow now some error :
https://hastebin.com/ocadozanon.md
Testbook_script:
    type: book
    debug: true
    title: test
    author: test3
    signed: true
    text:
    - test

**Comment by mergu** [comment]
Repeat of https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1693
Fixed in https://github.com/mcmonkey4eva/Denizen/pull/119
