### ISSUE TITLE
Mergu's Tags, Mechs, and Properties Work List

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#1705]
~~dLocation and dItem lock-related mecs/tags for:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Lockable.html~~

dItem CommandBlock attributes:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/CommandBlock.html

dItem Bed color:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Bed.html

dItem CreatureSpawner attributes:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/CreatureSpawner.html

dLocation EndGateway attributes:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/EndGateway.html

~~dItem sign attributes:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Sign.html~~

**Comment by mergu** [comment]
[EnderSignal](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EnderSignal.html)

[Structure Blocks](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Structure.html)

**Comment by mergu** [comment]
`animateblock` command, actually check if `animatechest` is a chest:
http://wiki.vg/Block_Actions

**Comment by mcmonkey4eva** [comment]
`actually check if animatechest is a chest:` nah, allow it to do its current action, don't place restrictions ad hoc unless they're an actual danger or problem to leave in.

**Comment by mcmonkey4eva** [comment]
How's this going @mergu

**Comment by mergu** [comment]
working on it ™

**Comment by mergu** [comment]
never

**Comment by mcmonkey4eva** [comment]
Closing due to, er, @mergu not being part of the team anymore :(
