### ISSUE TITLE
Npcs and sitting

### ISSUE THREAD

**Issue by HeadlessJoey** [DenizenScript/Denizen-For-Bukkit#1707]
Whenever the server restarts I suddenly find myself with an npc (who was sitting before the restart) who is standing again and 1 block lower than what he is supposed to be at (so 1 block in the ground) and suddenly an invisible npc armorstand with the name floating above it "Armor Stand" (a newly created npc) floating in the npc.
I have to manually remove that newly created npc named Armor Stand and ofcourse teleport the npc back to his spot and make him sit again.
Is this fixable? I remember sitting being an issue before with the arrows etc.. but I could technically work with this if it wouldn't spawn that armorstand npc upon restart.

**Comment by mcmonkey4eva** [comment]
sit logic has been fixed recently in Citizens dev builds.
(Also: it's basically just powered by Citizens, rather than Denizen internal code. Denizen just adds user-accessible control to it)
