### ISSUE TITLE
<player.groups> Listing All Groups Inheritence

### ISSUE THREAD

**Issue by Elxafil** [DenizenScript/Denizen-For-Bukkit#1711]
So basically the above tag is not only listing the group I am in but the rest of the groups that they inherit from, for example when running `/ex narrate <player.groups>`: http://prntscr.com/hztgda shows the all the groups which inherit into each other like this:

Owner
CoOwner
Assistant
Manager
HeadAdmin
Admin
Moderator
Helper
Member

I however am only in the Owner rank so can you please fix this and an idea would be to fix it and potentially change what it does now to a separate tag such as <player.groups.inheritance>?

**Comment by mergu** [comment]
This is intended behavior. `<player.groups.get[1]>` will return your highest group.

**Comment by Elxafil** [comment]
But that's not what I want to use it for, I need to loop through all the groups a player is in using `foreach` so I can add prefixes but I can't do that if it's listing all the groups.

**Comment by mcmonkey4eva** [comment]
As discussed on Discord, we can't fix that.
