### ISSUE TITLE
CraftAbstractHorse Error

### ISSUE THREAD

**Issue by Ugikie** [DenizenScript/Denizen-For-Bukkit#1713]
Basically what I am trying to do in my script (and I know this is achievable through other methods) is that I am trying to spawn a Horse with certain data, i.e. a custom display name, speed/jump values, and health, etc. And then flag the player with said horse data via the <entitiy.describe> tag. 

Upon attempting to spawn this horse again through means of - spawn <pl.flag[myHorse]> <pl.location>

I get this error. 

http://old.mcmonkey.org/paste/46265

**Comment by mergu** [comment]
The issue is `color=gray|white|horse`. Setting horse variant has been deprecated since 1.11, just remove the `|horse` and you should be good. I'll update the docs and get rid of the error.
