### ISSUE TITLE
Sprint event can't be cancelled

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1715]
Hello, I just tested the sprint event and it won't cancelled. In the console I get "Event cancelled!"

**Comment by mergu** [comment]
This is a Spigot/clientside issue. If the player is holding down their sprint key, you can't stop them from sprinting without setting their food_level to 6 or below, or using other clever means like potion effects.

**Comment by Noiknez** [comment]
Ok, thank you for the clarification
