### ISSUE TITLE
Workbench Inventories Broken

### ISSUE THREAD

**Issue by doitliketyler** [DenizenScript/Denizen-For-Bukkit#1716]
Once upon a time, workbench inventories worked but now they are broken. Could someone take a look into this? Here is a simple sample script that still doesn't work:

https://pastebin.com/raw/vZzWZuGf

**Comment by mergu** [comment]
Looks like md_5 patched this just yesterday:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/49ecc7c7a28bf0074690ce2f1a02232b7fb2385b

Update spigot then let us know if the issue persists

**Comment by doitliketyler** [comment]
Yep. Works perfectly now. Thanks for letting me know. Cheers.
