### ISSUE TITLE
Request: tablist modification mechanism

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1717]
Hello, my suggestion is to make a mech to add/remove a fake/real player on the tablist, in relation to DepenizenBungee. I searched for information and see what possibilities can be made http://wiki.vg/Protocol#Player_List_Item, this mech would include all the information provide normally in the tablist for a player (connection, head, name, etc)

In the moment in D1 we can only modify theses 2 thing :
- The header & footer of the tablist (tab_list_info)
- The player name in the tablist (player_list_name)

**Comment by mcmonkey4eva** [comment]
Adding fake players to the list is not allowable.

**Comment by Noiknez** [comment]
Can we do this for real player with DepenizenBungee ? like other plugin does ?
![](https://www.spigotmc.org/attachments/2014-05-09_13-29-58-png.3026/)
