### ISSUE TITLE
Denizen conflicting with an other plugin (ImageOnMap) ?

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1720]
Hello ! 

Yesterday I got an message error when using the plugin Denizen & Cartographer, I was in creative mode but I don't really know how to reproduce it. I have made an issue on the cartographer github here --> https://github.com/BananaPuncher714/Cartographer/issues/2 but i am going to you because the error place is unknow
What can it possibly be ?

Regards

**Comment by mcmonkey4eva** [comment]
You somehow have a nonsense item with invalid enchantments on it, which Spigot internals then crash on because they can't process the item.

**Comment by Noiknez** [comment]
Ok, I see what it could be : It is the plugin "ImageOnMap" it give an enchanted map

**Comment by bibo38** [comment]
This is a bug in the ImageOnMap plugin, as pointed out by me at https://github.com/zDevelopers/ImageOnMap/issues/41 .
Denizen just triggered the bug by querying the enchantments of the ItemStack.
So this issue can be closed...
