### ISSUE TITLE
Error when opening another player inventory

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1721]
Hi, I got this error https://pastebin.com/Vaw9tNmN

**Comment by mcmonkey4eva** [comment]
it looks like you may have given an offline player inventory to open and worldguard was unhappy with that (as it expected an online player)?

**Comment by Noiknez** [comment]
Yes it is that, is there any way to open an offline player inventory without getting error ?

**Comment by mcmonkey4eva** [comment]
It's a worldguard issue. It's not anything wrong with our code or minecraft.

Opening inventories is usually fine, just fix whatever went wrong in worldguard.
