### ISSUE TITLE
Denizen/Depenizen Error

### ISSUE THREAD

**Issue by doitliketyler** [DenizenScript/Denizen-For-Bukkit#1722]
Hey there. Getting this Denizen console error and Depenizen is not loading up. 

https://pastebin.com/raw/k9ArqBfN

Thoughts?

**Comment by mergu** [comment]
Funny enough this is a Denizen-Core error, should be fixed in my upcoming PR

**Comment by doitliketyler** [comment]
Awesome. Thanks for the quick update.
