### ISSUE TITLE
.list_chunks .list_partial_chunks tags not working

### ISSUE THREAD

**Issue by Mickket** [DenizenScript/Denizen-For-Bukkit#1723]
I am unable to get a list of chunks using these 2 tags. I am using `chunkload <cu@3767,0,-445,world|4449,255,30,world.list_partial_chunks>`

<cu@3767,0,-445,world|4449,255,30,world.list_partial_chunks> returns cu@3767,0,-445,world|4449,255,30,world.list_partial_chunks

Denizen build #'1645 
PaperSpigot build #'1320 (1.12.2)

Here is the error that is occurring upon using these tags

> 9:32:19 AM CONSOLE: WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
9:32:19 AM CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:54)
9:32:19 AM CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
9:32:19 AM CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
9:32:20 AM CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
9:32:20 AM CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
9:32:20 AM CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:181)
9:32:20 AM CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:625)
9:32:20 AM CONSOLE: WARN]: at org.bukkit.Location.getChunk(Location.java:82)
9:32:20 AM CONSOLE: WARN]: at net.aufdemrand.denizen.objects.dCuboid$20.run(dCuboid.java:1293)
9:32:20 AM CONSOLE: WARN]: at net.aufdemrand.denizen.objects.dCuboid.getAttribute(dCuboid.java:1382)
9:32:20 AM CONSOLE: WARN]: at net.aufdemrand.denizencore.tags.TagManager.fetchObject(TagManager.java:245)
9:32:20 AM CONSOLE: WARN]: at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
9:32:20 AM CONSOLE: WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
9:32:20 AM CONSOLE: WARN]: at java.lang.reflect.Method.invoke(Unknown Source)
9:32:20 AM CONSOLE: WARN]: at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:84)
9:32:20 AM CONSOLE: WARN]: at net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:259)
9:32:20 AM CONSOLE: WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
9:32:20 AM CONSOLE: WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
9:32:20 AM CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
9:32:20 AM CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
9:32:20 AM CONSOLE: WARN]: at java.lang.Thread.run(Unknown Source)
9:32:29 AM CONSOLE: WARN]: java.lang.InterruptedException
9:32:29 AM CONSOLE: WARN]: at java.lang.Object.wait(Native Method)
9:32:29 AM CONSOLE: WARN]: at java.lang.Object.wait(Unknown Source)
9:32:29 AM CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.get(Waitable.java:39)
9:32:29 AM CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:63)
9:32:30 AM CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
9:32:30 AM CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
9:32:30 AM CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
9:32:30 AM CONSOLE: WARN]: at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
9:32:30 AM CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:181)
9:32:30 AM CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:625)
9:32:30 AM CONSOLE: WARN]: at org.bukkit.Location.getChunk(Location.java:82)
9:32:30 AM CONSOLE: WARN]: at net.aufdemrand.denizen.objects.dCuboid$20.run(dCuboid.java:1293)
9:32:30 AM CONSOLE: WARN]: at net.aufdemrand.denizen.objects.dCuboid.getAttribute(dCuboid.java:1382)
9:32:30 AM CONSOLE: WARN]: at net.aufdemrand.denizencore.tags.TagManager.fetchObject(TagManager.java:245)
9:32:30 AM CONSOLE: WARN]: at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
9:32:30 AM CONSOLE: WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
9:32:30 AM CONSOLE: WARN]: at java.lang.reflect.Method.invoke(Unknown Source)
9:32:30 AM CONSOLE: WARN]: at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:84)
9:32:30 AM CONSOLE: WARN]: at net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:259)
9:32:30 AM CONSOLE: WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
9:32:30 AM CONSOLE: WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
9:32:30 AM CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
9:32:30 AM CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
9:32:30 AM CONSOLE: WARN]: at java.lang.Thread.run(Unknown Source)

**Comment by mcmonkey4eva** [comment]
- Don't use Paper, use Spigot.
- Might be beneficial to disable tag timeout (set duration to 0)
- Chunkload doesn't take a list

**Comment by Mickket** [comment]
I had a feeling PaperSpigot was the issue. I was able to output a list of the chunks using Spigot then switched back to PaperSpigot. I assume the chunkload command handles chunks differently than the chunk tags. Using the tags appears to temporarily load map chunks anyway but PaperSpigot has no issues using the chunkload command when supplied with my pre-recorded list of chunks.

**Comment by mcmonkey4eva** [comment]
tags with tag timeout not disabled means they will be loaded "async" (in the eyes of broken code) which means there's a risk of crashing. Tag timeout is enabled less often in latest builds to help avoid that.
