### ISSUE TITLE
give to slot will still default to stacking if possible

### ISSUE THREAD

**Issue by zozer** [DenizenScript/Denizen-For-Bukkit#1727]
when i give an item through the give command and specify a slot, it will still put the item in a stack if there is room elsewhere.
such as, if i have 27 glass bottles in slot 8, and i attempt to give a glass bottle to slot 5, the glass bottle will be added to slot 8 instead.

**Comment by Morphan1** [comment]
Well that's strange. But there's not really a whole lot we could do about that (at least, not without potentially breaking compatibility with some scripts) as it's just a straight Spigot call
```
List<ItemStack> leftovers = inventory.addWithLeftovers(slot.asInt() - 1, limited, is);
```
If you don't like the weirdness of the give command, you should maybe look into the `inventory add` command.
