### ISSUE TITLE
EventException at SignChangeEvent

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#1729]
Error: https://one.denizenscript.com/haste/46745

Difficult to reproduce since the error only appears sometimes. 
I have a script that changes a sign when a sign is changed.
I also have a script that makes so I can edit a sign with shift+right-click.

Additional debug: http://old.mcmonkey.org/paste/46746

**Comment by mcmonkey4eva** [comment]
`
I have a script that changes a sign when a sign is changed.`
... And that's a good idea how?
Don't do that.
At minimum `wait 1t` it out of the event.
Or just use a determine, lol.

**Comment by Mwthorn** [comment]
I use determine to change the sign for that
https://one.denizenscript.com/haste/46747

**Comment by mcmonkey4eva** [comment]
It looks a lot like the event fired but when Denizen got it, the block wasn't a sign block.
Possibly from a nonsense event, or more likely from some event listener destroying the block for some reason.
