### ISSUE TITLE
PropertyEscape Inconsistency?

### ISSUE THREAD

**Issue by oldquestman** [DenizenScript/Denizen-For-Bukkit#1730]
Hello!
I noticed that when you for example do <player.item_in_hand> it returns the i@ with many of the problematic characters escaped but if the item name contains spaces, they aren't escaped as &sp. For my script I'd really need it to consistently return a string with spaces escaped too. Do I have any way to have the <player.item_in_hand> return the exact same information but the space characters would be replaced with &sp?
Some examples how it would look like <player.item_in_hand.replace[ ]with[&sp]> or <player.item_in_hand.escape_spaces>

Best Regards
OldQuestMan

**Comment by oldquestman** [comment]
Thank you for your quick response!
Unfortunately,  <player.item_in_hand.after[i@].replace[ ].with[&sp]>
doesn't seem to work, since the space cuts it in half and makes it return
<player.item_in_hand.after[i@].replace[
Escaping it with <player.item_in_hand.after[i@].replace[&sp].with[example]>
leaves the space characters untouched again.
Any more ideas?

2018-02-26 19:34 GMT+02:00 mcmonkey4eva <notifications@github.com>:

**Comment by mcmonkey4eva** [comment]
First: Please visit the github issues page, do not reply by email. I hate that github option as it causes way more issues that it solves lol.

Second: quotes. Just put `"` on either side of the argument to automatically consider spaces a part of the full argument, rather than a separator thereof.

**Comment by oldquestman** [comment]
Adding quotes around the <> helped! Thanks a bunch! Adding that "after[i@]" didnt seem to be necessary for it to work. This can be closed now.
