### ISSUE TITLE
suggestion : <context.is_critical> for swords hits in "on player damaged entity"

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#1736]
All is in the title ^^
It might be very nice 😊

**Comment by Morphan1** [comment]
I don't believe there's any API for that, and I don't feel comfortable adding a manual check for it. You might be able to implement it somewhat easily in scripting, though. See this link for a general reference on how to accomplish it: https://www.spigotmc.org/threads/check-if-a-hit-is-a-critical-hit.187105/
