### ISSUE TITLE
first login event

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1738]
In the event "on player first login" or "on player logs in for the first time", the "first time" part is not working

**Comment by mcmonkey4eva** [comment]
How are you testing that?

You realize you basically just about need to get a new user onto your server for each and every testing of it?

(Or resetting all the server data)

**Comment by GomaTerzu** [comment]
I can confirm, that the event works correctly since I have new players on a daily basis and log data.

**Comment by Noiknez** [comment]
Is this related to file saving or something ? If a file is not save when I shutdown the test server then the server won't know that it is not a new player

**Comment by Noiknez** [comment]
Had done multiple testing and it work fine
