### ISSUE TITLE
Wow.

### ISSUE THREAD

**Issue by doitliketyler** [DenizenScript/Denizen-For-Bukkit#1741]
https://www.linkedin.com/in/doitliketyler/

Read my recommendations where everyone refers to me as "her" genius. Egomaniacal weirdo.

**Comment by mcmonkey4eva** [comment]
Lying.
Spamming.
Trolling.
Inviting other trolls.
Being generally defensive and shitty.

And a lot of it.

I don't know what you expected with that shitty behavior... but not even the active and safe Discord group with the fewest retained bans ever is going to put up with your shit.
