### ISSUE TITLE
Now who is lying

### ISSUE THREAD

**Issue by doitliketyler** [DenizenScript/Denizen-For-Bukkit#1742]
"Lying.
Spamming.
Trolling.
Inviting other trolls.
Being generally defensive and shitty.

And a lot of it.

I don't know what you expected with that shitty behavior... but not even the active and safe Discord group with the fewest retained bans ever is going to put up with your shit."

_______

None of that is true. I never lied, spammed, trolled, or invited my friend to troll. I also straight up said, "just because she is my friend doesn't mean I invited her to troll". I never denied that we were friends. I just said I didn't invite her to troll. So tell me exactly how I lied? Oh right, I didn't. Furthermore, how is sticking up for myself after you attacked me a bannable offense? Oh right, its not...it just seems like you were being defensive and shitty yourself. I mean I straight up asked you to stop referring to me as him and you accused me of lying and instantly banned me. You are out of control and I didn't deserve that which is unfortunate because I really liked the other members of the community.

Cheers

**Comment by mcmonkey4eva** [comment]
Fuck off. Stop this spamming shit.

If you post any further on here I will contact GitHub staff and request administrative support in dealing with this.

This is a project issues page, not a page for you to post your stupid fucking lies about yourself getting banned from Discord for posting stupid fucking lies.
