### ISSUE TITLE
Notable-inventories-related event additions

### ISSUE THREAD

**Issue by WaterQuarks** [DenizenScript/Denizen-For-Bukkit#1744]
**on player clicks in notable inventory**
**on player opens notable inventory**
**on player closes notable inventory**

Using the standard inventory events would mean firing them when players interact with any inventory; even if its only for a queue clear, the check's still there.

**Comment by mcmonkey4eva** [comment]
added in latest dev, use `on player clicks in notable:` (like if the inventory were just named "notable")
