### ISSUE TITLE
bug: midi command

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1745]
When a playing midi is getting stopped:
```
- midi <player> file:music
- wait 15
- midi <player> cancel
```
The sound stops. But in some situations for specific songs it can throw this error 1-4 times:
 "Trying to play notes on closed midi NoteBlockReceiver!"

Which leads to this line:
https://github.com/DenizenScript/Denizen-For-Bukkit/blob/5016cefd083d1e0cfc67c2b5ec78c8cbc8aef263/plugin/src/main/java/net/aufdemrand/denizen/utilities/midi/NoteBlockReceiver.java#L87

**Comment by BloodEko** [comment]
@mergu Maybe you know more here, as you rewrote midi command.

**Comment by mcmonkey4eva** [comment]
Can you upload the image somewhere that actually retains it (like imgur) and/or post whatever error as text (not a screenshot)?

**Comment by BloodEko** [comment]
I updated my post.

It's now about 1 year ago, but as I remember `- midi <player> cancel` seems "working" while still throwing the error (sometimes) as `channelPatches == null` then.

But I can't say how it internally leads to this situation.

**Comment by mcmonkey4eva** [comment]
Is this still an actual issue on current builds?

**Comment by BloodEko** [comment]
I made now a test, the answer is: yes

/ex if true { - midi <player> file:denizen - wait 2 - midi <player> cancel }
https://one.denizenscript.com/paste/51959

It varies from song to song:
https://one.denizenscript.com/paste/51956
