### ISSUE TITLE
on player unequips armor - does not trigger

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1747]
On latest version of Spigot and Denizen.

```
on player unequips armor:
- announce "test"
```

This just doesn't do anything.  If I use 'on player equips armor', it works fine.

Thanks,
Uledrith

**Comment by mcmonkey4eva** [comment]
Review https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1567 or really anything on a search for 'unequips' https://github.com/DenizenScript/Denizen-For-Bukkit/issues?utf8=%E2%9C%93&q=unequips
