### ISSUE TITLE
Book and proximity triggers

### ISSUE THREAD

**Issue by silentspectr** [DenizenScript/Denizen-For-Bukkit#1748]
Hi 
How are you ?

i used to create quests a few years ago with denizen and i'm just getting back to it now with version 1.12.2
i installed the plugin and reacreated a quest. and it's not working properly.
First, the proximity trigger won't work at all, i don't even receive log in the console.
here's my code:

`Proximity Trigger:
                entry radius: 5
                entry:
                    script:
                    - if <player.has_flag[QP1Debut]> {
                      - chat "Vas te presenter aux habitants."
                      } else {
                      - engage
                      - chat "<&e>Hey toi la!"
                      - disengage
                      }`

second, i created a book as i did on my other server but the console throws an error when an npc gives it to me:

my book
`LQP1C1:
    type: book
    title: Chapitre 1
    author: Joseph
    signed: true
    text:
    - <&n>Visitez l'île pour faire la connaissance de ses habitants.<&r>`

the command the NPC inputs is `- give i@LQP1C1 qty:1`

and the console gives me this

`[16:05:07] [Server thread/INFO]:  ERROR in script 'QP1JOSEPH'! Woah!! An exception has beencalled with this command! [m[16:05:07] [Server thread/INFO]:  ERROR in script 'QP1JOSEPH'! Internal exception was thrown! [m[16:05:07] [Server thread/WARN]: java.lang.UnsupportedOperationException: Not supported yet.[16:05:07] [Server thread/WARN]: at org.bukkit.inventory.meta.ItemMeta$Spigot.isUnbreakable(ItemMeta.java:225)[16:05:07] [Server thread/WARN]: at net.aufdemrand.denizen.objects.properties.item.ItemUnbreakable.getPropertyString(ItemUnbreakable.java:54)[16:05:07] [Server thread/WARN]: at net.aufdemrand.denizencore.objects.properties.PropertyParser.getPropertiesString(PropertyParser.java:63)[16:05:07] [Server thread/WARN]: at net.aufdemrand.denizen.objects.dItem.identify(dItem.java:530)[16:05:07] [Server thread/WARN]: at net.aufdemrand.denizen.objects.dItem.toString(dItem.java:624)[16:05:07] [Server thread/WARN]: at java.lang.String.valueOf(String.java:2994)[16:05:07] [Server thread/WARN]: at java.lang.StringBuilder.append(StringBuilder.java:131)[16:05:07] [Server thread/WARN]: at java.util.AbstractCollection.toString(AbstractCollection.java:462)[16:05:07] [Server thread/WARN]: at net.aufdemrand.denizencore.objects.aH.debugObj(aH.java:361)[16:05:07] [Server thread/WARN]: at net.aufdemrand.denizen.scripts.commands.item.GiveCommand.execute(GiveCommand.java:128)[16:05:07] [Server thread/WARN]: at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:252)[16:05:07] [Server thread/WARN]: at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)[16:05:07] [Server thread/WARN]: at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:678)[16:05:07] [Server thread/WARN]: at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue.access$000(TimedQueue.java:12)[16:05:07] [Server thread/WARN]: at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue$1.run(TimedQueue.java:154)[16:05:07] [Server thread/WARN]: at net.aufdemrand.denizencore.utilities.scheduling.RepeatingSchedulable.tick(RepeatingSchedulable.java:20)[16:05:07] [Server thread/WARN]: at net.aufdemrand.denizencore.DenizenCore.tick(DenizenCore.java:155)[16:05:07] [Server thread/WARN]: at net.aufdemrand.denizen.Denizen$2.run(Denizen.java:929)[16:05:07] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)[16:05:07] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)[16:05:07] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)[16:05:07] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)[16:05:07] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)[16:05:07] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)[16:05:07] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)`

is there something i missed during this years far away from denizen ?
thanks

**Comment by mcmonkey4eva** [comment]
Make sure you're running latest Denizen developmental builds - http://ci.citizensnpcs.co/job/Denizen_Developmental/

That book error looks like a version related issue (older version of Denizen in use probably)
the prox trigger - it's hard to be sure without seeing a properly pasted script. We recommend you use https://one.denizenscript.com/haste to paste and share scripts.

Also, use https://discord.gg/Q6pZGSR to chat / get help. The github issues page is generally for feature requests or bugs in Denizen.
