### ISSUE TITLE
inject command not executing

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1750]
I've had this script for many months and it just recently stopped working.  On a related note, I had some weird issues with a run command as well.  I had to change the 'definitions:' to 'context:' before it would finally actually run the command so i'm not sure if these issues are related.

https://hastebin.com/exukasalus.scala

As you can see in the debug below, the event triggers it, but it never actually runs.  I tried adding 'path:', but same thing.
https://hastebin.com/eyofominel.scala

Thanks,
Uledrith

**Comment by uledrith** [comment]
if I try typing ```/ex run s@death path:player``` in game, I get this:

[21:02:02 INFO]: +- Executing dCommand: RUN/p@Uledrith ---------+
[21:02:02 INFO]: +> Executing 'RUN': script='DEATH(TASK)'  path='player'
[21:02:02 INFO]:  Starting TimedQueue 'DEATH_FioricetArrangeMary'...
[21:02:02 INFO]:  Queue 'DEATH_FioricetArrangeMary' Executing: INJECT
                   "s@ArmorUnequipSetBonuses"
[21:02:02 INFO]: +- Executing dCommand: INJECT/p@Uledrith ---------+
[21:02:02 INFO]: +> Executing 'INJECT': script='ARMORUNEQUIPSETBONUSES(TASK)'
[21:02:02 INFO]:  Completing queue 'EXCOMMAND_BasenameRoughlySpa' in 0ms.



So it runs the first line of script, but not completely.  running manually like that with debug: true should give me a bunch of errors.

**Comment by mcmonkey4eva** [comment]
Please reopen issue with correct pasted scripts and logs using the standard paste services.

**Comment by uledrith** [comment]
Here are both of the scripts.

https://one.denizenscript.com/haste/47158

**Comment by mcmonkey4eva** [comment]
Did you at anyone point stop to look at the debug or the script or anything and wonder if maybe that injected script that it stops at might be relevant to include in a script paste and debug log?

**Comment by uledrith** [comment]
ooops, sorry for not paying attention to this.  I'll try harder next time :)

that other inject had a "- queue clear" in it........ *slap forehead*
