### ISSUE TITLE
Add spawner data to dItem

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#1751]
I've noticed that I can't copy a customized spawner item in hand. I've simply tried /ex give <pl.item_in_hand> but I got a different item.

Debug log: http://old.mcmonkey.org/paste/47161 Tested on both 1.8 and 1.12.2 versions.
You can see the difference of the spawners when printing the item in json format.

Original spawner: 
![image](https://user-images.githubusercontent.com/8504075/38459081-9c22d786-3aa5-11e8-8043-1945e6f34212.png)

Copied spawner: 
![image](https://user-images.githubusercontent.com/8504075/38459145-69e18596-3aa6-11e8-85c5-cc5c64330070.png)

Also <item.spawner_type> would be useful to look at the spawner type (just like the location tag).

**Comment by mcmonkey4eva** [comment]
That isn't Minecraft data that was lost, that's data from SilkSpawners that was lost. We don't really generically support custom data right now.

Maybe make your own SilkSpawners equiv in Denizen? :D!
