### ISSUE TITLE
Hidden NamePlates become visible after adding/modifying 'scoreboard'

### ISSUE THREAD

**Issue by redshirt2** [DenizenScript/Denizen-For-Bukkit#1752]
Hidden NamePlates/NameTags become visible after adding/modifying 'scoreboard'

After I have picked the NPCs that won't show their nameplates and then start a scoreboard, the hidden nameplates reappear and I'm unable to hide them again.

eg - scoreboard add "viewers:< exampleplayeruuid >" "id:DISPATCH" "obj:<&6>NPCs" "lines:Players Online" "score:<server.list_online_players.size>"

will make the nameplates to reappear.  and I must restart my server to hide them again...

Denizen 290 Citizens 1537

(I can and do use denizen sidebar.  But scoreboard seems more appropriate this time.  And shouldn't we be able to use the minecraft scoreboard, sucky as it is?)

Please and thankyou

**Comment by mcmonkey4eva** [comment]
Scoreboard control in minecraft is very borky.
Nameplates are backed by scoreboards.
Any incompat you accidentally create in the scoreboard system is going to immediately break nameplates set on NPCs.
Note that the Denizen scoreboard command is built with the intent of forcing its way past obstructions - whereas if you just want to cleanly interact with the default scoreboard system, executing the minecraft version of the command will generally make more sense.

**Comment by redshirt2** [comment]
OK.  so I suspect using the minecraft scoreboard technique will also bork the nametags for NPCs with hidden namtags.

How about denizens sidebar?  I am already able to switch sidebars (reconfigure the lines) and not have trouble.  Though, there's the score total that is really quite hard to work with (start, increment)  Is it possible to have Sidebar have a 'setscore' method so I could access and set the score numbers directly rather than using start and increment?

**Comment by mcmonkey4eva** [comment]
I think `lines:...` works for setting the numbers (alongside `values:...` setting the text values)

You cannot hide the numbers on the side, they are a dedicated field of data sent to the client. It's internally a scoreboard ... each line of text is sent as a playername and the number is their score.

**Comment by redshirt2** [comment]
Thank you.  I'll work with native mnecraft scoreboards.  You can close this
