### ISSUE TITLE
Blobs aren't getting applied  (again)

### ISSUE THREAD

**Issue by redshirt2** [DenizenScript/Denizen-For-Bukkit#1754]
Using latest Citizens 1537 and Denizen 290
I understand that one could get a Player or NPC's skin-blob and store it somewhere, like a flag or yaml file, and then using the mech skin_blob to apply to another player entity. I'm sure this worked a while ago, but lost track.  Anyway, it isn't working now...
http://old.mcmonkey.org/paste/47195

Also, here are pastes of my scripts and a couple of blobs with my denizen scripts that show how I save blobs and read them .  I'm not doing anything tough...
http://old.mcmonkey.org/paste/47196
http://old.mcmonkey.org/paste/47197
http://old.mcmonkey.org/paste/47198

**Comment by mcmonkey4eva** [comment]
Check syntax of modern skin_blob mech:
`tex;sig;name`
If you only have the standard `tex;sig`, you need to manually append `;name` to the end.

Also, sent in a commit to remove that weird exception error (was from a typo in the handling of too-short input)

**Comment by redshirt2** [comment]
Thank you! So Before I started to append the ';name' (I assumed a real name and not the word 'name') It all worked anyway.

Do I need?

**Comment by mcmonkey4eva** [comment]
I haven't actually particularly tested how useful that bit of data was, it was included in the skin_blob fixing so... it's nice to have! Better to have too much data than too little, eh?
