### ISSUE TITLE
Player heads bug

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#1755]
Debug log:
http://old.mcmonkey.org/paste/47181#428

The script is showing a player's head in a inventory (menu) which seems to work but gives out an internal error.

**Comment by mcmonkey4eva** [comment]
The error is from a script not visible in debug logs.
Also, you've had so many errors in the current server run (at time of logging) that it autotrimmed that error to a length so short it contains no useful data.
Restart server, figure out the actual source of the error, record proper logs.

**Comment by Mwthorn** [comment]
This debug should show it right http://old.mcmonkey.org/paste/47225
It seems like the bug is actually a player being linked to a new queue is returning null.

**Comment by mcmonkey4eva** [comment]
`
CraftBukkit Version: git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)`

what.

Update.

1.12.2

There is no excuse for old server software.

Also the error is still misrendered, which is generally from java handling too many errors already and giving up on rendering them fully anymore.
