### ISSUE TITLE
suggestion: configurable default color tag

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1756]
Hey!
First off let me show it on a practical example:

`- chat "this is grey text <&o>this is grey-cursiv <&r>this is white now..."`

The goal is to have "this is white now" in default configured, grey text.

For this I suggtest to have a configurable, short color tag (1-2 letters long would be best) to replace the <&r> in the example above.
Such highlighted words in dialogues can be very powerful. But atm i have only 3 options:
- I don't do it
- I use unclean long tags (flags/procs)
- I hardcode the colors (just use <&7> there)

**Comment by mcmonkey4eva** [comment]
I suggest you just hard-code the color of choice.
