### ISSUE TITLE
Custom Potion Color

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1760]
Not sure if this is already implemented in Denizen somehow, but it seems that custom colors for potions is not implemented. I used this vanilla command to give myself a custom colored potion:

```/give @p minecraft:potion 1 0 {CustomPotionEffects:[{Id:4,Amplifier:1,Duration:600},{Id:6,Amplifier:0,Duration:20}],Potion:"minecraft:strength",CustomPotionColor:2228479}```

But when I narrated the item back to me via `/ex narrate <player.item_in_hand>`, nothing about the potion's custom color showed up.

The NBT tag relevant is `CustomPotionColor`. It looks like this particular Spigot method is useful: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/PotionMeta.html#getColor--

**Comment by mcmonkey4eva** [comment]
Apparently this was added in 1.9 ish as a new option. Would be good to add explicit support for this.

**Comment by mcmonkey4eva** [comment]
added in latest dev build
