### ISSUE TITLE
on chat events, determine cancelled

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1762]
Hello, the determine cancelled event here is not detected by DiscordSRV, I don't know what I have do wrong here
https://pastebin.com/YSfRnmkU
And on discord : 
![image](https://user-images.githubusercontent.com/20723083/40629857-2fd0dab4-62ce-11e8-848f-cb7d9784ee26.png)

**Comment by Noiknez** [comment]
@Mwthorn I would like to but there is only dev build

**Comment by mcmonkey4eva** [comment]
Use dDiscordBot https://github.com/DenizenScript/dDiscordBot

Don't be the kind of noob that gets scared by phrases like "dev build" or "current patch" or "latest revision" or any other words like that.
