### ISSUE TITLE
async chat event

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1763]
This is a continuation for the closes issue https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1762

![image](https://user-images.githubusercontent.com/20723083/40677721-bacb5dbe-637e-11e8-9246-cac69a02cedd.png)

**Comment by Noiknez** [comment]
🤔 
![image](https://user-images.githubusercontent.com/20723083/40677956-7497eece-637f-11e8-9bc8-5a3549b4713d.png)

**Comment by mcmonkey4eva** [comment]
What is this issue post meant to be

Denizen strongly discourages the async event as it is dangerous.
Other plugins might use the async event without an option to switch to sync if they were written by dumb people.
If you want a 100% Denizen compatible guaranteed Discord bot, use https://github.com/DenizenScript/dDiscordBot
