### ISSUE TITLE
Player bed spawn returning null while online

### ISSUE THREAD

**Issue by Morphan1** [DenizenScript/Denizen-For-Bukkit#1765]
What the title says, `<player.bed_spawn>` returns `null` when the player is online. When they're offline, it fills perfectly fine.

**Comment by mcmonkey4eva** [comment]
Are you sure it's `null`, not an error (EG a tag timeout)?
A tag timeout is possible from that tag - it may cause the relevant chunk to be loaded in, which in some cases causes tag timeout fails (if tag timeouts are enabled, chunk loading can freeze).

**Comment by Morphan1** [comment]
I didn't have debug on at the time, but the response seemed instant. Strangely, I just tested it with myself and it seemed to work fine, even when I was in an entirely different world. Though, online returned the space above the bed and offline returned the bed block itself, but I'm sure the former is intentional.

I'll try it again when people get on the server.

**Comment by mcmonkey4eva** [comment]
It's a duration input - `10` means 10 seconds by default in a duration input.

**Comment by Morphan1** [comment]
Finally got around to testing this

```
>ex narrate <p@REDACTED.bed_spawn>
[22:52:55 INFO]: Executing dCommand... to see debug, use /denizen debug
[22:52:55 INFO]: l@2912.0,72.0,-761.0,world2
[22:54:13 INFO]: UUID of player REDACTED is REDACTED
[22:54:14 INFO]: REDACTED logged in with entity id 61 at ([world2]2990.126190331613, 63.0, -714.9246535837625)
>denizen debug
[22:54:48 INFO]: Denizen dBugger is now: ENABLED
>ex narrate <p@REDACTED.bed_spawn>
[22:54:49 INFO]: Executing dCommand... check the console for debug output!
[22:54:49 INFO]:  Starting InstantQueue 'EXCOMMAND_DeutschLampsGuess'...
[22:54:49 INFO]:  Queue 'EXCOMMAND_DeutschLampsGuess' Executing: NARRATE
                   "<p@REDACTED.bed_spawn>"
[22:54:49 INFO]: +- Executing dCommand: NARRATE ---------+
[22:54:49 INFO]:  Filled tag <p@REDACTED.bed_spawn> with 'null'.
[22:54:49 INFO]:  ERROR! Tag <p@REDACTED.bed_spawn> is invalid!
[22:54:49 INFO]: +> Executing 'NARRATE': Narrating='null'  Targets='null'
[22:54:49 INFO]: null
[22:54:49 INFO]:  Completing queue 'EXCOMMAND_DeutschLampsGuess' in 5ms.
```

As you can see, they were offline and the narration worked fine. As soon as they came online, however, it stopped functioning. The name is typed correctly, and the bed works just fine for them. No clue as to what the problem is here.

**Comment by mcmonkey4eva** [comment]
Options for what caused that to fail are:
- Outdated/broken Denizen build
- Issue in Bukkit
- Damaged world management (`world2` got unloaded for some reason or something like that)
- Offline mode server

**Comment by BloodEko** [comment]
For me, <pl.bed_spawn> works. Actually I found out: when somebody breaks the bed, it becomes null

**Comment by Morphan1** [comment]
I'm using dev build 297, which isn't terribly far behind. I'll update anyway. As for the latter two, the only world loaded is `world2` and I'd never switch to offline mode.

As a side note:
```
>ex narrate <server.flag[invincidogs].as_list.parse[as_entity]>
[01:54:28 INFO]: Executing dCommand... check the console for debug output!
[01:54:28 INFO]:  Starting InstantQueue 'EXCOMMAND_ByeLoudMarble'...
[01:54:28 INFO]:  Queue 'EXCOMMAND_ByeLoudMarble' Executing: NARRATE
                   "<server.flag[invincidogs].as_list.parse[as_entity]>"
[01:54:28 INFO]: +- Executing dCommand: NARRATE ---------+
[01:54:28 INFO]: +> [Denizen] valueOf dEntity returning null:
                   e75f8722-efda-4ae2-a12b-b854342a5a99
[01:54:28 INFO]:  ERROR! 'e75f8722-efda-4ae2-a12b-b854342a5a99' is an invalid
                   dEntity!
[01:54:28 INFO]:  Unfilled attributes '[as_entity]' for tag <as_entity>!

...

[01:54:28 INFO]:  Filled tag
                   <server.flag[invincidogs].as_list.parse[as_entity]> with
                   'li@null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null|null'.
```
...maybe there was a dcore tag parsing issue in this build

**Comment by mcmonkey4eva** [comment]
I think that's roughly expected for a list of invalid uuids.

**Comment by Morphan1** [comment]
I'll check that at some point.

Also, for the other thing: most of the UUIDs weren't invalid. A few were in an unloaded world and probably couldn't be reached, that's reasonable, but for example doing `<server.flag[invincidogs].as_list.separated_by[|e@].as_list.filter[is_spawned].parse[name]>` worked fine (minus the first one in the list, of course).
Weird 💩 goin' on.

**Comment by mcmonkey4eva** [comment]
Oh yeah, build DEV-313 patches that.
`as_entity` was failing because you had literally a list of UUIDs, and `dEntity.valueOf` doesn't accept that - it only accepts `e@UUID`. Patch makes it no longer demand an `e@` prefix

**Comment by Morphan1** [comment]
So... I've updated Spigot, updated Denizen, and the bed spawn bug still exists. NBT file seems fine for the player... Maybe it's a Spigot bug.

![image](https://user-images.githubusercontent.com/4834997/41271632-ac459a82-6ddf-11e8-8144-423792447cb5.png)

**Comment by mcmonkey4eva** [comment]
My Spigot build is slightly outdated but https://i.imgur.com/W7DgRCY.png
![TagTest](https://i.imgur.com/W7DgRCY.png)

**Comment by mcmonkey4eva** [comment]
Have you verified (since you stripped them from your posting) that the UUID that you're trying to read a bed_spawn for while offline exactly matches the UUID seen while online?

**Comment by Morphan1** [comment]
It's using the tag when the player is online that's the problem

**Comment by mcmonkey4eva** [comment]
Oh... I had that backwards, woops! That's a lot more complicated code then.
```java
    public Location getBedSpawnLocation() {
        World world = this.getServer().getWorld(this.getHandle().spawnWorld);
        BlockPosition bed = this.getHandle().getBed(); // returns "this.d", direct field read
        if (world != null && bed != null) {
            bed = EntityHuman.getBed(((CraftWorld)world).getHandle(), bed, this.getHandle().isRespawnForced()); // RespawnForced returns NBT value "SpawnForced" as boolean
            if (bed != null) {
                return new Location(world, (double)bed.getX(), (double)bed.getY(), (double)bed.getZ());
            }
        }

        return null;
    }
```
and EntityHuman portion:
```java
    @Nullable
    public static BlockPosition getBed(World world, BlockPosition blockposition, boolean flag) {
        net.minecraft.server.v1_12_R1.Block block = world.getType(blockposition).getBlock();
        if (block != Blocks.BED) {
            if (!flag) {
                return null;
            } else {
                boolean flag1 = block.d();
                boolean flag2 = world.getType(blockposition.up()).getBlock().d();
                return flag1 && flag2 ? blockposition : null;
            }
        } else {
            return BlockBed.a(world, blockposition, 0);
        }
    }

```

That actually verifies that the block is validly a bed

**Comment by mcmonkey4eva** [comment]
Works while online for me still tho: https://i.imgur.com/BguSauC.png
![TagOutp](https://i.imgur.com/BguSauC.png)
The location is for whatever reason 1 block off on the X axis, here is screenshot of me standing at the bed_spawn location: https://i.imgur.com/RbUhVuc.png
![Bed](https://i.imgur.com/RbUhVuc.png)
But the offline value of a genuine bed spawn is different from that: https://i.imgur.com/zBOdyAT.png
![Offline](https://i.imgur.com/zBOdyAT.png)

Not particularly sure why it seems to be offset by 1 on x and 1 on z

**Comment by mcmonkey4eva** [comment]
I imagine that latter bit is caused by BlockBed.a:
```java

    @Nullable
    public static BlockPosition a(World var0, BlockPosition var1, int var2) {
        EnumDirection var3 = (EnumDirection)var0.getType(var1).get(FACING);
        int var4 = var1.getX();
        int var5 = var1.getY();
        int var6 = var1.getZ();

        for(int var7 = 0; var7 <= 1; ++var7) {
            int var8 = var4 - var3.getAdjacentX() * var7 - 1;
            int var9 = var6 - var3.getAdjacentZ() * var7 - 1;
            int var10 = var8 + 2;
            int var11 = var9 + 2;

            for(int var12 = var8; var12 <= var10; ++var12) {
                for(int var13 = var9; var13 <= var11; ++var13) {
                    BlockPosition var14 = new BlockPosition(var12, var5, var13);
                    if (b(var0, var14)) {
                        if (var2 <= 0) {
                            return var14;
                        }

                        --var2;
                    }
                }
            }
        }

        return null;
    }
```
Whatever that is... is probably mis-implemented.
Should not induce the error you have, though.

**Comment by Morphan1** [comment]
Yeah, as I mentioned at some point before: when I tested it on myself with a brand new bed, I was getting the actual bed block while I was offline but the block above it for some reason when I was online. It *was* actually returning something during that for me, which is super strange. Perhaps something was setting the forced respawn flag? Possibly a difference between creative and survival? 🤷‍♂️ This whole thing is weird

**Comment by mergu** [comment]
Seems to be working fine on latest

**Comment by mcmonkey4eva** [comment]
@Morphan1 does this still occur? It probably is/was a Spigot bug either way...
If it still occurs, probably would be something to report to spigot.
