### ISSUE TITLE
Cant give armor to specified slot

### ISSUE THREAD

**Issue by zozer** [DenizenScript/Denizen-For-Bukkit#1768]
Im trying to give armor by its slot number (such as boots to slot 37), however it says that "The inventory didn't have enough space, the rest of the items have been placed on the floor"

http://old.mcmonkey.org/paste/47837

(im using the latest denizen developmental version)

**Comment by SXRWahrheit** [comment]
As a counterpoint, "ex give diamond_sword quantity:1 slot:37" works fine for me on build 300.

**Comment by zozer** [comment]
I am specifically talking about armor, as seen by the debug the give command clearly works, it just for some reason detecting that the armor slot is full when its not

**Comment by SXRWahrheit** [comment]
"ex give diamond_boots quantity:1 slot:37"

![2018-06-12_10 58 01](https://user-images.githubusercontent.com/774463/41302203-83fac76e-6e2f-11e8-95c3-bf9e5855d293.png)

**Comment by zozer** [comment]
Ok, well something clearly changed between build 300 and build 315, but as of build 315 that does not work

**Comment by mcmonkey4eva** [comment]
If it is broken suddenly in a way it wasn't before, that needs fixing.
But also, equip command exists y'know https://one.denizenscript.com/denizen/cmds/equip

**Comment by SXRWahrheit** [comment]
Does this still occur on the latest build?

**Comment by mergu** [comment]
Yes, issue occurs on latest:
```[18:41:42 INFO]: Mergu issued server command: /ex give gold_boots q:1 slot:37
[18:41:42 INFO]:  Starting InstantQueue 'EXCOMMAND_PondGordonNodes'...
[18:41:42 INFO]:  Queue 'EXCOMMAND_PondGordonNodes' Executing: GIVE "gold_boots" "q:1" "slot:37"
[18:41:42 INFO]: +- Executing dCommand: GIVE/p@Mergu ---------+
[18:41:42 INFO]: +> Executing 'GIVE': Type='ITEM'  inventory='in@player[holder=p@4f1e61de-6f0c-46aa-8c26-52354c4bd9cc]'  Quantity='1.0'
                   engrave='false'  unlimit_stack_size='false'  Items='[i@gold_boots]'  slot='37'
[18:41:42 INFO]:  The inventory didn't have enough space, the rest of the items have been placed on the floor.
[18:41:42 INFO]:  Completing queue 'EXCOMMAND_PondGordonNodes' in 20ms.
```

**Comment by mcmonkey4eva** [comment]
Equipment slots are not considered part of the inventory anymore.
Use the equip command.
