### ISSUE TITLE
The "on player completes advancement " not working anymore!

### ISSUE THREAD

**Issue by ColonelOverspel** [DenizenScript/Denizen-For-Bukkit#1773]
Denizen doesn't seem to register the completion of an advancement. I wanted to use advancements and Denizen to create a way of preventing the player from opening his own inventory.

**Comment by ColonelOverspel** [comment]
Hmmm it is a bug, but I think the inventory stuff will not work. The event is not cancellable (sadly).

**Comment by mcmonkey4eva** [comment]
Completes advancement is not cancellable.
Might be able to add a separate mechanism to revoke an advancement, which would be useful there.
I'm assuming your idea is listening to the opens-inventory advancement, revoke the advancement and forceclose their inventory?

**Comment by mcmonkey4eva** [comment]
believe this was fixed via discord chatter
