### ISSUE TITLE
EXECUTE Command issues

### ISSUE THREAD

**Issue by MithrandirCraft** [DenizenScript/Denizen-For-Bukkit#1775]
Denizen v.1.0.2 SNAPSHOT b1641
Spigot for MC 1.12.2

Hi, I'm kinda new to Denizen, however, I encountered an issue when attempting to create scripts containing the EXECUTE command as a on click action.

This would be the script: https://hastebin.com/vemofaripe.scala
This is the console output (And I don't get teleported): https://hastebin.com/hocivasizo.md
It seems like the player tag is being substituded by an uuid instead of my actual player name. Which renders the command useless.

**Comment by MithrandirCraft** [comment]
Ok, I found out by testing that <player.name> works better for this xD

**Comment by MithrandirCraft** [comment]
However, In these situations: 
https://hastebin.com/qicozakexi.scala
https://hastebin.com/icemiruwim.scala

The player is not sent to another server, and the command is not recognized. Even though it clearly works.

**Comment by SXRWahrheit** [comment]
`<player.name>` returns the player's name. If you use a `narrate` command, you will see what `<player>` returns. When in doubt, narrate your tags to ensure the variables are parsing correctly.

I'm not sure whether `asserver` is an accepted value, but the suggested form of that is `as_server`.

**Comment by SXRWahrheit** [comment]
You will need to provide server logs - and ideally Denizen debug output - in order for us to help you more quickly. Again, you should also `narrate` the output of the variables you're trying to parse to ensure they're parsing properly.

**Comment by MithrandirCraft** [comment]
https://hastebin.com/ifemabuyix.scala

**Comment by mcmonkey4eva** [comment]
Do not use `execute` for basic commands like that.
There's a `teleport` command for teleporting.

Also:
Bungee does not exist on the Spigot server (it exists as a layer between client and server).
To functionally interact with it from the server, you'll need Depenizen configured for bungee usage https://github.com/DenizenScript/Depenizen

**Comment by MithrandirCraft** [comment]
Ok @mcmonkey4eva, teleporting wasn't my intention anyway. Sorry for spamming with multiple issues.
What I want, is to use citizens as a hub teleportation system towards the network's servers, as you may imagine
I just noticed what you commented about bungee myself, however, I was thinking maybe an npc could do it, since I can send any player to another server while ingame.

I'll try using Depenizen as you suggested. Thanks for the help :)

**Comment by SXRWahrheit** [comment]
@MithrandirCraft You can also join the Denizen discord if you just want help working on your scripts:

https://discord.gg/Q6pZGSR
