### ISSUE TITLE
bug: crafting determination

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1777]
When I use a shift-click in the crafting menu, to craft the item instant multiple times, then the determination is only applied to 1 item, instead to all.

So here i.e. I get 1 custom sword and the rest as default swords.
```
on player crafts wood_sword:
- determine <proc[173item].context[hSchwert]>
```

**Comment by MrMaleficus** [comment]
Confirmed

**Comment by mcmonkey4eva** [comment]
You might want to also alter the recipe formed event.
If it still has the issue with both events modified, it's likely an issue with Spigot itself.
If this involves item-script items, see also #1851

**Comment by mcmonkey4eva** [comment]
Use item scripts for this, per the resolution to #1851
