### ISSUE TITLE
Message Constructor Library issue

### ISSUE THREAD

**Issue by adamlaughlin** [DenizenScript/Denizen-For-Bukkit#1780]
My RAM is getting eaten up by queues created during a failed update check in MCL.  I'm too busy to learn any code related to Denizen at the moment so I just deleted MCL_Events and moved on WML.  For anyone who wants to fix it:

https://one.denizenscript.com/paste/48117

**MCL Problem begins at line 646 of paste, top part is unrelated Depenizen issue**

**Comment by mcmonkey4eva** [comment]
Latest dev builds are highly experimental and feature a lot of issues. If you don't want to deal with those issues, uses latest main build from http://ci.citizensnpcs.co/job/Denizen/
if you'd like to help with fixing the experimental new dev version, chat with us on discord https://discord.gg/Q6pZGSR
