### ISSUE TITLE
suggestion: bed_color tag

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1781]
The new beds have colors, which aren't detected by `.material`
They work exactly like the base colors of the Banner block, where we have the `.base_color` tag.

Either `.base_color` could be advanced by a else-if to work also for beds, or a own tag, like `.bed_color`.

**Comment by mcmonkey4eva** [comment]
added dmaterials for this in latest dev build (so you can do `RED_BED` and `BLUE_BED` and etc as material names)
