### ISSUE TITLE
proximity script exception

### ISSUE THREAD

**Issue by adamlaughlin** [DenizenScript/Denizen-For-Bukkit#1782]
getting an exception repeatedly while standing next to the good judge:

`30.06 00:10:53 [Server] WARN [Denizen] Task #85 for Denizen v1.0.2-SNAPSHOT (build 342) generated an exception 30.06 00:10:53 [Server] INFO java.lang.NoClassDefFoundError: net/aufdemrand/denizen/scripts/containers/core/InteractScriptHelper 30.06 00:10:53 [Server] INFO at net.aufdemrand.denizen.objects.dNPC.getInteractScriptQuietly(dNPC.java:235) ~[?:?] 30.06 00:10:53 [Server] INFO at net.aufdemrand.denizen.scripts.triggers.core.ProximityTrigger$1.run(ProximityTrigger.java:219) ~[?:?] 30.06 00:10:53 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1470] 30.06 00:10:53 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) [patched_1.12.2.jar:git-Paper-1470] 30.06 00:10:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1470] 30.06 00:10:53 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1470] 30.06 00:10:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1470] 30.06 00:10:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1470] 30.06 00:10:53 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]30.06 00:10:53 [Server] WARN [Denizen] Task #85 for Denizen v1.0.2-SNAPSHOT (build 342) generated an exception 30.06 00:10:53 [Server] INFO java.lang.NoClassDefFoundError: net/aufdemrand/denizen/scripts/containers/core/InteractScriptHelper 30.06 00:10:53 [Server] INFO at net.aufdemrand.denizen.objects.dNPC.getInteractScriptQuietly(dNPC.java:235) ~[?:?] 30.06 00:10:53 [Server] INFO at net.aufdemrand.denizen.scripts.triggers.core.ProximityTrigger$1.run(ProximityTrigger.java:219) ~[?:?] 30.06 00:10:53 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1470] 30.06 00:10:53 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) [patched_1.12.2.jar:git-Paper-1470] 30.06 00:10:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1470] 30.06 00:10:53 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1470] 30.06 00:10:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1470] 30.06 00:10:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1470] 30.06 00:10:53 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]`

and here is the proximity trigger:
`
npc_judge_interact:
    type: interact
    debug: false
    steps:
        #Step one will contain a dialogue tree only heard by players at rank default.
        1:
            proximity trigger:
                entry:
                    script:
                    #Set chat window headers
                    - flag player 'chat_header1:<gold>Cato the Younger'
                    - flag player 'chat_header2:<aqua>Provincial Judge'
                    
                    - flag player 'chat_entries:Welcome to <green>Legitimus<white>, <gold><player.name><white>! Everyone has been informed of your arrival, and we are glad you have chosen to visit our province.|We need you to agree to our laws before you will be issued a <green>Visa<white> for travelling beyond the capitol.|Are you ready to take your oaths? We should only need five minutes. Have a seat, if you like.|<proc[msgChat].context[<&e>Yes|oaths|Proceed with oaths]>|<proc[msgChat].context[<&e>No|I would like to look around more.|Wait until later]>|<proc[msgHover].context[Explanation|A brief tutorial on our rules grants permission to use plugins. The guards will kill anyone else who tries to leave the Capitol.]>'
                    - execute as_player "paginate 1"
                move:
                    script:
                    - look <npc> <player.location>
                exit:
                    script:
                    - flag player 'chat_entries:Leaving already? Your immigration is not yet complete. You may return to our courthouse later to finish.'
                    - execute as_player "paginate 1"
                    - flag player 'chat_entries:!'
                    - flag player 'chat_header1:!'
                    - flag player 'chat_header2:!'`

also here is the proxy from step 2, I can't remember which one my player is on.

`
        2:
            proximity trigger:
                entry:
                    script:
                    - if !<player.in_group[players]> {
                        - zap 1
                    }
                    - flag player 'chat_header1:<gold>Cato the Younger'
                    - flag player 'chat_header2:<aqua>Provincial Judge'
                    - flag player 'chat_entries:Welcome to back, <gold><player.name><white>! Is there anything you would like to see me about?|<proc[msgChat].context[<&e>Ticket|ticket|Cato will help you open a ticket for staff to read.]>|<proc[msgChat].context[<&e>Rules|rule|Cato is a good person to ask about this.]>|<proc[msgChat].context[<&e>Nevermind|nevermind|Talk another time.]>'
                    - execute as_player "paginate 1"
                move:
                    script:
                    - look <npc> <player.location>
                exit:
                    script:
                    - flag player 'chat_entries:Have a nice day!'
                    - execute as_player "paginate 1"
                    - flag player 'chat_entries:!'
                    - flag player 'chat_header1:!'
                    - flag player 'chat_header2:!'
`

**Comment by mcmonkey4eva** [comment]
Use latest dev build http://ci.citizensnpcs.co/job/Denizen_Developmental/
or latest non-dev build http://ci.citizensnpcs.co/job/Denizen/
As I said in your issue yesterday, that build doesn't work https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1780
