### ISSUE TITLE
Experience Set only can do two things

### ISSUE THREAD

**Issue by Rickytehduck** [DenizenScript/Denizen-For-Bukkit#1784]
Dev Build: 385
The experience command has an option, set, and can only accept values between 0.0 and 1.0.
Setting xp to 0 and 1 work, (filling and emptying the experience bar) as expected, but values between those two like 0.4 do nothing. (Denizen seems to see those values as just 0)

![image](https://user-images.githubusercontent.com/5568932/42406926-347a82c2-81f5-11e8-9fab-c5da3e534a93.png)

**Comment by mcmonkey4eva** [comment]
I reworked the command to just properly call the Spigot API instead of all the weird nonsense it has.

Input is an integer for all values. `experience set 5` will set the player to have exactly 5 xp total.
