### ISSUE TITLE
suggestion: - inject improvement

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1785]
```
checkMoney:
- if <player.flag[money]> < <def[1]> {
  - narrate "not enough money!"
  - queue clear
  }
checkSpace:
- if <player.inventory.empty_slots> < <def[1]> {
  - narrate "not enough space!"
  - queue clear
  }
```
```
  - inject Util path:checkMoney def:20
  - inject Util path:checkSpace def:1
```

What do you think about the idea, to give a def: argument to the inject command ? 
To give it functionality to more method-like calls.

It would just create definitions named 1,2,3,4... like the run command, but in the injected queue.
So for the example above, it would fill 1 with '20', do checks , then override 1 with '5', do checks.

**Comment by Morphan1** [comment]
And what would happen to the definitions in the remaining non-injected queue? I think this could end up making unclear code.

**Comment by BloodEko** [comment]
Can you give an example how you think of unclear code?

**Comment by mcmonkey4eva** [comment]
The inject command injects commands into the current queue and is used primarily as a formatting/organization improvement tool. It's directly equivalent to copy/pasting a section code right on in.

The run command is when you want to 'call a method' (as you mentioned on Discord as being what you wanted). It is capable of *more* than what most languages (C/Java/C#/etc) can achieve with a method call, so I have no idea what the issue there is. You can pass in arguments, you can read return values (as many as you wish, not even just one as some langs like Java limit you to), you can scrub data from how it processed even if it wasn't meant to be returned (which most langs don't have), you can analyze how it processed (usually very limited in most langs) including timing details and whatever else, you can wait for the method to run even if the method slow-processes (meaning: the wait command is used inside the script being run) without in any way messing up your own script (impossible in most langs. Somewhat possible in modern C# using async keywords everywhere).

Procedure tags are handy for in-line method calls to grab a bit of data as well.

Your request makes no sense...

Conceptually, it's trying to use the 'inject' command as though it's just the 'run' command with the original queue up-ref'd... which you can replicate already by just passing the queue in as a def
`run <script> path:checkMoney def:20`
and in `checkMoney`, just do `- queue <def[1]> clear`

Implementation-wise, it's making the inject command arbitrarily fill its own current queue up with definitions in a way that is not at all visibly clear with its effects. If you see `- inject npc_chatter def:a|b|c path:speako` in the middle of a script, you're not at all expecting that a later read of `<def[3]>` within the same script section now returns `c`, as that's weird and unreasonable. That was just an argument to some random other piece of script section ... why is it now altering the current script?

**Comment by BloodEko** [comment]
Thanks for your detailed answer!
So one of these 2 options will make it then. (even if the syntax is bit clunky)
```
- define money 20
- inject Util path:checkMoney

- ~run Util path:checkMoney def:<queue>|20
```
Inject feels bit like a method call without arguments, and run rather feels like starting a new Thread, but with arguments.

**Comment by mcmonkey4eva** [comment]
inject may "feel" like a method call to you, but it is absolutely not that.

**Comment by mcmonkey4eva** [comment]
In fact the ability of the inject command to end the calling queue is something non-existent in methods calls in common langs (C/Java/C#/etc)

**Comment by BloodEko** [comment]
Is not `Thread.sleep()` in Java exactly that  ?

**Comment by mcmonkey4eva** [comment]
Not even close no

**Comment by Morphan1** [comment]
And to add on, the run command most certainly is not anything like starting a new Thread. Yes, we use a prominent "queue" system to handle sandboxing pieces of code, but they are in no way a

**Comment by mcmonkey4eva** [comment]
Threads are a much more complicated and involved concept.

And I thought you meant the sleep comment in related to inject command ending the calling queue.
It is closer to the wait command but... also not quite the same, again for reasons relating to threading be a much more complicated and involved concept.
