### ISSUE TITLE
1.13 Update

### ISSUE THREAD

**Issue by Morphan1** [DenizenScript/Denizen-For-Bukkit#1788]
Due to the large amount of changes in the Minecraft 1.13 update, I've decided to drop a list of what I noticed needs to be looked at and/or worked on. Current progress can be found [here](/mcmonkey4eva/Denizen).

- [x] Material ID management - Spigot seems to supply possible options to maintain backwards compatibility (such as, we could theoretically loop through legacy materials and check for a specific ID) but we should probably try to figure out a way to handle the new systems instead. The following features need to be updated for this:
  - [x] BlockHelper get/setFlowerpotContents
  - [x] The BlockData interface and implementation, along with BlockHelper getBlockData
  - [x] ~~A lot of stuff in the non-NMS plugin. You can just attempt to compile right now and see the list.~~<br>It compiles now.
    - [x] dMaterial valueOf - should we bother keeping integer ID compatibility?
    - [x] dItem valueOf - same as above
    - [x] dMaterial isStructure - I don't understand the implementation of this.
    - [x] dEntity spawnAt - switched portal checks to weirder portal checks...
    - [x] PlayerEditsBookScriptEvent - better method of checking material?
    - [x] LeashCommand - better method of checking material?
    - [x] BlockPhysicsScriptEvent - better method of checking material?
    - [x] SwitchCommand - better method of checking material? also, does this command still work?
    - [x] ItemBaseColor and ItemPatterns properties - is there a better way?
    - [x] Utilities choose/setSignRotation - better method of checking material?
    - [x] ItemChangeMessage - stained glass pane mess, better method?
    - [x] FireworkBurstsScriptEvent - better method of making a firework?
    - [x] EntityFirework - same as burst event
    - [x] ~~ItemListenerInstance listenItem - better method? also, should we even keep any of this? does it even work???~~ ListenCommand has been removed.
    - [x] PathBlockExaminer - ........
    - [x] SignCommand - make sure any of that works, maybe a better method?
    - [x] BookScriptContainer writeBookTo - handle signed book material better?
    - [x] dLocation switched tag - switched doors check to weirder doors check, need to confirm this works and maybe use less hacky methods??
    - [x] dLocation command_block_name/command_block tags/mechanisms - better way to make the check?
    - [x] dLocation block_type mechanism - check if it works, maybe use a better method??
    - [x] ModifyBlockCommand setBlock - check if it works, maybe use a better method??
    - [x] CopyBlockCommand - check if it works, maybe use a better method??
    - [x] dLocation furnace_burn_time/furnace_cook_time mechanisms - same as command blocks
    - [x] dItem constructors - ItemStacks no longer support integer id construction, should we find a workaround? goes back to whether we want to keep silly compatibility
    - [x] dItem identifySimple/identifyNoIdentifier/identifySimpleNoIdentifier - weird check, I switched it from `item.getTypeId()` to `item.getType().getId()` for now but... should it just be re-done??
    - [x] ProjectileHitScriptEvent - same weird id check
    - [x] dItem id tag - changed to same method as the weird checks above, but should we still allow this tag?
    - [x] TakeCommand - ITEMINHAND case used `ItemStack newHandItem = new ItemStack(0);` ??? switched to Material.AIR, does this even work?

- [x] BlockHelper setPlayerProfile - skull types no longer handled by the tile entity, they're handled as actual block types. Should we bother updating the block to a player skull here?
- [ ] BlockHelper isSafeBlock - I've been told that Bukkit's modern material.isSolid() is reliable so I just switched it to that. Needs proper testing/confirmation
- [x] ChunkHelper getHeightMap - chunks now have multiple height maps for various purposes.
- [x] SoundHelper - do the 1.12 midi patches still work in 1.13?
- [x] Effect/Particle system - we should really probably switch over to the class-based system for effect data, rather than using ints
- [x] PacketOutTradeList - is the serialization still functional? need to re-find the internal code for it and double check. It's probably fine, but they switched custom payloads from "MC|x" to "minecraft:x_ish" so can't hurt to check rest of the implementation.
- [x] BiomeNMS getSpawnableEntities - `String n` was set to the "minecraft" part of "minecraft:entity_name" in 1.12, I switched it to the "entity_name" part. Need to make sure that system actually works (also check 1.11 implementation of it)

- [x] PlayEffectCommand - iconcrack/blockcrack/blockdust systems have changed.

1.13.1:

- [x] ItemPotion property - Bukkit's PotionEffect class no longer uses colors at all

**Comment by Morphan1** [comment]
Updated the main post for plugin side of things. I guess I basically just marked everything I changed as "needs testing" or beyond

**Comment by mcmonkey4eva** [comment]
for material number IDs: We've been telling people to not use those for quite a while now, but a lot of people still do, so I'd say output some error messages whenever those are used warning people to change, and remove it fully in the future.

**Comment by mcmonkey4eva** [comment]
You have changes like:
````diff
-                    if (block.getTypeId() != 0) {
+                    // TODO: 1.13 - ???
+                    if (block.getType().getId() != 0) {
```
Uh... that's literally just an air check. It shouldn't be using the number ID there. Surely `Material.AIR` is still valid across both 1.13 and older versions? If not, a reusable method for `isAir` would work

**Comment by mcmonkey4eva** [comment]
Also we should probably delete all the old listener code at this point

**Comment by MusicScore** [comment]
Morphan told me to do this, don't hurt me

- The `switch` command doesn't seem to toggle anything.<br>Debug: http://old.mcmonkey.org/paste/48664
- Holding a patterned banner in hand and using `<i@item.base_color>` returns a null. However, `<i@item.patterns>` still works.<br>Debug: http://old.mcmonkey.org/paste/48656
- A banner with no patterns or any shield (patterned or otherwise) does not return values properly.<br>Debug for a blank white banner: http://old.mcmonkey.org/paste/48658<br>Debug for a patterned shield: http://old.mcmonkey.org/paste/48659<br>Debug for a blank shield: http://old.mcmonkey.org/paste/48660
- Using the sign command and excluding the direction argument seems to produce strange results.<br>Debug: http://old.mcmonkey.org/paste/48661<br>Screenshot: https://i.imgur.com/P2xC7Y0.png<br>(Note: I ran the command standing near the blocks indicated by the screenshot)
- It looks like the firework_rocket item isn't recognized. It returns as "i@air". The entity appears to be fine though.<br>Debug for the FireworkBursts event: http://old.mcmonkey.org/paste/48662
- `<l@location.switched>` always returns false.
- `command_block` and `command_block_name` tags and mechanisms seem to work perfectly fine.
- `furnace_cook_time` and `furnace_burn_time` tags and mechanisms seem to work.
- The ProjectileHit event seems to work fine.<br>Debug: http://old.mcmonkey.org/paste/48663
- `- take iteminhand quantity:<#>` seems to work.<br>Debug: http://old.mcmonkey.org/paste/48665
- The `midi` command seems to still work. However, I did not create a MIDI with an entire range of notes to test. I just used the default, provided `Denizen.mid` file.<br>Debug: http://old.mcmonkey.org/paste/48666

From my own tests, the following seems to be Spigot issues:
- It seems that the writable_book and written_book items are just completely unusable. The PlayerEditsBook event, by extension, does not fire.
- Banners and shields are not properly implemented. Many inventory actions/events involving banners throws a heavy amount of Spigot-related errors.

**Comment by mcmonkey4eva** [comment]
Dev build line at http://ci.citizensnpcs.co/job/Denizen_Developmental/ starting with **build 394** are now using 1.13 initial-update code.

**Absolutely do not** put these dev builds on your main servers, they are not yet stable or even fully functional.

Those interested in testing:
- We need testing on 1.13 as described in the posts above
- We need testing of the current builds on OLDER MINECRAFT VERSIONS (**especially 1.12.2**) as well! We need to make sure newer builds won't break older servers! The 1.13 release changed a lot of things in Bukkit/Spigot, and there's a risk of damaging old minecraft versions from updating.

**Comment by Rickytehduck** [comment]
Here's some of my findings to corroborate suspic's:
**Commands**
- `midi`: seems completely functional. I tested a variety of midis and I didn't hear anything out of place.
- `switch`: is broken. Returns no errors but doesn't function.
- `sign`: if no sign direction is specified, existing floor signs will have their direction changed to south, even if type is automatic.
 It actually seems like direction doesn't work at all- https://one.denizenscript.com/paste/48678
 For regular signs, it simply defaults to south, for wall signs, it returns the above error.
- `copyblock`: Seems to work fine. Tested with chests, furnaces, command blocks, banners, some rotated blocks.
- 'take': `take iteminhand` seems to work fine

**Tags**
- `<l@location.switched>`: returns false in pretty much all configurations. However, it will return true if a lever is on and facing WEST.
- `<b@biome.spawnable_entities>`: returns an empty list, li@

**Mechanisms**
- `block_type`: appears to work fine, tested with new 1.13 blocks. Also still works with block ids.

That's all I tested so far- I'm not 100% on how to use the new block particle in Denizen.

**Comment by mcmonkey4eva** [comment]
map items - including vanilla gotten ones - are considered `air` apparently in Denizen. Narrating the item will just say `i@air`.

**Comment by Fortifier42** [comment]
Tab complete in Command Script containers no longer works with new update. Nil functionality.

**Comment by MusicScore** [comment]
Maybe we can have a new mechanism for locations/materials, like `blockdata=rotation/east|waterlogged/true|...`

**Comment by mergu** [comment]
Seems all events that required packet interception aren't working. This includes PlayerReceivesMessage

**Comment by Morphan1** [comment]
Updated main post for 1.13.1

**Comment by WaterQuarks** [comment]
Fishing event doesn't fire -> https://one.denizenscript.com/haste/49762

**Comment by mcmonkey4eva** [comment]
`schematic` command borkish with save/load sequence, not sure exactly where it's going wrong but loading it in gives a `null` material value resulting from `dMaterial.getLegacyMaterial(blocks[index])`... since schematics save/load with short-integer id's, it's likely just something borked in our handling of old id numbers.

**Comment by xr001** [comment]
I am having an issue with schematics, specifically loading them after they were created.

The schematic will work the first time, but if it is unloaded the schematic will not load again.

Here is a debug of the error that pops up after loading a previous unloaded schematic:
http://old.mcmonkey.org/paste/49851
Here is the script where the schematic for test works every time it is used: https://one.denizenscript.com/haste/49856
Here is the script where it will throw up an error after being unloaded. The schematic will paste one time without error after running the task. As soon as the script unloads the schematic, it is unable to load it again.
https://one.denizenscript.com/haste/49857
Attached is the schematic file that Denizen generated.

I hope I have included enough information to help!
[test.zip](https://github.com/DenizenScript/Denizen-For-Bukkit/files/2385843/test.zip)

**Comment by mcmonkey4eva** [comment]
Spawn egg item identify issue: https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1814

**Comment by WaterQuarks** [comment]
mysteriously kicks out people on joining 1.13.1 https://one.denizenscript.com/haste/49933

**Comment by WaterQuarks** [comment]
> mysteriously kicks out people on joining 1.13.1 https://one.denizenscript.com/haste/49933

It was the tab_list_info mechanic! Disabled it and now it works just fine (:

**Comment by mcmonkey4eva** [comment]
receives message event fixed in newest dev builds

**Comment by mcmonkey4eva** [comment]
@WaterQuarks ^ that fix + tablist mechanism fixed as well

**Comment by mcmonkey4eva** [comment]
@xr001 schematic trouble is somewhat fixed in newest build.

The problem, though, is that the schematic file format no longer makes sense, as it relies on legacy ids which are no longer in use... we need a new schematic file format, to match Minecraft's new world format.

**Comment by mcmonkey4eva** [comment]
@WaterQuarks Fishes event fixed in newest build now as well

**Comment by mcmonkey4eva** [comment]
switch command/tag might now be fixed (need testing)

**Comment by Morphan1** [comment]
Fixed most all the material things I was worried about, with the only remaining one being the PathBlockExaminer. Maybe it's fine

**Comment by mcmonkey4eva** [comment]
Command scripts tab complete handler probably needs a rewrite/update for 1.13

**Comment by mcmonkey4eva** [comment]
Considering 1.13 to be "good enough" for a release build, and from here on any trouble with it should be given situation-specific issues.

Only issue I know of offhand is schematic saving/loading, and #1830 (which should probably be patched before releasing onto spigot actually...)
