### ISSUE TITLE
Item behaving strangely, cannot open dInventories

### ISSUE THREAD

**Issue by xr001** [DenizenScript/Denizen-For-Bukkit#1794]
I have a script that was working in previous versions, but doesn't seem to be working now and helpers on discord seemed stumped.
it's not throwing up any errors and the debugs are entirely unhelpful (but I will provide them).

I am able to give myself the item from the script using /ex, but I am able to drop it and it doesn't remain with me on death (as it should). Further, right clicking in the inventory on the item does not bring up the inventory as it should.

Suffice to say, nothing about this script works.

I am running Spigot 1.13 and the latest Denizen dev build as of the date of this post.

Script: https://one.denizenscript.com/haste/48757
Debug when using /travelpack : http://old.mcmonkey.org/paste/48764

**Comment by Morphan1** [comment]
Does `<player.inventory.contains.scriptname[premiumtravelpack]>` fix the command issue? Also, does the right click event you have output anything into the console or just silently do absolutely nothing? What if you replace the script name with a generic `item` and output the item's script name?

**Comment by mcmonkey4eva** [comment]
Line 7,
```

  - if <player.inventory.contains[i@premiumtravelpack]> && <player.has_flag[travelpack]>{ 
```
You formatted the if wrong (missing a space before the `{`)
