### ISSUE TITLE
Metadata implementation

### ISSUE THREAD

**Issue by SXRWahrheit** [DenizenScript/Denizen-For-Bukkit#1795]
Suspic told me to make an issue about this. I'm specifically interested in entity-related applications - I would like to be able to read entity metadata on death, for example.

Suspic was under the impression that it wasn't accessible outside of NMS, but this doesn't appear to be the case:
```
- https://bukkit.org/threads/tutorial-metadata-what-it-is-and-how-to-use-it.276338/
- https://hub.spigotmc.org/javadocs/spigot/org/bukkit/metadata/MetadataValueAdapter.html
- https://bukkit.org/threads/metadata-q-a-i-wrote-the-metadata-api-ama.68447/
- https://docs.google.com/document/d/1OPU1ITKY1qO6PyEDvx6NpLTfNIAHQLaXdIqIT0dZqGw/edit
```

**Comment by mcmonkey4eva** [comment]
Those links are irrelevant, that's an entirely unrelated system to anything you could be asking for.
(That's the ancient Bukkit metadata shitshow)
I assume you're interested in the newly added in 1.13 minecraft metadata systems.

**Comment by SXRWahrheit** [comment]
I basically just want a way to store data in a mob that can be set/retrieved by other plugins. MythicMobs, via BerndiVader's MME, can set NBT data on mobs, but Denizen has no way to check / set it, and I guess you have to use NMS for that.

**Comment by mcmonkey4eva** [comment]
To my knowledge there is no generally supported universal plugin interop setup for that kind of thing.

Plugins would need to be explicitly programmed to interface with each other. Even setting NBT values, Bukkit metadata, anything, would require all involved plugins to explicitly add interop functionality systems.

If you know of a specific plugin or set of plugins that have this type of interop system already built, link to that specific thing (details of it as apply to specific plugins) and we can integrate into that.
