### ISSUE TITLE
<context.location.switched> is invalid

### ISSUE THREAD

**Issue by redshirt2** [DenizenScript/Denizen-For-Bukkit#1797]
Included is paste.  When Player right clicks a block , and script checks for 'switched' I get invalid

Also, there's error right off the top about acacia_trapdoor amd that isn't in 1.12.2

http://old.mcmonkey.org/paste/48843

**Comment by mcmonkey4eva** [comment]
Fixed in dev build 400

**Comment by redshirt2** [comment]
Fixed
