### ISSUE TITLE
Sitting and armor stands

### ISSUE THREAD

**Issue by Redzilla22** [DenizenScript/Denizen-For-Bukkit#1802]
I can't get error or consoles or anything because all our developers have gone to sleep I'm just seeking help for an issue that may or may not be easily fixed.

Coming on this morning our quests plugin broke along with a new sudden mass of npcs created from the npcs sitting and armor stands being underneath them. I had removed all the ones with names but theres still armor stands underneath all the npcs and I'm afraid of the mass creation of no named npcs with armor_stand above all of their heads that I haven't put most of the npcs back into place.

Heres an example: [https://i.imgur.com/kKiBxzI.png]
Is there anyway to fix this?

**Comment by mcmonkey4eva** [comment]
Citizens issue, not Denizen
Update Citizens to latest: http://ci.citizensnpcs.co/job/Citizens2/
