### ISSUE TITLE
Leash Command not Creating Leash Between Entities

### ISSUE THREAD

**Issue by Elxafil** [DenizenScript/Denizen-For-Bukkit#1809]
As the title says the `- leash` command does not work, I've tested this on both NPCs, mobs and armorstands all of which have no leash created between them.

**Comment by mergu** [comment]
Can't replicate on 1.13.2 using latest dev build. Seems to be working fine

**Comment by mcmonkey4eva** [comment]
Need script/debug information if this is still an issue @Elxafil
