### ISSUE TITLE
Add onSpawnerSpawn event

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#1813]
It should be possible to cancel the event.

For context tags, I am looking for the location of the spawner.

It would also be neat to get the entities or the amount it tries to spawn.

**Comment by mcmonkey4eva** [comment]
This event: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/SpawnerSpawnEvent.html
Which is Spigot-API specific (not Bukkit).
