### ISSUE TITLE
The splash potion event doesn't work

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1815]
Hello, I use the spigot version 1.12.2

The event 
`on potion splash (in <area>)`
`on <item> splashes (in <area>) `
Does nothing

I used a simple event with a splash potion in hand : 
`on potion splash`
`- announce "test"`

**Comment by mcmonkey4eva** [comment]
Can you please post:
- Your full Spigot version (copy-paste from `/version`)
- Your full Denizen version (copy-paste from `/version Denizen`)
- A small but complete script that you have confirmed does not work - using https://one.denizenscript.com/haste
- Any debug logs if relevant

**Comment by Noiknez** [comment]
Sure :
- Spigot version : CraftBukkit version git-Spigot-eb3d921-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
- Denizen version 1.0.2-SNAPSHOT (build 1647)

I am not up-to-date with the Denizen version (5 version behind), I will test it with it

**Comment by mcmonkey4eva** [comment]
Build `1647` was released in early May.
Latest release, Build `1651` was released in late June.

There's a significant number of differences between those versions.

There's another entire massive amount of additional changes in the dev builds waiting (as it's now September). They haven't been pushed to the release line yet as they feature experimental 1.13 Minecraft support.

**Comment by mcmonkey4eva** [comment]
Will reopen if/when issue is confirmed on up-to-date builds
