### ISSUE TITLE
shield baseColor handled unproperly

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1817]
Shields without basecolor are handled as BLACK shields, dublicating them i.e. results then in real black shields.

/ex give i@shield <--- without basecolor/brown
/ex give <player.item_in_hand>   <--- black shield

debug: http://old.mcmonkey.org/paste/50031

**Comment by mcmonkey4eva** [comment]
Is this still an issue on latest builds?
