### ISSUE TITLE
The version 1651 had broken MessageConstructorLibrary

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1818]
Hi,

(I had some problem with the /denizen debug -r)

![image](https://user-images.githubusercontent.com/20723083/46408321-0c082800-c712-11e8-9f1e-29b93f464015.png)

Server version : CraftBukkit version git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Denizen version : version: 1.0.2-SNAPSHOT (build 1651), core version: 1.15 (Build 152)

**Comment by mcmonkey4eva** [comment]
Post **your script** and **a full debug log** as recorded by `-r`

**Comment by Noiknez** [comment]
http://old.mcmonkey.org/paste/50154

**Comment by mcmonkey4eva** [comment]
Post **your script** and **a full debug log** as recorded by `-r`

**Comment by Noiknez** [comment]
Full debug : http://old.mcmonkey.org/paste/50158

Scripts : 

(MCL) https://one.denizenscript.com/haste/50159


(My script) https://one.denizenscript.com/haste/50160

**Comment by mcmonkey4eva** [comment]
Do not use `%` definition syntax, especially not mixed with symbols like `>` (which is the result of `<&gt>` tag.
Use `<def[name]>` to read definitions.
