### ISSUE TITLE
Leather colored armor problem in #1651

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1820]
Server version : ```
CraftBukkit version git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
This is a final build for 1.12.2.```

Denizen version : `1.0.2-SNAPSHOT (build 1651), core version: 1.15 (Build 152)`

Script : https://one.denizenscript.com/haste/50214
Debug : http://old.mcmonkey.org/paste/50213
Command used : `/ex give Botte_hermes`

**Comment by mcmonkey4eva** [comment]
err...
`  color: co@F9801D `
^ that's not valid.

View the debug output (in your own link) to see the correct format for a color object.

**Comment by Noiknez** [comment]
It doesn't work with the command `/ex give i@leather_boots[display_name=Hermes;color=co@160,101,64]`

**Comment by Noiknez** [comment]
Update : The format color: co@F9801D worked before version 1651
Now it work only with `co@blue` or for eg: `co@50,50,50`

**Comment by mcmonkey4eva** [comment]
No part of the relevant parsing logic has changed recently.
There's no reason that input should have / would have worked on any recent versions to my knowledge.

**Comment by Noiknez** [comment]
The successful test was on #1647, there where many change since

**Comment by Noiknez** [comment]
Update : after some test, it was before this version. We where using the script related to `co@F9801D` 2 years ago and we doesn't use it since. It was just now that we where again interested in using the color format in leather armor
Sorry but I have not time to test it on older version, I should check the updated use next time
