### ISSUE TITLE
Light command rewrite

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#1822]
The light command seems to update the light source and surrounding chunks every 5 ticks, which noticeably drops both serverside and clientside performance. It could probably use some work.

https://github.com/mcmonkey4eva/Denizen/blob/master/v1_13_R2/src/main/java/net/aufdemrand/denizen/nms/impl/blocks/BlockLight_v1_13_R2.java#L69

Other light-related plugins don't have this issue it seems

**Comment by mcmonkey4eva** [comment]
I found a rather painful "woops forgot that" style of issue in how the light command works. Not sure how it ended up there but might be related to some performance trouble.
Patched those in build DEV-545+
Not sure how much (if any) improvement results from that, would be good to test

**Comment by mergu** [comment]
Issue still seems to be present, getting 50-60fps away from the single light source and 5-8fps near it/looking at it

**Comment by mcmonkey4eva** [comment]
The light command needs a total rewrite to function in 1.14.

**Comment by mcmonkey4eva** [comment]
Now works in 1.14.x, and seems to be lag free, using a brand new internal backing
Via https://github.com/DenizenScript/Denizen-For-Bukkit/compare/8413afc57c51...29f79ef3f1c7
