### ISSUE TITLE
'On player crafts [custom item]' half works

### ISSUE THREAD

**Issue by Hazelfraz** [DenizenScript/Denizen-For-Bukkit#1823]
Name: 'On Player Crafts 'Custom Item' Half works

About: If you use determine canceled in the event 'On player crafts' with a custom item from an item script you can still craft said item

The issue is: Using on player crafts for regular items works fine, but if I create an item script with a recipe I can craft said item even if I have it as determined cancelled. I said it half works though: You can click on said item in crafting bench and plop it into your inventory but you can not shift+click to craft the item.

**Comment by mcmonkey4eva** [comment]
- Are you testing in survival or create?
- Please paste a copy of your script to https://one.denizenscript.com/haste - save it and post the link here
- Please record a copy of debug. Use `/denizen debug -r` in-game, then run through the steps of it working and not working as relevant, then use `/denizen submit`. It will give you a link to post here as well.

**Comment by Hazelfraz** [comment]
https://one.denizenscript.com/haste/50362

**Comment by mcmonkey4eva** [comment]
I've edited your posts into the order they were posted (undoing the weird edit cycle). Please use replies to respond to other replies, not editing.

Please follow the instructions I gave regarding debug logs.

Use survival for testing that. Creative mode is not compatible with raw inventory edit control - in minecraft, Creative mode grants the clientside full control of their inventory, which means serverside alterations (eg those done by a script) will not always properly take effect.

**Comment by Hazelfraz** [comment]
my bad i misunderstood what you were wanting me to do.  

http://old.mcmonkey.org/paste/50381

**Comment by mcmonkey4eva** [comment]
Redirecting to #1851

**Comment by mcmonkey4eva** [comment]
Probably better now thanks to the resolution to #1851
