### ISSUE TITLE
Tags time-out in scipts: <server.list_plugins> and <server.list_plugin_names>

### ISSUE THREAD

**Issue by Dopplizzle** [DenizenScript/Denizen-For-Bukkit#1826]
The output of `/version` on my server is: CraftBukkit version git-Spigot-e4d0c66-f3f2fe5 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
The output of `/version denizen` on my server is: Denizen version 1.0.3-SNAPSHOT (build 447-DEV)
(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/haste/50468
The issue is:
The tags <server.list_plugins> and <server.list_plugin_names> both time-out when used in scripts, (generating "Tag filling timed out!" errors).

Weirdly, they both work fine when run from client as /ex narrate <server.list_plugins>.

**Comment by mcmonkey4eva** [comment]
As a workaround, you can either disable debug (via `debug: false` on the script container) or disable tag timing in the config (set the limit to `0`).

Now as to _why_ that would happen... probably Spigot made a borked thread lock again somewhere...

**Comment by mcmonkey4eva** [comment]
not an issue on Spigot 1.14.2 with Denizen DEV-807
