### ISSUE TITLE
Minecraft village / villager events

### ISSUE THREAD

**Issue by LeafyMitsuwa** [DenizenScript/Denizen-For-Bukkit#1827]
Villager entities create villages. These villages are often manipulated by popular designs for iron farms.

Is it possible to capture the creation of these villages, e.g. on village forms, or something along the lines -- or anything else that might not have been tapped into with this Minecraft's resource, such as perhaps villager inventories.

**Comment by MusicScore** [comment]
By "villager entities create villages", he means the way villagers define a village (as discussed on Discord). That is, doors and possibly other special conditions.

Might be worth adding if any event exists for it in the Spigot API.

**Comment by mcmonkey4eva** [comment]
I don't think it _quite_ works that way (though it might?).
What you can do is listen to `on villager spawns` for handling villagers popping into the world and `on iron_golem spawns` to handle iron golems spawning (there's even a cause value of `village_defense` available for specifically golems spawning as guardians of a village)

**Comment by LeafyMitsuwa** [comment]
I've looked for my source on this particular topic, and it was an iron farm design by TangoTek.

https://youtu.be/kxixJ5P_V7k

The explanation starts at the end of the video, at 1:19:45.

**Comment by mcmonkey4eva** [comment]
That isn't relevant at all.

**Comment by mcmonkey4eva** [comment]
Please reply below if you find any reference for such an event existing in Spigot.
Otherwise, use the events I mentioned above.

**Comment by LeafyMitsuwa** [comment]
I found this on the Jira, where you could not trade with villagers outside a village.

Thought the trace in the bug report might be useful as it might give insight to how a village functions, or is referenced by nms.
