### ISSUE TITLE
Tag <w@world.world_type> (or similar)

### ISSUE THREAD

**Issue by lmorgh** [DenizenScript/Denizen-For-Bukkit#1828]
I was missing a tag that would display the world worldType, and Suspic pointed out it could be implemented using this:

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/WorldType.html

Thanks for considering it.

**Comment by mcmonkey4eva** [comment]
Or more specifically this: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#getWorldType--
