### ISSUE TITLE
Outdated framed mechanic documentation

### ISSUE THREAD

**Issue by Den1zen** [DenizenScript/Denizen-For-Bukkit#1834]
The framed mechanic only has 4 valid rotations documented: Valid rotations: NONE, CLOCKWISE, FLIPPED, COUNTER_CLOCKWISE
There are currently 8 functional values here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Rotation.html

The 8 rotations do work as of denizen developmental snapshot 444.
The document ion for the rotations are just inaccurate.

**Comment by Den1zen** [comment]
Tried to do a thing on the thing. I may or may not have made a 'commit' for it. I can't really tell.

**Comment by mcmonkey4eva** [comment]
Duplicate of #1829
