### ISSUE TITLE
Error with on entity spawns event 1.13.2

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1837]
Got some errors in this event

Spigot-2474d93-e693496 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Denizen version 1.0.3-SNAPSHOT (build 451-DEV)

Can't get a decent nice to look at debug submit because that event really fires a lot. Here is the error

http://one.denizenscript.com/paste/50623

**Comment by mcmonkey4eva** [comment]
Depenizen issue, report on Depenizen page (though it might be fixed in Depenizen build DEV-421 already)

**Comment by Morphan1** [comment]
This should be fixed in the latest Depenizen build
