### ISSUE TITLE
about compatible placeholderapi

### ISSUE THREAD

**Issue by bushuaichen** [DenizenScript/Denizen-For-Bukkit#1844]
Is it possible to increase compatibility with PAPI?
for example:
```
ore:
    type: world
    debug: false
    events: 
        on player breaks iron_ore: 
        - determine passively fulfilled
        - if <papi.%plugin_number%> >= 5 { 
          - narrate '<&6>[<&a>Server<&6>]: <&c>Your value is not enough.' 
          - queue clear
          }
```
I hope your plugin will get better and better.

**Comment by Mwthorn** [comment]
You need the add-on Depenizen in order to use PlaceholderAPI tags.
Use <placeholder[<name>]>

Tag info: https://one.denizenscript.com/denizen/tags/placeholder
Depenizen: https://github.com/DenizenScript/Depenizen

**Comment by mcmonkey4eva** [comment]
Yup ^ eg if you wanted to use placeholder `%player_name%` in a Denizen script, you would write `<placeholder[player_name]>`

Need to install Depenizen as mentioned by Mwthorn - specifically DepenizenBukkit, available via http://ci.citizensnpcs.co/job/Depenizen/ (be sure you're running the latest Denizen build as well before installing Depenizen)
