### ISSUE TITLE
NPE on context.location.skull_skin check

### ISSUE THREAD

**Issue by Sahariza** [DenizenScript/Denizen-For-Bukkit#1845]
The output of `/version` on my server is: git-Spigot-e8ded36-acbc348 (MC: 1.12.2)
The output of `/version denizen` on my server is: 1.0.3-SNAPSHOT (build 470-DEV)
A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/haste/50761
The issue is:
java.lang.NullPointerException
https://one.denizenscript.com/paste/50760

**Comment by mcmonkey4eva** [comment]
```

    - if <context.location.skull_skin||none> == 5bbf06d1-66f5-40ce-8893-bc3ab70abae0

**Comment by Sahariza** [comment]
This will not work. Empty skull is returning PLAYER type too, but throwing exception. Empty skin check should return null, but not NPE

**Comment by mcmonkey4eva** [comment]
Based on the reply being immediate and the thumbs up being attached later, I'm going to guess the thumbsup is to indicate the issue is indeed resolved.
If it's not, please reply below
