### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MithrandirCraft** [DenizenScript/Denizen-For-Bukkit#1846]
https://one.denizenscript.com/haste/50762
The output of `/version` on my server is: [21:42:11 INFO]: This server is running CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[21:42:11 INFO]: You are 315 version(s) behind
The output of `/version denizen` on my server is: [21:42:39 INFO]: Denizen version 1.0.2-SNAPSHOT (build 1641)
[21:42:39 INFO]: Authors: aufdemrand, mcmonkey and Morphan1
The issue is: Just an error showing up on console occasionally
It's a Spigot test server in online mode by the way, just to clear that out.

**Comment by MusicScore** [comment]
You are multiple builds behind.

For the latest stable build: http://ci.citizensnpcs.co/job/Denizen/lastSuccessfulBuild/
For the latest developmental build: http://ci.citizensnpcs.co/job/Denizen_Developmental/lastSuccessfulBuild/

**Comment by mcmonkey4eva** [comment]
Yup, just a significantly outdated build there. Update, per links above ^
