### ISSUE TITLE
Player clicks inventory event bug

### ISSUE THREAD

**Issue by ColonelOverspel** [DenizenScript/Denizen-For-Bukkit#1849]
Debug output: https://one.denizenscript.com/paste/50807
(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/paste/50809
The issue is:
The <context.action> tag will always return PLACE_ALL, even when that is not the action that was taken. I clicked in several different ways (pickup one, pickup half, drop half etc.), yet all it returned was PLACE_ALL.

**Comment by mcmonkey4eva** [comment]
If anything that's likely an issue with the spigot 1.13 build, not Denizen
