### ISSUE TITLE
Feature Request - Ability to remove arrows stuck inside player models

### ISSUE THREAD

**Issue by LeafyMitsuwa** [DenizenScript/Denizen-For-Bukkit#1850]
Mergu referred me to this place to request a feature with which arrows stuck in players could be removed.

Normally, if a player drinks an invis potion, any arrows stuck inside the player model do not turn invisible along with the player.

So, rather than masking them, I was hoping that they can be removed, such as with - remove, or perhaps a new function.

After some digging, I came across a Spigot thread that had the following to say.

https://www.spigotmc.org/threads/removing-arrows.72723/

((CraftPlayer)player).getHandle().getDataWatcher().set(new DataWatcherObject<>(10, DataWatcherRegistry.b),0);

I personally do not know what these functions do, but apparently Mergu did have some idea -- and adviced to make a feature request, so that this can be given a thought, or examination, or ... perhaps a ponder.

Thanks!

**Comment by mergu** [comment]
Magic number seems to be 9 instead of 10 in 1.8, will require testing in each version but seems useful and interesting.

**Comment by mcmonkey4eva** [comment]
I doubt the event comment is relevant/helpful here.
Unless you can use `on player damaged by arrow: - remove <context.damager>` and it removes the arrow

**Comment by LeafyMitsuwa** [comment]
That was more to reference the major CPU load it might cause.

I do not know if that is accurate, but since someone thought of it, I thought to mention it.

As for events. <context.damager>is the entity firing the bow, so lets not do that. Instead, <context.projectile> is the arrow in flight, which can be removed if the arrow rebounds, like, from a Citizens2 NPC, but once it gets stuck inside of a player, it no longer is that entity that <context.projectile> covers.

If you need more testing done, let me know, and I'll try to provide the results.

**Comment by mcmonkey4eva** [comment]
@mergu do you want to try to make this work?

**Comment by mergu** [comment]
Sure I can do this
