### ISSUE TITLE
Banner color in 1.13

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1857]
The output of `/version` on my server is: **CraftBukkit version git-Spigot-e769fe4-068dab5 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **1.0.3-SNAPSHOT (build 483-DEV)**
The issue is:

They were some change with banner in 1.13

Every non-white banner when executing `<player.item_in_hand>` result in `i@black_banner`
only the white banner result in `i@white_banner`

The problem is we can't get the base color of all the banner (only the white and black)

**Comment by mcmonkey4eva** [comment]
Need debug logs / testing details

**Comment by Noiknez** [comment]
Sure, I have tested all the banner in my hand
![image](https://user-images.githubusercontent.com/20723083/49750928-6e4e4d80-fcac-11e8-910f-f6ba79f96515.png)

https://one.denizenscript.com/paste/51079

**Comment by Noiknez** [comment]
Update : when searching about some information I found this

```
DyeColor | getBaseColor​()
Deprecated. 
banner color is now stored as the data value, not meta.
```
It is related to https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1863

**Comment by Noiknez** [comment]
Fixed in the latest dev build
