### ISSUE TITLE
redirect_logging disabled?

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Denizen-For-Bukkit#1861]
https://github.com/DenizenScript/Denizen-For-Bukkit/edit/master/plugin/src/main/java/net/aufdemrand/denizen/utilities/debugging/LogInterceptor.java

**Comment by mcmonkey4eva** [comment]
Yes.
As I said on Discord, use `- adjust system redirect_logging` instead of the server one, due to the 'server' one being non-functional

**Comment by KeangDavid** [comment]
config: https://one.denizenscript.com/haste/51120
script: https://one.denizenscript.com/haste/51122
Nothing happens...

**Comment by mcmonkey4eva** [comment]
Please record debug (`/denizen debug -r`, run test script, `/denizen submit`) and post the link it gives you.

**Comment by KeangDavid** [comment]
https://one.denizenscript.com/paste/51125

**Comment by mcmonkey4eva** [comment]
It's just the 
```
- adjust system redirect_logging:true 
```
one, not the others.
The world event is just `on console output:`

I tested it locally, it works fine.

If anything, it's more likely you're having trouble with the `announce` command (it uses the Bukkit broadcast system, which has a required permission key)
