### ISSUE TITLE
Direction for chest and sign

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1863]
The output of `/version` on my server is: **CraftBukkit version git-Spigot-140f654-b446cb5 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **version: 1.0.3-SNAPSHOT (build 489-DEV), core version: 1.20 (Build 169)**
The issue is:
Before the version 1.13.2 I were using direction value for chest, trapped_chest, sign and wall_sign for my shop script (material.data or in material.name directly). Now it seems that the direction data is non-existant anymore

**Comment by Noiknez** [comment]
Also tested with #483 dev

**Comment by Noiknez** [comment]
Full script : https://pastebin.com/JBUkHmRD
Debug : https://one.denizenscript.com/paste/51170

**Comment by Noiknez** [comment]
Update : This issue need `public BlockFace getFacing​()`

**Comment by mcmonkey4eva** [comment]
btw `%%` is way old and deprecated.
In your script ` - define valueNote <%value%.after[l@]>` for example should instead be:
` - define valueNote <def[value].after[l@]>`
