### ISSUE TITLE
Event for Entity Breeding

### ISSUE THREAD

**Issue by Elxafil** [DenizenScript/Denizen-For-Bukkit#1870]
As mentioned by Mergu there is currently no event to detect entity breeding, you currently as a workaround have to use the `on entity spawns` event which fires during every entity spawn event regardless of if it is just bred.

Link to Spigot API: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityBreedEvent.html

Example of the event/s:
on entities breed:
<context.parents>/<context.entities> (Would provide a dList of both entities that are breeding i.e. `li@e@someuuid|e@someotheruuid`.
<context.child>/<context.entity> (Would return the entity created from breeding)
<context.location> (Would return the location of where the entities bred and the new entity was spawned)

**Comment by SXRWahrheit** [comment]
Amazed this doesn't already exist - great suggestion.
