### ISSUE TITLE
Allow "title" mec to affect location-based inventories

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1871]
The `dInventory.title` mechanism does not change the title of placed chests' inventories. The `in@inventory.title` tag seems to be able to read the title though.

Relevant method: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Nameable.html#setCustomName-java.lang.String-
Relevant class that inherits the interface that the above method is in: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Chest.html

**Comment by mcmonkey4eva** [comment]
_Can_ chest blocks be named (in minecraft itself)?

**Comment by MusicScore** [comment]
Yes they can. A renamed chest will make the block inventory adopt the display name of the chest item. The specific vanilla NBT tag used is "CustomName", which (in 1.13.2) is a JSON text component.

**Comment by mcmonkey4eva** [comment]
Added to build DEV-520.
