### ISSUE TITLE
 problem of duplication during custom craft

### ISSUE THREAD

**Issue by BlackFox3000** [DenizenScript/Denizen-For-Bukkit#1873]
[https://one.denizenscript.com/haste/51311](https://one.denizenscript.com/haste/51311)
The output of `/version` on my server is:
  This server is running CraftBukkit version git-Spigot-19c3c5a-5932f8a (MC: 1.13.2) (Implementing API 
  version 1.13.2-R0.1-SNAPSHOT)
The output of `/version denizen` on my server is:
 [13:52:39] [Server thread/INFO]: Denizen version 1.0.3-SNAPSHOT (build 503-DEV)
 [13:52:39] [Server thread/INFO]: Authors: aufdemrand, mcmonkey and Morphan1
(If relevant) A link to a paste of a script demonstrating the issue: **paste here**
The issue is:

When using the craft table to have a custom item. The game gives us the desired goal and we duplicate the resources present in the table.

**Comment by mcmonkey4eva** [comment]
Merges into https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1851

**Comment by mcmonkey4eva** [comment]
Fixed by the resolution to #1851
