### ISSUE TITLE
Playeffect with blockcrack/dust does not recognize quantity/offset

### ISSUE THREAD

**Issue by Rickytehduck** [DenizenScript/Denizen-For-Bukkit#1875]
The output of `/version` on my server is: **git-Spigot-8173d06-7560d3b**
The output of `/version denizen` on my server is: **505-DEV**

It seems that the blockcrack/blockdust particles do not recognize when a quantity is specified.
The playeffect command will only create one of that particle, and the offset will always be `l@0.5,0.5,0.5`.

Can be replicated with:
`playeffect effect:blockcrack_ice <player.location> quantity:101 offset:2`
`playeffect effect:blockdust_sand <player.location> quantity:101 offset:21`

Example:
![image](https://user-images.githubusercontent.com/5568932/50743782-12a5be80-1270-11e9-9d17-35cde128815e.png)

**Comment by mcmonkey4eva** [comment]
fixed in DEV-507
