### ISSUE TITLE
Debug not shown.

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#1879]
The output of `/version` on my server is: final build 1.12.2
The output of `/version denizen` on my server is: 517-DEV

The issue is:
When `/denizen debug` is _off_,  even non-hideable debug isn't shown in the console.
`/ex debug log "This is not shown."`

May this be a side-effect from the last global debug-update?

**Comment by mcmonkey4eva** [comment]
"When debug is off, debug doesn't show"
yeah that's how that works what are you even expecting

**Comment by BloodEko** [comment]
The documentation tells about _hideable_ and _non-hideable_. I'd expect the last one to be shown.
https://one.denizenscript.com/denizen/cmds/debug

**Comment by mcmonkey4eva** [comment]
That's for whether `debug: false` on a script hides it.

**Comment by BloodEko** [comment]
Aight. Was just a bit confusing as I tried to use `- debug` for writing informations into the console, which didn't appear while it's presented as "non-hidable" in the docs.

**Comment by mcmonkey4eva** [comment]
Use `- announce to_console "..."`
