### ISSUE TITLE
Sign command direction weirdness

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#1880]
Hello, when testing the sign command, everything was fine except the direction argument

```
+++ [world command] sign: Modifies a sign.
+++ Syntax: - sign (type:{automatic}/sign_post/wall_sign) ["<line>|..."] [<location>] (direction:n/e/w/s)
```
**WALL_SIGN:**

_Problem n°1:_ 

Only the s (South) and w (West) argument place the wall sign block, the e (East) and n (North) doesn't place the wall_sign (if the location is a block, it replace the block with air)

_Problem n°2:_

When using the w (West) argument, the sign face the West (as normal) but when using the s (South) argument, the sign face the North.

_Screenshot of the situation_
![image](https://user-images.githubusercontent.com/20723083/51268869-4942ae00-19c1-11e9-81e4-39b35dfbe229.png)

**NORMAL SIGN**

_Problem n°1:_

The line is seen as a unknow argument (instead of wall sign where this error not happen)
`'line1|line2|line3|line4' is an unknown argument!` and the first word is replace by "sign" and the other line vanish

![image](https://user-images.githubusercontent.com/20723083/51268926-6f684e00-19c1-11e9-99fb-0303b81c65ea.png)

_Problem n°2:_

The placement work but not the direction of sign. Every sign when using the directions (n, s, e, w) place it facing South. The same is happening  without the direction argument in the command.

![image](https://user-images.githubusercontent.com/20723083/51269097-e1d92e00-19c1-11e9-9c6d-7ee864feb42d.png)

---------------------

The output of `/version` on my server is: **CraftBukkit version git-Spigot-19c3c5a-5932f8a (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

The output of `/version denizen` on my server is: **Denizen version 1.0.3-SNAPSHOT (build 531-DEV)**

Command use for the test : 
/ex SIGN "type:sign" "line1|line2|line3|line4" "<player.location.cursor_on> direction:n" (all the direction)
/ex SIGN "type:wall_sign" "line1|line2|line3|line4" "<player.location.cursor_on> direction:n" (all the direction)

Debug: http://old.mcmonkey.org/paste/51592

**Comment by mcmonkey4eva** [comment]
Should be fixed in DEV-533+

**Comment by Astrareach** [comment]
Tested with 536 dev

Everything work fine except the line for the normal sign (there is no such problem for wall_sign)
![image](https://user-images.githubusercontent.com/20723083/51322402-a728d180-1a65-11e9-863d-98ef32d3a63e.png)

What I should get : (wall sign image)
![image](https://user-images.githubusercontent.com/20723083/51322654-5665a880-1a66-11e9-9f37-aee0407c54be.png)

**Comment by mcmonkey4eva** [comment]
What is the issue now?

**Comment by Astrareach** [comment]
The issue is when I use the command
`
/ex sign type:SIGN line1|line2|line3|line4 <player.location.cursor_on>`

There is only the text "SIGN" that appear on the normal sign

```
Problem n°1:

The line is seen as a unknow argument (instead of wall sign where this error not happen)
'line1|line2|line3|line4' is an unknown argument! and the first word is replace by "sign" and the other line vanish
```

**Comment by mcmonkey4eva** [comment]
`type:SIGN` isn't a valid type.
From the meta docs:
` (type:{automatic}/sign_post/wall_sign)`
