### ISSUE TITLE
waterdrip --> dripping_water (1.13) & redstone --> reddust (1.13) doesn't get recognise

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#1887]
The new dripping_water and reddust effect doesn't work

The output of `/version` on my server is: **CraftBukkit version git-Spigot-19c3c5a-5932f8a (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **1.0.3-SNAPSHOT (build 545-DEV)**

`Command used : /ex playeffect effect:dripping_water <player.location.add[0,1,0]>`
`Command used : /ex playeffect effect:reddust <player.location.add[0,1,0]>`(with multiple color data)
(tested also with waterdrip, redstone, dust)

debug : http://old.mcmonkey.org/paste/51635

`In 1.13, dust is followed by four extra arguments: red green blue size. red green blue are numbers between zero and one specifying the color of the particle, and size is a number specifying the size of the particle. Don't get crazy with size, or the game will crash.`

**Comment by mcmonkey4eva** [comment]
Refer to https://one.denizenscript.com/denizen/cmds/PlayEffect and https://one.denizenscript.com/denizen/lngs/particle%20effects for correct syntax and particle effect names.
