### ISSUE TITLE
fake_food_level

### ISSUE THREAD

**Issue by HER5H** [DenizenScript/Denizen-For-Bukkit#1889]
Similar to the fake_health but split out for ease.

**Comment by mergu** [comment]
To clarify - this is a feature request. Looked into it a bit and seems strange to split apart, as it's all bundled in one packet: `PacketPlayOutUpdateHealth(float health, int food, float saturation)`. Setting a single value would mean resetting the others which might not be intended if the user already has fake health/saturation

**Comment by mcmonkey4eva** [comment]
There's no real point in splitting it out.
As the fake_health meta shows:
```
- adjust <player> fake_health:<player.health>|3|0
```
It's that easy to fake only the food level.
