### ISSUE TITLE
Showfake resets on right-click in Adventure Mode

### ISSUE THREAD

**Issue by Konvett** [DenizenScript/Denizen-For-Bukkit#1890]
The output of `/version` on my server is: **CraftBukkit version git-Spigot-f56e2e7-4385562 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**

The output of `/version denizen` on my server is: **Denizen version 1.0.3-SNAPSHOT (build 1660-REL)**
(If relevant) A link to a paste of a script demonstrating the issue: `/ex showfake stone l@81,37,42,world_spawn players:<p@mergu> duration:10s`

The issue is:
When you set a fake block, a player in adventure mode can right click and the block will reset to the actual block prior to the showfake expiring. Left clicking does not have this issue. Mergu and I ran a test on another server in which a tree is destroyed and confirmed the showfake blocks were barriers and we were unable to reset it by right clicking. Only he could see the destroyed tree, I could still see the full tree.

**Comment by mergu** [comment]
For further info: this has always been a known issue with fake blocks in every gamemode. Seems like it's possible to cancel the block update sent to the client though, as we were able to find fully working fake blocks on wynncraft.

**Comment by mcmonkey4eva** [comment]
I edited the formatting of your post.

Theoretically cancelling the block update is just a straightforward packet interception job - wasn't done in the past because when that command was being worked on we definitely didn't have any packet interception tooling.

**Comment by mcmonkey4eva** [comment]
It turned out to be slightly less straightforward than I thought.
Because the underlying code is a nightmare...
![wtf](https://i.alexgoodwin.media/i/misc/6fbec1.png)

But, this is now a feature! Showfakes persist until you intend them to stop being around!
