### ISSUE TITLE
Fakebook Item does not despawn item using duration

### ISSUE THREAD

**Issue by BehrRiley** [DenizenScript/Denizen-For-Bukkit#1896]
The output of `/version` on my server is: **Paper 1.13.2 #504**
The output of `/version denizen` on my server is: **Denizen-1.0.3-b568-DEV--**
(If relevant) A link to a paste of a script demonstrating the issue: **https://one.denizenscript.com/haste/51704**
The issue is:
What I wanted to happen: Fake item BOOK is given to player replacing any item in hand, player is forced to open the book and see "TESTING TESTING 123" and in 5 ticks removes the fake item, keeping the player inside the open book mech. 
What happened: Player was given book, the book was not removed with any time.
what i think should have happened: the book should have been removed in 5 ticks, different time intervals did not change the outcome

**Comment by mcmonkey4eva** [comment]
`The output of /version denizen on my server is: Denizen-1.0.3-b568-DEV--`
That is not the output of that command. That's the name of your jar file.

Also, I edited your post to fix formatting.

**Comment by mcmonkey4eva** [comment]
This miiiight be fixed in build DEV-570+
