### ISSUE TITLE
Tag <item.plant_growth> only output "seeded"

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#1899]
The output of `/version` on my server is: **CraftBukkit version git-Spigot-f56e2e7-b634e05 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**

The output of `/version denizen` on my server is: **Denizen version 1.0.3-SNAPSHOT (build 578-DEV)**

Script used : https://pastebin.com/rwn7Qe9n
Debug : https://one.denizenscript.com/paste/51765
Tag related : `<item.plant_growth>
`

Hi, I broke the first one and the second one and get the same result with wheat : "seeded"
I got the same thing for beetroot
![image](https://user-images.githubusercontent.com/20723083/51791277-e27f7a80-21a0-11e9-92cf-aba9dfc95506.png)

I have always seeded as a result of the tag, even if the plant is ripe

**Comment by mcmonkey4eva** [comment]
this is a problem with 1.13's new way of handling block data separate from material type.

We need to build some form of new system in 1.13 to handle this stuff...

**Comment by GomaTerzu** [comment]
Any progress on this issue?

**Comment by mcmonkey4eva** [comment]
In the new update (as of DEV-668+) you can do `<context.material.plant_growth>`

This is part of the new material property system, see Discord `#changelog` channel for further info.
