### ISSUE TITLE
Addition of the polar bear attack as an available animation through the animate command

### ISSUE THREAD

**Issue by LSTOMAR** [DenizenScript/Denizen-For-Bukkit#1902]
Is there a possibility this could be added?

**Comment by mcmonkey4eva** [comment]
This should theoretically be possible via nms packet logic if nothing else.
https://wiki.vg/Entity_statuses doesn't seem to list it but that's not necessarily a complete list.
@mergu might be able to help on this

**Comment by mergu** [comment]
Yes that's possible. You can assign this issue to me
