### ISSUE TITLE
Tag for Scoreboard Team

### ISSUE THREAD

**Issue by Konvett** [DenizenScript/Denizen-For-Bukkit#1905]
It'd be nice to have a tag available for listing the scoreboard teams a player is in. For using teams as a faction or PvP mechanic in a server, calling teams through a tag would be helpful as opposed to flagging a player for a specific team when adding them to that team.

**Comment by mcmonkey4eva** [comment]
As of build DEV-610+
You can use `<server.scoreboard[(<board>)].team_members[<team>]>`
Be aware that the scoreboard system does not guarantee any specific format to the members, but generally it will be player names that will need to be validated.
