### ISSUE TITLE
execute command don't work

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#1906]
The output of `/version` on my server is: **git-Spigot-b0f4c22-2ced023 (MC: 1.13.2)**
The output of `/version denizen` on my server is: **1.30 (Build 196), CraftBukkit: 1.0.3-SNAPSHOT (build 607-DEV)**
debug : https://one.denizenscript.com/paste/52171
The issue is:

The "execute command don't work with every command (tested with different things see : pastebin eg execute as_server "timings on")
We get for example 
```
13:22:10: Incorrect argument for command
13:22:10: <--[HERE] 

```
Trying with the console and in a script, (another person had tested it and confirm that issue)

logs : https://pastebin.com/1j85dwip

**Comment by mcmonkey4eva** [comment]
`/execute` is not a Denizen command.
`- execute` is a Denizen command.
The Denizen in-game command is `/ex`, which can be used like `/ex execute as_server "something"`
