### ISSUE TITLE
Feature request : target argument for group command

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#1907]
Tag request : `target:` argument for the group command
https://one.denizenscript.com/denizen/cmds/group

This way we can target any player or list of player for the group command

**Comment by mcmonkey4eva** [comment]
Use the standard `player:` argument: https://one.denizenscript.com/denizen/vids/The%20Player%20and%20NPC%20Arguments
For lists, use foreach.
