### ISSUE TITLE
Can't login at some map positions

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1911]
Is this in any way denizen related? Updated my 1.12.2 map to 1.13.2 lately and sometimes experience regions where people get disconnected and can't reconnect again with this error

Error: http://one.denizenscript.com/paste/52333

Does the error give a hint what the problem could be?

**Comment by mcmonkey4eva** [comment]
That doesn't look at all related to Denizen.

Seems to be some entity is equipped with leather armor that's in some way glitched.

Might try using server console and Denizen `/ex` commands to load the relevant chunks and test what entities are around and what items they're wearing.
