### ISSUE TITLE
Error when reloading scripts after installing depenizen

### ISSUE THREAD

**Issue by Klawdek** [DenizenScript/Denizen-For-Bukkit#1912]
The output of `/version` on my server is: **paste here**
14.02 20:54:50 [Server] INFO This server is running CraftBukkit version git-Spigot-e8ded36-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
14.02 20:54:50 [Server] INFO This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.

The output of `/version denizen` on my server is: **paste here**
14.02 20:55:46 [Server] INFO Denizen version 1.0.3-SNAPSHOT (build 497-DEV)
(If relevant) A link to a paste of a script demonstrating the issue: **paste here**
The issue is:
**Describe your issue in full here**
After installing depenizen I get the following error when I restarted server and whenever scripts are reloaded, https://one.denizenscript.com/paste/52370

**Comment by mcmonkey4eva** [comment]
Depenizen is over here: https://github.com/DenizenScript/Depenizen/

**Comment by mcmonkey4eva** [comment]
also, update mcMMO and Depenizen to latest builds
