### ISSUE TITLE
VillagerAcquireTradeEvent

### ISSUE THREAD

**Issue by LeafyMitsuwa** [DenizenScript/Denizen-For-Bukkit#1913]
Name(s)
on villager recipe//trade unlocks

Triggers
when a villager/entity unlocks a new trade due to player trading.

Cancellable
This event can be cancelled. This adds 'context.cancelled', and determines 'CANCELLED' and 'CANCELLED:FALSE'

Context
- <context.entity> Returns the dEntity of the villager/entity
- <context.trade> // <context.recipe> Returns a dList of the recipe.

Determine
- dList to set a new recipe.

**Comment by LeafyMitsuwa** [comment]
1.14 will feature a new villager type. This may or may not be split into a different entity later down the line, and there may be a different event by spigot (or may already be -- or not, since Spigot has 1.14 pre builds).

**Comment by mergu** [comment]
Just for reference - link the javadocs and don't create your own meta in the future. 

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/VillagerAcquireTradeEvent.html

This would also be nice to implement: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/VillagerReplenishTradeEvent.html

**Comment by LeafyMitsuwa** [comment]
The monkey said to pull an event from that page and post it as a feature, so that's what I did. Figured I'd work out the idea with examples of meta.

**Comment by mcmonkey4eva** [comment]
I also implied (but didn't really state clearly) to do that _if you need an event_ to be available.

What even do you need this event for?!

**Comment by LeafyMitsuwa** [comment]
I'd like to adjust villager trades as they are being generated?

**Comment by mcmonkey4eva** [comment]
@MusicScore this might be an issue for you to do?

**Comment by MusicScore** [comment]
Funny story was, I did do some work with the acquires and replenishes trade events, but they were both unfortunately purged when I did a small reorganization of my workspace.

I'll see if I can dredge up any of my past work on it. If not, I'll work on this after I get attack cooldown stuff up and running.

**Comment by Fortifier42** [comment]
This has been implemented.
