### ISSUE TITLE
Lore linewrap option on item scripts

### ISSUE THREAD

**Issue by SXRWahrheit** [DenizenScript/Denizen-For-Bukkit#1914]
Per Discord discussion: https://discordapp.com/channels/315163488085475337/315163488085475337/546431979340562447

```my_item:
  material: stick
  lore linewrap: 10
  lore:
    - "hello"
    - "there"
    - "this is a line that would get wrapped because it is too long"
```

The third line in this example would wrap based on the specified length

**Comment by mcmonkey4eva** [comment]
Makes no sense for item scripts. Those are hand-built, why do you need an auto-line-wrapper _there_ of all places? Takes very little effort to do it manually _in an item script_
+
There is no sane serverside linewrapper. Lengths are handled clientside, different characters are different widths based on the font.
The best line-wrapper is trial and error tbh. A by-character line wrapper would split "iiiiiiiiiiiiiiiiiiiiiiiiiiiiii" into 3 lines and consider "WWWWWWWWWW" just one. Those are about the same width on my screen, but one is 30 characters and the other is 10.
