### ISSUE TITLE
Add support for anvil inventories

### ISSUE THREAD

**Issue by waterquarks** [DenizenScript/Denizen-For-Bukkit#1915]
#1702 the screenshot in here shows the desired functionality: be able to put items inside anvil inventories, here's a reference for how to implement it https://github.com/WesJD/AnvilGUI/blob/master/api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java#L87

#1030 the event described here will complement the first feature, and its doable now since Spigot added support for it

**Comment by mcmonkey4eva** [comment]
The relevant event (issue 1030) is non-addable (as it doesn't exist in Spigot).
The linked code is based around sending NMS packets directly. We could have an 'anvil GUI' style of magic packet mech based on that conceptual setup, I guess... don't see much benefit to that though.

**Comment by smellyonionman** [comment]
I was actually hoping for exactly that.  Anvil GUIs could allow for capturing player text without cluttering the chat dialog.  Hypixel uses them for text input for the same reason, as their chat is so busy.

**Comment by mcmonkey4eva** [comment]
We don't have anvil GUIs yet, but earlier today I pushed some fixes to make anvil inventorytags at least work in the first place, which is step 1

**Comment by seb303** [comment]
Perhaps this library would be useful, either as a reference or a dependency:
https://github.com/WesJD/AnvilGUI
It looks quite comprehensive and actively maintained, covering the NMS integration from MC 1.7.10 to 1.18.2

**Comment by seb303** [comment]
Is there a reason why https://github.com/WesJD/AnvilGUI can't be used as a dependency?
Seems like it is quite actively maintained.  Wouldn't this be preferably to maintaining the NMS integration within the Denizen codebase?

Whichever way it's done, I would say that player text input is an important feature when implementing GUIs.  And I believe the Anvil GUI is the only way to achieve this.  (It's very clunky to take the user out of a GUI flow to type some text into the chat.)

**Comment by mcmonkey4eva** [comment]
In modern Denizen this is possible thanks to methods in paper, see example script @ https://paste.denizenscript.com/View/97593
