### ISSUE TITLE
More enum lists

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1916]
Tree types: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/TreeType.html
Map cursor types: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/map/MapCursor.Type.html
Potion types: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html
Potion effect types: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
Entity types: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
Banner/shield patterns: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/banner/PatternType.html

I had also found structure types, but since Denizen doesn't really have much things related to structures, I dunno if I should add them yet. Will link it just in case: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/StructureType.html

**Comment by mcmonkey4eva** [comment]
Invalid issue.

These are already documented in meta.

**Comment by Morphan1** [comment]
Per Discord:
```
suspicbot - Today at 3:35 PM
I probably should have clarified that I wanted them in tag format and not in the meta hm

Mergu - Today at 3:36 PM
@suspicbot yeah, go make it very clear you want tag versions and the benefits of those are:
1) version independence
2) cool list tags like .random
3) more magic stuff
```

**Comment by MusicScore** [comment]
Thanks Morphan! I already have the tags written out, just need to test on every Spigot version (*shudders*) and make a PR.
