### ISSUE TITLE
Cake consumption levels

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1921]
Thankfully Spigot isn't very clear on which one works :D 

Blockdata interface:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/data/type/Cake.html

Material data:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/material/Cake.html

**Comment by mcmonkey4eva** [comment]
BlockData is 1.13+ only

**Comment by mcmonkey4eva** [comment]
This appears to inexplicably not just use the Levelled interface despite being perfectly equivalent data.

**Comment by mcmonkey4eva** [comment]
Added as just part of the material level property... makes more sense than separating it.
