### ISSUE TITLE
Cauldron tags, mecs, and event

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1922]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/material/Cauldron.html
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/CauldronLevelChangeEvent.html
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/CauldronLevelChangeEvent.ChangeReason.html

**Comment by MusicScore** [comment]
Well, the only cauldron tags that can be added from the Spigot API are `isFull()` and `isEmpty()`. Completely pointless. The only other option for cauldron tags is a tag that returns the cauldron's water level, which can be achieved through equally pointless metadata (for 1.12 and below) or NMS.

I'll just add the event.

**Comment by MusicScore** [comment]
So the Cauldron material class is completely useless with regards to setting the water level of the cauldron, but there is a `Levelled` blockdata interface.

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/data/Levelled.html

**Comment by mcmonkey4eva** [comment]
Level property added in https://github.com/DenizenScript/Denizen-For-Bukkit/commit/613930898d0cb3539c3ae99be2f596adc00385e7

**Comment by mcmonkey4eva** [comment]
Event added.
