### ISSUE TITLE
feature request : (un)equips armor event cancellation

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#1928]
+++  on player (un)equips armor: 
+++   AKA: on player (un)equips <item>, on player (un)equips [helmet/chestplate/leggings/boots]
+++   Triggered: when a player (un)equips armor. 
+++   Context: <context.armor> returns the dItem that was (un)equipped.
+++   Context: <context.reason> returns the reason that the armor was (un)equipped. Can be "INVENTORY", "INTERACT", "DISPENSER", or "BREAK".

The idea is to add a "determine cancelled" possibility to this event like in <1.12.2

**Comment by mcmonkey4eva** [comment]
This was intentionally removed due to it not working and there not being any reasonable way to make it work.
