### ISSUE TITLE
Tags, Events & Mechanics for Recipe Book

### ISSUE THREAD

**Issue by ArctoranDev** [DenizenScript/Denizen-For-Bukkit#1931]
Essentially I have found there is nothing to interact with the recipe book but I also wanted to see if it was possible to have events for the recipe book open to override and open something else or just disable it.

**Comment by mcmonkey4eva** [comment]
Handled by the completion of #2031 

Events for the recipe book being opened/etc aren't possible. You can abuse `forget_recipe` mech to prevent the recipe book from being used.
