### ISSUE TITLE
Java 11 support: Missing classes for debug mode

### ISSUE THREAD

**Issue by Joo200** [DenizenScript/Denizen-For-Bukkit#1932]
The output of `/version` on my server is: 
21.02 21:56:48 [Server] INFO This server is running Paper version git-Paper-501 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) 21.02 21:56:48 [Server] INFO Previous version: git-Paper-a5172f8d (MC: 1.13.2)

The output of `/version denizen` on my server is: Denizen version 1.0.3-SNAPSHOT (build 1655-REL)

(If relevant) A link to a paste of a script demonstrating the issue: -
The issue is:
The plugin requires the class `sun/reflect/Reflection` for debug functions. This class is not in Java Runtime Environment 11.

How to get this error: Start a server with Java 11, enable debug mode and reload scripts from the disk.

**Comment by mcmonkey4eva** [comment]
Use Java 8.
Java 9+ are not supported by Minecraft, Spigot, or plugins.

**Comment by baba43** [comment]
Don't you think that future deprecations should be fixed anyway?

**Comment by Morphan1** [comment]
As the linked commit mentions, this should be fixed. However, other issues may arise when using currently unsupported Java versions and we continue to recommend you stick to 8.
