### ISSUE TITLE
Local Location Offsets

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#1938]
Minecraft 1.13 added "local coordinates" using caret symbols: https://minecraft.gamepedia.com/1.13

Although already technically possible with denizen, this would be super useful to have as a builtin utility. Syntax would be along the lines of `<l@location.local[<left>,<up>,<forwards>]>`

Here's an example of several armor stands being teleported to variations of `^3 ^ ^`, `^ ^3 ^`, and `^ ^ ^3` (in denizen, <location.local[0,0,3]> etc): 
https://streamable.com/pa3n7

**Comment by mcmonkey4eva** [comment]
That looks roughly like;
```
on tick:
- teleport <some entity> <player.location.add[<l@0,0,3.rotate_around_y[<player.location.yaw>]>]>
```

Is that `^` actual accessible functionality or is it just the native commands automatically do roughly the above?

**Comment by mcmonkey4eva** [comment]
(after getting clarification on Discord that it's the command block spamming it and that's not part of the feature request):
The request seems to just be a shorter premade tag for `<player.location.add[<l@0,0,3.rotate_around_y[<player.location.yaw>]>]>` ?

That could be handy, yeah.

**EDIT**: I'd suggest the name `relative` or ... something. I don't know, the name `local` is rather unclear I think.
