### ISSUE TITLE
Add varying blockdata and blockdata type properties

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1940]
May as well open an issue so I remember what needs doing.

Block data: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/data/package-summary.html
Block data types: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/data/type/package-summary.html

Note: some of the block data types seem to just be random things that directly implement the block data interfaces with no additional features. There are a few block data types with unique data, though. Like TurtleEgg: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/data/type/TurtleEgg.html

Partially covers #1922, minus the events.
Covers #1921

**Comment by mcmonkey4eva** [comment]
This is at least mostly covered now.
