### ISSUE TITLE
Item serialization/deserialization

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#1941]
We should have better ways to serialize/deserialize spigot objects that extend ConfigurationSerializable. Particularly for itemstacks, since those are unsafe to store if you prioritize data loss. Any unimplemented properties, which there are dozens to hundreds of (most requiring nms work), are lost. This feature would be a mostly internal one for use in notables, but could also be exposed to end users.

I actually haven't looked to see how notables (particularly notable inventories) serialize this stuff. If they already do this without data loss, feel free to correct me. I looked into reversing our `<i@item.json>` tag but couldn't find anything in nms to do this directly. We might consider creating mecs to adjust minecraft nbt directly, in which case json can be stored & parsed and the section below is mostly irrelevant.

Spigot has the ability to store objects implementing ConfigurationSerializable in yaml with very little to no data loss. We should look into https://hub.spigotmc.org/javadocs/spigot/org/bukkit/configuration/ConfigurationSection.html. Would be great to also expose this as tags & mecs.

**Comment by mcmonkey4eva** [comment]
`Any unimplemented properties, which there are dozens to hundreds of `
Whoa, what? Where are these missing item properties? I'm not aware of that at all.

`I actually haven't looked to see how notables (particularly notable inventories) serialize this stuff. If they already do this without data loss, feel free to correct me.`
They are lossless insofar as we implement properties for things - which the primary goal of our property system is to implement every property explicitly.
If there's anything missing, we should be explicitly implementing support.

-----

There is no way to losslessly serialize items stably - that's part of why the Denizen item property system exists.
The way item internal values are handled *changes* between Minecraft versions, and cannot be trusted. Denizen provides a system that is intercompatible.

**Comment by mergu** [comment]
From my previous research, bukkit has internal logic that converts serialized things between versions

Edit: Items are mostly missing EntityTag/BlockEntityTag nbt that defines what entity spawns on use or what the block's tiledata is on use
