### ISSUE TITLE
open_book mech should work for book and quill

### ISSUE THREAD

**Issue by lmorgh** [DenizenScript/Denizen-For-Bukkit#1943]
As far as I'm aware, there is currently no way of opening an editable book for players to type in, only signed ones.

**Comment by mcmonkey4eva** [comment]
Have you, er... tested `open_book` with a writable book? I don't see any reason that wouldn't work

**Comment by lmorgh** [comment]
Yes I have, no success.

**Comment by mcmonkey4eva** [comment]
I've confirmed that this is an issue. It seems `Book and Quill` doesn't open from usage of `open_book` - perhaps there's a separate packet for it? I can't find what it would be ... @mergu maybe you'd be interested in finding the proper packet?

**Comment by mergu** [comment]
From what I can tell it seems to be entirely clientside

**Comment by mcmonkey4eva** [comment]
:(

**Comment by Berufeng** [comment]
Yikes this is almost a year old. So it’s handled clientside, meaning there’s currently no way to make it work?

**Comment by mcmonkey4eva** [comment]
Correct.
