### ISSUE TITLE
on command event has both FULFILLED and CANCELLED as acceptable inputs

### ISSUE THREAD

**Issue by BehrRiley** [DenizenScript/Denizen-For-Bukkit#1944]
The output of `/version` on my server is: **git-Paper-591 (MC: 1.13.2)**
The output of `/version denizen` on my server is: **Denizen-1.0.4-b718-DEV**
The issue is:
on command event has both FULFILLED and CANCELLED as acceptable inputs

**Comment by MusicScore** [comment]
To add on to this: Note that the `on command` meta has no mention of the "CANCELLED" determination

**Comment by mcmonkey4eva** [comment]
This is not an issue.
`FULFILLED` is the proper input. `CANCELLED` is compatibility with mistakes (since most events are blocked by `CANCELLED`, and that's technically what `FULFILLED` does as well).
