### ISSUE TITLE
Add NPC option for `on player enters notable area`

### ISSUE THREAD

**Issue by BehrRiley** [DenizenScript/Denizen-For-Bukkit#1948]
Currently I'm detecting if NPCs enter cuboids specified in a timed queue and was interested in seeing if adding NPCs as a valid entity to detect for could be implemented. For the same reason why an event like 'on player steps on block' wouldn't have compatibility for entities specifically, I would imagine that NPCs would be different for this kind of event because they are controllable rather than for the most part spontaneous

**Comment by mcmonkey4eva** [comment]
There's nothing equivalent to an 'NPC move event' so any event like this would have some inherent performance and clean-impl issues.

**Comment by mcmonkey4eva** [comment]
I'm going to consider this part of #1996
