### ISSUE TITLE
add "on player clicks air"

### ISSUE THREAD

**Issue by waterquarks** [DenizenScript/Denizen-For-Bukkit#1953]
as a supporting feature of the "on player clicks block" event

**Comment by mcmonkey4eva** [comment]
This should work already, so long as you're holding an item.

I've been told in the past that if you click open air with an empty hand, there literally isn't even a packet sent to the server for that (ie we can't detect it). But just holding something suffices to make it work.

**Comment by mergu** [comment]
Clicking in the air with no held item *does* send the packet, but spigot intercepts and cancels it for some unknown reason
