### ISSUE TITLE
InventoryClickEvent error with no script and no plugin (only denizen)

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#1956]
The output of `/version` on my server is: **Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**

The output of `/version denizen` on my server is: **Denizen v1.0.4-SNAPSHOT (build 1673-REL)**
Error : **https://pastebin.com/EGXzgrWT**

denizen debug : **https://one.denizenscript.com/paste/54111**

The issue is:
**I open my inventory, take an item in it and click in the air with it (outside of my inventory) and I get an error**

Step : 
1. Open personal inventory
2. Take an item in it
3. Click with this item outside of the inventory, in the air (ex to trow it)

**Comment by mcmonkey4eva** [comment]
This was fixed by https://github.com/DenizenScript/Denizen-For-Bukkit/commit/e917fba0c8bd74d7454bccd881fddb0cd87deec9

Run latest dev build: https://ci.citizensnpcs.co/job/Denizen_Developmental/
