### ISSUE TITLE
NPCS TELEPORT

### ISSUE THREAD

**Issue by 3L3G4N7C0D3F24N** [DenizenScript/Denizen-For-Bukkit#1957]
I just want to ask if with this I can create (through the citizens) NPCS for teleports?

**Comment by Mwthorn** [comment]
I'm not exactly sure what you want to make, I assume you want players to teleport somewhere when they interact (click) on a npc? That can totally be done.

It is recommended you go through the guide videos first if you have not done that already: https://one.denizenscript.com/denizen/vids

If you need further help on how to get started or got other quick questions, head over to Discord: https://discord.gg/Q6pZGSR
