### ISSUE TITLE
On Identifying Items in Backpacks

### ISSUE THREAD

**Issue by FxRayHughes** [DenizenScript/Denizen-For-Bukkit#1958]
The output of `/version` on my server is: **This server is running CraftBukkit version git-Spigot-1eece4f-fac0eca (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **Denizen version 1.0.5-SNAPSHOT (build 777-DEV)**
(If relevant) A link to a paste of a script demonstrating the issue: **<inventory.can_fit[i@<context.args.get[2]>].quantity[<context.args.get[4]>]> == true**
The issue is:
**Describe your issue in full here**
  - if <context.args.get[1]||null> == test:
    - narrate '<inventory.can_fit[i@<context.args.get[2]>].quantity[<context.args.get[3]>]>'
![image](https://user-images.githubusercontent.com/25192142/57173529-d40dc280-6e63-11e9-926c-ebb652d3baaa.png)
It's not a Boolean value that's returned to me.
I want to identify whether there are a certain number of items in my backpack.
If this method can not be expected to provide an alternative detection method

**Comment by mcmonkey4eva** [comment]
Hi, I see you're new to Denizen! What you've written there isn't quite how scripts work in Denizen (primary visible problem is conceptual object handling).

Check the tutorial videos: https://one.denizenscript.com/denizen/vids
Or our new text tutorials: https://docs.denizenscript.com/

Also you can join us on Discord at https://discord.gg/Q6pZGSR to get help with scripting!
