### ISSUE TITLE
<l@location.material> throw NPE if world not loaded

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Denizen-For-Bukkit#1960]
The output of `/version` on my server is:
**This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
This is a final build for 1.13.2.**

The output of `/version denizen` on my server is: 
**Denizen version 1.0.5-SNAPSHOT (build 773-DEV)
Authors: mcmonkey, Morphan1 and aufdemrand**

(If relevant) A link to a paste of a script demonstrating the issue: 

**[16:05:36 INFO]:  ERROR in queue 'EXCOMMAND_KeepingClosedCrisis'! Tag <l@229,8,-18,0,150,flat.above.material> is invalid!
[16:05:36 INFO]: +> Executing 'NARRATE': Narrating='l@229,8,-18,0,150,flat.above.material'  Targets='[p@Oruss7]'
[16:05:36 INFO]:  Completing queue 'EXCOMMAND_KeepingClosedCrisis' in 10020ms.
[16:05:36 INFO]:  ERROR! Internal exception was thrown!
[16:05:36 INFO]:  ERROR! 16:05:36 [SEVERE] java.lang.NullPointerException
16:05:36 [SEVERE] org.bukkit.Location.getBlock(Location.java:96)
16:05:36 [SEVERE] net.aufdemrand.denizen.objects.dLocation.getAttribute(dLocation.java:738)
16:05:36 [SEVERE] net.aufdemrand.denizen.objects.dLocation.getAttribute(dLocation.java:649)
16:05:36 [SEVERE] net.aufdemrand.denizencore.objects.dObject.getObjectAttribute(dObject.java:115)
16:05:36 [SEVERE] net.aufdemrand.denizencore.utilities.CoreUtilities.autoAttrib(CoreUtilities.java:129)
16:05:36 [SEVERE] net.aufdemrand.denizencore.tags.TagManager.fetchObject(TagManager.java:306)
16:05:36 [SEVERE] net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:110)
16:05:36 [SEVERE] net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:326)
16:05:36 [SEVERE] java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
16:05:36 [SEVERE] java.util.concurrent.FutureTask.run(Unknown Source)
16:05:36 [SEVERE] java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
16:05:36 [SEVERE] java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
16:05:36 [SEVERE] java.lang.Thread.run(Unknown Source)**

The issue is:
**<l@location.material> throw NPE if world not loaded**

Thanks

**Comment by mcmonkey4eva** [comment]
What are you expecting would happen, when you try to read block data from a world that effectively doesn't exist?
