### ISSUE TITLE
furnace_recipe in Item script container wont work with Blast Furnace 1.14.1

### ISSUE THREAD

**Issue by Baktus79** [DenizenScript/Denizen-For-Bukkit#1962]
The output of `/version` on my server is: **git-Paper-20 (MC: 1.14.1)**
The output of `/version denizen` on my server is: **1.0.5-SNAPSHOT (build 1674-REL)**

The issue is:
**The furnace_recipe doesnt seem to work with blast furnace in 1.14.1. It works fine with normal furnace though.**

**Comment by mcmonkey4eva** [comment]
Not a bug. That's a feature. Blast furnaces are new in MC 1.14

**Comment by mcmonkey4eva** [comment]
This goes in #1951

**Comment by mcmonkey4eva** [comment]
Also going to crosslink to #1851

**Comment by mcmonkey4eva** [comment]
Added during the resolution to #1851
