### ISSUE TITLE
Mechanisms for Explosion Power and Explosion Radius

### ISSUE THREAD

**Issue by Lexo2011** [DenizenScript/Denizen-For-Bukkit#1965]
I request a feature to modify the mechanisms "Explosion Power" and "Explosion Radius" for [eplosive entities](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Explosive.html) similiar to the the parameters already existing in vanilla minecraft.

example command from vanilla: /summon Fireball ~ ~1 ~ **{ExplosionPower:5,ExplosionRadius:3}**

having those mechanisms implemented could proof usefull to further utilize the "shoot" and "summon" command in interesting ways.

**Comment by mcmonkey4eva** [comment]
Added ( thanks to @mergu !) in build DEV-811+
