### ISSUE TITLE
Add fancy-text handling support

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Denizen-For-Bukkit#1968]
Similar to D2's FormattedTextTag, possibly take advantage of something MCL-styled.
Needs to support both outputting in the `narrate` command, and usage for things like the book property and book scripts.

**Comment by BloodEko** [comment]
Depending on the complexity the narrate command could have simple new arguments hover:/click:/... or maybe a new dObject with/withot a own scriptcontainer ?

**Comment by mcmonkey4eva** [comment]
Done :D created a really awesome new system that doesn't involve any of that raw json nonsense (but then processes into/from the json nonsense)
