### ISSUE TITLE
OpenTrades command broken in 1.14

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Denizen-For-Bukkit#1969]
Related to #1951
Spigot 1.14.2, Denizen build DEV-816+, OpenTrades command is non-functional and requires reworking for the Minecraft 1.14 update (which alters villager trades significantly).

**Comment by MusicScore** [comment]
I would like to point out that the `opentrades` command seems to work for Spigot/Paper 1.14.4. I have not encountered an issue with the command after #1995 was fixed by commit 2b482915ede0171adbb59f255f902b79c0d03768.
