### ISSUE TITLE
Flag System Rewrite

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Denizen-For-Bukkit#1970]
We have a pending total rewrite of the flag system.

This relates in part to #1951 

Spigot 1.14 includes new tools (PersistentDataContainer) that allow for a newer, better way of storing entity flags, which may also be beneficial to players.

The flag code in general is very old and needs rewriting regardless.

The new code should add support for flagging locations.
It might be good as well to add support flagging items, taking over the 'nbt' command/tag/mech logic

**Comment by BloodEko** [comment]
Flags could be handled then also as Objects instead of Strings? When the server starts up the Strings from File are converted into Objects only once? Then flag[].as_item or so can be spared.

**Comment by mcmonkey4eva** [comment]
this happened
