### ISSUE TITLE
Event not triggering

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/Denizen-For-Bukkit#1974]
The output of `/version` on my server is: paper-mc 55 (1.14.2>
The output of `/version denizen` on my server is: Development build 829

The issue is:
on player RIGHT_CLICK_BLOCK clicks:
event isn't triggering

**Comment by mergu** [comment]
for some more info, it's because left/right click are hardcoded instead of checking against all click types

edit: also, these are the valid click types: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/Action.html

**Comment by mcmonkey4eva** [comment]
Why would you ever expect that event to work?
That's not valid syntax at all.
`on player right clicks block:`
