### ISSUE TITLE
Item Duping with Multiple items.

### ISSUE THREAD

**Issue by tardreted** [DenizenScript/Denizen-For-Bukkit#1980]
The output of `/version` on my server is: [08:32:32 INFO]: This server is running Paper version git-Paper-83 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
The output of `/version denizen` on my server is: [08:33:51 INFO]: version: 1.0.6-SNAPSHOT (build 851-DEV), core version: 1.40-SNAPSHOT (Build 275)
(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/paste/54715

Denizen recorded debug: https://one.denizenscript.com/paste/54713
The issue is:
Set this up on a test with ONLY those 2 scripts loaded, and ONLY citizens, denizen, depenizen, and sentinel installed. 
Here is a video of the dupe glitch https://cdn.discordapp.com/attachments/584919119124758529/589799350008414208/bug.mp4

putting more than 1 of an item in the crafting inventory for some reason causes the crafting inventory to double the items in it it seems like.

I've tried this on paper build 83 and 89, both do the exact same thing and output

**Comment by mcmonkey4eva** [comment]
Part of the item crafting meta-issue #1851

**Comment by mcmonkey4eva** [comment]
Fixed by the resolution to #1851
