### ISSUE TITLE
Context.breeder has issues when using the breed event

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/Denizen-For-Bukkit#1981]
The output of `/version` on my server is: git-Paper-90 (MC: 1.14.2)
The output of `/version denizen` on my server is: 1.0.6-SNAPSHOT (build 851-DEV)
The issue is:
When using the event "on entity breeds" the following tag does not parse:
<context.breeder.has_permission[SomePermissionHere]>
 
while the following tag works just fine:
<server.match_player[<context.breeder.name>].has_permission[SomePermissionHere]>:

this is a debug I've run on the tag that doesn't parse: 
https://one.denizenscript.com/paste/54718

**Comment by mcmonkey4eva** [comment]
Fixed for build DEV-852+
