### ISSUE TITLE
I can not connect to the server

### ISSUE THREAD

**Issue by llronaldoll** [DenizenScript/Denizen-For-Bukkit#1982]
The output of `/version` on my server is: **paste here** 1.14.2
The output of `/version denizen` on my server is: **paste here** Denizen-1.0.5-b1674-REL
(If relevant) A link to a paste of a script demonstrating the issue: **paste here**
The issue is:
**Describe your issue in full here**

I can not connect to the server after adding denizen plugin, apparently there is no error, but I can not connect!

**Comment by MoreUmph** [comment]
Update to the latest developmental build of Denizen, the last release doesnt support 1.14x

**Comment by llronaldoll** [comment]
Can you show me the link?

**Comment by MoreUmph** [comment]
https://ci.citizensnpcs.co/job/Denizen_Developmental/
