### ISSUE TITLE
Ability to set Repair Cost and Custom Model Data in Item Script Containers.

### ISSUE THREAD

**Issue by Dystify** [DenizenScript/Denizen-For-Bukkit#1984]
Hello,

I would like to request two things for the Item Script Containers:

1) The ability to set a repair cost for a custom item.
In vanilla Minecraft this would be RepairCost. For example: /give player item{RepairCost:99999}

2) The ability to set Custom Model Data for a custom item. This is a new feature in 1.14 which allows any item to have any texture/model, depending on the resource pack used. It's a really great an important feature, in my opinion. In vanilla Minecraft this would be CustomModelData. For example: /give player item{CustomModelData:1} 

I'm not sure if RepairCost is already a thing, I asked on Discord and apparently it is not, but I'm not 100% sure.

Thank you in advance.

**Comment by mcmonkey4eva** [comment]
Added both!
