### ISSUE TITLE
dDiscordbot <context.message>

### ISSUE THREAD

**Issue by LeafyMitsuwa** [DenizenScript/Denizen-For-Bukkit#1985]
Any chance we might be able to use <.get[]> or <.args.get[]> on <context.message> within 'on discord message received'

I'd like to set up custom discord commands such as 'd!MyDiscordCommand <Variable>', or something along the lines. Ofcourse, I'm open to feedback on better implementations.

Currently, <context.message.contains_any_text[d!MyDiscordCommand]> can catch the discord message, but then ... eh.

I guess converting the message into a word-separated list could do the trick, but I'm hoping there's an easier solution.

**Comment by mcmonkey4eva** [comment]
dDiscordBot issues go on the dDiscordBot repo https://github.com/DenizenScript/dDiscordBot/issues

**Comment by mcmonkey4eva** [comment]
You can also just do `<context.message.split>` btw, to get basically the exact same result.
