### ISSUE TITLE
shoot

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/Denizen-For-Bukkit#1986]
The output of `/version` on my server is: Paper 632 (MC 1.13.2)
The output of `/version denizen` on my server is: Denizen dev build 898
The issue is:
When using the shoot command and looking straight down a console error is thrown. The entity just falls to the ground. (tested with arrows and fireball, on the above version, and Paper 115 (Mc 1.14.3)
https://one.denizenscript.com/paste/54975

**Comment by mcmonkey4eva** [comment]
Use the `speed:` argument when using the shoot command.
