### ISSUE TITLE
"automatic type" sign command broken between BuildREL 1673 and 1676

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#1989]
The output of `/version` on my server is: **git-Paper-597 (MC: 1.13.2)**
The output of `/version denizen` on my server is: **1.0.6-SNAPSHOT (build 1676-REL)**

The "type: automatic" for the sign change the direction of the sign
Command used : /Ex sign <player.location.cursor_on> li@bla|nlah|bha|dfjso type:automatic

![image](https://user-images.githubusercontent.com/20723083/60357819-f55add00-99d4-11e9-9f67-e4b099dee209.png)
![image](https://user-images.githubusercontent.com/20723083/60357837-fc81eb00-99d4-11e9-9ee4-6326bee105f6.png)

same for wall sign
![image](https://user-images.githubusercontent.com/20723083/60357907-2affc600-99d5-11e9-969e-fd9d6dd99dad.png)
![image](https://user-images.githubusercontent.com/20723083/60357916-318e3d80-99d5-11e9-8184-b20d82d52c1b.png)

**Comment by Astrareach** [comment]
as we can see here, all the sign are pointing south when using "automatic"
![image](https://user-images.githubusercontent.com/20723083/60358286-f3dde480-99d5-11e9-9858-6eae48de3c1b.png)

**Comment by Astrareach** [comment]
When it is wall_sign, they transform into normal sign pointing also the south
![image](https://user-images.githubusercontent.com/20723083/60358435-5505b800-99d6-11e9-971a-d57a611d7a7f.png)

**Comment by mcmonkey4eva** [comment]
This was broken by morph's initial 1.14 update here: https://github.com/DenizenScript/Denizen-For-Bukkit/commit/3255c273088a5d33edfab48d7d03f93ebb42c057#diff-b69675742fe4ec7f1807da97e3e183d9L117 due to an accidentally inverted if check.

Fixed for build DEV-907+, and fix validated (at least in 1.14)
