### ISSUE TITLE
<location.attached_to> returning block above when placed on top

### ISSUE THREAD

**Issue by DerrickDenum** [DenizenScript/Denizen-For-Bukkit#1990]
https://one.denizenscript.com/paste/55114

**The output of `/version` on my server is:** This server is running Paper version git-Paper-120 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
**The output of `/version denizen` on my server is:** Denizen version 1.0.6-SNAPSHOT (build 914-DEV)

**The issue is:**
Placing a lever, on top a block, while facing **south** or **east** will return the location above the lever instead of the one it's attached to.
Placing a button, on top a block, while facing **south**, **east** or **west** will return the location above the button instead of the one it's attached to.

**Comment by mcmonkey4eva** [comment]
The return value there is entirely based on Spigot MaterialData methods. If that's wrong, Spigot broke it not us.
That said, we could still replace the logic in 1.13+ with BlockData based methods (the new preferred option).

**Comment by mcmonkey4eva** [comment]
Fixed for build DEV-927+ for 1.13+ servers using modern block data.
