### ISSUE TITLE
When the server start, Denizen failed to load notables

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#1991]
The output of `/version` on my server is: **git-Paper-624 (MC: 1.13.2)**
The output of `/version denizen` on my server is: **1.0.6-SNAPSHOT (build 934-DEV)**
Content of notables.yml : **https://pastebin.com/4cwCZgdA**
Specific error : **https://pastebin.com/SuijVDgC** (that don't show everytime)
The issue is:
**Creating the notable work fine, but when we restart the server, certains notables won't load**

**Comment by Astrareach** [comment]
Result of the test command (at the creation of the notable its not like that, its written with the name but not after the restart)
![image](https://user-images.githubusercontent.com/20723083/61075035-6d83c280-a419-11e9-83bf-97e2ffa5af75.png)

**Comment by Astrareach** [comment]
When updating to dev 908 to dev 934 there is a risk that all the cuboids notable get deleted
My file after the update : https://pastebin.com/Fy0AePX4

**Comment by mcmonkey4eva** [comment]
Are those worlds late-loaded? (ie they're not present at server start?) It might be breaking because it doesn't have the worlds

**Comment by mcmonkey4eva** [comment]
Also: If you have `debug` disabled in the Denizen config (ie defaults to off at server start) please enable that. The information output at startup is important.

**Comment by mcmonkey4eva** [comment]
If world late-loading is the issue, should be fixed as of build DEV-940. If it's not, please reply below with any additional information you can provide.
