### ISSUE TITLE
Showfake Schematics, Schematic.blocks Tag Feature Request

### ISSUE THREAD

**Issue by Insilvon** [DenizenScript/Denizen-For-Bukkit#1992]
Currently, the <CuboidTag.blocks[<material>|...]> tag provides a nice list of all block locations in the cuboid, where as the similar schematic tag <schematic[<name>].blocks> only returns the number of blocks present in the schematic. This makes traversal of cuboids far easier than that of schematics.

A tag which would allow iteration over all schematic blocks relative to their origin would allow for easy traversal of potential schematics, allowing for easy previewing of schematics with showfake. 

Alternatively, the ability to simply showfake an entire schematic similar to traditional paste would be even better.

**Comment by mcmonkey4eva** [comment]
For the blocks tag thing, use `<schematic[<name>].cuboid[<origin location>]>` and then use cuboid tags.
