### ISSUE TITLE
Event: on flag expires, only fires when the flag is created

### ISSUE THREAD

**Issue by DerrickDenum** [DenizenScript/Denizen-For-Bukkit#1994]
The output of `/version` on my server is: **This server is running Paper version git-Paper-147 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **Denizen version 1.1.0-SNAPSHOT (build 989-DEV)**

The issue is:
**If I create a new flag on an entity/player or server with a duration, the on flag expires event will fire immediately, when the flag with a duration is created. When the flag eventually does expire, the event does not fire.**

**Comment by mcmonkey4eva** [comment]
https://one.denizenscript.com/denizen/evts/flag%20expires
The docs say:
`
Warning | This event will fire rapidly and  not exactly when you might expect it to fire. Generally, do not use this  event unless you know what you're doing.
`

Don't use that event.
