### ISSUE TITLE
on entity enters/exits notable cuboid

### ISSUE THREAD

**Issue by realdagumboss** [DenizenScript/Denizen-For-Bukkit#1996]
An event for entities entering/exiting notable cuboids would be useful. I'm still getting a handle on denizens but from what I'm seeing there's no similar event.

**Comment by mcmonkey4eva** [comment]
Any system to process this would almost certainly induce lag, making it a rather weird one to attempt.

**Comment by ArctoranDev** [comment]
> 
> 
> Any system to process this would almost certainly induce lag, making it a rather weird one to attempt.

If it's in relation to vehicles could you not link it to `on player steers entity` and check the context entity's location, I know it would fire rapidly but could probably add a small tick counter to only run every so many ticks.

**Comment by mcmonkey4eva** [comment]
This issue is not specific to vehicles at all
