### ISSUE TITLE
show_book mechanic doesn't work

### ISSUE THREAD

**Issue by Nakigoee** [DenizenScript/Denizen-For-Bukkit#1997]
Spigot version and Denizen version: https://one.denizenscript.com/paste/56398
My script: https://one.denizenscript.com/haste/56386

I cannot display the book when I use the command /ex -q adjust `<player>` show_book:GREETING_BOOK, but I hear the sound

**Comment by mcmonkey4eva** [comment]
Fixed for build DEV-999+ https://ci.citizensnpcs.co/job/Denizen_Developmental/

Thanks for the report!
