### ISSUE TITLE
No Show Sneaking After /npc sneak

### ISSUE THREAD

**Issue by TheCalypso** [DenizenScript/Denizen-For-Bukkit#1999]
![image](https://user-images.githubusercontent.com/33781244/62531059-f7208780-b841-11e9-9637-97f31d64ac0e.png)

Hello,

From the tests we have done, when we run the command "/ npc sneak" the message shows that the NPC is sneak but the NPC does not sneak. It's an NPC player like you and me.

We have no error in the console.

```
This server is running Paper version git-Paper-156 (MC:1.14.4) Implementing API version 1.14.4-R0.1-SNAPSHOT)
Checking version, please wait...
You are 3 version(s) behind

Citizens version 2.0.25-SNAPSHOT (build 1738)
Website: https://www.citizensnpc.co
Author: Fullwall

Denizen version 1.0.6-SNAPSHOT (build 1676-REL)
Author: The DenizenScript Team
```

**Comment by mcmonkey4eva** [comment]
- Please include your Denizen version
- What entity type is the NPC (player, villager, ...?)

**Comment by TheCalypso** [comment]
It's good

**Comment by mcmonkey4eva** [comment]
... That confused me, until I realized you edited the main post.

Update Denizen, you're quite far behind: https://ci.citizensnpcs.co/job/Denizen/

**Comment by TheCalypso** [comment]
We have just tried with the latest version but the result is the same :(

Version 1.1.0 of Denizens

**Comment by TheCalypso** [comment]
I have test something like that: 
/npc sneak
/npc sneak
/npc stand
and I have like anwser "test (npc name) is already standing !' 
But the NPC never sneak.

**Comment by axemwa** [comment]
I think it might be client side visual bug, cause when I join my 1.14.4 server on a 1.14.4 client the NPC doesn't appear to be crouching however when I join my 1.14.4 server on a 1.13.2 client the npc crouches

**Comment by jedrekiki** [comment]
I have the same problem. I have Minecraft 1.14.4. When i use /npc sneak command there is message that npc is sneaking but npc is still just standing. I have tried several versions of denizen and citizens but it hasn't changed 
anything.

**Comment by mcmonkey4eva** [comment]
The original code for this relied on Bukkit calls... but Spigot appears to have not updated how those calls work for 1.14.x.
I've gone ahead and implemented an NMS module based solution to make it work properly again.

**Comment by TheCalypso** [comment]
Thank you very much for your work !
