### ISSUE TITLE
on votifier vote spits out an error in console

### ISSUE THREAD

**Issue by DerrickDenum** [DenizenScript/Denizen-For-Bukkit#2000]
https://one.denizenscript.com/paste/56573
The output of `/version` on my server is: **This server is running Paper version git-Paper-159 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **version: 1.1.0-SNAPSHOT (build 4003-DEV), core version: 1.50-SNAPSHOT (Build 344)**
Depenizen version is: **Depenizen-2.0.0-b512**
The issue is:
**That error in the paste is in the console whenever the server receives a vote record and the on votifier vote event is triggered. I only have a narrate command, since I was just testing it out.**
Server Plugins:
Plugins (5): Citizens, CoreProtect, Denizen, Depenizen, Votifier

**Comment by mcmonkey4eva** [comment]
Wrong repo. Post on Depenizen: https://github.com/DenizenScript/Depenizen

**Comment by mcmonkey4eva** [comment]
Also, fixed in Depenizen build 513+
