### ISSUE TITLE
Item display name change to cursive

### ISSUE THREAD

**Issue by DerbanTC** [DenizenScript/Denizen-For-Bukkit#2001]
`/version` **git-Paper-641 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
`/version denizen` **1.1.0-SNAPSHOT (build 4002-DEV)**
**https://one.denizenscript.com/haste/56534**

**The issue is:**
Saveing content from a specific slot (e.g. from a dInventory) into a yaml or flag does change the item display name to cursive when the item are reproduced (e.g. with procedural items) by the stored arguments. This only happens when the item are a dItem and the display name are only white, other colors are working fine.

Replicate (script above): Grab the dItem, put it into the dInventory and re-open the dInventory. The display name from the dItem are now cursive and also not longer stackable with the original item.

Thanks und greets, Derban

**Comment by mcmonkey4eva** [comment]
I'd recommend using Notable Inventories instead of the YAML setup for tracking persistent inventories.

As for the error itself: Please post a debug recording of the issue (use `/denizen debug -r`, then run the script to demonstrate the issue, then `/denizen submit`)

**Comment by DerbanTC** [comment]
debug: https://one.denizenscript.com/paste/56626

the only filled <white> Tag into the debug is by giving the original item. 
In this debug here https://one.denizenscript.com/paste/56627 I had put a dItem with a blue display name and you will finde the `&ss9` into the debug often.

YAML notation provides data storage with none-loading if they are not needed, and that is pretty smart and usefull for an extended GUI using e.g. in my case for blocks with function kinda like machines. I will ask you in the discord about..but it looks like a none-notation of white tags above..

greets Derban

**Comment by mcmonkey4eva** [comment]
This appears to amount to an issue in Spigot or Minecraft itself: It's built to strip redundant characters, and it treats `<white>` at the start as redundant (ie it doesn't understand that item names aren't white by default).

This has nothing specific to any of your script there other than the item script itself, the usage of `<white>` as the first text in a display name gets borked.

To counteract this, use `<reset><white>`
