### ISSUE TITLE
Issue with "on player takes item from inventory" event

### ISSUE THREAD

**Issue by Baileyc889** [DenizenScript/Denizen-For-Bukkit#2002]
The "on player takes item from furnace" event seems to be working incorrectly. From my testing, the <context.item> tag returns the item that was cooking (not the fuel) and not the resulting item. When I tested "on player takes HeatedIron from furnace" in the event header, the event did not fire. When I tested "on player takes iron_ingot from furnace" the event did fire. 

In the furnace, I placed iron_ingot to be cooked, and the resulting item was HeatedIron, as expected. However the tag did not parse the correct item.

Here are the links to my code and the debug:
https://one.denizenscript.com/haste/56632
https://one.denizenscript.com/paste/56633

My discord name is Bailey#7973

**Comment by mcmonkey4eva** [comment]
The item context isn't "the cooking item and not the result".
It's the result item with all extra data stripped. This is an unfortunate oddity of the underlying Spigot API event.
Consider using `<context.location.inventory.*>` tags instead.
