### ISSUE TITLE
server crashing when using wait commands in a world script

### ISSUE THREAD

**Issue by calico-kid** [DenizenScript/Denizen-For-Bukkit#2003]
server crash report https://one.denizenscript.com/haste/57093

version is 1.14.4 paper build 173
denizen version is Denizen-1.1.0-b4041-DEV

script is https://one.denizenscript.com/haste/57094

it appears the wait in the events is crashing the server 
to reproduce do /ex give i@mountain_dew ingame and right click with it. it will make the correct sounds and then crash right at the wait portion of each script. does the same with the burritos and tacos too

**Comment by mcmonkey4eva** [comment]
Wait commands are not the problem. The LACK of wait commands are.
```

        on player right clicks with mountain_dew:
        - take i@mountain_dew  
```

You can't edit the inventory in an inventory related event.
