### ISSUE TITLE
Shift Click Inventory issue.

### ISSUE THREAD

**Issue by Tombstone1973** [DenizenScript/Denizen-For-Bukkit#2005]
The output of `/version` on my server is: This server is running Paper version git-Paper-642 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

[INFO] Previous version: git-Paper-641 (MC: 1.13.2)

[INFO] You are running the latest version
The output of `/version denizen` on my server is: [INFO] by:  DENIZEN: scriptable Minecraft!

[INFO]

[INFO] by: the DenizenScript team, with help from many skilled contributors!

[INFO] chat with us at: https://discord.gg/Q6pZGSR

[INFO] or learn more at: https://denizenscript.com

[INFO] version: 1.1.0-SNAPSHOT (build 1681-REL), core version: 1.50-SNAPSHOT (Build 346)
(If relevant) A link to a paste of a script demonstrating the issue: https://pastebin.com/x6DhE0Y1
The issue is:
Shulker Boxes are able to be manipulated with hot bar clicks and with shift clicks. Debug Report: https://one.denizenscript.com/paste/57194

**Comment by mcmonkey4eva** [comment]
Can you get rid of `/denizen debug -v` and post a cleaner debug recording? That one's rather difficulty to read

Also, use https://one.denizenscript.com/haste to paste your script

**Comment by mcmonkey4eva** [comment]
Also this looks to be a script issue rather than a bug, please join our Discord at https://discord.gg/Q6pZGSR and ask for help there
