### ISSUE TITLE
Tags for item frame and the block it hangs on

### ISSUE THREAD

**Issue by Baileyc889** [DenizenScript/Denizen-For-Bukkit#2006]
Could a tag be added to return the location of the block an item frame is hung on? The tag could be:

<entitytag.hung_block> Returns a location

In addition to this, could a tag be added for if a block has an hung item frame. It could be:

<locationtag.has_hung_entity> Returns true or false.

<locationtag.hung_entity> Returns the entity that is hung.

**Comment by mcmonkey4eva** [comment]
use `entity.attached_block` in new dev build.

For the Location get hanging -> use `find.entities[item_frame|painting].within[1]` or similar
