### ISSUE TITLE
Cauldron Events Not Triggering

### ISSUE THREAD

**Issue by CounterCrysis** [DenizenScript/Denizen-For-Bukkit#2012]
The output of `/version` on my server is: 
**This server is running CraftBukkit version git-Spigot-065a373-8d4bc54 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)**

The output of `/version denizen` on my server is: 
**version: 1.1.0-SNAPSHOT (build 4072-DEV), core version: 1.50-SNAPSHOT (Build 360)**

(If relevant) A link to a paste of a script demonstrating the issue: 
**https://one.denizenscript.com/haste/57494**

The issue is:
**Cauldron events for when the water level changes are not working.**

**Comment by Ph4i1ur3** [comment]
Testing on the latest dev builds shows this event is working fine with the exception of "on cauldron level raises"

As for your example script, two of those events would work if you specified a player to narrate to.
