### ISSUE TITLE
base_color mechanic doesn't work

### ISSUE THREAD

**Issue by Nakigoee** [DenizenScript/Denizen-For-Bukkit#2015]
Spigot version and Denizen version: https://one.denizenscript.com/paste/57539

I cannot change colors or patterns of banners. What I see when I target a banner and use the command: "/ex -q adjust <player.location.cursor_on> base_color:red" :
---> https://cdn.discordapp.com/attachments/480724473046237204/617361466374225921/log.jpg

**Comment by Ph4i1ur3** [comment]
Banners cannot be modified via the adjust command (blocks neither, for that matter). You must replace it with a new one, with the mechanisms you wish to apply.

**Comment by Nakigoee** [comment]
For exemple it works perfectly with signs (a block), by only using adjust command (sign_content mecha), or to change the type of a block with block_type mecha, I needn't replace it

**Comment by Ph4i1ur3** [comment]
As of 1.13.2 base_color can no longer be changed via this mechanism, due to each color of banner now having it's own material, opposed to saving it's color in blockstate.

**Comment by Ph4i1ur3** [comment]
As an aside, the block_type mech works just fine.

**Comment by mcmonkey4eva** [comment]
What's wrong with `patterns`?

**Comment by Nakigoee** [comment]
My bad, `patterns` works fine, it's just `base_color` that doesn't work

**Comment by mcmonkey4eva** [comment]
In that case: refer to the meta correction made and to what @Ph4i1ur3 said.
