### ISSUE TITLE
Tag <n@id.location> is invalid!

### ISSUE THREAD

**Issue by XonePlay** [DenizenScript/Denizen-For-Bukkit#2016]
Tags like **`<n@49.location>`** don't work.

Denizen version: **1.1.0-SNAPSHOT (build 4070_DEV)**
Spigot version: **1.14.4-R0.1-SNAPSHOT**

**Comment by calico-kid** [comment]
What is the relevant script your trying to use that with?

**Comment by XonePlay** [comment]
Just with a narrate it does not work,

`/ex narrate "<n@49.location>"`

**Comment by Ph4i1ur3** [comment]
what is the output of `/ex narrate <npc[49]>`

**Comment by calico-kid** [comment]
Well location would be a tag so make that a tag <>

**Comment by mcmonkey4eva** [comment]
I've edited almost every post here to fix the lack of \` usage (if you don't put your tags into code blocks, GitHub won't render it properly).

Regarding the original question:
- You did not follow the issue template, therefore your post is automatically invalid until you correct that.
- If you run old dev builds, you deserve any issues you get. Use a release build OR latest dev build.
- Don't use raw object notation in scripts (the `n@id` format). Use actual objects (or tags that get the objects). For `/ex` usage, generally just do `<npc.location>` while the NPC is selected.
- Post a debug recording for errors like this. We can't read minds.
- If you haven't already... join the Discord: https://discord.gg/Q6pZGSR
