### ISSUE TITLE
<context.slot> tag addition for “on player item takes damage” event

### ISSUE THREAD

**Issue by Baileyc889** [DenizenScript/Denizen-For-Bukkit#2024]
Could a tag be added for the slot the item taking damage is in?

**Comment by mcmonkey4eva** [comment]
I believe the event will only fire for the player's held item (not armor/etc) based on the description of the underlying Spigot event. The underlying Spigot event also does not supply slot info.
So, `<player.item_in_hand.slot>`.
If you can get it to actually fire for equipment/similar, reply below and I'll see about janking a way to get that data.

**Comment by Baileyc889** [comment]
The event does indeed fire for when armor is damaged via mobs, cactus, explosion, etc.

**Comment by mcmonkey4eva** [comment]
That's... annoying, that Spigot doesn't have a slot value included.

**Comment by mcmonkey4eva** [comment]
Added via https://github.com/DenizenScript/Denizen/commit/e0b62d0540a3e05851795bef7f4cb944603c3ed1

Does some quick calculations to try to locate the item. I can't guarantee total accuracy but I think it should be correct.
