### ISSUE TITLE
Mec/tag to grab item from trident projectile

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#2025]
Spigot doesn't expose an easy way to grab the trident item from a trident entity, meaning that data is inaccessible for the various projectile events. Minecraft stores the item inside the projectile though: https://minecraft.gamepedia.com/Trident#Entity_data. Would be nice to have access to that info

**Comment by mcmonkey4eva** [comment]
Added via NMS calls to the `Item` entity property.
