### ISSUE TITLE
Broken <def[hit_entities]> in 1.14.4

### ISSUE THREAD

**Issue by DerbanTC** [DenizenScript/Denizen-For-Bukkit#2027]
`/version`  **git-Paper-187 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)**
`/version denizen`  **version: 1.1.0-SNAPSHOT (build 4122-DEV), core version: 1.50-SNAPSHOT (Build 372)**
Debug: https://one.denizenscript.com/paste/58326
Script: https://one.denizenscript.com/haste/58327

The tag `<def[hit_entities]>` is broken in 1.14.4
It works in in 1.13.2 tested with same denizen version

**Comment by mcmonkey4eva** [comment]
This looks like you just didn't hit anything? The tag returned an empty list.

**Comment by DerbanTC** [comment]
Video and referenced debug:
https://youtu.be/8hBysVJfHeg
https://one.denizenscript.com/paste/58389

After the Video I also updatetd both server to build `4136` you can see the debug vom the shooting there, same result...
https://one.denizenscript.com/paste/58393

**Comment by mcmonkey4eva** [comment]
You are very clearly not hitting your targets (notice how they don't react at all?)
I don't think `item_projectile` _can_ hit targets in the first place actually. You'd need an actual weapon projectile, like snowball or arrow.
