### ISSUE TITLE
Broken <player.item_in_hand.slot> in 1.13.2

### ISSUE THREAD

**Issue by DerbanTC** [DenizenScript/Denizen-For-Bukkit#2028]
`/version` **git-Paper-645 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
`/version denizen` **1.1.0-SNAPSHOT (build 4130-DEV), core version: 1.50-SNAPSHOT (Build 379)**
Debug: https://one.denizenscript.com/paste/58329
Script: https://one.denizenscript.com/haste/58330

Tag `<player.item_in_hand.slot>` is broken in both MC-Versions,
1.13.2 and 1.14.4 tested with same denizen versions `4130-DEV`

**Comment by mcmonkey4eva** [comment]
Are you sure this is a 1.14 vs 1.13 issue? Both this and your other issue #2027 say "same Denizen version" but that one is 4122-DEV and this is 4130-DEV.
I'd suspect a Denizen version difference at fault here rather than a server version difference...

**Comment by DerbanTC** [comment]
Updatet both server to `4136`.
The <player.item_in_hand.slot> tag works now, this issue can be closed, thanks...
