### ISSUE TITLE
Portal Create Bug

### ISSUE THREAD

**Issue by CounterCrysis** [DenizenScript/Denizen-For-Bukkit#2029]
The output of `/version` on my server is: 
**This server is running CraftBukkit version git-Spigot-94af569-6ddeb98 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)**

The output of `/version denizen` on my server is: 
**version: 1.1.0-SNAPSHOT (build 4131-DEV), core version: 1.50-SNAPSHOT (Build 379)**

A link to a paste of a script demonstrating the issue: 
**https://one.denizenscript.com/haste/58376**

The issue is:
**The _portal create_ event does not trigger unless the optional _because reason_ is provided.**

**Comment by mcmonkey4eva** [comment]
Fixed via #2030
