### ISSUE TITLE
Recipe book / knowledge_book item additions

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#2031]
With the newly fixed recipes (thanks!), it'd be great to have them also optionally show up in players' recipe books. Assumption is the recipe-related methods here would work for this: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/HumanEntity.html, would be nice to have accessors/mutators for vanilla and denizen recipes. Maybe even an item script arg.

Would also be nice to have some knowledge_book properties: 
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/meta/KnowledgeBookMeta.html
https://minecraft.gamepedia.com/Knowledge_book

**Comment by mcmonkey4eva** [comment]
- Added knowledge_book item property.
- Added information to item scripts about what their internal Namespace:Key ID will be (a way to set it manually might make sense, but also seems like it'd be a bit of extraneous complication / mess in the item script format).
- Added mechanisms to add/remove discovered recipes.

I wanted to add a tag to display the list of recipes a player has discovered, but there doesn't seem to be a Spigot API method for that? The NMS calls to read it manually would need to be reflection-based, which is awkward...

**Comment by mergu** [comment]
The 2nd to last post here seems to imply you can use another class instead of a reflection-based way. I haven't looked too much into it, but would be nice to have. https://www.spigotmc.org/threads/get-discovered-recipes.382243/ Also would be nice to be able to get a list of all loaded item scripts and a way to get an item script's list of internal recipe ids for doing stuff like discovering on login or clearing on script reload. Can make a new feature request for this if needed

Edit: Access to the various types of recipes (furnace, crafting, etc.) for this would also be super useful: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Bukkit.html#getRecipesFor-org.bukkit.inventory.ItemStack-

**Comment by mcmonkey4eva** [comment]
That linked code seems to start getting the recipe book from a player... then at the point where it should be reflecting to get the discovered list, switches over to just getting the global recipe list instead for some reason. The part where you go from RecipeBook instance to list of recipes is the part that looked like it needed a reflection based reading.
Regardless: having to NMS something that should reasonably be in the API is annoying.

Also, added a tag `recipe_ids` that does both vanilla and script items in one.
