### ISSUE TITLE
Problem with sitting NPC

### ISSUE THREAD

**Issue by Flayer1s** [DenizenScript/Denizen-For-Bukkit#2033]
Hello.

I´ve got a problem. When I create a sitting NPC and i restart the server. It makes this. >> https://ctrlv.cz/CcuN << Any ideas what can I do? Thanks.

**Comment by mcmonkey4eva** [comment]
Follow the issue template.
We need your `/version`, `/version denizen`, and `/version citizens`

**Comment by Flayer1s** [comment]
Spigot 1.12.2 , 1.1.0 Snapshot Denizen , Citizen - 2.0.22 Snapshot

**Comment by mcmonkey4eva** [comment]
Yeah, no... that's not the output of the commands requested. Also, update all of those.

Closing as old-version-induced issue (user error). For basic help, ask on Discord: https://discord.gg/Q6pZGSR
