### ISSUE TITLE
Paper server list ping event

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#2035]
Paper allows for full control of the packet sent to the client in the server list via https://papermc.io/javadocs/paper/1.14/com/destroystokyo/paper/event/server/PaperServerListPingEvent.html

Ideally the denizen implementation should also allow arbitrary (colorable) strings in the player list.

**Comment by mcmonkey4eva** [comment]
What needs to be included in the paper-version of the event that isn't in the Spigot version?
Bearing in mind that altering the players-online value is intentionally excluded from scripts.

**Comment by mcmonkey4eva** [comment]
Closing until an answer is given, at which point the issue will be reopened.
