### ISSUE TITLE
Add line context tag for "on script generates error"

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#2036]
Since the newer versions of denizen has an error message containing the line of the source of the error, it would be nice to also include it in the script event.

A tag for line of the source script file the error came from, I suggest: <context.line>
We can already get the file-name of the source using <context.queue.script.relative_filename>
If the line of the error cannot be found, it should just return an error and use fall back tags.

This issue is also related to #1653

**Comment by mcmonkey4eva** [comment]
`using <context.queue.script.relative_filename>`
No.
Use: `<context.script.relative_filename>`
There's already a `<context.script>`.

'line' context added.
