### ISSUE TITLE
Pre script reload event

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#2039]
Reloading scripts involves unregistering recipes from the server but not online players. An event should fire before this step so we can clean player recipes up without requiring a relog. Cases where this might become weird, such as server restarts or crashes, won't involve online players and so they will always reliably fix recipes even without dScript being called. 

If there is a more elegant way of solving this issue, I am all ears

**Comment by mcmonkey4eva** [comment]
`more elegant way of solving this issue,` -> ` requiring a relog`

`Cases where this might become weird,` requesting a Denizen feature != just for you. It's for all Denizen users, and it's _general_ applicability needs to be considered, not your personal use case alone.

**Comment by mergu** [comment]
Requiring a relog is unacceptable for tasks that can be done without one. The general applicability of this event is access to script containers before changes are applied.

**Comment by mcmonkey4eva** [comment]
Added
