### ISSUE TITLE
Uplift to PortalCreateEvent

### ISSUE THREAD

**Issue by CounterCrysis** [DenizenScript/Denizen-For-Bukkit#2043]
Class [EntityCreatePortalScriptEvent](https://github.com/DenizenScript/Denizen/blob/dev/plugin/src/main/java/com/denizenscript/denizen/events/entity/EntityCreatePortalScriptEvent.java) is using [EntityCreatePortalEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityCreatePortalEvent.html) (_depreciated_). 

Should uplift to  [PortalCreateEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/world/PortalCreateEvent.html).

**Comment by mcmonkey4eva** [comment]
It is **not** "depreciated". It is deprecated. These are two different words that are pronounced very differently and mean very different things, despite looking visually similar when typed.

**Comment by CounterCrysis** [comment]
Mistype, but doesn't matter. A [study](https://www.mrc-cbu.cam.ac.uk/people/matt.davis/cmabridge/) was published by the University of Cambridge which explains why in more detail.

**Comment by mcmonkey4eva** [comment]
After looking into it, it's not such a clean update (the `portal create event` only has most of its features in 1.14+, and Denizen still supports 1.12 and 1.13).
So, there's now both events available in Denizen.
