### ISSUE TITLE
custom brewing recipes

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#2046]
Now that we have custom crafting recipes working great, I started to look into making custom brewing recipes. Unfortunately that doesn't seem to be a thing but I'm still going to try to hack some in. Doesn't appear like we support brewing location/inventory stuff:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/BrewingStand.html
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/BrewerInventory.html

**Comment by mcmonkey4eva** [comment]
What features are you actually wanting for this? Just a custom brewing recipe system? Or...?

**Comment by mergu** [comment]
A custom brewing recipe system would be amazing. I was looking into mocking one myself but that would be even easier on me/others. Basically I'd like complete control over brewing stands - whether that's a builtin system or a bunch of tags/mecs/etc

Edit: This also should be supported: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/BrewingStandFuelEvent.html

**Comment by SXRWahrheit** [comment]
How would this differ from existing features?

**Comment by mergu** [comment]
Which existing features?

**Comment by SXRWahrheit** [comment]
For example, `<InventoryTag.fuel>`

**Comment by mergu** [comment]
That's for furnaces

**Comment by SXRWahrheit** [comment]
Right, and it's just shorthand for numbered item slots.

It seems like this request could be benefited by specificity!

**Comment by mergu** [comment]
Accessors/mutators and an unimplemented event available in posted javadocs as usual. Going above and beyond this feature request would be to have a builtin system, but OP was just requesting better brewing stand support in general

**Comment by SXRWahrheit** [comment]
What would that look like?

**Comment by mergu** [comment]
The ability to fully control all aspects of a brewing stand (exposed by the bukkit api at least - who knows what kind of nms/packet hackery you can achieve). Most of our other inventories are based directly off their bukkit javadocs so should be able to follow those quite easily 😄

**Comment by SXRWahrheit** [comment]
Tags? Mechanisms?

**Comment by mergu** [comment]
Both, and an event, as mentioned in previous posts.

**Comment by SXRWahrheit** [comment]
You've alluded to that, yes, without being specific.

**Comment by mergu** [comment]
Well whatever naming scheme is decided for the denizen implementation is up to the implementer. Ideally if they are convenience properties that already exist for other types of blocks they would be grouped in, like the fuel one you posted. Otherwise new tag/mec pairs should be made

**Comment by SXRWahrheit** [comment]
It might be helpful to that implementer, and thus more likely to be implemented, if you took the time to write out exactly what you're looking for. :)

**Comment by mergu** [comment]
Sure,
![image](https://user-images.githubusercontent.com/29823405/66728767-ed546b00-ee14-11e9-91ed-3e3b43838a9f.png)
![image](https://user-images.githubusercontent.com/29823405/66728786-0eb55700-ee15-11e9-9f6e-5ff1ab43c1a9.png)
![image](https://user-images.githubusercontent.com/29823405/66728819-50460200-ee15-11e9-9f1b-06de8eb36b0f.png)

These are the types of operations that should be possible with brewing stands via denizen. Currently the only thing I would like to see remain is the ability to get the inventory or inventory holder, otherwise the rest would be nice to have as new additions and aliased properties to avoid inventory slot hacks

**Comment by mcmonkey4eva** [comment]
Please stop this nonsense fighting. At this point (given the above and the preceding conversation on Discord) it's beyond clear that you're not just confused, you've made the active choice to give anti-answers.

**Comment by MrMaleficus** [comment]
Some elements that can be handy :

**BrewingStandRefueled** event:
_Triggers when a brewing stand block is about to refuel_
- Context : 
-- <context.item> returns the ItemTag of the item about to be used as fuel.
-- <context.power> returns the ElementTag(Number) of the fuel power of the item.
-- <context.consuming> returns the ElementTag(Boolean) of whether the item will be consumed.
-- <context.location> returns the LocationTag of the brewing stand.
- Determination
-- Element(Number) to set the new fuel power.
-- Element(Boolean) to set whether the item will be consumed.

tag `<InventoryTag.brewing_ingredient>` & mec `brewing_ingredient`
- Returns the item being used as the brewing ingredient in this brewer inventory.
- Sets the brewing ingredient of this brewer inventory.

tag `<LocationTag.brewing_fuel_level>` & mec `brewing_fuel_level`
- Returns the fuel level of this brewing stand block.
- Sets the brewing fuel level of this brewing stand block.

tag `<InventoryTag.brewing_results>` & mec `brewing_results`
- Returns the list of items in the result slots in this brewer inventory.
- Sets the result slots in this brewer inventory.

tag `<InventoryTag.is_brewing_stand>`
- Returns `true` if the inventory is a brewing stand

Support for custom brewing recipes
- example template : https://one.denizenscript.com/haste/59671

**Comment by mcmonkey4eva** [comment]
I believe said on Discord rather than here when that was posted, @MrMaleficus those seem like rather poor tag/mech names.

**Comment by mcmonkey4eva** [comment]
The results don't appear to be independently tracked in Spigot. Probably just the normal inventory contents. Not sure if we should maybe just follow Spigot's API setup there.
It makes sense, for a _list_ of items to be treated as an inventory rather than a separate magical list thingy (vs. singular items, which make more sense to have a dedicated handler, and won't be missing any functionality the concept of "a set of items" normally has attached)

**Comment by mcmonkey4eva** [comment]
- Fuel/Ingredient: I just integrated them with existing tags instead (refer to changelog).
- `<InventoryTag.is_brewing_stand>` is silly, just check the `inventory_type`.
- fuel_level: added basically as requested.
- Also tossed in a brewing_time.
- event added very similar to request

Actual custom recipe system still TODO

**Comment by SXRWahrheit** [comment]
Ya boi is on 1.16 now and I would also like this feature please. <3

**Comment by mcmonkey4eva** [comment]
added by #2358
