### ISSUE TITLE
<PlayerTag.damage[<#>]>

### ISSUE THREAD

**Issue by lwd-adam** [DenizenScript/Denizen-For-Bukkit#2047]
Can we have a tag which outs the damage a "weapon" would do, accepting a player and returning a list?  The numerical argument is an optional slot, defaulting to the item in hand.  I assume the list would be li@min,max as the game uses some RNG for damage calculations.

I realize we already have one for projectiles; this tag would probably return the damage from smacking someone in the face with your bow.

I was initially looking for a way to get the base damage from an item and came up short, but this could be more useful in the end as it could account for strength/weakness/etc by passing it a Player object instead of an Item.

**Comment by mcmonkey4eva** [comment]
After a bit of NMS research, I've added `<EntityTag.weapon_damage[(<entity>)]>`
This is mostly just powered by the damage attribute, as it seems to be automatically correct to the held item, but does also factor in enchantments (via an NMS call)

**Comment by mcmonkey4eva** [comment]
Note that attack speed is not included (and seems to be the primary source of random variance in modern minecraft). Other effects (sprinting, sweeping, etc) are not included either.

These were excluded for the sake of a more "definitive" value, that could then be varied by script later if desired.
