### ISSUE TITLE
Internal errors when playing sounds.

### ISSUE THREAD

**Issue by LeafyMitsuwa** [DenizenScript/Denizen-For-Bukkit#2048]
Debug: https://one.denizenscript.com/paste/58601
Script: https://one.denizenscript.com/haste/58602

To the best of my knowledge, the output appears to be working as intended, however there are internal errors in the console.

I have no idea what it means, but from my limited knowledge, I am assuming it is to do with the sound being played.

Thank you in advance for your time.

**Comment by LeafyMitsuwa** [comment]
Issue resolved by the ever-helpful Mergu. Can be closed.

**Comment by mergu** [comment]
Sound category should still go through a to_uppercase in the implementation.
