### ISSUE TITLE
world unloads event not possible

### ISSUE THREAD

**Issue by mindw0rm** [DenizenScript/Denizen-For-Bukkit#2051]
The output of `/version` on my server is: **This server is running CraftBukkit version git-Spigot-94af569-6ddeb98 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **Denizen version 1.1.0-SNAPSHOT (build 1688-REL)**

The issue is:
The event `world unloads` will not match. 
The reason is obvious when you look in the code:
`return path.eventArgLowerAt(1).equals("saves");`
(https://github.com/DenizenScript/Denizen/blob/release/plugin/src/main/java/com/denizenscript/denizen/events/world/WorldUnloadsScriptEvent.java#L43 and also https://github.com/DenizenScript/Denizen/blob/dev/plugin/src/main/java/com/denizenscript/denizen/events/world/WorldUnloadsScriptEvent.java#L43)
Looks like a copy/paste error.

**Comment by mcmonkey4eva** [comment]
Yep, good catch. Thanks!
