### ISSUE TITLE
<ElementTag.to_json> and <ElementTag.from_json> tags

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#2052]
Basically, I just want a way to convert a standard string to a JSON text component compliant string (for example, `<&a>my string` to `{"text":"my string","color":"green"}`) and back (for example, `{"text":"my string","color":"green"}` to `<&a>my string`).

`<ElementTag.to_json>` is possible using [`ComponentSerializer#toString(BaseComponent...)`](https://ci.md-5.net/job/BungeeCord/ws/chat/target/apidocs/net/md_5/bungee/chat/ComponentSerializer.html#toString-net.md_5.bungee.api.chat.BaseComponent...-).

I didn't do too much research so I can't quite say what `<ElementTag.from_json>` could use, but I'm fairly certain that there is a clean way of doing that.

**Comment by mcmonkey4eva** [comment]
Not sure what benefit that has (other than compensating for missing usages of the new `FormattedTextHelper`) but there ya go
