### ISSUE TITLE
"on player enters/exits notable ellipsoid" event

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#2053]
The only other alternative to such an event would be to make an absolute monster of a CuboidTag, which I think most people would love to avoid. Besides, this does have its uses. For example, entering a hollow spherical area (which can exist for a variety of reasons) and wanting to detect if the player enters the area at all through any method of movement.

**Comment by mcmonkey4eva** [comment]
This connects to https://github.com/DenizenScript/Denizen/issues/1799
