### ISSUE TITLE
Tags for list map organization 

### ISSUE THREAD

**Issue by Baileyc889** [DenizenScript/Denizen-For-Bukkit#2054]
Say I have a list li@Player1/10|player5/2|player3/15

Could a few tag be added for list maps?

<listtag.numerical_with_key>
Would return li@player1/10|player3/15|player5/2
Same for alphanumerical (since player names are always different)

<listtag.numerical_with_value>
Would return li@player5/2|player1/10|player3/15
Same for alphanumerical 

<listtag.numerical_with_value.reverse>
Would return li@player3/15|player1/10|player5/2
Allowing reverse to affect keys and values

**Comment by mcmonkey4eva** [comment]
As a more generalized alternative, I've added `<ListTag.sort_by_value[<tag>]>`

Which you can then do `<ListTag.sort_by_value[before[/]]>`

For numeric values you can already just do `<ListTag.sort_by_number[after[/]]>`
