### ISSUE TITLE
has_flag different than expected immediately following 'reload scripts'

### ISSUE THREAD

**Issue by lwd-adam** [DenizenScript/Denizen-For-Bukkit#2055]
*Probably read the end first.  If that's the case I'll be closing the issue in a couple of hours.*

The output of `/version` on my server is: ****
The output of `/version denizen` on my server is: **4172 (yes the deleted one) and 4212 (latest 1 Oct)**
(If relevant) A link to a paste of a script demonstrating the issue:
```
containername:
    type: world
    debug: true
    events:
        on reload scripts:
        - if <server.has_flag[flagname].not||null> inject taskscript
        on other events:
        - code that works just fine
```
The issue is:
I expected the if condition to fill 'true' the first time a script is run, provided it's the only script which sets the `flagname` flag.
Just to be sure, I took these steps:
 - delete all scripts which set, check or even mention `flagname`
 - reload scripts (other times I tried reloading all including saves)
 - run `ex flag global "flagname:!"`
 - narrate `flagname` just to be sure, tag does not fill - this is good
 - at this point I have restarted the server and have also continued without restarting
 - now I upload the script with the snippet from above - it is 'taskscript' which sets the flag, by the way
 - enable debug
 - reload scripts and download latest log

The log always says that the tag filled "false," as if it was never deleted.  But in between that portion and the earlier section where `ex narrate <server.flag[flagname]>` returned null, no flag are set.  In fact no tags of any kind are parsed from what I read, it just magically isn't the case anymore.

Is there something I don't know about saves.yml or the reload command that could explain why it's doing that?  I'd really like this script to run its own init file somehow, this seems like the best way to do a "First Run" routine.

I'll update this issue with any different results once I can test it from home with a flag name that has never, ever been used, like `MSWindows4Life`.

Oh wait... is it reading through the script I am injecting (obviously it will have to in order to fulfill an inject) and seeing that it sets the flag, and going "oh hai nice flag you **have** there?"
I feel like when I get home, `<server.flag[flagname].matches[null].not||null>` will work as intended.  I'll post the issue in case you want to add a footnote about this to either cmds/inject or tags/has_flag.

**Comment by mcmonkey4eva** [comment]
`The output of /version on my server is: ****
The output of /version denizen on my server is: 4172 (yes the deleted one) and 4212 (latest 1 Oct)
(If relevant) A link to a paste of a script demonstrating the issue:`
^ That's not the information requested, making this issue invalid.

`<server.flag[flagname].matches[null].not||null> will work as intended. `
^ The matches tag does not do whatever you think it does.

`Is there something I don't know about saves.yml or the reload command that could explain why it's doing that?`
^ Depends what you're doing to reload. If you're using `/denizen reload ...`, there's your problem. If you're doing `/ex reload`, that's not the issue.

`ex flag global "flagname:!"`
^ 'global' is outdated/wrong. Use 'server'.

`<server.has_flag[flagname].not||null>`
^ That fallback to null is pointless there, that tag should never fail. (And if it does, you _want_ an error message!)

----

To accurately identify the issue, we would need to see a debug recording (db -r).

----

For simple scripting issues, please join Discord @ https://discord.gg/Q6pZGSR and ask there.
