### ISSUE TITLE
Can not load new custom item formats

### ISSUE THREAD

**Issue by smellyonionman** [DenizenScript/Denizen-For-Bukkit#2056]
The output of `/version` on my server is:
```
[Sun, 6. Oct 2019 17:08:45 EDT INFO] This server is running Paper version git-Paper-209 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[Sun, 6. Oct 2019 17:08:45 EDT INFO] Previous version: git-Paper-203 (MC: 1.14.4)
[Sun, 6. Oct 2019 17:08:45 EDT INFO] You are running the latest version
```
The output of `/version denizen` on my server is:
```
[Sun, 6. Oct 2019 17:09:42 EDT INFO] Denizen version 1.1.1-SNAPSHOT (build 4228-DEV)
[Sun, 6. Oct 2019 17:09:42 EDT INFO] Author: The DenizenScript Team
```
(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/haste/58935
The issue is:
I've updated to the new itemscript formats and believe I may have done something wrong.  Is this the kind of error you'd expect from that?  I took the time to get the formatting just like the web site, or maybe not.
```
sc_item_detector:
  type: item
  debug: false
  display name: "<&r>Metal Detector"
  lore: "<&9>Great for finding<&nl><&a>Buried Treasure<&9>!"
  material: i@compass
  recipes:
      1:
          type: shapeless
          input: i@compass|i@ender_eye
```
Maybe there's something wrong with the above, or perhaps it could be another item.

Would having outdated item recipes laying around somewhere alongside the new ones be a possible cause of that error?

**Comment by smellyonionman** [comment]
It was either that newline character, or a series of stonecutter recipes which didn't have groups.  It's fine now.

**Comment by mcmonkey4eva** [comment]
That error is an invalid item as the base item for an item script. There would likely be more to the error than just what you posted, which would give the missing details.

Looking at your script, it's probably the lore being formatted wrong.
