### ISSUE TITLE
Fake Schematics not Unloaded fully

### ISSUE THREAD

**Issue by CounterCrysis** [DenizenScript/Denizen-For-Bukkit#2058]
The output of `/version` on my server is: 
**This server is running CraftBukkit version git-Spigot-56f8471-606c19e (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)**

The output of `/version denizen` on my server is: 
**Denizen version 1.1.1-SNAPSHOT (build 4255-DEV)**

(If relevant) A link to a paste of a script demonstrating the issue: 
**/ex schematic paste name:lava_ball <player.location> fake_to:<server.list_online_players> fake_duration:10s**

The issue is:
**It seems that when using the newly added fake options for the schematic command, it has issues unloading parts that intersect chunks. Please see image:**
![image](https://user-images.githubusercontent.com/47706960/67164196-ce7e3900-f32c-11e9-9d52-d92c0e4d59c1.png)
This image is of several runs of the above mentioned command. It loads in a sphere of lava and then should remove it after 10 seconds.

**Comment by mcmonkey4eva** [comment]
Replicated, and fixed in latest builds (which also feature the new schematic persistence system!)
