### ISSUE TITLE
Passing defintions to an inventory script

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/Denizen-For-Bukkit#2059]
It'd be pretty useful to be able to pass defintions into an inventory script for them to be used in the Procedural Items section. There are ways you can jank it, but real support for passing in definitions directly would have a wide potential of practical applications

**Comment by mcmonkey4eva** [comment]
Step 1: Don't.
If you're defining things in a script to begin with... define the contents of the inventory there. The inventory command is a magical thing.
