### ISSUE TITLE
Lookup Logic Rewrite

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#2060]
This is meant to be as an milestone for the denizen internals.

Maybe one day all core elements (events, cmds, tags, mechs) will be stored in a HashMap structure instead of repeated if conditions.

Benefits:
- improved speed O(1) instead of O(n) 
- easy and simple creating of new entries by external plugins like Depenizen and others
- easy and simple overriding of existing entries by external plugins

**Comment by mcmonkey4eva** [comment]
This issue post is actual nonsense. Stop posting this junk.
