### ISSUE TITLE
context.clicked_inventory produces errors when clicking side panels of dispenser.

### ISSUE THREAD

**Issue by MacValken** [DenizenScript/Denizen-For-Bukkit#2062]
The output of `/version` on my server is: **git-Paper-223 (MC: 1.14.4)**
The output of `/version denizen` on my server is: **version: 1.1.0-SNAPSHOT (build 1688-REL), core version: 1.50-SNAPSHOT (Build 394)**
The issue is: When using the event _on player clicks in inventory_ if the script references _context.clicked_inventory_ when clicking on blank side panels of dispensers than java errors will produce.

**Comment by mcmonkey4eva** [comment]
First, you're a bit behind, please update: https://ci.citizensnpcs.co/job/Denizen/
Second: post the actual error message (while running the new build)

**Comment by mcmonkey4eva** [comment]
Replicated, fixed in latest dev build.
