### ISSUE TITLE
NPC sleep does not work

### ISSUE THREAD

**Issue by pgmann** [DenizenScript/Denizen-For-Bukkit#2064]
The output of `/version` on my server is:
```
This server is running Paper version git-Paper-214
 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

The output of `/version denizen` on my server is:
```
Denizen version 1.1.0-SNAPSHOT (build 1688-REL)
Citizens version 2.0.25-SNAPSHOT (build 1770)
```

The issue is:

Create an NPC on top of a bed. Run the `/npc sleep` command. The NPC remains standing. Note re-running the sleep command reports that the NPC is already sleeping although it is still shown standing in-game.

(Also, at least some of the location checking code works as running `/npc sleep` with no bed at the NPC's location will throw an exception as the bed direction cannot be determined. Ideally this should be handled rather than throwing an exception.)

**Comment by mcmonkey4eva** [comment]
This is a Citizens issue. While `/npc sleep` is in Denizen, it's just a handler for `PlayerAnimation.SLEEP` in Citizens.
