### ISSUE TITLE
Interacting with top of doors returns invalid other_block data.

### ISSUE THREAD

**Issue by MacValken** [DenizenScript/Denizen-For-Bukkit#2065]
The output of `/version` on my server is: **git-Paper-223 (MC: 1.14.4)*
The output of `/version denizen` on my server is: **Denizen version 1.1.1-SNAPSHOT (build 4313-DEV)**
(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/haste/59568
The issue is:
I am attempting to grab other_block data on a specific locationtag on an oak_door and while interacting with the bottom half of the door results in perfect data, interacting with the top half results in inaccurate data such as a different locationtag than the bottom half of the door and different switch states. A full debug can be viewed here: http://one.denizenscript.com/paste/59567

**Comment by mcmonkey4eva** [comment]
Fixed in new dev builds.
