### ISSUE TITLE
Item Recipe Tag

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/Denizen-For-Bukkit#2066]
Can we has a tag to get a list of items required for a denizen recipe?
<itemTag.list_recipe_items[#]> or something like that?

**Comment by mcmonkey4eva** [comment]
This is a slightly messier thing to add, cause need to figure out how to return in a clean format:

Recipe type (furnace? Shaped? shapeless? etc.), recipe details (furnace burn rate and such?), the items themselves but ALSO whether they are material based matchers or full item detail matchers.

I think there'd probably need to be a recipe _ID_ returned, and then like... `<server.recipe_items[ID]>`, `<server.recipe_type[ID]>`, etc.

**Comment by mcmonkey4eva** [comment]
Er, there's already a `ItemTag.recipe_ids`. Would just need the server tag part of it.

**Comment by smellyonionman** [comment]
I came here to make the same request, this would be an awesome way to override display and lore on items such as worldedit axes, griefprevention shovels, and other special items which have unpredictable materials we need to pull from config files!

**Comment by mcmonkey4eva** [comment]
@smellyonionman I don't think the tag requested here would help with that at all?
