### ISSUE TITLE
Player starts/stops spectating entity event

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#2068]
I'd like an event for when a player starts or stops spectating an entity. I'm pretty sure there are events for this in Paper that we can take advantage of. Preferably we'd be able to cancel the event.

**Comment by MrMaleficus** [comment]
More precisely : 
https://papermc.io/javadocs/paper/1.13/com/destroystokyo/paper/event/player/PlayerStartSpectatingEntityEvent.html
https://papermc.io/javadocs/paper/1.13/com/destroystokyo/paper/event/player/PlayerStopSpectatingEntityEvent.html
