### ISSUE TITLE
Location Facing Degrees Tag

### ISSUE THREAD

**Issue by ArctoranDev** [DenizenScript/Denizen-For-Bukkit#2069]
The output of `/version` on my server is:
This server is running Paper version git-Paper-223 (MC: 1.14.4) (Implementing API version 1.14.1-R0.1-SNAPSHOT)
Checking version, please wait...
Previous Version: git-Paper-221 (MC: 1.14.4)
You are 3 version(s) behind.

The output of `/version denizen` on my server is:
Denizen version 1.1.1-SNAPSHOT (build 4313-DEV)
Author: The DenizenScriptTeam

(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/paste/61973

The issue is location.facing returns false when specifying custom degrees, in the example I test it without degrees using the default 45 degrees to check 5 blocks in front of the player, than when I use it with .degree and specify 90 it returns false.

**Comment by mcmonkey4eva** [comment]
Fixed, thanks
