### ISSUE TITLE
Notable Cuboid Entries Trigger for Players in Vehicles or Mounts

### ISSUE THREAD

**Issue by ArctoranDev** [DenizenScript/Denizen-For-Bukkit#2070]
Basically at the moment when riding mounts that are not standard vehicles such as armorstands, etc. aren't being triggered by the player riding them into a notable cuboid and I would very much like them to be able to, I've done standard testing by just using:
`on player enters notable cuboids:
- narrate <context.cuboids>`
and I've only had it trigger while walking, running, flying or swimming through the cuboid and not on a vehicle/armorstand.

Maybe something like `on player enters notable cuboid riding <entity>` would be handy to have as an optional extra?

**Comment by mcmonkey4eva** [comment]
I think a complete rewrite of the backing logic would be required, as I don't think there's any Spigot even fired for that - probably because the player isn't causing movement in that situation, some script/plugin would be.

**Comment by ArctoranDev** [comment]
Is there an event I could use or we could add to detect other entities entering cuboids?

**Comment by mcmonkey4eva** [comment]
Open issue for that: #1996

**Comment by ArctoranDev** [comment]
If that other one will be a lot harder work and require a weird system may I suggest a vehicle entry event be added?

**Comment by ArctoranDev** [comment]
I guess as an alternative I could use on player steers entity to apply a flag when the location is within the cuboid using a standard script. Problem solved.
