### ISSUE TITLE
Color tag in title

### ISSUE THREAD

**Issue by smellyonionman** [DenizenScript/Denizen-For-Bukkit#2071]
There's a bit of wonkiness in the title command when it comes to escaping, I guess?

```
narrate <element[foo].color[a]>
narrate <element[<&a>foo]>
```
both return `foo` in lime, but

`title title:<element[foo].color[a]>` outputs `fooreset=a]` in lime, while `title title:<element[<&a>foo]>` works as expected / desired.

Should we expect `title` to parse `.color` the same way other commands do?

**Comment by mcmonkey4eva** [comment]
No. `.color` is only for output to chat or books. I should make that clearer in the meta
