### ISSUE TITLE
Player Closes Inventory Cancellation

### ISSUE THREAD

**Issue by ArctoranDev** [DenizenScript/Denizen-For-Bukkit#2072]
Basically as far as I know from the bot and looking at the code myself it has no determination to cancel it and reopen the inventory script once closed, I've tried using the open inventory command in that event but that triggers a weird spam loop of opening inventories and basically breaks Denizen and the server as this is some of the error spammed through the console when I tried to use:

`on player closes myinventory:
    - inventory open d:<inventory[myinventory]>`

Any ideas or thoughts?

**Comment by BloodEko** [comment]
In onPlayerQuit you can't force the player staying online. 
Here it works the same way, there is no way to cancel it. 
That's how these specific events were designed by Mojang.

The workarround is to spam inventory open, as you tried.
To see what's going wrong debug/logs will be nice.

**Comment by ArctoranDev** [comment]
https://one.denizenscript.com/haste/62070

**Comment by ArctoranDev** [comment]
Basically in short the event ends up creating a loop for some reason rather than just firing once.

**Comment by mergu** [comment]
Wait a tick before opening the inventory

**Comment by mcmonkey4eva** [comment]
^ yup, `wait 1t`. This issue falls under the common issue described by https://one.denizenscript.com/denizen/lngs/safety%20in%20events
