### ISSUE TITLE
Change "On Chunk Loads" event

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/Denizen-For-Bukkit#2074]
Could we get the "chunk loads for the first time" event changed to be "chunk loads (for the first time)"
This would enable better systems for using yaml to handle data when chunks are being loaded/unloaded

**Comment by mcmonkey4eva** [comment]
This was historically not done on the grounds that if you ever use that event your server will definitely lag really hard.
In modern Denizen, with all the optimizations made since that time, it will now only rather probably lag. It is technically _possible_ to not cause lag now at least.

**Comment by mcmonkey4eva** [comment]
BTW if you want YAML data per-chunk for like, edits and such... absolutely only load it in when the first edit occurs. You will be doing SO MUCH LESS file loading.
