### ISSUE TITLE
ProjectileCollideEvent for paper

### ISSUE THREAD

**Issue by DerbanTC** [DenizenScript/Denizen-For-Bukkit#2075]
An event to prevent arrows from collideing with an entity would be nice to have. 
The goal would be to keep the arrow flying.

The related paper link is there
https://papermc.io/javadocs/paper/1.14/com/destroystokyo/paper/event/entity/ProjectileCollideEvent.html

Suggestion: 
```
# force the arrow to keep flying
on projectile hits entity:
- determine cancelled

**Comment by mcmonkey4eva** [comment]
Would definitely not be named that due to inevitable event conflict but could be added
