### ISSUE TITLE
Notable chunks

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/Denizen-For-Bukkit#2076]
If chunks were able to be noted, this would open the door for a "on notable chunk load/unloads", potentially making the current event more usable. This would make block/chunk specific data much easier to effeciently manage without the likely lag resulting from the current implementation.

**Comment by mcmonkey4eva** [comment]
You know you can already do `in:<area>` on the chunk events, right?

**Comment by Ph4i1ur3** [comment]
Yes, but this is one of the few things that the spigot/bukkit api offers, that is generally unusable within Denizen, or requires advanced logic. The proposed change would make it viable, while also doing it in a very "denizen-like" way.

**Comment by mcmonkey4eva** [comment]
I'm still unclear on why `- note <CHUNK.cuboid> as:mychunk` and then doing `on chunk loads in:mychunk:` isn't sufficient.
`potentially making the current event more usable.` -> wouldn't be any more usable than the above example
`without the likely lag resulting from the current implementation` -> lag potential would not be much at all different.
