### ISSUE TITLE
Mechanism registration overhaul

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/Denizen-For-Bukkit#2077]
I'm looking to contribute some paper specific mechanisms (and associated tags). The tags wouldn't be hard, due to the newer registration system, mechanisms however still use the old method tags used to use.

If there is a clean way to implement these already, please let me know!

**Comment by mcmonkey4eva** [comment]
There is already a clean way to implement those, yes.

Request a few tags/mechs from Paper, I'll implement them. After that, you'll have a clean example that you can follow to contribute more yourself!
