### ISSUE TITLE
Add narrate or script to the ratelimit command

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/Denizen-For-Bukkit#2079]
It would be cool to be able to run a task script, or even narrate to a player when using the "ratelimit" command, and the following code is not run due to hitting the ratelimit.

**Comment by mcmonkey4eva** [comment]
At that point, why not just track the rate limit yourself (via flag duration)?
The sole purpose of the `ratelimit` command is to do one very specific thing in a very simple way. If you want complexity, the `ratelimit` command no longer has a point.
