### ISSUE TITLE
new tag: ChunkTag.biomes

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/Denizen-For-Bukkit#2081]
With the relatively recent change to LocationTags no longer loading chunks automatically, getting the biomes for the chunk require a load. If doing this multiple times, adds a lot of server load that is not needed.

By using "getChunkSnapshot", i believe it would be possible to get a "ChunkTag.Biomes" that would bypass the requirement of actively loading the chunk.

**Comment by mcmonkey4eva** [comment]
`that would bypass the requirement of actively loading the chunk.`
There is no way to load a chunk without loading the chunk.

`With the relatively recent change to LocationTags no longer loading chunks automatically, getting the biomes for the chunk require a load. If doing this multiple times, adds a lot of server load that is not needed.`
The referenced change doesn't relate to an end result of increased server load, it DECREASES the server load. If chunks were automatically loaded, that would be the same final server load as manually loading them.

Also, if you're working with chunks that aren't already loaded (which generally should be somewhat rare): just use `chunkload` a single time per relevant chunk, then perform any or all actions you need in that chunk, then disable the chunkload (or have a duration pre-set on the initial chunkload call).
