### ISSUE TITLE
Factorial tag

### ISSUE THREAD

**Issue by Baileyc889** [DenizenScript/Denizen-For-Bukkit#2085]
Could I request a tag for the factorial function?

<util.factorial>

My discord name is Bailey

**Comment by BloodEko** [comment]
```
# <proc[factorial].context[5]>
factorial:
  type: procedure
  script:
  - define val 1
  - repeat <def[1]> {
    - define val <def[val].mul[<def[value]>]>
    }
  - determine <def[val]>
```
A function/procedure might work too. 
In which context could it be useful to have it as an internal tag?

**Comment by mcmonkey4eva** [comment]
The above script from @BloodEko has invalid syntax :(
c'mon you can do better than that.

A tag might be nice, though I am indeed also wondering what use you have for it

**Comment by Baileyc889** [comment]
It’s ok, I made a procedure for it. We can close the issue if you’d like

**Comment by mcmonkey4eva** [comment]
That does not answer the question at all

**Comment by Baileyc889** [comment]
I am using it to equate a purchase cost for our tiered weapons. The cost equation is (Tier +1)!*10,000
