### ISSUE TITLE
issue when using npc sleep

### ISSUE THREAD

**Issue by Motzie** [DenizenScript/Denizen-For-Bukkit#2086]
When I use the command /npc sleep I get a java error in return.
https://one.denizenscript.com/paste/62576
Server Version - 1.14.4-R0.1-SNAPSHOT
Denizen Version - 1.1.1-SNAPSHOT (build 4443-DEV)
Citizens Version - 2.025-SNAPSHOT )build 1784)

**Comment by mcmonkey4eva** [comment]
A: NPC must be standing on a bed to use the sleep command.
B: None of those versions are valid. The only valid version information is when it's copy/pasted or screenshotted from the output of `/version` and `/version (pluginname)`.
Your server "version" is not a version at all, and your Citizens version is clearly falsified.
C: This is not a Denizen issue, this is a Citizens issue.
