### ISSUE TITLE
mirror issue

### ISSUE THREAD

**Issue by Hafner2000** [DenizenScript/Denizen-For-Bukkit#2087]
The output of `/version` on my server is: This server is running Paper version git-Paper-224 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

The output of `/version denizen` on my server is: Denizen version 1.1.1-SNAPSHOT (build 1690-REL)
[17:36:16 INFO]: Author: The DenizenScript Team

(If relevant) A link to a paste of a script demonstrating the issue: https://pastebin.com/59DN2zMi

The issue is:
Using /npc mirror does not allow for multiple players to see their own skin on display when each player passes by the same npc. For clarification npc "test" shows steve skin. After using /npc select and /npc mirror each payer still sees the steve skin rather than their own.

**Comment by Ph4i1ur3** [comment]
Reproduced this issue with following plugin versions:
Denizen 4443
Citizens 1784

Plugins: Vault, LuckPerms, Citizens, Depenizen, Denizen.

**Comment by mcmonkey4eva** [comment]
@Hafner2000 You posted a log file in a spot that asks for a script link... bit mixed up there.
@Ph4i1ur3 None of those 'versions' are valid. The only valid version information is when it's copy/pasted or screenshotted from the output of `/version` and `/version (pluginname)`.

**Comment by mcmonkey4eva** [comment]
Fixed for new dev build (4444)
