### ISSUE TITLE
Feature Req: Include .dsc files from elsewhere (on the filesystem).

### ISSUE THREAD

**Issue by gominecraft** [DenizenScript/Denizen-For-Bukkit#2088]
**Use-Case:**

The ability to load other dsc files on an optional basis. As a "developer", this feature would cover cases where I want end-users to be able to load features as a compnent rather than being forced to go find the offending .dsc file and remove it.

This is both a developer-friendly feature *and* a user-friendly feature.

**Painfully rough sample scenario:**

~~~
LoadScripts:
  type: task
  script:
  - yaml load:/path/to/config.yml id:someConfig
  - if <yaml[someConfig].read[Features-Enabled.SomeFeature]>:
    - include file:/path/to/SomeFeature.dsc
  - if <yaml[someConfig].read[Features-Enabled.SomeOtherFeature]>:
    - include file:/path/to/SomeOtherFeature.dsc
  # ... rinse and repeat as necessary
~~~

**Functionality:**

~~~
- include file:/path/to/file.dsc
~~~

* Treated as a script (re)load.
  * Should not parse tags after file: (if possible)

**Security Threats/Concerns:**
* Code injection would be a nightmare.
  * Only plausible if a bad actor has access to the server in order to place a bad script.

**Comment by mcmonkey4eva** [comment]
Including script files from elsewhere: use folders and/or symlinks.

Loading script files dynamically by command: not reasonably possible.

Loading external scripts by command: Absolutely never.
