### ISSUE TITLE
Permissions Switches Not Working

### ISSUE THREAD

**Issue by smellyonionman** [DenizenScript/Denizen-For-Bukkit#2089]
Error: https://one.denizenscript.com/haste/62627
Server: `This server is running Paper version git-Paper-235 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)`
Plugin: `Denizen version 1.1.1-SNAPSHOT (build 4451-DEV)`

I think this is likely a bug specific to LuckPerms, but if you wouldn't mind looking into a fix, maybe it won't be hard?  It appears I'm using the exact same syntax as on the meta docs, but maybe there's an error below.

Here's the event code used:
```
        on player starts sneaking permission:smellycraft.item.autotillers:
        - if <player.inventory.equipment.get[1].as_item.scriptname.matches[SC_ITEM_AUTOTILLER_BOOTS]||null>:
          - if <player.location.standing_on.material.name.matches[(dirt|grass_block|grass_path)]||null>:
            - modifyblock <player.location.standing_on> farmland
            - playsound <player> sound:block_gravel_place
          - else if <player.location.standing_on.material.name.matches[coarse_dirt]||null>:
            - modifyblock <player.location.standing_on> dirt
            - playsound <player> sound:block_gravel_place
```

**Comment by mcmonkey4eva** [comment]
Not specific to Luckperms, is actually something I failed to account for when adding the `permission:` option in the first place. Fixed by way of core upgrade.
