### ISSUE TITLE
walk command teleport non-npc entity

### ISSUE THREAD

**Issue by Godivctor** [DenizenScript/Denizen-For-Bukkit#2090]
The entity zombie is on l@105,6,0,world and when I run the command walk to the zombie to l@100,6,0,world the zombie teleport instead walk
https://one.denizenscript.com/paste/62637

**Comment by mcmonkey4eva** [comment]
If you were trying to make a zombie walk, your first problem is that you weren't doing that command on a zombie, that's a snowman.

**Comment by mcmonkey4eva** [comment]
Teleportation, for both NPCs and mobs, indicates that a path could not be found. If it affects mobs but not NPCs in the same path, it's likely related to a difference in pathfinder logic between Citizens and vanilla (vanilla pathfinder tends to get stuck easily).

That said, the `walk` command doesn't seem to work on mobs _at all_ in 1.14 in my local testing
