### ISSUE TITLE
Denizen NBT not fully removed

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#2103]
Bugreport:

Denizen Version: 4491-DEV

When interacting with Denizen NBT externally via CustomNBT#removeCustomNBT and removing the last entry it will still add the empty compound, so producing an Item which then doesn't stack with vanilla ones.

The problematic line seems to be this: https://github.com/DenizenScript/Denizen/blob/dev/plugin/src/main/java/com/denizenscript/denizen/utilities/nbt/CustomNBT.java#L255 as #put runs anyway.

Only when accessed by denizen istself some property parser magic or something else seems to skip the empty compound and the propety is not applied when you give them item to yourself, but not so in a java way.

This would mean the retrieved item differs by this data and then cannot be stacked with vanilla items in example. Also, out of general inconsistency it could lead to new bugs in the future, i.e. when more detailed NBT editing would be allowed by denizen and so empty compounds are no longer magically skipped.

![image](https://user-images.githubusercontent.com/15678727/71337798-5fe87200-254d-11ea-9876-498bc4330605.png)

**Comment by mcmonkey4eva** [comment]
"doesn't apply to Denizen scripts"

Not a Denizen bug, it's a you bug.

**Comment by BloodEko** [comment]
This depends on whether you want Denizen beeing a bubble which is extra hard to access or an modern plugin where compatibility with other plugins can easily be archieved, so already existing util methods dont have to be fully rewritten to fix minor bugs.
