### ISSUE TITLE
narrate "per_player" don't work as expected

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#2107]
https://one.denizenscript.com/haste/63195

The output of `/version` on my server is: **git-Paper-31 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **version: 1.1.2-SNAPSHOT (build 4504-DEV), core version: 1.60-SNAPSHOT (Build 490)**
The issue is:
Player related tags are not parsed depending of the player reading the output of the narrate command even with "per_player" set

**Comment by mcmonkey4eva** [comment]
Woops.
Fixed.
Thanks!
