### ISSUE TITLE
Error message in console using custom item to kill entities

### ISSUE THREAD

**Issue by Baileyc889** [DenizenScript/Denizen-For-Bukkit#2109]
The output of `/version` on my server is: **paper-32    most recent version**
The output of `/version denizen` on my server is: **1699   most recent release build*
(If relevant) A link to a paste of a script demonstrating the issue: **https://one.denizenscript.com/paste/63319**
The issue is:
**Describe your issue in full here**
I am getting an error message when attacking certain mobs with a custom item. So far, spiders are what is causing the error (when killed, and in this case one-shotted).

I am getting the following error message on the most recent Paper 1.15.1 server:
https://one.denizenscript.com/haste/63320
Here is the item I am using
https://one.denizenscript.com/paste/63319

**Comment by mcmonkey4eva** [comment]
```
The output of /version on my server is: paper-32 most recent version (not the output of the command)
The output of /version denizen on my server is: *1699 most recent release build (not the output of the command)
(If relevant) A link to a paste of a script demonstrating the issue: (debug link wtf)
```
You have filled out the template incorrectly. Please actually do what the template says to do.

**Comment by mcmonkey4eva** [comment]
You also have several enchantments at level zero, which is not valid.
