### ISSUE TITLE
Bell ringing event and switch interaction

### ISSUE THREAD

**Issue by Rickyling97** [DenizenScript/Denizen-For-Bukkit#2110]
If possible, it'd be great to get a "on bell rings" type event.
This detection would ideally cover not only successful ringing using the right click, as well as ringing caused by projectiles, along with redstone activation if possible.

Also, currently the switch mechanic does not ring bells, which I believe the mechanic should cover.

Thanks as always!

**Comment by mcmonkey4eva** [comment]
Both of these seem to be... not things in the Spigot API, but also indeed things that *should* be in the Spigot API.

I'd encourage you to post an issue on the Spigot JIRA requesting a bell event and a bell ring method.

**Comment by mcmonkey4eva** [comment]
Closing as this is an issue only Spigot can resolve. If you ever posted that Spigot JIRA issue @Rickyling97 a link to it would be appreciated

**Comment by mcmonkey4eva** [comment]
Update: bell ringing added via NMS, the event added via Paper
