### ISSUE TITLE
1.12.2 Crafting Issues

### ISSUE THREAD

**Issue by Ssoumeh** [DenizenScript/Denizen-For-Bukkit#2111]
The output of `/version` on my server is: git-Spigot-eb3d921-2b93d83 (MC: 1.12.2)
The output of `/version denizen` on my server is: 1.1.2 SNAPSHOT (build 4525-DEV)
(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/haste/63549

The issue is:
2x2 Crafting recipes seem to not work in MC 1.12.2
This item container works when tested on 1.15, but doesn't on 1.12.2

**Comment by mcmonkey4eva** [comment]
Update to a more recent server version.
1.12.2 is on minimum-support, and new features are not being backported except where that happens automatically.
