### ISSUE TITLE
nms Error on Paper B33

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#2112]
00:59:22 INFO]: UUID of player mon is dd6e3522-ac29-4ccd-82cc-29a93c8317be
[00:59:22 INFO]:  ERROR!
     Error Message: Internal exception was thrown!
[Error Continued] java.lang.NullPointerException
[Error Continued] com.denizenscript.denizen.nms.v1_15.impl.network.handlers.DenizenNetworkManagerImpl.setNetworkManager(DenizenNetworkManagerImpl.java:533)
[Error Continued] com.denizenscript.denizen.nms.v1_15.impl.network.handlers.DenizenNetworkManagerImpl.setNetworkManager(DenizenNetworkManagerImpl.java:51)
[Error Continued] com.denizenscript.denizen.nms.v1_15.impl.network.handlers.DenizenPacketListenerImpl$PlayerEventListener.onPlayerJoin(DenizenPacketListenerImpl.java:70)
[Error Continued] com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor26.execute(Unknown Source)
[Error Continued] org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[Error Continued] co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[Error Continued] org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[Error Continued] org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[Error Continued] net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:192)
[Error Continued] net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174)
[Error Continued] net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65)
[Error Continued] net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256)
[Error Continued] net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139)
[Error Continued] net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1263)
[Error Continued] net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417)
[Error Continued] net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106)
[Error Continued] net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933)
[Error Continued] java.base/java.lang.Thread.run(Thread.java:830)

[00:59:22 INFO]: mon[/192.168.0.2:1822] logged in with entity id 1172 at ([world]27.05397563208986, 80.0, -177.45163104209675)

**Comment by mcmonkey4eva** [comment]
You have intentionally falsified the contents of this issue. This issue and all others by you are now support-refused.
