### ISSUE TITLE
Add entity scoreboard tag property

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#2113]
Entities have access to scoreboard tags, essentially string data attached to them that can interact with scoreboards and command blocks. Looks like the spigot Entity class has easy access to getting/setting these values, so would be nice to have in Denizen too.

Example w/ vanilla commands of setting/viewing tags:
![image](https://user-images.githubusercontent.com/29823405/71785183-a23c9500-2fca-11ea-8624-929fafe4ac83.png)
![image](https://user-images.githubusercontent.com/29823405/71785201-c4ceae00-2fca-11ea-976e-6f6a7848f57b.png)

**Comment by mcmonkey4eva** [comment]
Added basically as requested, property of `scoreboard_tags` with matching tag+mech names, also `clear_scoreboard_tags` convenience mech.
