### ISSUE TITLE
generates a unknown question mark

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#2115]
The output of `/version` on my server is: Paper version git-Paper-34 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
The output of `/version denizen` on my server is: Denizen version 1.1.2-SNAPSHOT (build 4534-DEV)
(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/haste/63667
https://one.denizenscript.com/haste/63668
The issue is:
**Describe your issue in full here**
There's a bug that generates a question mark.
![2020-01-07_21 21 13](https://user-images.githubusercontent.com/2612373/71895292-078fb200-3194-11ea-9d4b-0ba8b9bd3893.png)

**Comment by mcmonkey4eva** [comment]
Because you wrote those symbols into your script.
![scr](https://i.alexgoodwin.media/i/misc/4ba8fb.png)

Those symbols being these:
https://apps.timwhitlock.info/unicode/inspect?s=%EF%BB%BF
