### ISSUE TITLE
New Inventory Tag

### ISSUE THREAD

**Issue by ArctoranDev** [DenizenScript/Denizen-For-Bukkit#2116]
Basically wondering if we can have a tag like `<InventoryTag.with_contents[ListTag]>` to return inventories with a new list of contents added? Mainly used for exchanging InventoryTag.list_contents between inventories.

**Comment by ArctoranDev** [comment]
Forgot about InventoryTag.includes[ItemTag] but not sure if it supports lists?

**Comment by mcmonkey4eva** [comment]
Added list support to `inventory.include`

But also, for your original request, consider using `- inventory swap o:in1 d:in2`

**Comment by ArctoranDev** [comment]
@mcmonkey4eva thanks for the list support and I would use swap for dynamic inventories but these are for storage systems.
