### ISSUE TITLE
Paper issue

### ISSUE THREAD

**Issue by Cynocles** [DenizenScript/Denizen-For-Bukkit#2117]
The output of `/version` on my server is: **erver is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **Denizen v1.1.2-SNAPSHOT (build 4540-DEV)**
**Geting this huge error log found in here at line 715 (full log)**
https://pastebin.com/9Q78tzQ1

Just the error
https://hatebin.com/jmfissgswa

**Comment by mcmonkey4eva** [comment]
Update to a more recent server version.
1.12.2 is on minimum-support only.

**Comment by mcmonkey4eva** [comment]
Paper themselves also no longer support 1.12.2 for that matter.

As this is a non-fatal error, it just fails to fully load the paper submodule (which is an optional side-feature anyway), no fix will be made.
