### ISSUE TITLE
definitions modify list type

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#2119]
```
# returns Player
/ex narrate <server.list_offline_players.get[1].type>

# returns Element
/ex if true { - define list <server.list_offline_players> - narrate <def[list].get[1].type> }

# fails
/ex if true { - define list <server.list_offline_players> - narrate <def[list].get[1].name> }
```

The output of `/version` on my server is: 1.13.2
The output of `/version denizen` on my server is: 4544-DEV

When an definition is used to hold an List, the type of the entries seems to change.
So when you expect to have an List of Players in reality you have an List of Elements.
This behavior differs from older versions, but I can't say when exactly it was introduced.

**Comment by mcmonkey4eva** [comment]
This specific issue isn't a list / define / etc. issue, this is an issue with ServerTags, which still used a typeless handler. Fixed.
There's also an argument that maybe Lists being reparsed from a string should reparse the individual entries as well... might as well, though it has potential implications related to context loss / etc. Done, though side effects are currently uncertain.

BTW you should be on the Discord @ https://discord.gg/Q6pZGSR if you use Denizen.

**Comment by BloodEko** [comment]
Fix confirmed in 4546-DEV.
Originally I hit the problem via `define list <player.location.regions>`. Can't say so far whether Depenizen still uses typeless handlers anywhere after it's rewrite.

**Comment by mcmonkey4eva** [comment]
Probably everywhere in Depenizen, realistically. Depenizen is a mess.
