### ISSUE TITLE
Dynmap Integration

### ISSUE THREAD

**Issue by Insilvon** [DenizenScript/Denizen-For-Bukkit#2121]
It would be really neat to add Dynmap compatibility to Denizen/Depenizen. 
Being able to send chunk/cuboid markers to dynmap for visual zones would be an amazing feature, especially for people who do their own location defining/regions (no towny/wg, etc.)

Possible functions:
-> Send cuboid data to Dynmap for display
-> Define groups of cuboids to send as one entity (unique shapes, not just cubes.)

**Comment by mcmonkey4eva** [comment]
Depenizen issues go to https://github.com/DenizenScript/Depenizen/issues
