### ISSUE TITLE
"on shutdown" is not matched to anyScriptEvents

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#2122]
The output of `/version` on my server is: Paper version git-Paper-238 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
The output of `/version denizen` on my server is: version: 1.1.2-SNAPSHOT (build 4552-DEV), core version: 1.60-SNAPSHOT (Build 505)
(If relevant) A link to a paste of a script demonstrating the issue: **paste here**
The issue is:
There's an event "on shutdown" that's not working.
[03:09:13 INFO]: +> [ScriptEvent] Event CANCEL_ITEM_SPAWN_HANDLER.events.on shutdown is not matched to any ScriptEvents.

**Comment by mcmonkey4eva** [comment]
The event works fine. That message is not an error.
