### ISSUE TITLE
Add "force" arguments to filecopy command

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#2123]
When I tried to copy script file in Denizen/scripts folder
Denizen says "Can't copy files to there"
How about enable forced copying using arguments ?
With forced argus, scripter can use reload commands and synergies to create more flexible scripts.
Like makesimplecommand script

**Comment by Ph4i1ur3** [comment]
This is an intentional safeguard built into Denizen.

**Comment by mcmonkey4eva** [comment]
Dynamically generating scripts is a great way to have a terrible time.
