### ISSUE TITLE
How to make citizen sleeping

### ISSUE THREAD

**Issue by Misio12320** [DenizenScript/Denizen-For-Bukkit#2124]
The output of `/version` on my server is: **Paper version git-Paper-51**
The output of `/version denizen` on my server is: **Denizen version 1.1.2-SNAPSHOT (build 1700-REL)**
(If relevant) A link to a paste of a script demonstrating the issue: **paste here**
The issue is:
Hello. I want to let my citizen sleep on middle without bed. I mean when I destroy the bed of citizen it automatic change the sleeping little weird and I want to let he sleep normal but without bed

**Comment by mcmonkey4eva** [comment]
First: that's not a valid Paper version. Please copypaste or screenshot  the details output by `/version`


You have to put the NPC on a bed. That's required. You can, however, move the NPC after it's on the bed (via mechanism `EntityTag.move` specifically). So generally the best is to put a hidden bed (eg underground) and sleep the NPC on that, _then_ `move` the NPC back to where it's actually meant to be.

**Comment by Misio12320** [comment]
This server is running Paper version git-Paper-51 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

Gamer 1. I force sleep citizen. 2.I destroy the bed. 3.The citizen get screenshot:
![2020-01-17_23 01 28](https://user-images.githubusercontent.com/42146429/72649217-59e38680-397d-11ea-8757-cddf9d3d778e.png)

**Comment by mcmonkey4eva** [comment]
That isn't the thing I said to do. If you're unsure how to use mechanisms or something like that, ask on Discord @ https://discord.gg/Q6pZGSR
