### ISSUE TITLE
Fix for Spawner Tags

### ISSUE THREAD

**Issue by ArctoranDev** [DenizenScript/Denizen-For-Bukkit#2125]
So basically I've found that certain spawner related block tags such as <ItemTag.spawner_player_range> don't actually exist anymore for example it shows in the data of a spawner block when using .cursor_on or something but then it claims to be an invalid mechanism or tag so just wondering if it we can get better tags and/or mecs that work?

**Comment by mcmonkey4eva** [comment]
Gonna need a debug recording on that

**Comment by ArctoranDev** [comment]
So this debug log is me mostly messing around and experimenting with the mecs first.
https://one.denizenscript.com/haste/64296
For some reason various mecs such as spawner_player_range are only able to apply to an item rather than a spawner entity/block as well as based on the debug it doesn't change it at all.

**Comment by mcmonkey4eva** [comment]
Debug recording. as in, `debug -r` and `submit`.
