### ISSUE TITLE
Can't open shulker box item inventory

### ISSUE THREAD

**Issue by Guardelola** [DenizenScript/Denizen-For-Bukkit#2127]
**The output of `/version` on my server is:** "This server is running CraftBukkit version git-Spigot-56f8471-3e3818b (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)"
**The output of `/version denizen` on my server is:** "Denizen version 1.1.2-SNAPSHOT (build 1700-REL)"
**A link to a paste of a script demonstrating the issue:** /ex inventory open d:<player.item_in_hand.inventory>
**The issue is:**

I am currently trying to make a script that allows users to open shulker boxes in their inventory.
I got it to the point where it worked perfectly on my local test server (Running v1.1.0-b1680 Release) but once I took the script to my main server (Running 1.1.2-b1700 Release) the inventory of the shulker box closed almost immediately after opening it.

So... I did some testing with the following results:

- Just using the command /ex inventory open d:<player.item_in_hand.inventory> has the same result.
- I updated the test server to "Version 1.1.2-b1701 Release" and had the same result I got on the main server.

Which brings me to the conclusion that I am either doing it wrong, or something broke in between those versions.
[Here's](https://one.denizenscript.com/paste/64412) the debug log of the single command, just to make sure

**Comment by mcmonkey4eva** [comment]
Irrelevant on modern servers, as shulker box items in Denizen now work in a way that makes more sense.
