### ISSUE TITLE
"on player walks over notable" doesn't seem to fire

### ISSUE THREAD

**Issue by Berufeng** [DenizenScript/Denizen-For-Bukkit#2128]
After extensive testing, it seems that the event "on player walks over notable" doesn't seem to fire at all. I successfully note a block on the ground in front of me with `/ex note <player.cursor_on> as:MyNotable` then verify it worked with `/ex narrate <player.cursor_on.notable_name>` and walk over it, and the event does not fire. Tested with debug and with a simple narrate script. Also I verified that the notable is storing the actual block I wanted it to, not an air block or something like that.

**Comment by mcmonkey4eva** [comment]
The block _needs_ to be an air block. If it's a solid block, it is incorrectly placed.

----

That said, you should almost definitely just use `on player enters <cuboid>:` instead, probably with a size larger than just 1 block (unless you're expecting the player to stand on exactly 1 specific marked block, in which case a very tiny cuboid)
