### ISSUE TITLE
Showfake not working after modifying nearby blocks

### ISSUE THREAD

**Issue by zozer** [DenizenScript/Denizen-For-Bukkit#2130]
The output of `/version` on my server is:paper-71
The output of `/version denizen` on my server is: 4562-dev
(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/haste/64479
The issue is:
the script is a pretty basic demonstration of the bug.
after modifying a block to a different block as well as an adjacent block to air and then showfake the block to a new block, the showfake will not reveal until player provides some block update to the block (such as clicking on it)

**Comment by mcmonkey4eva** [comment]
use `- wait 1t` in the event before the showfake.  Refer to https://one.denizenscript.com/denizen/lngs/safety%20in%20events
