### ISSUE TITLE
Missing dependency declaration

### ISSUE THREAD

**Issue by SlimeDog** [DenizenScript/Denizen-For-Bukkit#2134]
The output of `/version` on my server is: **git-Spigot-bcd458a-10763a8 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **1.1.2-SNAPSHOT (build 4563-DEV)**

**Description**
Beginning with Spigot 1.15.2 (Jenkins 2596), missing dependency declarations are reported in the log on server start-up as WARN messages.

Reference: [https://hub.spigotmc.org/jira/browse/SPIGOT-5546](https://hub.spigotmc.org/jira/browse/SPIGOT-5546)

The relevant log entry is:
```
[22:03:36] [Server thread/WARN]: [Denizen] Loaded class com.freneticllc.freneticutilities.freneticdatasyntax.FDSSection from Sentinel v2.0.1-SNAPSHOT (build 336) which is not a depend, softdepend or loadbefore of this plugin.
```

**Steps to reproduce the behavior**
- Update Spigot to 1.15.2 latest
- Start the server
- Search the log for 'Loaded class'

**Expected behavior**
Dependencies should be declared in plugin.yml

**Comment by mcmonkey4eva** [comment]
This is a completely wrong message. Spigot is breaking here, not Denizen.
It's getting confused about the owner of a class that appears in multiple plugins.

**Comment by SlimeDog** [comment]
There are multiple plugins that generate these new WARN messages, as you can see in the issue cited above. Several have already posted fixes.

If this is not a Citizens/Denizen/Sentinel issue, please comment in the Spigot issue cited above, or post a new Spigot issue so that it can be properly addressed.

I am only the messenger. My logs are getting spammed with these messages, as will everyone starting with the latest Spigot build.
