### ISSUE TITLE
Unable to get “on lingering potion splash” event to fire

### ISSUE THREAD

**Issue by Baileyc889** [DenizenScript/Denizen-For-Bukkit#2136]
The output of `/version` on my server is: **Paper version git-paper-87 (MC: 1.15.2) (Implementing api version 1.15.2-R0.1-SNAPSHOT **
The output of `/version denizen` on my server is: **Denizen version 1.1.2-SNAPSHOT (build 4572-DEV)**
(If relevant) A link to a paste of a script demonstrating the issue: **paste here**
The issue is:
**Describe your issue in full here**

I am unable to get the “on lingering potion splash” event to fire. I also cannot get it to fire with an item script in the event line to work either

**Comment by mcmonkey4eva** [comment]
There was a typo in the source code. Fixed for DEV-4575+
