### ISSUE TITLE
Sitting NPCs float

### ISSUE THREAD

**Issue by TheRealVicere** [DenizenScript/Denizen-For-Bukkit#2137]
I know this is more likely an issue with Citizens, but whenever I make an NPC sit, they float above the block they're supposed to be sitting on.

`/version` Output:
```
This server is running Paper version git-Paper-85 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-62 (MC: 1.15.1)
You are 2 version(s) behind
```
`/version denizen` Output:
```
Denizen version 1.1.2-SNAPSHOT (build 4572-DEV)
Author: The DenizenScript Team
```
`/version citizens` Output:
```
Citizens version 2.0.26-SNAPSHOT (build 1815)
Website: http://www.citizensnpcs.co
Author: fullwall
```
Screenshot: https://cdn.discordapp.com/attachments/315163488085475337/672945326927118349/2020-01-31_17.22.56.png

**Comment by mcmonkey4eva** [comment]
They don't float, they just disagree on where to sit. You might consider `/npc sit -c` or `/npc sit --location x,y,z,world` to better place the sitting position. Generally, sitting works best on a stair block or slab (stairs tend to look like chairs).

Also, please join the Discord @ https://discord.gg/Q6pZGSR for questions like this
