### ISSUE TITLE
"Determine Cancelled" no longer working on "player exits notable cuboid" event

### ISSUE THREAD

**Issue by Berufeng** [DenizenScript/Denizen-For-Bukkit#2145]
The output of `/version` on my server is:

> [02:21:14 INFO]: This server is running Paper version git-Paper-99 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[02:21:14 INFO]: Checking version, please wait...
[02:21:15 INFO]: Previous version: git-Paper-88 (MC: 1.15.2)
[02:21:15 INFO]: You are running the latest version

The output of `/version denizen` on my server is: 

> [02:21:42 INFO]: Denizen version 1.1.3-SNAPSHOT (build 4590-DEV)
[02:21:42 INFO]: Author: The DenizenScript Team

The script in question:

> https://one.denizenscript.com/haste/65148

The issue is:

Since updating to a newer Denizen dev build, a script that previously worked no longer works. The line `- determine passively cancelled` passes but does not stop the player from moving as it used to. The result in the above script is that the next `if` command executes, returns true, and runs the narrate and flag commands, but I am allowed to keep running. The intended behavior is that the walk action would be cancelled and the player is unable to move any farther.

**Comment by mcmonkey4eva** [comment]
User error.
Please read https://one.denizenscript.com/denizen/lngs/safety%20in%20events

EDIT: Bad link in hindsight. The problem is you need to *remove* the `wait 1t` actually. Determine needs to be WITHIN the event, not outside it.
