### ISSUE TITLE
Suggestion: run multiple commands inside <&click>

### ISSUE THREAD

**Issue by Spyrion** [DenizenScript/Denizen-For-Bukkit#2147]
It would be nice to have the option to run multiple commands in

> https://one.denizenscript.com/denizen/tags/%3C&click[%3Cclick%20command%3E].type[%3Ctype%3E]%3E

For example,
`<&click[/command one,/command two].type[RUN_COMMAND]> click here <&end_click>`

**Comment by mcmonkey4eva** [comment]
That's a Minecraft limitation, not Denizen.


You can replicate the goal in Denizen by having a command script that's triggered by the click and that command script does multiple things.
