### ISSUE TITLE
on player signs book - determine not_signing

### ISSUE THREAD

**Issue by realdagumboss** [DenizenScript/Denizen-For-Bukkit#2149]
The output of `/version` on my server is: Paper version git-Paper-93 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
The output of `/version denizen` on my server is: Denizen version 1.1.2-SNAPSHOT (build 1702-REL)
(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/haste/65418
The issue is:
determine not_signing on the player signs book event spits out an unknown determination error, but still prevents books from being signed as it should. Though, if the script goes on for too long (seems like 20 ticks) before determining not_signing, the book gets signed regardless and will stay signed. Wasn't sure how to demonstrate the second half of this in a script, but the determination is pretty self-explanatory.

Additionally the book contents don't seem to be saved until that point so calling them wont be accurate until after whatever this mystery period is. As in, to get an accurate reading of the book contents you just edited, you'd have to click done on the book window once before trying to sign. A wait command at the start of the script rectifies this issue, but the prior issue of the book being signed after ~1 second and not being able to determine otherwise prevents that.

**Comment by mcmonkey4eva** [comment]
`determine not_signing on the player signs book event spits out an unknown determination error,`
Fixed, there was a missing line in the code.

`Though, if the script goes on for too long (seems like 20 ticks) before determining not_signing, the book gets signed regardless and will stay signed.`
You cannot use a `wait` prior to a determine. You either determine *in* the event or you don't determine at all... you can't change the past.

`Additionally the book contents don't seem to be saved until that point so calling them wont be accurate until after whatever this mystery period is.`
The `<context.book>` should contain the accurate contents of the book, other than the title/author, which can be found via `<context.title>` and `<player.name>`.

`(seems like 20 ticks)`, `after ~1 second `
The duration is almost certainly: 1t, aka "the next tick". The event happens the moment all logic listening to the event *finishes*, ie when either the script ends or a `wait` is used (for all scripts, and equivalent for all plugins). At that point the signing goes through (unless it was cancelled).
