### ISSUE TITLE
- if E3 == E3:  <-- Error!

### ISSUE THREAD

**Issue by Berufeng** [DenizenScript/Denizen-For-Bukkit#2150]
The output of `/version` on my server is: 

> [23:55:02 INFO]: This server is running Paper version git-Paper-118 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[23:55:02 INFO]: Checking version, please wait...
[23:55:03 INFO]: Previous version: git-Paper-105 (MC: 1.15.2)
[23:55:03 INFO]: You are running the latest version

The output of `/version denizen` on my server is: 

> [23:55:32 INFO]: Denizen version 1.1.3-SNAPSHOT (build 4621-DEV)
[23:55:32 INFO]: Author: The DenizenScript Team

(If relevant) A link to a paste of a script demonstrating the issue: 

Debug (Line 86)
https://one.denizenscript.com/paste/65560

The issue is:
I was comparing two tags in an if statement: `- if <tag1> == <tag2>:` and was getting console errors, so I tried narrating instead. `- narrate "<tag1> == <tag2>"` This correctly output "E3 == E3" in chat. I did a little digging and discovered that, for some strange reason, even a direct comparison of `- if E3 == E3:` throws an error. See my debug above for a test of exactly that.

**Comment by mcmonkey4eva** [comment]
Post your actual test script please
