### ISSUE TITLE
Notables don't work as expected when using it in a script

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#2151]
The output of `/version` on my server is: **git-Paper-654 (MC: 1.13.2)**

The output of `/version denizen` on my server is: **Denizen version 1.1.3-SNAPSHOT (build 4623-DEV)**

Script paste : **https://one.denizenscript.com/paste/65620** 

A link to a paste of a script demonstrating the issue: **https://one.denizenscript.com/paste/65619**

The issue is:
**The notable command don't work as expected when in a script. It only work manually in the console using /ex**

Tested version : REL 1701, REL 1702, DEV 4623.

**Comment by mcmonkey4eva** [comment]
- NEVER use raw object notation (`cu@`) in a script.
- You do not need to manually persist notables like that. They persist over restart on their own.
- Your script uses world `testmap`, which doesn't exist on your server.
- That debug looks like it worked fine regardless.

**Comment by Astrareach** [comment]
Update : The worldname was for testing purpose, I have made a new debug here with proper formating and proper worldname : https://one.denizenscript.com/paste/65622

New debug : https://one.denizenscript.com/paste/65621

The script show that it is fine in the console, but in reality I got a blank notable file even after reloading :
![image](https://user-images.githubusercontent.com/20723083/75354005-8f4c8f80-58ac-11ea-99c1-b1b8be69945c.png)

**Comment by mcmonkey4eva** [comment]
- That debug is still from an old script
- The notables save file does not instantly update, it only updates after Denizen is saved.

**Comment by Astrareach** [comment]
Sorry, I gave you a wrong link. Here is the new one : **https://one.denizenscript.com/paste/65623**

After every attempt I am doing **denizen reload notables** to see the result

**Comment by mcmonkey4eva** [comment]
That command you're doing will delete any changes made. Do not do that.
