### ISSUE TITLE
Mec for Block Strength on Specific Locations

### ISSUE THREAD

**Issue by ArctoranDev** [DenizenScript/Denizen-For-Bukkit#2152]
So I know we have `MaterialTag.block_strength` which modifies the strength of all the blocks but is it possible to have a mec that can modify the strength of any block, obviously not obsidian since it's hardcoded, but then make it entirely specific to a single LocationTag.

**Comment by mcmonkey4eva** [comment]
Nope.

You can imitate it by setting it high and breaking it early where needed. That's about the closest you can do.
