### ISSUE TITLE
Inventory Script Container Bug

### ISSUE THREAD

**Issue by ArctoranDev** [DenizenScript/Denizen-For-Bukkit#2153]
https://one.denizenscript.com/haste/65808
The output of `/version` on my server is: http://prntscr.com/rat95j
The output of `/version denizen` on my server is: http://prntscr.com/rat9en
The issue is:
Essentially there's a "Invalid Book Input" error when using procedural items.

**Comment by mcmonkey4eva** [comment]
Unsupported+Unsupportable Denizen version.

Run release builds or latest dev builds. We cannot and will not support outdated dev builds.

If errors can be replicated on supported builds, include a debug log recording of the error.

Additionally, be aware of the following issues with your script (per the checker bot):
![check](https://i.alexgoodwin.media/i/misc/09fba3.png)
