### ISSUE TITLE
Issue with Citizen sleeping.

### ISSUE THREAD

**Issue by Misio12320** [DenizenScript/Denizen-For-Bukkit#2155]
The output of `/version` on my server is: **This server is running Paper version git-Paper-129 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **Denizen version 1.1.3-SNAPSHOT (build 1703-REL)**
(If relevant) A link to a paste of a script demonstrating the issue: **none**
The issue is:
**The issue is with sleeping Citizen. I wan't to make them sleep like in bed but they don't do what I mean. If I rotate them by script by Skript they rotate somewhere else. I think the developer should add rotation by "90 is e.g south, the 180 is west, north 270 and east is 360. Here's a video: https://youtu.be/xvK2hNLauKY**

**Comment by mcmonkey4eva** [comment]
This is Denizen support, why are you posting Skripts?

**Comment by Misio12320** [comment]
Without scripts is this same. Why you don't add "ex rotate <npc> west"?

**Comment by mcmonkey4eva** [comment]
Because that already exists, just not written that way.

**Comment by mcmonkey4eva** [comment]
Join the Discord for basic Denizen help https://discord.gg/Q6pZGSR
