### ISSUE TITLE
Permission based triggers

### ISSUE THREAD

**Issue by lwd-adam** [DenizenScript/Denizen-For-Bukkit#2156]
What about adding the permission: switch to NPC triggers?
`trigger name:click state:true permission:group.admin`
Only admins can click.
`trigger name:click state:true`
Re-declaring the trigger without the permission switch removes it, now everyone can click.

Or, perhaps we could add a permission sub-key to the actual trigger blocks.

**Comment by mcmonkey4eva** [comment]
This is a basic usage question, not a feature request
```
- if <player.has_permission[someperm]>:
  - ...
```
Join the Discord to ask basic questions about how to use Denizen like this one https://discord.gg/Q6pZGSR
