### ISSUE TITLE
id_holder of shopkeeper inventories invalid

### ISSUE THREAD

**Issue by mindw0rm** [DenizenScript/Denizen-For-Bukkit#2160]
The output of `/version` on my server is: **git-Spigot-6de3d4b-fc24934 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**

The output of `/version denizen` on my server is: **1.1.3-SNAPSHOT (build 1703-REL)** (same with *1.1.3-SNAPSHOT (build 4639-DEV)*)

Other relevant plugins:
- Citizens2 version 2.0.26-SNAPSHOT (build 1842)
- Shopkeepers version 2.9.2
- Depenizen version 2.0.0 (build 608)

(If relevant) A link to a paste of a script demonstrating the issue:  minimal example
```
inv_type:
    type: procedure
    definitions: inv
    script:
        - determine <[inv].inventory_type>
shopkeeper_test:
    type: world
    events:
        on player opens inventory:
            - narrate "inv type = <proc[inv_type].context[<context.inventory>]>"
```
The issue is:
The holder id of NPC shopkeeper inventories is 'MERCHANT',  which is apparently invalid. When passing such an inventory to a procedure script and accessing it as an inventory, an exception is thrown. In the above example:
```
[18:38:28] [Server thread/INFO]:  ERROR in script 'inv_type' in queue 'INV_TYPE_RpEarthLabour' while executing command 'DETERMINE' in file 'scripts/test.yml' on line '16' with player 'p@621707eb-5811-457f-a889-6ecca695b463 (EnigmaAntares)'!
     Error Message: Internal exception was thrown!
[Error Continued] java.lang.IllegalArgumentException: Cannot open an inventory of type MERCHANT
[Error Continued] org.apache.commons.lang.Validate.isTrue(Validate.java:71)
[Error Continued] org.bukkit.craftbukkit.v1_15_R1.CraftServer.createInventory(CraftServer.java:1574)
[Error Continued] com.denizenscript.denizen.objects.properties.inventory.InventoryHolder.setHolder(InventoryHolder.java:127)
```
(line 16 is `- determine <[inv].inventory_type>` and inv is set to `in@generic[holder=MERCHANT;title=Chest;uniquifier=0]`).
When using the script on a villager, inv is set to `in@entity[holder=e@c6d4a52e-4a66-4897-a3b7-d71528d1ef4e]` and the procedure returns 'CHEST' which imho is another bug (the inventory type of a shopkeeper NPC is 'MERCHANT' - which I would expect for villagers as well). 
Expected value for holder id would be something like 'n@42'. 
Due to this bug it also isn't possible to directly determine the npc of such an inventory.

I _think_ this is a Denizen bug, but it might actually be a Depenizen issue?

**Comment by mindw0rm** [comment]
Other holder-dependent data (like location) ist also not available (`Error Message: Tag <context.inventory.location> is invalid!`). 
Meanwhile I found out, that InventoryOpenEvent.getInventory().getHolder() is null in that case - so maybe it's more of a shopkeepers bug?

**Comment by mcmonkey4eva** [comment]
Have you asked the Shopkeepers dev about this?

**Comment by mindw0rm** [comment]
Nio I haven't yet. Sorry, I somehow completely forgot about this issue ;)

Please give me some time (days, I guess) to recreate he bug with minimal plugins in the current version and then file a shopkeepers bugreport. I'll link it here when I'm done.
