### ISSUE TITLE
Add filter to precise_target tags

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#2161]
A filter for entity types.
This is useful for targeting other entities through other players.
Example of the tag extension:
<LocationTag.precise_target[(<range>)].entities[<entity>|...]>

Might also be a good idea to add this to all the other related tags.

**Comment by mcmonkey4eva** [comment]
Added `<LocationTag.precise_target[(<range>)].type[<entity_type>|...]>`
