### ISSUE TITLE
Suggestion: add an npc argument in the sit/sleep command to control remote npc

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#2163]
Hi, the idea is to add an npc object argument in the sit/sleep command. This way we can order remotely for the npc to sit or sleep. Exemple `- sit <npc[46]>`

**Comment by mcmonkey4eva** [comment]
Nonsense request of a feature that already exists https://one.denizenscript.com/denizen/vids/The%20Player%20and%20NPC%20Arguments / https://one.denizenscript.com/denizen/lngs/player%20and%20npc
