### ISSUE TITLE
Trouble with the sit/sleep command

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#2164]
The output of `/version` on my server is: **git-Paper-624 (MC: 1.13.2)**
The output of `/version denizen` on my server is: **1.1.4-SNAPSHOT (build 4645-DEV)**

I am placing NPC automatically and I have a code to choose the npc state between (stand, sit and sleep)
I load the chunk for 4 second and placing the npc just in those 4 second. Right after placing this NPC I set the ``- sit npc:<[mynpc]>`` and it work correctly when I join the server 10 second after the automatic execution. 
For the ``- sleep npc:<[mynpc]>`` however the npc is still standing up. (It has the state sleeping but the npc is standing up)

Its maybe related to loading chunk and such because when I connect 10 second after the execution I see the npc is changing state from standing up to sit mode

I dont understand why there is a difference like this between such mode

For exemple 
```
- choose <[pose]>:
  - case assis;
    - sit npc:<[npc_nouvellement_cree]>
  - case allonge:
    - sleep npc:<[npc_nouvellement_cree]>
```

**Comment by mcmonkey4eva** [comment]
Your script you pasted has clear basic errors in its syntax.

Please use the Discord to discuss issues related to recent commits / new dev builds.
