### ISSUE TITLE
Additional fishing control.

### ISSUE THREAD

**Issue by LeafyMitsuwa** [DenizenScript/Denizen-For-Bukkit#2165]
Would it be possible to extend the fishing event?

Particularly, when a player casts a fishing rod, determine a time when the rod would get a catch, or a time when the fish particles would start appearing, going towards the fishing rod hook entity.

Secondarily, could the event also determine a non-item entity? Such as a Squid, or a Drowned?

Thanks in advance.

**Comment by NextoEsKawii** [comment]
A mechanism to adjust/set what entity the fishing hook is attached to would also be really helpful as it would help to 'force' what it hooks to and have a more realistic fishing, also if possible, a tag that tells what entity is the hook/bait attached to

**Comment by Fortifier42** [comment]
None of this is available within spigot itself, not sure how you'd accomplish this?

**Comment by LeafyMitsuwa** [comment]
Ok, fair enough.
Are there perhaps different means to start the fish bubble trail?

**Comment by Fortifier42** [comment]
Perhaps the [WATER_BUBBLE](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html#WATER_BUBBLE) particle effect? Give it a shot

**Comment by mcmonkey4eva** [comment]
A bunch of mechanisms for fish hooks were added, covering I think at least the majority of the intended request here https://meta.denizenscript.com/Docs/Mechanisms/hook
