### ISSUE TITLE
The Title Command No longer Works

### ISSUE THREAD

**Issue by TheLastBlockbender** [DenizenScript/Denizen-For-Bukkit#2166]
The output of `/version` on my server is: git-Paper-136 (MC:1.15.2)
The output of `/version denizen` on my server is: 1.1.4-SNAPSHOT (build 4645-DEV)
(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/paste/66157
The issue is:
The title command literally just doesn't work anymore when it used to. Here is the debug script.
https://one.denizenscript.com/paste/66155

**Comment by mcmonkey4eva** [comment]
Please discuss issues related to new dev builds on the Discord.
