### ISSUE TITLE
Item Tag for Vanilla Names

### ISSUE THREAD

**Issue by ArctoranDev** [DenizenScript/Denizen-For-Bukkit#2167]
Basically I'm stuck with `ItemTag.display` only working for Denizen items and there not being a tag that would return the vanilla display name. For example i@Porkchop has the display name "Raw Porkchop" but even the material name is "Porkchop" and this isn't the only block/item with these issues so trying to fake it with `.material.name.replace[_].with[ ].to_titlecase` or something similar doesn't work without requiring extra formatting for all items.

**Comment by ArctoranDev** [comment]
Ideally something like `ItemTag.vanilla_name` would be helpful.

**Comment by mcmonkey4eva** [comment]
Nonsense request for an existing tag.

https://one.denizenscript.com/denizen/tags/MaterialTag.translated_name

**Comment by ArctoranDev** [comment]
Well you still ended up not doing it right: https://one.denizenscript.com/paste/66240
