### ISSUE TITLE
is_odd fails for negative numbers

### ISSUE THREAD

**Issue by FurykOne** [DenizenScript/Denizen-For-Bukkit#2168]
The output of `/version` on my server is: This server is running Paper version git-Paper-65 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
The output of `/version denizen` on my server is: Denizen version 1.1.4-SNAPSHOT (build 4645-DEV)
(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/paste/66175
https://one.denizenscript.com/haste/66176
The issue is:
The is_odd tag isn't evaluating locationtag.z tags correctly.

**Comment by mcmonkey4eva** [comment]
That title is ridiculous, I corrected it to be the actual issue title per looking at Discord discussion from the time when you posted this.
