### ISSUE TITLE
add "players:<player>" argument for "map" command

### ISSUE THREAD

**Issue by DerbanTC** [DenizenScript/Denizen-For-Bukkit#2175]
Adding a way to sending different maps (which are hanging) client-side would be glad.

e.g. for world-maps with highlighted quest-markers if you have them activ or something other.

**Comment by mcmonkey4eva** [comment]
This is already possible with a map script: https://one.denizenscript.com/denizen/lngs/map%20script%20containers
Check the 'visible' key usage example
