### ISSUE TITLE
Input quantity on Item Script Containers

### ISSUE THREAD

**Issue by LeafyMitsuwa** [DenizenScript/Denizen-For-Bukkit#2176]
I'd like to request quantity input control for custom items.

Example item: https://one.denizenscript.com/haste/66591

I had hoped to sort-of add quantity via a tag to the input items. Unfortunately, this does not work, and the recipe fires with 5x 1 item, as opposed to 5x 32 items.

Thank you.

**Comment by mcmonkey4eva** [comment]
If a vanilla recipe can't do it, an item script one can't either. Item script recipes just inject new recipes to the vanilla crafting handler.
You can try to hack it based on crafting events but uh... good luck making that work.
