### ISSUE TITLE
Knowledgebook does not use denizen items.

### ISSUE THREAD

**Issue by LeafyMitsuwa** [DenizenScript/Denizen-For-Bukkit#2177]
Version
[11:55:13] [Render thread/INFO]: [CHAT] This server is running Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[11:55:13] [Render thread/INFO]: [CHAT] Checking version, please wait...
[11:55:13] [Render thread/INFO]: [CHAT] Previous version: git-Paper-126 (MC: 1.15.2)
[11:55:13] [Render thread/INFO]: [CHAT] You are 3 version(s) behind

Denizen Version
[11:56:20] [Render thread/INFO]: [CHAT] Denizen version 1.1.3-SNAPSHOT (build 1704-REL)
[11:56:20] [Render thread/INFO]: [CHAT] Author: The DenizenScript Team

Knowledge book does not use Denizen items.

Item Script: https://one.denizenscript.com/haste/66593

For the above item script, when the player has the required items, the knowledgebook filters the recipe as able to be crafted, but doesn't actually use the items as required. Manually creating the recipe as intended works fine.

In the above item script, if a player has 9 vanilla emeralds, the knowledgebook forms the recipe in the 3x3 grid, but does not output the item, due to the recipe requiring denizen items.

All vanilla recipe's had been removed from the server, and a substitute item has been made to give each recipe category a valid recipe.
Impossible item: https://one.denizenscript.com/haste/66594

**Comment by mcmonkey4eva** [comment]
This is technically an issue that can be fixed from the server side, but... yikes, the amount of NMS needed would be a lot.

`NMS.AutoRecipe#b` I think is the key to the problem, as it's the code that does the item choosing, and it matches based exclusively by material. A fix would involve either replacing the AutoRecipe class somehow (not sure how but maybe), or hacking the ItemStack class to provide a different `doMaterialsMatch` (which would involve 3-5 classes being replaced, so... no).

I'll leave the issue open, but I'm not so sure whether I'll be able to hack it myself anytime soon.

**Comment by mcmonkey4eva** [comment]
Update: after testing NMS changes and attempting a few things, I've realized it's actually matching wrong on *both* client *and* server side, and therefore can't be fixed from the server, unfortunately :(
(Also `#b` isn't the right method for it, was wrong on that earlier)
