### ISSUE TITLE
list_players_flagged issue

### ISSUE THREAD

**Issue by Robsando** [DenizenScript/Denizen-For-Bukkit#2178]
The output of `/version` on my server is: **This server is running CraftBukkit version git-Spigot-9de398a-9c887d4 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)**

The output of `/version denizen` on my server is: **Denizen version 1.1.3-SNAPSHOT (build 1704-REL)**

A link to a paste of a script demonstrating the issue: [Log](https://one.denizenscript.com/haste/66613)

My problem:
I have two players:
- player A (my account)
- and player B (also my (same) account but when I login to server when online-mode is disabled)

When I flag bouth of them with specific flag like here [saves.yml](https://one.denizenscript.com/haste/66615) and check this flag by list_players_flagged tag only one of them is returned (player A).
When I delete flag in player A,  list_players_flagged returns empty list.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
