### ISSUE TITLE
Tag <surface_blocks> does not work with void

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#2179]
The output of `/version` on my server is: **git-Paper-149 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **1.1.3-SNAPSHOT (build 1704-REL)**
(If relevant) A link to a paste of a script demonstrating the issue: **https://pastebin.com/3mY8jEy2**
The issue is:
**The tag <surface_blocks> does not work with void. For exemple I execute /ex narrate <player.location.chunk.surface_blocks> and I get this java error https://pastebin.com/3mY8jEy2**

**Comment by SXRWahrheit** [comment]
This doesn't seem like a bug with surface_blocks, but rather user error on assuming what a tag will do. You should probably use separate logic for determining whether a player is in the void at all, whether or not any change is made to surface_blocks.

**Comment by Astrareach** [comment]
I created this issue because with older version of Denizen, the "surface_blocks" tag in void will take the bottom coordinates, it has changed since.
If a chunk had flying blocs and void around, the java error will pop up.
I use flying island so this functionnality is important for me

**Comment by Astrareach** [comment]
Here is the denizen debug as requested https://one.denizenscript.com/paste/66693
