### ISSUE TITLE
Suggestion : Jukebox support

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#2180]
Greeting, my suggestion is to add jukebox support because :
- I want to prevent some player to take cd's from a jukebox block
- I want to prevent some player to put cd's to a jukebox block

At first I tested two event like `on player interacts with JUKEBOX` & `on player right clicks JUKEBOX` and search for other solution

**Comment by mcmonkey4eva** [comment]
Does the right clicks jukebox event not work? 0.o

**Comment by Astrareach** [comment]
The event fire when you right click a jukebox but you cannot determine cancelled it for the cd's in and out

**Comment by mergu** [comment]
Works fine for me:
```
test_event:
    type: world
    events:
        on player right clicks jukebox:
        - narrate "nope"
        - determine cancelled
```
Properly cancels the event when I try to put a disk in, and properly cancels the event when I try to take a disk out or swap it with another.

To prevent players from doing one or the other action, you can just detect the item they're clicking with and handle that logic yourself. I *do* see an opportunity here to add some blockdata properties and a mec to force the jukebox to play. But the event works fine.

**Comment by Astrareach** [comment]
I can confirm that the event for jukebox work fine now
