### ISSUE TITLE
New whitespace support problem with MCL 

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#2181]
The output of `/version` on my server is: **git-Paper-155 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **1.1.4-SNAPSHOT (build 4677-DEV), core version: 1.80-SNAPSHOT (Build 572)**

The issue is:
**Greeting, whitespace is again not supported when using Message Constructor Library**
![image](https://user-images.githubusercontent.com/20723083/78052882-08de0e80-7380-11ea-91b1-cbb39f031f7b.png)

**Comment by BehrRiley** [comment]
you can ditch MCL now for the internal fancy-text handler tags that replaced it
Check out these tags using the bot:
```
<&hover[<hover text>]>
<&hover[<hover text>].type[<type>]>
<&click[<click command>]>
<&click[<click command>].type[<type>]>
<&insertion[<message>]>
<&end_click>
<&end_hover>
<&end_insertion>
<&keybind[<key>]>
<&selector[<key>]>
<&translate[<key>]>
<&translate[<key>].with[<text>|...]>
<&score[<name>|<objective>(|<value>)]>
```
