### ISSUE TITLE
Cannot list entities with cuboid

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/Denizen-For-Bukkit#2182]
The output of `/version` on my server is: **git-Paper-155 (MC: 1.15.2)**
The output of `/version denizen` on my server is: **1.1.4-SNAPSHOT (build 4678-DEV)**
(If relevant) A link to a paste of a script demonstrating the issue: **https://one.denizenscript.com/paste/66791**
The issue is:
**I cannot use the <CuboidTag.list_entities[<entity>|...]>. I am using /ex narrate <player.location.chunk.cuboid.list_entities> for testing purpose. I have a java error in the console**

**Comment by mcmonkey4eva** [comment]
You have an entity spawned from an entity script, but you deleted that entity script.

The error has nothing to do with listing entities or that tag. It's an entity identification problem, caused by the deletion of relevant scripts.

**Comment by Astrareach** [comment]
Thank you for the update, 
before it give me an error when trying to remove these entities (and don't remove them)

But now I can "- remove" them without error !
