### ISSUE TITLE
Non-Denizen NBT mech

### ISSUE THREAD

**Issue by poser-1** [DenizenScript/Denizen-For-Bukkit#2183]
Simply, a mechanism that allows you to set an item's NBT tag without it being a Denizen NBT tag.

Something along the lines of ``simple_nbt`` for the mech's name would be fine, although there are probably better names for it.

Example:
- Adjusting an item with "nbt=test/test":
When using the /data command in-game, it'd return it's NBT tag as being ``{"Denizen NBT": {test: "test"}}``
- Adjusting an item with "simple_nbt=test/test":
/data would return ``{test: {"test"}``

Why not use Denizen NBT?
There are several cases where using normal NBT is better, either for making the code shorter, or for easier use with Optifine's custom item's feature.

Why not use ``custom_model_data`` for custom items?
It isn't supported by 1.13, and custom model data is generally not the same thing as having new textures.

**Comment by SXRWahrheit** [comment]
https://github.com/DenizenScript/Denizen/issues/2142
