### ISSUE TITLE
List Based Definitions

### ISSUE THREAD

**Issue by Insilvon** [DenizenScript/Denizen-For-Bukkit#2184]
Command option for a list based **define** command/new command for multiple definitions in one line. (Just an idea. It won't break my heart if it doesn't happen.)

For example, instead of:
- define var1: val1
- define var2: val2
...

Doing:
- define var1|var2|var3: val1|val2|val3

**Comment by mcmonkey4eva** [comment]
yeah, no, just use multiple lines. (Or, one day, MapTag, when that's done... not quite the same but close)
