### ISSUE TITLE
Commands through FAWE not listening to as_op

### ISSUE THREAD

**Issue by BlindMag** [DenizenScript/Denizen-For-Bukkit#2187]
The output of `/version` on my server is: CraftBukkit version git-Spigot-ae72bf4-183139d (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

The output of `/version denizen` on my server is: 1.1.4-SNAPSHOT (build 4689-DEV)
(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/haste/67287

FAWE Build 166

The issue is: 
FAWE is not listening to commands with execute as_op. It just gives the notification that the user does not have the permission. Plain world edit appears to be executing fine with as_op.

**Comment by mcmonkey4eva** [comment]
This is an inevitable and unfixable result of the way FAWE works (ie, the command is not executed at the time you enter it). Avoid FAWE, or use an alternative methodology (eg execute as_server, or just make a script to do the job)
