### ISSUE TITLE
addition to modifyblock

### ISSUE THREAD

**Issue by BasedUser** [DenizenScript/Denizen-For-Bukkit#2197]
`- modifyblock naturally using:<ItemTag>`

With the `using:` parameter, a scripter can break a block as if it was done by hand, holding a specific item in their main hand. This includes the effects of enchantments like Fortune, Silk Touch, as well as custom scripts bound to those items.

**Comment by Fortifier42** [comment]
Is this not already achieved with `naturally:<tool>` and `source:<player>` as the BreakBlockEvent/BlockPlaceEvent is fired
