### ISSUE TITLE
Re-add Heroes Hook to denizen

### ISSUE THREAD

**Issue by Ugikie** [DenizenScript/Denizen-For-Bukkit#2198]
I know this has been asked before, and I know there is some beef in the community with Kainzo for many reasons that are completely his fault, but my server uses Heroes and for months now I have been very restricted by not having the ability to read certain values from a hero or catch certain events.

I know Denizen has supported Heroes in the past and no longer does. But I was wondering what it would take to just hook into it again. I wouldn't need much more than just being able to check the player's mana, level, class, and have just a few of the old events back like "on heroes player uses skill" or "on heroes player levels up".

I am stuck creating insane workarounds using denizen to flag players with their current class based on the commands they use, and its just not the best system. Its either that, or I am forced to completely rewrite Heroes using Denizen like I just did for Factions due to there not being a hook.

I would love to have control again over heroes through denizen, but I simply do not know enough about Java to create my own simple hook.

I would be willing to pay some money to have this feature added if that's what it takes.

Please take this request into consideration because it would really benefit my server and I would be forever grateful.

Best,
Ugikie

**Comment by mcmonkey4eva** [comment]
Denizen never supported Heroes.
_Depenizen_ supported Heroes. Unfortunately, there is no longer a public release of heroes that is compatible with modern minecraft server versions.
Depenizen cannot support what doesn't exist.
