### ISSUE TITLE
Nullpointer when using /npc sneak/sit

### ISSUE THREAD

**Issue by TheCardinalSystem** [DenizenScript/Denizen-For-Bukkit#2199]
The output of `/version` on my server is: **git-Spigot-ae72bf4-183139d (MC: 1.15.2) (Implementing API Version 1.15.2-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **1.1.3-SNAPSHOT (build 1704-REL)**
The issue is:
**Describe your issue in full here**
I got a nullpointer when trying to use the commands `/npc sneak` and `/npc sit`.
Attacked is a text file with the stacktrace.

[stacktrace.txt](https://github.com/DenizenScript/Denizen/files/4540313/stacktrace.txt)

**Comment by mcmonkey4eva** [comment]
Ask for support in the Denizen channel @ https://discord.gg/Q6pZGSR
