### ISSUE TITLE
NullPointerException for skull_skin of npc named Arulean

### ISSUE THREAD

**Issue by Xericore** [DenizenScript/Denizen-For-Bukkit#2200]
**Denizen debug:**
https://one.denizenscript.com/paste/68183

This server is running Paper version git-Paper-192 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Denizen version 1.1.4-SNAPSHOT (build 1706-REL)**

**Steps to reproduce:**

1. /npc create Arulean
2. /ex narrate <player.target.skull_skin>

**The issue is:**
Error Message: Internal exception was thrown!

I've tested with several skins. This is the only one where I found the issue. I don't know how to test if the skin is somehow "broken", but ingame it looks correct. 
This is how the skin looks like: https://de.namemc.com/profile/Arulean.1

**Comment by BehrRiley** [comment]
you're 34 paper versions and 100 Citizens versions behind, you may consider updating that. A relevant issue was fixed recently here:
https://github.com/DenizenScript/Denizen/commit/9bd7b56e43d6d2eb3fbce6e11914e9e63b30253e
fullwall reworked how skins are handled in Citizens very recently, the problem at the time was a SKinTrait issue.

**Comment by Xericore** [comment]
Thanks. I updated Denizen and completely forgot to update Citizens as well. That fixed the issue.
