### ISSUE TITLE
NPCTag.skull_skin always returns "Tag is invalid"

### ISSUE THREAD

**Issue by Xericore** [DenizenScript/Denizen-For-Bukkit#2201]
**Denizen debug:**
https://one.denizenscript.com/paste/68192

**Paper version git-Paper-226** (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Denizen version 1.1.4-SNAPSHOT (build 1706-REL)**

**The issue is:**
<NPCTag.skull_skin> always returns e.g. Tag <npc[148].skull_skin> is invalid!

**Steps to reproduce:**
1. Look at any NPC
2. /ex narrate <player.target.skull_skin>

**Note:**
I was able to reproduce the issue with Citizens: 2.0.26-SNAPSHOT (build **1904**).
Citizens: 2.0.26-SNAPSHOT (build **1804**) however works for most NPCs (except for a one case described in here: https://github.com/DenizenScript/Denizen/issues/2200)

**Comment by BehrRiley** [comment]
this issue was fixed in a developmental build here: https://github.com/DenizenScript/Denizen/commit/9bd7b56e43d6d2eb3fbce6e11914e9e63b30253e
this bug exists with the latest release of Denizen and is currently fixed in the latest developmental build

**Comment by Xericore** [comment]
Thanks. I can confirm it works correctly.
