### ISSUE TITLE
Tag <context.location.other_block> returns bad location

### ISSUE THREAD

**Issue by DerbanTC** [DenizenScript/Denizen-For-Bukkit#2202]
`/version` **git-Paper-227 (MC: 1.15.2)**
`/version denizen` **(build 4741-DEV)**
**debug:** https://one.denizenscript.com/paste/68310
**script:** https://one.denizenscript.com/haste/68311

The tag <context.location.other_block> does not return the right location when breaking a bed. When I let me return the <context.location> and the <context.location.other_block> by breaking a bed I've got 4 different locations for the same one bed.

**Comment by mcmonkey4eva** [comment]
Fixed.
The tag was reading beds backwards.
