### ISSUE TITLE
Getting console error on bootup that server stopped responding.

### ISSUE THREAD

**Issue by Klawdek** [DenizenScript/Denizen-For-Bukkit#2209]
The output of `/version` on my server is: git-Paper-251 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
The output of `/version denizen` on my server is: Denizen version 1.1.4-SNAPSHOT (build 1707-REL)
(If relevant) A link to a paste of a script demonstrating the issue: **paste here**
The issue is:
**Describe your issue in full here**
I just upgraded paper, denizen and depenizen to the latest versions (as of a few hours ago) and now when I start server I get the console message above that says to check for plugins in the text.  The only plugin I saw mentioned was denizen.
I haven't had it happen at times other than server startup, however this just started happening so there has not been much opportunity for it to happen at other times.

**Comment by mcmonkey4eva** [comment]
Please pastebin the **full** startup log.

**Comment by zachbr** [comment]
Please also update Paper. I suspect this was our issue, not Denizen's.

**Comment by Klawdek** [comment]
I have only seen the message once or twice since posting this.  And it has been at least 5 days since seeing ti last.  I will upgrade paper and see if it happens again.
