### ISSUE TITLE
Hiding chunks mechanisms

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/Denizen-For-Bukkit#2211]
The ability to prevent players from seeing chunks would be a really cool addition, similarly to the entity hiding mechanisms. If possible to use in the same way:
ChunkTag.hide_from_players
ChunkTag.show_to_players
PlayerTag.hide_chunk
PlayerTag.show_chunk

**Comment by mcmonkey4eva** [comment]
You can technically do this with the `player receives packet event` now
