### ISSUE TITLE
on player completes advancement should have more context tags

### ISSUE THREAD

**Issue by rluodev** [DenizenScript/Denizen-For-Bukkit#2213]
the event `on player completes advancement` should have more context tags to use, such as `<context.get_advancement_name>` which returns the name of the advancement completed, and should have the ability to `determine: cancelled`.

**Comment by Ph4i1ur3** [comment]
The inability to be cancelled comes from the Spigot API, outlined here:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerAdvancementDoneEvent.html

Any request for the ability to cancel the event should be taken up with them. As for the a advancement name, that might be possible.
