### ISSUE TITLE
make custom Tab Completions in Command Scripts simpler

### ISSUE THREAD

**Issue by Baileyc889** [DenizenScript/Denizen-For-Bukkit#2218]
Would it be possible to implement an optional and different type of tab complete for command scripts? The current method can be quite lengthy and tedious for commands with several arguments. I propose a format as such:

```My_command:
type: command
name: /warp
tab format:
- create: permission:NODE.HERE:
    (a warp name is entered manually as new data, and thus no tab required here)
- delete: permission:NODE.HERE:
    - <list of warps probbaly stored as a flag>
- teach: permission:NODE.HERE:
    - <server.list_online_players>:
        - <list of warps probbaly stored as a flag>
        - ALL (to teach the player all warps)
    - ALL
        - <list of warps probbaly stored as a flag>
        - ALL (to teach all players all warps)
- forget: permission:NODE.HERE:
    - <server.list_online_players>:
      - <list of warps probbaly stored as a flag>
      - ALL (to make the player forget all warps)
    - ALL
        - <list of warps probbaly stored as a flag>
        - ALL (to make all players forget all warps)
- <list of warps probably stored as a flag>

script:
'script here' ```

Where each indent is a secondary argument of the previous, and typing an entry filters the list automatically

**Comment by mcmonkey4eva** [comment]
Something like this, not in that format, is already on my long-term TODO list (and open for PRs if anyone else wants to contribute it before I get around to it).

**Comment by mcmonkey4eva** [comment]
The thing requested in the title was done yesterday.
The thing requested in the body was not, as that's a fair bit more complex. Might still be open to expansion to something more like that in the future, but for now I'm considering the argument number basis thing ... close enough. If you need more, you might use a handler script that lets you define the per-command specifics in a format like that, such as this: https://forum.denizenscript.com/viewtopic.php?f=9&t=299
