### ISSUE TITLE
IllegalArgumentException from if commands with dashes

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#2219]
Getting a IllegalArgumentException: For input string: "18-05-2020"  when using <util.date.format[dd-MM-yyyy]> in the if command.
logs: https://one.denizenscript.com/paste/69158#38
script: https://one.denizenscript.com/haste/69160

Somewhat alternative solution to this is to change `<util.date.format[dd-MM-yyyy]>` into `<util.date.format[dd/MM/yyyy]>`

**Comment by mcmonkey4eva** [comment]
Has nothing to do with the tag, it's `1-2-3` format (dash in the middle of a number) being misrecognized as a number.
