### ISSUE TITLE
Exception from else if

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-For-Bukkit#2220]
server version: 1.15.2
denizen version: 1707-REL
script: /ex if false { - narrate a } else if <element[true]> { - narrate b }
log: https://hastebin.com/gorenavibo.cs
issue:
Hi, want to let you know the **else if** in this scenario results in an IndexOutOfBoundsException.
It has something to do with the tag, because just **else if true** works.

**Comment by mcmonkey4eva** [comment]
A: Whatever you're doing... stop it.
B: Join Discord for support https://discord.gg/Q6pZGSR
