### ISSUE TITLE
hide_from_players does not affect the visibility

### ISSUE THREAD

**Issue by DerbanTC** [DenizenScript/Denizen-For-Bukkit#2227]
**git-Paper-318 (MC: 1.15.2)**
**4816-DEV**
Debug: https://one.denizenscript.com/haste/69612
Script: https://one.denizenscript.com/haste/69609

`hide_from_players` does not affect the visiblity and the entities are only hidden when the player rejoins on the server

**Comment by mcmonkey4eva** [comment]
Please use Discord for issues like this.
