### ISSUE TITLE
Complex /ex commands using server console or rcon

### ISSUE THREAD

**Issue by DarkoreXOR** [DenizenScript/Denizen-For-Bukkit#2228]
Is it possible to send multilined command?

I want to send commands similar to:

```
foreach <server.list_online_players> as:player:
        - teleport <[player]> <[player].location.add[<util.random.int[-1].to[1]>,0,<util.random.int[-1].to[1]>]>
```

or run tasks with arguments

```
/ex run task_name arg1 arg2 "arg3 with spaces"
```

I want to use `/ex` command as `/ex foreach .... `, but I don't know how to use it in single command line.
Now I'm using tasks, but I want to know how run tasks with parameters and then read parameters in my script.

**Comment by mcmonkey4eva** [comment]
Ask for basic help on Discord https://discord.gg/Q6pZGSR
