### ISSUE TITLE
Inventory dragging tag empty

### ISSUE THREAD

**Issue by OwoUwuOwoUwuOwo** [DenizenScript/Denizen-For-Bukkit#2229]
Please fill in the asterisks sections below.
Use https://one.denizenscript.com/haste to pastebin any scripts.

The output of `/version` on my server is: Paper API version 1.12.2-R0.1-SNAPSHOT
The output of `/version denizen` on my server is: 1.1.4 SNAPSHOT (BUILD 1707-REL)
(If relevant) A link to a paste of a script demonstrating the issue: 
<context.clicked_inventory>
The issue is:

The InventoryTag for the event "on player drags" describing the clicked_inventory is always null, WHILE player already has an opened chest inventory on his screen.
The event "on player clicks" works well and returns correct "<context.clicked_inventory>".
"On player drags" returns correct data when inv is opened in other way than with a chest.
But if "on player drags" tries to process while player has opened a chest AND is viewing both the chest-inner-inventory and his own inventory, this single argument returns itself (aka null) without any data.
How to reproduce:
Open a chest with a "drags" listener, then drag items through any 2 adjacent slots.

**Comment by BehrRiley** [comment]
> `Paper API version 1.12.2-R0.1-SNAPSHOT`
this is not the full output of `/version`.

> `1.1.4 SNAPSHOT (BUILD 1707-REL)`
do NOT download builds from Spigot. Update Denizen. 
Latest Denizen dev builds are at https://ci.citizensnpcs.co/job/Denizen_Developmental/

Latest Denizen stable release builds are at https://ci.citizensnpcs.co/job/Denizen/
Most users should download the stable release build.

**Comment by OwoUwuOwoUwuOwo** [comment]
![2020-06-07_15 51 05](https://user-images.githubusercontent.com/66556536/83969135-dc41f800-a8d6-11ea-8d64-ff3bf10e8546.png)

Latest version, same listener issue, as you could see, sir.

**Comment by OwoUwuOwoUwuOwo** [comment]
![изображение](https://user-images.githubusercontent.com/66556536/83969220-6f7b2d80-a8d7-11ea-9c37-ff88da51d218.png)

**Comment by BehrRiley** [comment]
Can you provide a full startup log? I believe there's a stacktrace error you could be providing ~~(as well as the correct `/version` output)~~ edit: noted that you provided the full `/version` with the image.

**Comment by mcmonkey4eva** [comment]
Use the Discord @ https://discord.gg/Q6pZGSR for support questions please
