### ISSUE TITLE
on loot generates

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#2231]
**ScriptEvent :** `on loot generates`
Triggers when a chest or a container with loot tables is opened when the loot is generated

**Switch**
in:area to only process the event if it occurred within a specified area.

**Contexts**
`<context.entity>` returns the PlayerTag looting
`<context.inventory>` returns the InventoryTag of the container
`<context.loot>` returns the ListTag of all loots to be generated
`<context.has_plugin>` returns an ElementTag(Boolean) whether or not this event was called as a result of a plugin

**Determination**
This event can be cancelled. This adds 'context.cancelled', and determines 'CANCELLED' and 'CANCELLED:FALSE'
`ListTag` Set the loot to be generated via a ListTag of ItemTags

**Comment by mcmonkey4eva** [comment]
Please post an actual request, not whatever this mess of fake meta is.
Also, start requests via Discord, not GitHub.
