### ISSUE TITLE
HamsterAPI Breaking - NetworkManager is private

### ISSUE THREAD

**Issue by linsaftw** [DenizenScript/Denizen-For-Bukkit#2239]
Lot of people are having issues with HamsterAPI and denizen installed because Denizen makes the NetworkManager unobtainable.

Exception:
java.lang.NoSuchFieldException: networkManager

Code which i use to access:
playerConnection.getClass().getDeclaredField("networkManager");

Sadly without this i can't inject my stuff to listen to packets.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
