### ISSUE TITLE
on entity exits vehicle is not being cancelled

### ISSUE THREAD

**Issue by nomadjimbob** [DenizenScript/Denizen-For-Bukkit#2242]
The output of `/version` on my server is:
This server is running Paper version git-Paper-116 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[08:09:44 INFO]: Previous version: git-Paper-111 (MC: 1.16.1)
[08:09:44 INFO]: You are running the latest version

The output of `/version denizen` on my server is:
[08:10:21 INFO]: Denizen version 1.1.5-SNAPSHOT (build 4984-DEV)

A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/haste/73088
Debug: https://one.denizenscript.com/paste/73087

The issue is:
When cancelling a vehicle exit, the script runs and cancels the event, however the player falls through the cart. The cart can be destroyed but not remounted, nor does collisions apply to the cart, a player can walk through it.

**Comment by mcmonkey4eva** [comment]
Use the Discord.
