### ISSUE TITLE
1.16.1 spigot, unknown circumstances makes denizen fail to bind to citizens

### ISSUE THREAD

**Issue by hydridity** [DenizenScript/Denizen-For-Bukkit#2245]
The output of `/version` on my server is: **CraftBukkit version git-Spigot-9639cf7-8fb6585 (MC: 1.16.1)**
The output of `/version denizen` on my server is: **version 1.1.5-SNAPSHOT (build 1713-REL)**
Denizen's error message: **https://imgur.com/a/oVcp2tz**

The issue is:
When I was adding Gringotts plugin to my server, I've noticed after adding gringotts and starting server, denizen started to enable itself before citizens which resulted denizen error message as posted above with citizens not being activated error.
Denizen's traits and functions were indeed unusable on citizen's npcs and accompanied by citizen's error messages of failing to load denizen's traits.
Full plugin list: **https://pastebin.com/c7TuB6zP**

I've then proceeded to check if it's Gringotts fault by starting new server witch plugin combination consisting of: **https://pastebin.com/cKiBUvL7**, but citizens got enabled before denizen hence denizen was able to bind successfully.
At this point I started adding plugins one after one from the original list, watching if denizen enables itself before citizens, until I've assembled combination **https://pastebin.com/4jNuYcV5**, with placeholderAPI being last added, after which denizens kept enabling itself before citizens.
(Sever log without placeholderAPI: **https://pastebin.com/ydJuL1ZM** - line 469-476 Citizens is enabled before denizen, no error at line 634)
(Server log with placeholderAPI: **https://pastebin.com/cmwaUPb9** - line 474 - 548 Denizen is enabled first, failing to bind and then citizen is enabled, line 645 - citizens fails to load denizen's sleeping trait) 

Once again I've proceeded to check this time placeholderAPI with combination: **https://pastebin.com/HwLL0047**, but again, everything is enabled in correct order as seen in server log: **https://pastebin.com/PJH0YmPN** - line 169 - 176

At this point, i have no idea what might be causing this
Because of variable and not easily reproducible nature of this problem, denizen should ensure it's enabled after citizens, if citizens is installed

**Comment by mcmonkey4eva** [comment]
Support is given on Discord @ https://discord.gg/Q6pZGSR
