### ISSUE TITLE
Custom objects get double escaped when adjusted.

### ISSUE THREAD

**Issue by Yukitty** [DenizenScript/Denizen-For-Bukkit#2246]
The output of `/version` on my server is: git-Paper-134 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
The output of `/version denizen` on my server is: Denizen version 1.1.5-SNAPSHOT (build 1714-REL)
Script demonstrating the issue: https://one.denizenscript.com/haste/74462

The issue is:
The "`adjust`" command does not fully unescape the custom object before applying new values, resulting in existing values becoming double-escaped.

Expected output:
> custom@TEST[first=13&dot37;second=0]
> custom@TEST[first=13&dot37;second=11&dot55]

Actual result:
> custom@TEST[first=13&dot37;second=0]
> custom@TEST[first=13&ampdot37;second=11&dot55]

**Comment by mcmonkey4eva** [comment]
Support is on Discord: https://discord.gg/Q6pZGSR
