### ISSUE TITLE
mount and cancelling a dismount problems in Denizen's  1.16.1 series, last worked in Denizen-1.1.4-b1712-REL for 1.15.2

### ISSUE THREAD

**Issue by jplusc** [DenizenScript/Denizen-For-Bukkit#2247]
The output of `/version` on my server is: **This server is running Paper version git-Paper-135 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **Denizen version 1.1.5-SNAPSHOT (build 5024-DEV)**
(If relevant) A link to a paste of a script demonstrating the issue: examples at **https://one.denizenscript.com/denizen/cmds/mount**

The issue is:

I can't seem to find a combination of paper/denizen for 1.16.1 that successfully handles both **- mount** and cancelling a dismount with
```
  events:
    on player steers chicken:
    - if <context.dismount>:
      - determine passively cancelled
```

I last got this to work on 1.15.2 with **paper-385** and **Denizen-1.1.4-b1712-REL**

with Denizen's versions below, I can mount, but I can't cancel the dismount as described above:
- Denizen-1.1.5-b4908-DEV
- Denizen-1.1.5-b4962-DEV
- Denizen-1.1.5-b4987-DEV
- Denizen-1.1.5-b1713-REL

with Denizen's versions below, i cannot mount.  a simple **/ex mount player|boat** fails, the summoned boat can then be mounted in game with a right click:
- Denizen-1.1.5-b5024-DEV
- Denizen-1.1.5-b1715-REL

I am willing to try other combinations of paper/denizens if there is a possibility that one of them will work.

I would try the new 1.16.2 builds, but it seems there is not yet a public version of paper for 1.16.2

I am going to try a few versions between b4987 and b5024 to see when the mount command broke, but my guess is the newer versions probably still have the cancelling a dismount issue.

thanks!

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR

**Comment by jplusc** [comment]
just wanted to say **thanks** for the quick fix on the mount problem with commit: https://github.com/DenizenScript/Denizen/commit/3691460867dc5e7fbabdcd019a67a41cbc458e52

Now running 
**Denizen-1.1.6-b5028-DEV**, *1.1.6-SNAPSHOT (build 5028-DEV), core version: 1.90-SNAPSHOT (Build 719)*
server: **CraftBukkit   version git-Spigot-379750e-1e76d09**

and the mount seems to be working normally!

however I still have the problem that I can't cancel a dismount.

haste for an example. 
https://one.denizenscript.com/haste/74483

but it is pretty basic:
```
  events:
    on player steers chicken:
    - if <context.dismount>:
      - determine passively cancelled
```


update -- after some discussion, it appears that this is caused by a bug with spigot
https://hub.spigotmc.org/jira/browse/SPIGOT-5891 "VehicleExitEvent doesn't cancel properly"

**Comment by mcmonkey4eva** [comment]
# Support is on Discord
https://discord.gg/Q6pZGSR

**Support is on Discord @ https://discord.gg/Q6pZGSR**

## Support is on Discord

--------------> **__SUPPORT IS ON DISCORD @ https://discord.gg/Q6pZGSR__** <-------------
