### ISSUE TITLE
Chat triggers not working with Herochat Pro

### ISSUE THREAD

**Issue by hemfreitas11** [DenizenScript/Denizen-For-Bukkit#2248]
The output of `/version` on my server is: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
The output of `/version denizen` on my server is: Denizen version 1.1.4-SNAPSHOT (build 1712-REL)
(If relevant) A link to a paste of a script demonstrating the issue: This is the script i used to test it https://one.denizenscript.com/haste/74770
The issue is:
The plugin doesn't detect chat triggers when using the plugin [Herochat Pro](https://www.spigotmc.org/resources/herochat-pro-multi-server-chat-channels-and-more-50-off.34305/), no error in console, just nothing happens when you type in chat.

**Comment by SXRWahrheit** [comment]
1) Support is provided on Discord
2) 1.12.2 is no longer actively supported, nor are old Denizen builds
3) This is not a Denizen bug

**Comment by Fortifier42** [comment]
This is because Herochat Pro cancels the event and sends it's own chat messages. As Wahrheit said, not a bug.

**Comment by mcmonkey4eva** [comment]
https://discord.gg/Q6pZGSR
