### ISSUE TITLE
Add Player Context To Vehicle Created Event

### ISSUE THREAD

**Issue by MoonstoneStudios** [DenizenScript/Denizen-For-Bukkit#2249]
There should be a player context on the **on vehicle created** event. There should also be a <context.location>.

This would add:
1.  <context.player> which will return the playerTag of the player who created the vehicle.
2. <context.location> This would get the location
3. **on <playerTag> creates vehicle** event

I also thing there should be  .hexRainbow and .gradient[<colorTag.>|<colorTag.>] tags.

You can use them like this:

1. "<element[This is a rainbow].hexRainbow>" This will color the text with a rainbow gradient.

2. "<element[This is a gradient].gradient[#ffa74a|#000000]>" This will color the text with a gradient from orange to white

I know that the color tags you can do with <&color>, but I think it will save a lot of time and me a bit easier to use.

Thank you.

**Comment by mcmonkey4eva** [comment]
https://discord.gg/Q6pZGSR
