### ISSUE TITLE
ResourceKeyInvalidException when accessing nbt_attributes of 1.15.2 item in 1.16.2

### ISSUE THREAD

**Issue by Xericore** [DenizenScript/Denizen-For-Bukkit#2250]
The output of `/version` on my server is: git-Spigot-379750e-fe4efd1 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
The output of `/version denizen` on my server is: Denizen version 1.1.6-SNAPSHOT (build 5042-DEV)

A link to a paste of a script demonstrating the issue: 

- https://one.denizenscript.com/paste/74854

**The issue is:**
Calling ItemTag.nbt_attributes can cause ResourceKeyInvalidException.

**Steps to reproduce:**

1. Start a new spigot 1.15.2 server. 
2. Install Denizen 1.1.4 R2.
3. Copy https://one.denizenscript.com/paste/74854 to /Denizen/scripts.
3. Join server with 1.15.2 client.
4. /ex give test_item_115
5. /ex run provoke_exception
6. See no exception with 1.15.2 server.
7. Stop the server.
8. Replace /plugins/Denizen-1.1.4-b1712-REL.jar with Denizen-1.1.6-b5042-DEV.jar.
9. Start the same server with spigot 1.16.2.
10. Join with 1.16.2 client.
11. /ex run provoke_exception
12. See exception https://one.denizenscript.com/paste/74853

The problem doesn't happen when calling /ex narrate <player.item_in_hand.nbt_attributes> in 1.16.2 with test_item_115 in hand. It only happens when the item is passed to a task via definition or to a procedure via .context[].

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR
