### ISSUE TITLE
Suggestion: attached_entities tag

### ISSUE THREAD

**Issue by Robsando** [DenizenScript/Denizen-For-Bukkit#2251]
Some time ago the attach command was added and simplified my script. Command handle almost everything what I had to handle by myself before, but doesn't provide one thing: list of attached entities, so I have to still handling all entites in flag to my purposess. 
Summarizing I suggest to add EntityTag.attached_entities tag where all attached entites could be accessed.

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR
