### ISSUE TITLE
Using the rotate command on armor stands without gravity will cause a delay

### ISSUE THREAD

**Issue by The-Mr-Mango** [DenizenScript/Denizen-For-Bukkit#2252]
The output of `/version` on my server is: git-Paper-186 (MC:1.16.2)
The output of `/version denizen` on my server is: 1.1.6-SNAPSHOT (Build 1716-REL)
(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/haste/75543
The debug output: https://one.denizenscript.com/paste/75553
The issue is:

It seems that armor stands, with the gravity mechanism set to false, will have a delay when you rotate them via a world script. Commands work just fine (in game as well as Denizen-made commands), and so do other entities without gravity. I might be missing something.

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR
