### ISSUE TITLE
A inventory object can open, but work like a list object

### ISSUE THREAD

**Issue by sankakacomplux** [DenizenScript/Denizen-For-Bukkit#2253]
The output of `/version` on my server is: git-Paper-135 (MC: 1.16.1) 

The output of `/version denizen` on my server is: Denizen version 1.1.5-SNAPSHOT (build 4988-DEV)

**What i trying to do**:

Make a multipe block container system. Like a diamond block can store item.

**The issue is:**
1. I store a inventory object to server flag for virtual inventory like this:

- flag server "<context.location.x><context.location.y><context.location.z><context.location.world>:in@generic[title=<&a>Container <&f><context.location.x>,<context.location.y>,<context.location.z>;size=9]"

2. I tried do - inventory open d:<server.flag[theflag]> and i open the inventory, every thing seem good 
3. When i try to get inventory tag from the flag, like <server.flag[flag].title> , <server.flag[flag].list_contents> . It cause error and not return **(Unfilled attributes 'title' for tag <server.flag[3274-224W@FLAT1].title>!)**
4. But the flag seem like work as a list object, i try <server.flag[flag].size> -> return 1 , should be 9 for 9 slot of inventory. 
Try .include[barrier] return li@(the inventory tag in@...)|i@barrier

It kinda weird for me because i can open it with **- inventory open** so it seem like a inventory object, but can only return tag for list object.

### **Solution: add .as_inventory**

**Comment by Ph4i1ur3** [comment]
You can find support in the Discord: https://discord.gg/Q6pZGSR

**Comment by sankakacomplux** [comment]
So i am do
