### ISSUE TITLE
on block/plant/structure grows event

### ISSUE THREAD

**Issue by Nakigoee** [DenizenScript/Denizen-For-Bukkit#2255]
Spigot version and Denizen version : https://one.denizenscript.com/paste/76067

I created two years ago a script to manage plants/trees' growth. I use events like "**on block grows**", "**on plant grows**" or "**on structure grows**" for that (e.g. "on cocoa grows" for cocoa), and everything works very well.

I decided to upgrade my script and manage new plants and structures added on 1.14, 1.15 and 1.16, such as bamboo, wither_rose, crimson_fungus. But those events don't work for these plants and structures.

e.g : 

```
PLANTS_WORLD:
    type: world
    debug: true
    events:
            
        on block grows:
            - narrate "test" targets:<server.online_players>
        on plant grows:
            - narrate "test" targets:<server.online_players>
        on structure grows:
            - narrate "test" targets:<server.online_players>
        on block forms:
            - narrate "test" targets:<server.online_players>
        on entity changes block:
            - narrate "test" targets:<server.online_players>    
```
I don't have a message "test" when those plants / structures grow. (I used different events in case those plants are managed by another event).

Cordially,
Nakigoe

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR
