### ISSUE TITLE
On player clicks block event fires when it should not fire.

### ISSUE THREAD

**Issue by LeafyMitsuwa** [DenizenScript/Denizen-For-Bukkit#2256]
Denizen debug -r haste: https://one.denizenscript.com/paste/76295
Denizen events, and inventories involved: https://one.denizenscript.com/haste/76296

The issue is:
The event "on player clicks block" is firing when denizen inventories are open.
The event does not fire inside of regular chests.
I've asked the event to post a <context.location>, but these return as invalid, as there is no block being clicked, but rather, items/slots inside of Denizen inventories.

This affects latest Denizen release, and latest Denizen dev build on 1.16.3

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR
