### ISSUE TITLE
Add <chunkTag.cuboids>

### ISSUE THREAD

**Issue by lmorgh** [DenizenScript/Denizen-For-Bukkit#2257]
I'm trying to find if there's any noted cuboids in a chunk, and there doesn't seem to be a tag for it yet. The method I was advised to use is to foreach through every cuboid and test it with<CuboidTag.partial_chunks>, which seems like a lot of processing just for that purpose, especially when there would be a large amount of cuboids noted.

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR
