### ISSUE TITLE
Missing entity filters to precise_target* tags

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#2260]
As mentioned in the #2161, it might have been a good idea to have added this for the other tags. It doesn't make sense to only have it on the one tag.

Feature request is the same as #2161 but for the tags `LocationTag.precise_target_position`, `EntityTag.precise_target` & `EntityTag.precise_target_position`.
The usage should still be the same as implemented: `*.type[<entity-type>|...]`

**Comment by mcmonkey4eva** [comment]
support is on discord @ https://discord.gg/Q6pZGSR
