### ISSUE TITLE
Error spaming console

### ISSUE THREAD

**Issue by Euphillya** [DenizenScript/Denizen-For-Bukkit#2262]
The output of `/version` on my server is: **https://hastebin.com/ozagiqehuy.apache**
The output of `/version denizen` on my server is: **https://hastebin.com/tasemaqera.yaml**
(If relevant) A link to a paste of a script demonstrating the issue: **https://hastebin.com/sezigozehe.php-template**
The issue is:
**Spam console error**

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR
