### ISSUE TITLE
Custom Enchants

### ISSUE THREAD

**Issue by Eixl** [DenizenScript/Denizen-For-Bukkit#2266]
Possibly add a script type for creating an enchantment?
This would make custom enchantment creation a little easier if this were doable. The process of creating custom enchantments from my understanding requires lore modification and some workarounds that are passable, but undesirable.

   Workarounds being how the player applies the enchantment. I've been told in theory the custom enchantment should be able to be added to the enchanting table, but currently there is no way to do so. Thus the developer would have to make a custom enchanting menu which is fair but (personally) would prefer to apply those custom enchantments at any placed enchanting table around the world through the Enchantment GUI.
  
   (If the enchantment script type can be added, it should be able to modify the properties that are displayed like attack damage and attack speed.)

**Comment by mcmonkey4eva** [comment]
This was added in july: https://meta.denizenscript.com/Docs/Languages/enchantment%20script
