### ISSUE TITLE
Several events failing to match any ScriptEvents in latest release

### ISSUE THREAD

**Issue by BBCSS** [DenizenScript/Denizen-For-Bukkit#2268]
The output of `/version` on my server is: This server is running Paper version git-Paper-444 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

The output of `/version denizen` on my server is:  Denizen version 1.1.9-SNAPSHOT (build 1724-REL)

(If relevant) A link to a paste of a script demonstrating the issue: **paste here**
The issue is:
On startup or reload using the latest release build, I receive a errors about several events not matching any ScriptEvents despite being listed in the documentation. Here's a copy of debug on startup https://one.denizenscript.com/paste/80013

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR
