### ISSUE TITLE
Imperfect <item> argumet

### ISSUE THREAD

**Issue by Darwin1546** [DenizenScript/Denizen-For-Bukkit#2269]
Hello, can you please add **imperfect** argument for commands like **- take**  
I mean this: if you run vanilla command **/clear player_name minecraft:iron_ingot{CustomModelData:1} 1**  
Minecraft will take 1 iron_ingot with CustomModelData:1, no matter the name of this item, it's lore and etc.  
But Denizen matches item tags very accurate and if you want to take item according only **material** and **custom_model_data**, for example, you should use **- foreach** whole inventory and match every item, which is not cool.  
And anyway, we have no simple denizen alternative for that **/clear** vanilla command functionality.  

**- take <item[iron_ingot].with[custom_model_data=1]> quantity:2 from:<player.inventory> imperfect**  
_Takes 2 iron ingots from players inventory with custom model data=1 no matter the lore, display name, etc_  
**<InventoryTag.contains_imperfect[<item[iron_ingot].with[custom_model_data=1]>]>**
_Returns true if inventory has iron ingot with custom model data=1 no matter the lore, display name, etc_

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR
