### ISSUE TITLE
Mechanism piston_reaction to shulker_box

### ISSUE THREAD

**Issue by pobab** [DenizenScript/Denizen-For-Bukkit#2270]
The output of `/version` on my server is: **Zafkiel version git-Zafkiel-bef2adc (MC: 1.16.5)**
The output of `/version denizen` on my server is: **Denizen version 1.1.9-SNAPSHOT (build 5375-DEV)**
(If relevant) A link to a paste of a script demonstrating the issue: **sorry... i dont have it bcs im using /ex command**
The issue is:
**If we try to implement block piston_reaction's Mechanism to shulker box, it's still pushable and drop the shulker box.**

**Comment by mcmonkey4eva** [comment]
Support is on Discord https://discord.gg/Q6pZGSR
