### ISSUE TITLE
Inventory open at horse

### ISSUE THREAD

**Issue by pobab** [DenizenScript/Denizen-For-Bukkit#2273]
The output of `/version` on my server is: **Paper-581**
The output of `/version denizen` on my server is: **1.2.0-SNAPSHOT (build 5469-DEV)**
The issue is:
**It doesn't work properly if I'm trying to open horse inventory with `Inventory Command` like `/ex inventory open d:<player.target>` (the target is a horse)**

You can see that debug right here: **https://paste.denizenscript.com/View/82981**

**Comment by mcmonkey4eva** [comment]
https://github.com/DenizenScript/Denizen/issues/2270
