### ISSUE TITLE
Flag command does not accept expire as argument

### ISSUE THREAD

**Issue by bakaschwarz** [DenizenScript/Denizen-For-Bukkit#2275]
The output of `/version` on my server is:

**This server is running Paper version git-Paper-635 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)**

The output of `/version denizen` on my server is:

**Denizen version 1.1.9-SNAPSHOT (build 1732-REL)**

Script to reproduce:

```
test:
    type: task
    script:
        - flag <player> test expire:2m
```

The issue is:

Following the information on the Denizen Meta Website it should be possible to use `expire` as an argument to specify the expiration of a flag. However, when i execute the above script using `/ex run test` the following error message gets generated:

```
Error Message: 'expire:2m' is an unknown argument! Did you mess up the command syntax?                                                                                             
```

After that i got this info:

```
[16:29:36 INFO]: +> [Argument] Command usage: flag [<object>|...] [<name>([<#>])](:<action>)[:<value>] (duration:<value>)                                                               
```

I mean, okay. I just use `duration` then, but i think it should be decided if `expire` should be usable or not and the code and website/documentation have to be updated.

**Comment by zozer** [comment]
duration was changed to expire a few builds ago. you need to update denizen

**Comment by BehrRiley** [comment]
Your Paper and Denizen versions are both behind, you'll need to update them.

Latest Denizen stable release builds are at https://ci.citizensnpcs.co/job/Denizen/. Most users should download the stable release build.

Latest Denizen dev builds are at https://ci.citizensnpcs.co/job/Denizen_Developmental/. Dev builds are for usually for test servers only.

Latest Paper builds are at https://papermc.io/downloads.

Lastly, support is on Discord @ https://discord.gg/Q6pZGSR - you should request support there instead.

**Comment by bakaschwarz** [comment]
Oh, i downloaded from Spigot. I was not aware the version on there was behind. Thanks for the heads up.

**Comment by bakaschwarz** [comment]
Yeah, now i see your info on the spigot page as well. now i feel dump. Sorry for wasting time 😅
