### ISSUE TITLE
sidebar command broken in 1.17?

### ISSUE THREAD

**Issue by X0nePlay** [DenizenScript/Denizen-For-Bukkit#2277]
The output of `/version` on my server is: 
This server is running Paper version git-Paper-49 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 1c77d64)
You are 4 version(s) behind
Previous version: git-Paper-"c83aa1a" (MC: 1.17)

The output of `/version denizen` on my server is:
Denizen version 1.2.1-SNAPSHOT (build 5645-DEV)

The issue is:
The sidebar command doesn't work properly.
If you do "/ex sidebar set "title:Hello World!" "values:This is|My Message!|Wee!" players:<player>" only the title is shown but the scores are empty.

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR
