### ISSUE TITLE
Translated name not work as expected

### ISSUE THREAD

**Issue by pa6324641** [DenizenScript/Denizen-For-Bukkit#2280]
server log
https://paste.denizenscript.com/View/87241
denizen script
https://paste.denizenscript.com/View/87242

The issue is:
If <context.item.material.translated_name> in item spawn events,will not work as expected.

![image](https://user-images.githubusercontent.com/51245218/128638123-b94aa92e-b4c5-4d2a-8295-ff3b166ae635.png)

**Comment by BehrRiley** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR

**Comment by pa6324641** [comment]
Thanks, after listening to suggestions update to paper server fix this problem.

> Support is on Discord @ https://discord.gg/Q6pZGSR
