### ISSUE TITLE
Tag Broken

### ISSUE THREAD

**Issue by thanhbadaodz** [DenizenScript/Denizen-For-Bukkit#2290]
![image](https://user-images.githubusercontent.com/41854021/149459875-dfd08952-c7f8-4892-8fc9-eed24a7315c4.png)
The issue is:
tag **find_item[emerald]** is work, but **find_all_items[emerald]** is not

**Comment by mcmonkey4eva** [comment]
Support is on Discord https://discord.gg/Q6pZGSR
