### ISSUE TITLE
modifyblock not working with definitions

### ISSUE THREAD

**Issue by BBCSS** [DenizenScript/Denizen-For-Bukkit#2327]
Modifyblock does not want to accept definitions or other fill-ins for the material to be modified into

Here it is acting like it's working just fine but it does not modify the block in-game https://paste.denizenscript.com/View/94007

**Comment by BehrRiley** [comment]
Please be sure to read the template you erased and replaced with your message:

> IMPORTANT: Support is on Discord @ https://discord.gg/Q6pZGSR
> You should only post on GitHub if you've been directed here from the Discord.

Your debug log appears to be copied and pasted from what you assumed was relevant, and you've provided no script that indicates how the definition named `loc` has been defined. Using the debugging tools properly are essential for helping indicate you are on proper versions and builds for your server, you're using modernized script syntax, as well as help us see the full perspective.

Before seeking further support, we'd recommend viewing the guide in full which is found at https://guide.denizenscript.com/.
For help utilizing the debugging tool properly which you failed to do in your original post, please review the guide page which covers this topic at https://guide.denizenscript.com/guides/first-steps/problem-solving.html.

Please pursue any further support on our Discord as indicated above as well as prompted before creating an issue.

**Comment by BBCSS** [comment]
Nah I'm not going through a whole conversation going over something so simple. I barely have the time to waste on this anymore. You can see very clearly that it is passing all those definitions just fine and the command is accepting it. Fix it or don't, I've already reverted everything to the messy way you guys don't like, but was working so it's no hair off my back if you blow off bugs.

https://paste.denizenscript.com/View/94027

**Comment by mcmonkey4eva** [comment]
Support is on Discord https://discord.gg/Q6pZGSR

It is not on GitHub issues. You have been spamming this repo with nonsense issues rather than just clicking a link to a Discord to use a Discord thread which is the only accepted location for support.

Your attitude will get you nowhere.
