### ISSUE TITLE
NPCs Sinking into ground instead of sitting

### ISSUE THREAD

**Issue by fruitologistero** [DenizenScript/Denizen-For-Bukkit#2352]
It used to work perfectly fine, but one day, instead of sitting down the NPC was just sunk into the ground.

Now instead of sitting, the NPC looks like this when using the "/npc sit" command:
![image](https://user-images.githubusercontent.com/91402640/184576844-c7b34e8a-0912-469e-af40-19bb603e70f2.png)

No idea what happened, but we'd like to get this fixed soon.

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR

**Comment by fruitologistero** [comment]
> Support is on Discord @ https://discord.gg/Q6pZGSR

what's the point in having issues if you're just gonna tell people to go the discord like mb i didn't realize this was just the redirect section
