### ISSUE TITLE
Improve Tag <PlayerInventoryTag.map_slots>

### ISSUE THREAD

**Issue by thanhbadaodz** [DenizenScript/Denizen-For-Bukkit#2384]
Hello, i have some Idea to improve Tag map_slots
Tag <PlayerInventoryTag.map_slots> will better if it's include 37,38,39,40(Armor) Slot(just 1-36 slot for now)
or rework <PlayerTag.equipment_map> return Instead of 1 map containing Boots,Leggings,Chestplate,Helmet, Please Return 1 Map containing 37,38,39,40 (To Can Easily Combine With <InventoryTag.map_slots>)
Sorry for my bad English
Thankyou, hope for your reply

**Comment by mcmonkey4eva** [comment]
You were already informed that support is on Discord https://discord.gg/Q6pZGSR
