### ISSUE TITLE
Nested translate tags produce broken strings

### ISSUE THREAD

**Issue by lexiccn** [DenizenScript/Denizen-For-Bukkit#2461]
The output of `/version` on my server is: git-Paper-514 (also tried on git-Paper-368)
The output of `/version denizen` on my server is: build 1791-REL (also tried on build 1782-REL)

The issue is:
Nested translations (seemingly 3+ layers from testing) cause broken output:

`<&translate[potion.withDuration].with[<&translate[potion.withAmplifier].with[<&translate[effect.minecraft.speed]>|<&translate[potion.potency.1]>]>|08<&co>00]>` produces "%s %s;II] (08:00)"
`<&translate[potion.withDuration].with[Speed II||08<&co>00]>` produces Speed II (08:00)

Debug logs: https://paste.denizenscript.com/View/108976 

Clearly showing identical output; then producing different results.

Two layers (e.g forming Speed II) works fine in all cases.

**Comment by lexiccn** [comment]
Should note I have also tried wrapping each list in a <list[]> tag; as well as saving the translation results to definitions and passing that to the next layer - neither of these changed the results.

**Comment by mcmonkey4eva** [comment]
No you may not bypass your Discord ban by posting on GitHub.
