### ISSUE TITLE
Oraxen Support

### ISSUE THREAD

**Issue by ItzMeLilG** [DenizenScript/Denizen-For-Bukkit#2471]
It would be nice to have a proper way to make scripts with Oraxen items

Here is the Oraxen API to add support
https://docs.oraxen.com/developers/api

**Comment by tal5** [comment]
This would be added into [Depenizen](https://github.com/DenizenScript/Depenizen), but in this case we are unable to add Oraxen support as we are only able to provide Depenizen integration for plugins with public free jar files (they do provide the source code, but that's not a compiled jar, and their license explicitly prohibits redestrbuating it, which means it can't be in [Depenizen-Lib](https://github.com/DenizenScript/Depenizen-Lib)).
Can:

- Ask them to use a model like Citizens' (free and buying is a donation), MythicMobs' (free builds with buying having extra benefits), etc.
- Build external integration (I.e. your own plugin that's not directly related to either)
- Ask them to include Denizen support
- In a lot of cases you can interface with other plugins without built-in integration, feel free to open a thread on the [Discord](https://discord.gg/Q6pZGSR) and we can try and help.

Also, feature requests should generally go on the [Discord](https://discord.gg/Q6pZGSR).

**Comment by Boy0000** [comment]
@tal5 any reason this cannot just use Oraxens publicly available API and needs the full built jar?
You probably wouldnt need anything that you could not just get from the 2 or 3 API classes

Sidenote: Oraxen is also following a similar model to Mythic, paid = support and default assets.

**Comment by tal5** [comment]
> @tal5 any reason this cannot just use Oraxens publicly available API and needs the full built jar? You probably wouldnt need anything that you could not just get from the 2 or 3 API classes

See the [Depenizen-Lib](https://github.com/DenizenScript/Depenizen-Lib) repo - other then using the jars for the dependencies, we also have them there to make sure that contributors always have all the jars they need for testing

> Sidenote: Oraxen is also following a similar model to Mythic, paid = support and default assets.

Yeah, the issue is that they don't provide compiled jar files, and their license forbids distributing them (I.e. can't have them on that repo)
