### ISSUE TITLE
Some artifacts are missing in the published Maven artifacts

### ISSUE THREAD

**Issue by Joo200** [DenizenScript/Denizen-For-Bukkit#2478]
The output of `/version` on my server is: unrelated

The output of `/version denizen` on my server is: dev/master (1.2.7-SNAPSHOT)

The issue is:

The CI doesn't create the maven artifacts for denizen-parent and the version submodules like in 1.2.5-SNAPSHOT. 
Affected versions: Version 1.2.6-SNAPSHOT and 1.2.7-SNAPSHOT 

This is most likely broken since 39f3074e541925a509d92b17d7eefc185b15bb8f or with a CI change from Jenkins.

Using Denizen in some Maven project works fine however using it with gradle which will resolve parent modules doesn't work anymore.

Can you please deploy the maven pom for denizen-parent too? The version dependend artifacst (denizen-v1_1x) shouldn't be needed.

**Comment by mcmonkey4eva** [comment]
Support is on Discord @  https://discord.gg/Q6pZGSR
