### ISSUE TITLE
NoClassDefFoundError "craftbukkit/v1_20_R3/inventory/CraftInventoryCustom"

### ISSUE THREAD

**Issue by CrazyFish159** [DenizenScript/Denizen-For-Bukkit#2589]
The output of `/version` on my server is: 
> This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
> You are running the latest version
> Previous version: git-Paper-196 (MC: 1.20.1)

The output of `/version denizen` on my server is: 
>Denizen version 1.3.0-SNAPSHOT (build 1802-REL)

(If relevant) A link to a paste of a script demonstrating the issue: https://paste.md-5.net/faxudodaca.md
The issue is:
when the plugin is being loaded i get an error

**Comment by mcmonkey4eva** [comment]
Support is on discord @ https://discord.gg/Q6pZGSR
