### ISSUE TITLE
b1782 1.16.5 don't work

### ISSUE THREAD

**Issue by DonorKrovi** [DenizenScript/Denizen-For-Bukkit#2639]
https://mclo.gs/R71KtJr
The output of `/version` on my server is: **This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **Denizen version 1.2.5-SNAPSHOT (build 1780-REL)**
(If relevant) A link to a paste of a script demonstrating the issue: ****
Error obtaining version information**
The issue is:
I start the server and this plugin crashes.

**Comment by heypr** [comment]
Hi there! Please join the Discord to receive support: https://discord.gg/Q6pZGSR

**Comment by DonorKrovi** [comment]
bullshit
