### ISSUE TITLE
Even when using as_int still gets decimal (.0) added to the total, after subtraction.

### ISSUE THREAD

**Issue by mythan** [DenizenScript/Denizen-For-Bukkit#417]
Trying to subtract two values, both with the "as_int" suffixed, still still result with a decimal value, which doesn't work with the minecraft scoreboard function.

I am unable to do something like `<%finaldamage%.as_int>` on the total value, so can't have the decimal stripped off on last value.

What do?

Script to reproduce:

```
"Health Test":
  type: assignment

  interact scripts:
  - 10 Punch my Face

  actions:
    on assignment:
    - trigger name:damage toggle:true
    - execute as_server "npc sel <npc.id>"
    - execute as_server "npc vulnerable"

"Punch my Face":
  type: interact

  steps:
    1:
      damage trigger:
        script:
        - define phealth "<npc.health.as_int>"
        - wait 1t
        - define finaldamage "<m:%phealth%-<npc.health.as_int>>"
        - chat "npc.health.as_int<&co> <npc.health.as_int>"
        - chat "phealth<&co> %phealth%"
        - chat "finaldamage<&co> %finaldamage%"
```

Result of script:

<a href="http://imgur.com/zVFnNDp"><img src="http://i.imgur.com/zVFnNDp.png" title="Hosted by imgur.com" /></a>

**Comment by mcmonkey4eva** [comment]
@mythan what happened to yoooouuuu D:

**Comment by mythan** [comment]
I'm alive and well! Just been playing 7 Days to Die, it's awesome! Too bad you can't script NPC's like you can with Denizen. Wait a minute.... are you saying what I think you're saying? Denizen for 7DTD?? You are awesome! Can't wait to see v0.01  ;-)

**Comment by Morphan1** [comment]
@mythan we'll make Denizen-for-WhateverYouWant if you come back to us :crying_cat_face:

**Comment by Matterom** [comment]
It's somewhat true, we can. we have the technology

**Comment by mcmonkey4eva** [comment]
@mythan you should come into denizen-dev and chat with us some time, we miss you man.

Also if 7dtd opens to modding... we can do that >:D

**Comment by mythan** [comment]
@Morphan1 I never left you guys, I still watch you through the window sometimes.

@mcmonkey4eva Can't mod it as much as MC using Bukkit. They have highly customizable XML files, but you're still confined by what hasn't been exposed as a tag. We are running a modded server at "oz.nz" where we made some custom items, biomes, crafting recipes etc. It's a Steam greenlight game, so still under heavy development.

@Matterom hey man! Good to see you're still around :D

**Comment by Matterom** [comment]
I exist in spurts.. sometimes they don't see me in months. But im not near as bad as some other folks.

**Comment by mythan** [comment]
@mcmonkey4eva Actually, that's not exactly true. It uses the Unity engine, so you can extract assets files and add completely custom items etc but then the client side needs to download files which we're trying to avoid.

**Comment by mcmonkey4eva** [comment]
@mythan I'm talking open source code that we can edit and inject a scripting engine into

**Comment by mcmonkey4eva** [comment]
It /might/ be possible to decompile, but it's questionably legal to redist that

**Comment by Matterom** [comment]
Should message aufdemrand and ask to market denizens.

Denizen Script: Just tack it in..? Just...something.. im bad at slogans

**Comment by mythan** [comment]
@mcmonkey4eva Yeah, I dunno about that. My knowledge about modding 7DTD stops at the point where custom files are needed. But I'll definitely let you know if they open it further in the future :D

**Comment by mcmonkey4eva** [comment]
@mythan It's written in C#, and I happen to have a C# script engine very similar to Denizen that needs a proper home available.
Some differences, though. The syntax is different in a few ways... and it runs roughly 12x faster I believe.

**Comment by mcmonkey4eva** [comment]
@mythan now seriously get in denizen-dev http://mcmonkey.org/ircchat_denizen
