### ISSUE TITLE
Notables should respect casing

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#904]
Notable objects all get lowecased. This poses potential problems. Think of a situation where someone has 2 worlds, one is named *World*, the other is named *world*. Now the user wants to make a noted cuboid in each world around the spawn area, naming them each after their world. *World_spawn* and *world_spawn*. This is just one simple example, but the use cases are abundant.

**Comment by mcmonkey4eva** [comment]
I believe this was handled in an IRC discussion. Reply below if you still have trouble.

**Comment by AnthonyAMC** [comment]
I'm not remembering what the resolution was.

**Comment by Morphan1** [comment]
@AnthonyAMC I don't believe you were there. Just try whatever wasn't working in the latest build

**Comment by AnthonyAMC** [comment]
I've already .to_lowercase on just about everything, despite my better judgment.
