### ISSUE TITLE
"show_boss_bar" Mechanism Dissapears

### ISSUE THREAD

**Issue by OzOwnz** [DenizenScript/Denizen-For-Bukkit#908]
When the player looks in a different direction after using the show_boss_bar mechanism, the boss bar's custom text vanishes.

The fact that it (kinda) works again, was why I made this issue. I know we were waiting for better API for this function before re-adding it...

**Comment by mcmonkey4eva** [comment]
@Morphan1 - that might not be the worst idea.

**Comment by OzOwnz** [comment]
Other big-name servers on 1.8 have seemed to find a way to get this feature working, any news on this issue?

**Comment by mcmonkey4eva** [comment]
I'm betting it works similar to how @Morphan1 said to do it. MORPH IMPLEMENT PLS.

**Comment by OzOwnz** [comment]
Any news on this?

**Comment by GomaTerzu** [comment]
Seems to be fixxed. Just tried it, Boss bar blinks sometimes, but does not disappear, not matter how far I move

**Comment by mcmonkey4eva** [comment]
Hooray!
