### ISSUE TITLE
Weird teleport when canceling on player enter/exit notable cuboid

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#913]
Canceling the event teleports the player roughly one block above their actual location. This does not happen if the player enters/exits the cuboid via teleport. It's only on walk. This results in the player being able to scale an invisible wall and bounce along an invisible ceiling.

**Comment by mcmonkey4eva** [comment]
Cannot replicate.

**Comment by AnthonyAMC** [comment]
This isn't happening with dev-b65 and latest spigot. idk if something changed somewhere or what, but it's working as expected now.

**Comment by mcmonkey4eva** [comment]
:)
