### ISSUE TITLE
Scoreboard Disappears After a Few Seconds

### ISSUE THREAD

**Issue by OzOwnz** [DenizenScript/Denizen-For-Bukkit#915]
After using the scoreboard command, the sidebar seems to disappear after a couple of seconds. I can't recall if this happened in previous versions...

**Comment by mcmonkey4eva** [comment]
This was determined on IRC to be your own fault, wasn't it?

**Comment by OzOwnz** [comment]
> This was determined on IRC to be your own fault, wasn't it?

Yes, yes it was. My autosave script was deleting the scoreboards.yml and reloading.
