### ISSUE TITLE
add in a function to the note command

### ISSUE THREAD

**Issue by calico-kid** [DenizenScript/Denizen-For-Bukkit#918]
i would like it if the note command could have an add argument to add in a cuboid location something like:
`- note add cu@location|location as:name`
also a remove with a cuboid list would be cool but the add portion is mainly what i am interested in right now if it is possible :D

**Comment by mcmonkey4eva** [comment]
Why can't you just 
`- note <CUBOID.full>|location|location as:CUBOID`
?

**Comment by calico-kid** [comment]
wow i didnt even see you respond to this lol.... only thing is for that method is how would i remove the new cuboid? or even the old one? is it stored as a list of cuboids like in a flag cuz if so then i could use cuboid.get[2] or whatever
