### ISSUE TITLE
Entity Enter/Exit notable smart event

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#919]
Currently it only handles players. Could it be made to handle all entities?

**Comment by mcmonkey4eva** [comment]
Was thinking about that yesterday... NPCs are somewhere in my todolist...

**Comment by AnthonyAMC** [comment]
Not, just NPCs, but all mobs.

**Comment by AnthonyAMC** [comment]
If the on entity targets event fired for location type targets, i could just cancel that... which now that i think about it would be ideal.

**Comment by mcmonkey4eva** [comment]
I know.

**Comment by mcmonkey4eva** [comment]
I don't know if entity targets location is possible, will look into

**Comment by mcmonkey4eva** [comment]
Waiting on https://hub.spigotmc.org/jira/browse/SPIGOT-351

**Comment by mcmonkey4eva** [comment]
Please reopen when Spigot merges.
