### ISSUE TITLE
More context for player clicks block event.

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#920]
Can we have [getBlockFace](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerInteractEvent.html#getBlockFace%28%29) added to the available context?

**Comment by mcmonkey4eva** [comment]
I was thinking rather than that, a tag which returns the location + the blockface transition.

**Comment by AnthonyAMC** [comment]
Stop transmitting brainwaves.

**Comment by mcmonkey4eva** [comment]
Fix sent in to the dev repo
