### ISSUE TITLE
Missing context for on player clicks block event

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#921]
[PlayerInteractEvent](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerInteractEvent.html#getBlockFace%28%29) provides for [5](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/block/Action.html) action types, yet denizen modifies the event down to just 2, ```LEFT_CLICK_BLOCK``` and ```RIGHT_CLICK_BLOCK```. Can the full event context be made available?

**Comment by mcmonkey4eva** [comment]
Uh... Nope. Look at the source code for the player clicks block event, it provides everything :)
