### ISSUE TITLE
"on player enters <notable_cuboid>" Doesn't Fire With A Notable Ellipsoid

### ISSUE THREAD

**Issue by OzOwnz** [DenizenScript/Denizen-For-Bukkit#924]
The "on player enters <notable_cuboid>" event doesn't fire when the player enters the ellipsoid created by the command script, provided below.
```
Ellipsoid Command:
  type: command
  name: cb
  script:
    - ^note ellipsoid@-1615,3,-334,sandbox,8,1000,8 as:test
Ellipsoid World Events:
  type: world
  events:
    on player enters cu@test:
    - ^narrate "Entered"
```

(Note: I'm using 1000 for the y-radius to emulate a cylindrical shape.)

**Comment by mcmonkey4eva** [comment]
CUBOIDS
ARE NOT
ELLIPSOIDS.
STOP. ASSUMING. THAT.

**Comment by Morphan1** [comment]
*giggles* :smile_cat:
