### ISSUE TITLE
on block ignite event missing cause

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#925]
The BlockIgniteEvent event has a [cause](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockIgniteEvent.IgniteCause.html). Can we have that added to on block ignite?

**Comment by mcmonkey4eva** [comment]
Why even post an issue about something I could fix in ten seconds after an IRC message?

**Comment by AnthonyAMC** [comment]
Cause no one forgets git issues

**Comment by mcmonkey4eva** [comment]
... shut your face I don't forget things D:<

**Comment by AnthonyAMC** [comment]
Maybe not, but i certainly do. Thanks github for being a public scratch pad!
