### ISSUE TITLE
Potions not being taken from inventory

### ISSUE THREAD

**Issue by Croat** [DenizenScript/Denizen-For-Bukkit#926]
First of all, the problem appears only with NON-splash potions.

When holding a potion, "`take <player.item_in_hand>`" cannot remove it. Same thing if you have two identical potions and holding one of them.

BUT

if you do "`give <player.item_in_hand>`" and then "`take <player.item_in_hand>`", it will successfuly remove the potion it just gave it to you (regardless of its position on the inventory).

**Comment by mcmonkey4eva** [comment]
Fixed in the latest dev build, will update when pushed to the main repo.

**Comment by mcmonkey4eva** [comment]
Pushed to main.
