### ISSUE TITLE
Chat Trigger Not Firing When Using Async?

### ISSUE THREAD

**Issue by OzOwnz** [DenizenScript/Denizen-For-Bukkit#927]
The NPC chat trigger seems to only fire when both the:
```
Scripts:
  World:
    Events:
      On player chats:
        # Whether to use the dangerous 'async' chat event (not recommended!)
        Use asynchronous event: false
```
and the 
```
Triggers:
  Chat:
    Enabled: true
    Use asynchronous event: false
```
are set to false, or not to use the asynchronous chat method, which is a lot better for my server since it decreased the load the player chat event had on my timings.

**Comment by Morphan1** [comment]
Sounds like chat plugin interference.

**Comment by OzOwnz** [comment]
Without Denizen, my chat is the default Minecraft chat. I use Denizen's on player chats event to cancel and manually announce the message since I plan to integrate channels and whatnot.

I disabled my chat script and the chat trigger **does** work once again with the async option enabled. I guess I should flag the player or something when they enter a NPC's range so the player chats event doesn't cancel it too quickly.

Not even - determine passively cancelled lets the NPC check the chat spoken for a trigger.

**Comment by OzOwnz** [comment]
Whoops! Forgot to close.
