### ISSUE TITLE
dSentry script errors

### ISSUE THREAD

**Issue by o0ower0o** [DenizenScript/Denizen-For-Bukkit#929]
Hello, I tried this script for dsentry: http://mcmonkey.org/denizen/repo/entry/0

I occasionally get errors when the NPC attacks me and if I change world when the NPC is attacking me, a lot of error concerning distance between different worlds appears.

http://pastebin.com/uBZWRCLM
http://pastebin.com/ZJHezRAe

Denizen version: 0.9.6 build: 1542
Server version: git-Spigot-1.7.9-R0.2-207-g03373bb
Citizens version: 2.0.13 build:1175

**Comment by mcmonkey4eva** [comment]
https://raw.githubusercontent.com/mcmonkey4eva/DenizenScripts/master/dsentry.yml try this version of dSentry?

**Comment by o0ower0o** [comment]
Got this when I went from the world where the npc is to another world:
http://pastebin.com/K1Q5addL

Then I got this when I changed the type of the npc from human to zombie (in that moment the npc was attacking me, so maybe that's the reason):
http://pastebin.com/Q34TmGjP

And then i got this when i teleported from another world to the npc:
http://pastebin.com/TwB2d1tw

There was no spam in console this time, just these 3 errors.

**Comment by mcmonkey4eva** [comment]
I don't know what to say other than update Denizen / CB. We're building for the latest 1.8 servers now and it's hard to back-support.

**Comment by o0ower0o** [comment]
Oh ok. Well, this is better than before, it doesn't spam in console so it's easier to handle. Thanks for your help :)
