### ISSUE TITLE
Enter notable cuboid not working when teleporting from another world

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#930]
The event doesn't fire if you enter the cuboid from another world. I'm not sure if it has to do with the chunks not being loaded, or the world not being loaded, or if it just isn't listening to the world change event.

**Comment by mcmonkey4eva** [comment]
Is this still an issue on latest dev builds?

**Comment by AnthonyAMC** [comment]
Yes it is
