### ISSUE TITLE
List in flags not working?

### ISSUE THREAD

**Issue by michalet** [DenizenScript/Denizen-For-Bukkit#931]
Step one: `/ex flag server "test:1|2|3"`
Step two: `/ex narrate <server.flag[test].as_list.size>`
Server responds with: 1 (should respond with 3, I think)

This used to work, but it's been a while since I've last used Denizen & Citizens. So did something change and this doesn't work any more?

Server: git-Spigot-e497721-96d09e3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
Citizens v2.0.14-SNAPSHOT (build 1204)
denizen 0.9.6-SNAPSHOT (build 1552)

**Comment by AnthonyAMC** [comment]
To store a known list to a flag
```flag server test:|:1|2|3```
To add to the flag list
```flag server "test:->:4"```
To narrate the whole list
```narrate "<server.flag[test].as_list||fallback value>"```
To narrate a specific index
```narrate "<server.flag[test].get[1]||fallback value>"```

**Comment by michalet** [comment]
I tried `flag server test:|:1|2|3` but didn't work before, don't know exactly why. Worked this time, thanks.

btw, isn't `:|:` for adding multiple list items to a flag in general?

**Comment by mcmonkey4eva** [comment]
`btw, isn't :|: for adding multiple list items to a flag in general?`
Yes.

**Comment by michalet** [comment]
Thank you both for help, I think this can be closed now.
