### ISSUE TITLE
Update on entity spawn event

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#932]
Use new spigot API for [EntitySpawnEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntitySpawnEvent.html) instead of current [CreatureSpawnEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.html).

**Comment by mcmonkey4eva** [comment]
Waiting on Spigot to merge Spigot-API into Bukkit master

**Comment by mcmonkey4eva** [comment]
Please reopen when Spigot merges.
