### ISSUE TITLE
SUGGESTION: Improving item_message mech

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#934]
I talked about this with Morphan some days ago but i want to write it down so it is not forgotten.

At this mement the item_message mech works like this

- when i have an item in my hand the message above the Level-Counter shows up and the item in my hand gets renamed permanently. I can get the original name back when i repeat the adjust command with an empty entry.

- when i have no item in my hand i get free glass item with the message as it's name

I want to suggest that the message should show up, and does not change anything at all. Also it should work with no items in your hand.

**Comment by Morphan1** [comment]
@GomaTerzu you never did provide a link to any plugin with this capability...

**Comment by mcmonkey4eva** [comment]
"Suggestion: I think you should do the impossible."

**Comment by GomaTerzu** [comment]
Morphan because it's not public

mcmonkey how do i know it's impossible? so just close it here -.-

**Comment by mcmonkey4eva** [comment]
@GomaTerzu - Didn't mean any offense, I was just giggling around. Please do continue posting suggestions as you come up with them.
