### ISSUE TITLE
BUG experience calculation..again

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#935]
It seems to me that calculating experience is broken again. Here are my test results:

1. < player.xp.total> says i have 130 XP
2. now i use - experience take 20
3. result is i have now 129 XP

Ok so now i simply die and give myself 2000 xp
1. i now have 2000 XP
2. i take away 20
3. i now have 1157 xp.total

Best thing is < player.xp> changes in mysterious ways. sometimes it increases when i take away XP sometimes it decreases at random numbers.

Debug says no errors

**Comment by AnthonyAMC** [comment]
I'm not sure how the ```experience``` command is /supposed/ to behave, but it certainly isn't behaving like i expected. For now, use the give command.

Start by clearing your xp
```/ex give player xp qty:<el@val[0].sub[<player.xp.total>]>```
Add to your xp
```/ex give player xp qty:20```
Show your xp
```/ex narrate <player.xp.total>```

**Comment by GomaTerzu** [comment]
Thanks anthony give 200 or -200 works now, the experience command has this issue every few month i guess :D

**Comment by mcmonkey4eva** [comment]
The experience command breaks every version as Mojang arbitrarily rewrites how things work.

**Comment by Dandielo** [comment]
Might be fixed with the last fix, but you would need to check it
