### ISSUE TITLE
broken .region tags

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Denizen-For-Bukkit#936]
Region tags are returning with the tag and creating an internal error. This has persisted through multiple updates. I have done all the debug/troubleshooting I can think of. I made sure to update I have tried the latest dev and main builds of denizen. 

dScript: /ex narrate <player.location.regions>
Server Log: http://mcmonkey.org/paste/12719

Summery of error:
- Start server
- log on
- type: /ex narrate <player.location.regions>
- returns "player.location.regions"
- get internal error
- log out

Are you even in a region? Yes.

**Comment by mcmonkey4eva** [comment]
Depenizen issues go on the Depenizen page https://github.com/DenizenScript/Depenizen-For-Bukkit/issues
