### ISSUE TITLE
Armor slot numbers in getArmorContents array inversed

### ISSUE THREAD

**Issue by Hellgast23** [DenizenScript/Denizen-For-Bukkit#939]
The indexes of the armor in playerInventory#getArmorContents() are inversed.
Tested on Spigot 1.8 and Spigot 1.7 w/ protocal hack.

Normally:
Helmet -> armor slot with index 3
Chestplate -> armor slot with index 2
Leggings -> armor slot with index 1
Boots -> armor slot with index 0

 Methods in PlayerEquipsArmorSmartEvent.class affected:
```
private int getArmorTypeNumber(ItemStack itemStack) {
        return (itemStack.getTypeId()-298)%4;
    }
    
    private String getArmorType(ItemStack itemStack) {
        if (!isArmor(itemStack))
            return "helmet";
        switch (getArmorTypeNumber(itemStack)) {
            case 0:
                return "helmet";
            case 1:
                return "chestplate";
            case 2:
                return "leggings";
            case 3:
                return "boots";
        }
        return null;
    }

```

**Comment by AnthonyAMC** [comment]
Maybe i'm missing something, but the results of ```<player.equipment>``` return in the order you say they ought to.
```
- define equip '<player.equipment>'
- equip <player> 'boots:<def[equip].get[1]||i@air>' 'legs:<def[equip].get[2]||i@air>' 'chest:<def[equip].get[3]||i@air>' 'head:<def[equip].get[4]||i@air>'
```
The fifth index in the list would be the item in hand.

**Comment by Morphan1** [comment]
That method goes by item ID and is unrelated to anything I can see that you're trying to say.

**Comment by mcmonkey4eva** [comment]
@Hellgast23 ... did the two rather abrupt replies answer your question sufficiently? If not, please reply below with further explanation of the issue.

**Comment by Hellgast23** [comment]
Currently this isn't triggering right.
The getArmorTypeNumber() returns the INVERSED slot number index of the getArmorContents() array. This makes the event only trigger half of the time.
This part:

ItemStack currentItem = event.getPlayer().getInventory().getArmorContents()[getArmorTypeNumber(item)];
            if (currentItem == null || currentItem.getType() == Material.AIR) {

In this method:
  @EventHandler
    public void playerInteract(PlayerInteractEvent event) {
        if (event.hasItem()) {
            ItemStack item = event.getItem();
            Action action = event.getAction();
            Block clicked = event.getClickedBlock();
            if ((action != Action.RIGHT_CLICK_AIR && action != Action.RIGHT_CLICK_BLOCK)
                    || !isArmor(item) || (clicked != null && isInteractive(clicked.getType())))
                return;
            int x =0;
            ItemStack currentItem = event.getPlayer().getInventory().getArmorContents()[getArmorTypeNumber(item)];
            if (currentItem == null || currentItem.getType() == Material.AIR) {
                Player player = event.getPlayer();
                if (playerEquipsArmorEvent(player, item, "INTERACT")) {
                    event.setCancelled(true);
                    return;
                }
            }
        }
    }

**Comment by Morphan1** [comment]
That would have been nice info to begin with...
