### ISSUE TITLE
Tags <util.player_is_valid[<player name>]> isn't recognized as a tag.

### ISSUE THREAD

**Issue by Dopplizzle** [DenizenScript/Denizen-For-Bukkit#941]
Also applies to `<util.npc_is_valid[<npc>]>`  (this tag worked in build 1552, but not in 1558+).

**Comment by mcmonkey4eva** [comment]
How about on the dev builds?

**Comment by Dopplizzle** [comment]
Erm, I thought the Jenkins builds were dev builds...? (the ones betweem 1552 and 1558 are failed builds...)

**Comment by mcmonkey4eva** [comment]
http://ci.mineconomy.org/job/Denizen_Developmental/
These are super-duper-developmental.

The main Citizens CI ones are pretty much release builds, we only build every 10+ commits, and only after confirming stability.

(The failed builds were a jenkins error)

**Comment by Dopplizzle** [comment]
Ahhh...okay, it first fails in dev build #58...

**Comment by mcmonkey4eva** [comment]
... I just remembered, Util tags are broken and fixing that is on my todolist. From several days ago @.@
I need to hurry up and do that.

**Comment by mcmonkey4eva** [comment]
Should be fixed in the new latest dev build.
