### ISSUE TITLE
Static Player Heads

### ISSUE THREAD

**Issue by OzOwnz** [DenizenScript/Denizen-For-Bukkit#944]
Somehow, using nbt data or something, some guys over at http://heads.freshcoal.com/ have been able to create custom player heads not using player names, but using a skin a player had used previously.

Example: 
Permanent head that looks like a mug of cocoa or something:
```
/give PLAYERNAME skull 1 3 {display:{Name:"Mug Cocoa"},SkullOwner:{Id:"a3e815e9-dd5e-4c96-b6df-22e25f4c88e1",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2YyMzg4NDVjNjQ5NGExYzRiODdkOGQ3NTM4ZDI3MDI1ZTIwMWY4YjFkMzA3NjcyZWIxZTJlM2Q2OTQ3YmMifX19"}]}}}
```
I think we should hook into that rather than player skins due to skins being able to change whenever the owner wants, leading to their "not-so-usability" because of that danger. I see potential for advanced item scripts that don't rely on player names, and safer player heads for decoration.

Also, Denizen's skull tags such as ".skull_skin" return null when using these new heads.

I did a bit more research, and it turns out that the string
```
eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2YyMzg4NDVjNjQ5NGExYzRiODdkOGQ3NTM4ZDI3MDI1ZTIwMWY4YjFkMzA3NjcyZWIxZTJlM2Q2OTQ3YmMifX19
```
decodes to: 
```
http://textures.minecraft.net/texture/3f238845c6494a1c4b87d8d7538d27025e201f8b1d307672eb1e2e3d6947bc
```
which is a .png of someone's skin.

According to Dinnerbone: 
> Skulls are a snapshot of the skin as it was made; just change your skin, make a skull, and change > your skin back. That's intended behaviour.

Other useful links:
http://heads.freshcoal.com/index.php
http://heads.freshcoal.com/maincollection.php
http://www.reddit.com/r/MinecraftHeads/comments/251m9d/discussion_dinnerbone_changed_the_way_heads_work/
http://www.reddit.com/r/MinecraftHeads/comments/2gh1x9/subreddit_direction/

**Comment by OzOwnz** [comment]
Meh, not too sure where this was heading. Feature probably won't even stick around for all that long anyways.

**Comment by Morphan1** [comment]
I like this.

**Comment by mcmonkey4eva** [comment]
@Morphan1 I saw you were playing with this - did it get anywhere?

**Comment by Morphan1** [comment]
@mcmonkey4eva the final result seems to work
```
i@human_skull[display_name=Computer;skull_skin=35154f7d-0e43-4b65-80b2-13dca69b0626|eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0d
XJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmVkNGFlNzU3ZjIzNDQ1YjVjOTMzNWNjNWE4ZjdmN2M2ZjlhNWFlZTg1YmI2OWZlOTdmNTgxZGFmYjE4ZDMwIn19fQ==]
```
This look okay?

**Comment by mcmonkey4eva** [comment]
@Morphan1 Isn't display name the item's actual... displayed name? Why are you storing the skull name in that?

Beyond that, the skull_skin= is fine

**Comment by mcmonkey4eva** [comment]
```
[23:07:08] <Morphan1> mcmonkey: what are you talking about?
[23:07:14] <Morphan1> the display name is unrelated
[23:07:47] <Morphan1> mcmonkey: I just grabbed a head from the website he linked, it came with a custom display name
[23:08:38] <mcmonkey> Morphan1: so the skull_skin= includes an encrypted player name?
[23:08:43] <mcmonkey> in addition to the skin itself?
[23:09:06] <Morphan1> mcmonkey: it's UUID|encrypted_skin_JSON
[23:09:19] <mcmonkey> Ah
[23:09:21] <mcmonkey> okay
[23:09:29] <mcmonkey> Morphan1: in that case, it's solid
```

**Comment by Morphan1** [comment]
Oh... I forgot to close this.
Here's an example of how to use the new heads
http://mcmonkey.org/paste/14045
