### ISSUE TITLE
on piston extends/retracts missing isSticky() method

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#947]
I wouldn't request unless required. Both ```<context.material.name>``` and ```<context.location.material.name>``` are returning ```piston_moving_piece``` so there's no way for the script to know if the piston is sticky or not.

**Comment by Morphan1** [comment]
Why open 3 different issues for extremely relevant, tiny additions?...

**Comment by AnthonyAMC** [comment]
Because irnewb
