### ISSUE TITLE
Particle problems

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Denizen-For-Bukkit#948]
Notice a few problems with particles with the latest builds. missing and broken particles.
comparing Denizen particles: http://mcmonkey.org/denizen/lngs/particle%20effects
to Minecraft particles: http://minecraft.gamepedia.com/Particles
also referenced Bukkit list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html

Issues:
wake: missing
droplet: missing
mobappearance: missing
ender_signal: shows hearts
potion_break: shows hearts
depthsuspend: working but not listed

Updated with all effects tested.

**Comment by KeangDavid** [comment]
Going through the whole list real quick to report more findings.

bubble: 'not showing'
ender_signal: 'shows hearts'
explode: 'white smoke'
potion_break: 'hearts again'
step_sound: 'hearts. It is on the list but called step_sound?'

Also noticed depthsuspend (depth_suspend) is in the list and working.

BlackCoyote also report experiencing the mobapperance effect with one of the effects although I could not replicate it.

**Comment by KeangDavid** [comment]
Updated main post with all effects tested.
denizen dev-build 413

**Comment by Morphan1** [comment]
I forgot to response to this ever apparently... After looking into it a bit a while back, it kinda seems like these particles were just taken out of the game entirely, possibly replaced with similar particles.
I personally have to say blame Mojang

**Comment by KeangDavid** [comment]
The once tittle missing are missing. The ones with hearts seam to be removed. I will add a link referring to all Minecraft particles.

**Comment by Morphan1** [comment]
I'm going to assume that 1.9 either fixed this or broke it even worse. Either way, this issue is probably not relevant anymore, if there's any problems with confirmed existing 1.9 particles, open a new issue and we'll look into it
