### ISSUE TITLE
Shoot command animation very imprecise

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#949]
I was using the shoot command to create weapons long ago, The "bullets" that had origin:<player> went in a straight line

Now i tried using the shoot command again and the animation of the "bullets" was very imprecise. I still could hit the target, but the snowball flew in a different location. the short script i was using is:

"WeaponTest":
    type: world
    events:
        On player right clicks with i@MP5:
            - if < player.flag[MP5Speed].is_expired> {
              - shoot snowball origin:< player> speed:6 script:MP5Hit spread:0 gravity:0 height:0
              - flag player MP5Speed duration:0.2s
              - determine fulfilled
              }

"MP5Hit":
    type: task
    context: location
    script:
        - hurt 5 entities:< def[hit_entities]>

I tried to use the push command instead, but i gave the same unprecise animations

**Comment by GomaTerzu** [comment]
Looks like the problems appear when you set the speed over 4. Up to 4 it is kind of precise

**Comment by mcmonkey4eva** [comment]
Minecraft issue, nothing we can do about shit Mojang programming

**Comment by AnthonyAMC** [comment]
You can't go faster than the speed of light! You can circumvent the speed limit if you make a wormhole and bend the fabric of space time though.

**Comment by GomaTerzu** [comment]
Anthony suggestion sounds solid. Is it possible for you mcmonkey? Otherwise i'll ask Morph ;)

Closing now.
