### ISSUE TITLE
Bug take <player.item_in_hand>

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#951]
When i use the command 

`- take < player.item_in_hand> qty:1` to take away an item, and i have more than 1 stack of this item in my inventory, it does not remove from my hand but from the first stack. When every itejm from the other stacks is taken away only then the item in hand gets take away. But while it takes away from the other stacks, it does not decrease the number when you look at it, only when you switch to it and use from the first stack too.

So when you don't switch to the first stack and used every item, you simply dan move the first stack and use it again.

The item i am removing is a custom item made form a script.

**Comment by mcmonkey4eva** [comment]
`-take iteminhand qty:1`

**Comment by GomaTerzu** [comment]
nevermind... :D
