### ISSUE TITLE
Permission for player command do nothing

### ISSUE THREAD

**Issue by xion87** [DenizenScript/Denizen-For-Bukkit#955]
I tried to follow the istructions here http://mcmonkey.org/denizen/lngs/command%20script%20containers
```
my_command
  type: command
  permission: my.permission.node  <---- this one do absolutly nothing dunno why
  permission message: Sorry, <player.name>, you can't use my command because you don't have the   permission '<permission>'!    <--- same, no working
blabla
scripts:
- narrate lol
```
Players are able to use /command without any permission block....

**Comment by mcmonkey4eva** [comment]
@Morphan1  why

**Comment by AnthonyAMC** [comment]
What if the ```my.permission.node``` is encased in quotes? ```'my.permission.node'```

**Comment by xion87** [comment]
tried to use '' same thing
