### ISSUE TITLE
no with for event damage

### ISSUE THREAD

**Issue by zozer** [DenizenScript/Denizen-For-Bukkit#956]
the damage event has no "with" as part of the event. (i.e. on player damages entity with iron_sword)

**Comment by AnthonyAMC** [comment]
Is this not sufficient?
```
on player damages entity:
  - if <player.item_in_hand.material.name.is[!=].to[iron_sword]||false> queue clear
```

**Comment by zozer** [comment]
well wouldn't it not be easier to simply say what i suggested?

**Comment by AnthonyAMC** [comment]
Yes, being able to specify the item in the event would be handy, but for the time being so as not to slow your development down, just use the if statement :D

**Comment by GomaTerzu** [comment]
Suggestion sounds good to me, too
it's the same for permission nodes in command scripts, we don't really need them, because we could check in an "if" but they would still be handy for us lazy folks :D

**Comment by AnthonyAMC** [comment]
@GomaTerzu ffs dude. you have an open issue, don't hijack the issue please.

**Comment by mcmonkey4eva** [comment]
This'll happen after we upgrade 'entity damage[...]' to a ScriptEvent.

**Comment by Morphan1** [comment]
@mcmonkey4eva I think the event's been converted by @Talamar1 right?

**Comment by Talamar1** [comment]
I can put it on my todo list...that's assuming you want it broken first before I get it fixed.

**Comment by mcmonkey4eva** [comment]
This'll probably require some core work, so let me deal with it.

**Comment by Talamar1** [comment]
Not sure why this is an issue with players (I can see npcs), just add:
```
        dItem iih = null;
        if (entity.isPlayer()) {
            iih = new dItem(entity.getPlayer().getItemInHand());
        }
```
to the EventHandler and:
```
        if (lower.contains("with") && iih != null) {
            int loc = lower.indexOf(" with ") + 6;
            String item = lower.substring(loc);
            if (!item.equals(iih.identifyNoIdentifier()) && item.equals(iih.identifySimpleNoIdentifier())) {
                return false;
            }
        }
```
to matches().  (And declare private dItem iih;)

**Comment by mcmonkey4eva** [comment]
I have a fancier plan. To abuse the new Switch system.

**Comment by Talamar1** [comment]
but....but... my code would work...

**Comment by Talamar1** [comment]
Also, why is't there a getItemInHand for NPCs since they can equip?
