### ISSUE TITLE
error in tag <player.bed_spawn>

### ISSUE THREAD

**Issue by Newwings** [DenizenScript/Denizen-For-Bukkit#957]
```(/ex) narrate "<player.bed_spawn>"``` will send a long error if no bed spawn is set: http://pastebin.com/8Ujr1B1S
and ```(/ex) adjust <player> bed_spawn_location:-311,89,1241,World``` won't work, but this sends no error.

**Comment by mcmonkey4eva** [comment]
Sent in a patch to the dev repo.
