### ISSUE TITLE
Enter/exit notable cuboid while in a vehicle

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#958]
I thought that it'd be handled by the event itself, but it's not and now I'm not sure how to handle this. I thought this seemed sane enough, but it's throwing a very big [error](http://mcmonkey.org/haste/13433).

```
    on player enters notable cuboid:
    - if <player.is_inside_vehicle> {
      - define vehicle '<player.get_vehicle>'
      - mount cancel <player>|<def[vehicle]>
      - teleport <def[vehicle]> <c.from>
      }
    - determine cancelled
```

**Comment by mcmonkey4eva** [comment]
You know how you don't edit a player's inventory in an inventory event?
Don't edit a player's location within a location change event.

Also that script is not the script that caused the error you posted. The error you posted uses the inject command repeatedly before screwing with the player's location.

**Comment by AnthonyAMC** [comment]
lol, yeah i wasn't going post all of dRegions here for that. The players location isn't being altered in the event, unless canceling the mount counts as altering the location. Ideally, the event would handle a player mounted to another entity just the same as a player walking. Canceling the event /tries/ to stop the player, but the vehicle keeps on going... and the player is still mounted so it ends up shaking the player violently. So I added that if statement to no avail.

**Comment by mcmonkey4eva** [comment]
Have you gotten any ideas on this recently?

Cause I have nothing.

**Comment by AnthonyAMC** [comment]
Oh, yeah... i [have it handled](https://github.com/AnthonyAMC/Public-Denizen-Scripts/blob/master/dRegions/flags.dscript#L58) it, but it's meh.
