### ISSUE TITLE
missing player in sheep dye event 

### ISSUE THREAD

**Issue by DerEinpacker** [DenizenScript/Denizen-For-Bukkit#960]
Hello,
I made an item called i@grenade and it looks like green dye. now I wanted to prevent players using the i@grenade to dye sheep. so i wrote this script:
```
"BlockSheepGrenade":
    type: world
    debug: on
    events:
        on player dyes sheep:
            - if < player.item_in_hand> contains i@grenade {
              - determine cancelled
              }
```
i get this error:
```
[12:52:36 INFO]:  Filled tag < player.item_in_hand> with 'player.item_in_hand'.
[12:52:36 INFO]:  ERROR in script 'BlockSheepGrenade'! Tag < player.item_in_hand> is invalid!
```
I also tried to use the narrate command to check what is wrong and the player is null:
```
[12:56:43 INFO]: +- Building event 'ON PLAYER DYES SHEEP' for BlockSheepGrenade ---------+
[12:56:43 INFO]:  Starting InstantQueue 'BlockSheepGrenade_HoleUnionJudgment'...
[12:56:43 INFO]:  Queue 'BlockSheepGrenade_HoleUnionJudgment' Executing: NARRATE "lol"
[12:56:43 INFO]: +- Executing dCommand: NARRATE ---------+
[12:56:43 INFO]: +> Executing 'NARRATE': Narrating='lol'  Targets='null'
```

**Comment by AnthonyAMC** [comment]
The error is because you have a space in your tag. Also, you should be using the item scriptname like so.
```
BlockSheepGrenade:
  type: world
  debug: on
  events:
    on player dyes sheep:
    - if <player.item_in_hand.scriptname.is[==].to[grenade]||false> {
    - determine cancelled
    }
```

**Comment by DerEinpacker** [comment]
No I don't have a spaces in my tags. I thought Github can't handle tags. I made it so I can paste the script correctly. Just test it yourself, please.

**Comment by BlackCoyote** [comment]
You just did it again; you wrote "< player.item_in_hand>" instead of "<player.item_in_hand>". Note the space after <

**Comment by DerEinpacker** [comment]
Of course. Try writing this tag in Github without spaces. It doesn't show. How am I supposed to talk about tags when they disappear :D
Here with spaces: < player.item_in_hand>
Here without: <player.item_in_hand>

**Comment by BlackCoyote** [comment]
heh touché

**Comment by Morphan1** [comment]
@DerEinpacker @BlackCoyote 
Wrap the tag with the \` symbol
For example, `<player.whatever>`

**Comment by Morphan1** [comment]
There actually is no player attached to the Bukkit event.
I'd assume you'd need to use the `player right clicks entity (with item)` event
So, for example,
```
BlockSheepGrenade:
    type: world
    debug: on
    events:
        on player right clicks sheep with i@Grenade:
        - determine cancelled
```
If you have any further questions, feel free to just reply here

**Comment by DerEinpacker** [comment]
Hey Morphan thanks for the Info, but why did you close it? I have another Question because BlackCoyote and I tried the right click event today, but it doesn't work like you suggested and like we would expect:

"BlockSheepGrenade":
    type: world
    debug: on
    events:
        on player right clicks e@sheep with i@grenade:
            - determine cancelled

The sheep just gets painted green with the lime dye that is the i@grenade.

Only the following script works. I really have to call the adjust command two times, because it won't work otherwise and the sheep just becomes green. Also you can't see the sheep getting black. It just switches back to it's old color

'"BlockSheepGrenade":
    type: world
    debug: on
    events:
        on player right clicks e@sheep with i@grenade:
            - define colour <context.entity.color>
            - adjust <context.entity> color:black
            - adjust <context.entity> color:<def[colour]>
            - determine cancelled'

**Comment by Morphan1** [comment]
If that's what you have to do, then do it...
I'm sorry, but this is a Bukkit/Spigot issue that we don't really have control over
You could also try something with a flag in the dye event, which gets read by the interact event if it exists

**Comment by BlackCoyote** [comment]
the reason it works only with the 2nd adjust command, is because you can only change the colour back, once the event passes. Replace the first adjust with a - wait 1t, or with - determine cancelled passively (and drop the 2nd determine cancelled) to achieve the same results.

**Comment by BlackCoyote** [comment]
Ignore the above, delay should not matter in this as all commands will fire before the event happens unless actual delay is added through a wait command..

**Comment by mcmonkey4eva** [comment]
You might try -> http://mcmonkey.org/denizen/evts/clicks%20at%20entity -> right clicks AT entity, which might possibly determine cancelled better.

Reopening until it's confirmed to be resolved satisfactorily.

**Comment by DerEinpacker** [comment]
Hi, I just tried the "clicks AT entity"-event. Every tag works fine. It also gets the <context.entity.color> correct but 

- determine cancelled 

does not prevent the sheep from being. Painted. So basically the same result as the normal entity click event.

**Comment by mcmonkey4eva** [comment]
Well... Spigot bug yo

**Comment by AnthonyAMC** [comment]
The right clicks event DOES handle dyeing sheep just fine. What you're seeing is a client side glitch.
Tested and re-tested.
