### ISSUE TITLE
yaml yaml tags of yaml

### ISSUE THREAD

**Issue by calico-kid** [DenizenScript/Denizen-For-Bukkit#967]
having an issue with the yaml tag for reading... here is a snippet of the yaml i am pulling from

prices:
  i&atSTONE,0: '2'
  i&atGRASS,0: '20'
  i&atDIRT,0: '1'
  i&atCOBBLESTONE,0: '1'
  i&atWOOD,0: '6'
  i&atWOOD,1: '6'
  i&atWOOD,2: '6'
  i&atWOOD,3: '6'

http://mcmonkey.org/paste/13913#152

here is the debug showing the tag filling to be <yaml[prices].read[prices.i&atcobblestone,0]> but you can see its not returning  "1" like it should be.

here is the portion of script i have this issue here as well as in the rest of the script where this tag is called  http://mcmonkey.org/haste/13914#LINE13 as you can see it is the read portion of the yaml tag not returning like it was supposed to... lemme know if i am using it wrong or have something missing as i wouldnt be suprised if thats the case knowing me :)

**Comment by AnthonyAMC** [comment]
That's expecting child keys of the ```prices``` node which should be written like:
```
prices:
  i&atSTONE,0: '2'
  i&atGRASS,0: '20'
  i&atDIRT,0: '1'
  i&atCOBBLESTONE,0: '1'
  i&atWOOD,0: '6'
  i&atWOOD,1: '6'
  i&atWOOD,2: '6'
  i&atWOOD,3: '6'
```
Maybe that's how your prices.yml file is written and it just didn't get copied over like that here, but yaml cares about indentation.

**Comment by AnthonyAMC** [comment]
Actually, i'm not sure if you can have a comma in a yaml key...

**Comment by calico-kid** [comment]
yeah its indented but for some reason in here it doesn't carry over the indentation... all of the yaml that is there whether existing or added via cmd ingame wont be called by the tag

**Comment by calico-kid** [comment]
the comma worked fine in previous builds... all of this is escaped too so there is no comma tag apparently if it can write it with the comma it should read it with it too lol

**Comment by mcmonkey4eva** [comment]
Uhm... I think case-sensitivity might be an issue here.

**Comment by AnthonyAMC** [comment]
oh yeah... yaml cares about casing

**Comment by calico-kid** [comment]
all fixed
