### ISSUE TITLE
no event on entity breaks block

### ISSUE THREAD

**Issue by zozer** [DenizenScript/Denizen-For-Bukkit#971]
is it possible to get a general event for entities breaking blocks?

**Comment by AnthonyAMC** [comment]
http://mcmonkey.org/denizen/evts/entity%20changes%20block
That's one way. It depends on what entity you're talking about. That'll cover sheep eating grass, zombies breaking doors, enderman...

**Comment by zozer** [comment]
so can i do 
on entity changes chest into air: ?

**Comment by AnthonyAMC** [comment]
What are you trying to do specifically?

**Comment by zozer** [comment]
I'm trying to fix the dlock chest so that when any entity breaks it (including creepers, tnt, endermen, any other entity that breaks stuff) the chest dosnt break.

**Comment by mcmonkey4eva** [comment]
... I have no idea what's being requested here.

**Comment by Morphan1** [comment]
Can this be clarified/is it even a problem still?

**Comment by zozer** [comment]
what i was asking was: can there be an event of 'on entity breaks block' to include any damages that mobs do to blocks, or a block/set of block (specifically creepers/tnt in my case, but also include on entity changes block).

**Comment by mcmonkey4eva** [comment]
that's... a lot of additional events, especially if someone sets off a lot of TNT...

**Comment by Morphan1** [comment]
@mcmonkey4eva so is this gonna happen? or..

**Comment by mcmonkey4eva** [comment]
Nope!
