### ISSUE TITLE
<player.ip> and <player.ip.address> tags malfunction

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Denizen-For-Bukkit#973]
After using the (player.ip) tag for a player it adds the (player.ip) tag to the beginning of (player.ip.address). As long as you don't use (player.ip), than (player.ip.address) will return normally.

Steps to reproduce:
1. /ex narrate (player.ip.address)
2. /ex narrate (player.ip)
3. /ex narrate (player.ip.address)

Debug Paste: http://mcmonkey.org/paste/14158

I don't know the escape code to put tags in these comments. Replace ( and ) with carrots.

**Comment by Morphan1** [comment]
It looks like what's happening is that when `<player.ip>` is used, it does an address lookup and stores it in a cache. I'd guess that `<player.ip.address>` tries to get that cached address and prepend it to the address, which is what you're seeing.

To get the numeric address, you can simply use `<player.ip.address.after[/]>`.
(Or `/<player.ip.address.after[/]>` if you want to keep the `/` for whatever weird reason)

**Comment by mcmonkey4eva** [comment]
Yup ^ player.ip.address wants full details and can't get them unless the original IP function is called first for some weird only-Bukkit-knows reasons.

**Comment by KeangDavid** [comment]
Could you make "player.ip.address" grab the "player.ip" before "player.ip.address" returns?

**Comment by mcmonkey4eva** [comment]
Done ^
