### ISSUE TITLE
Enderpearls teleport bypassing WorldGuard setting

### ISSUE THREAD

**Issue by Xericore** [DenizenScript/Denizen-For-Bukkit#974]
BUG: WorldGuard region flag is overridden by Denizen.
As soon as this script is added to Denizen, enderpearls will teleport players regardless of the WorldGuard setting.
Tested with 0.9.6-SNAPSHOT (build 1567).
This script has been pasted to http://mcmonkey.org/haste/14217

Steps to reproduce:
0. Add this script to .../Denizen/scripts.
1. Download any WorldGuard-6.0.0 build. Download WorldEdit as well.
2. Select a region cuboid with the //wand tool
3. Define a region with: /rg define myregion
4. Deny enderpearls with: /rg flag myregion enderpearl deny
5. Throw an enderpearl within the region.
6. Notice WorldGuard messages: "You're not allowed to go there.". But the teleport still happens.
7. Remove this script from .../Denizen/scripts. Enderpearls are now correctly denied within the region.

Notes:
The player doesn't have to enter the cuboid defined below. The cuboid doesn't have to exist.
All WorldGuard regions are affected by this.

The actual script:

enderpearl:
  type: world

  events:
    on player enters ANY_STRING_HERE:

**Comment by mcmonkey4eva** [comment]
Fixed in https://github.com/mcmonkey4eva/Denizen/commit/50802b40a60a99ada8b42cc25379c909fbbfb13c
