### ISSUE TITLE
problem with constants

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#975]
http://mcmonkey.org/haste/14229

`... /ex narrate <s@msflowerfetch.constant[Flowersqty]>` returns null

but
`/ex narrate <s@msflowerfetch.yaml_key[Flowersqty]> ` works (thanks Anthony!).

Not sure what changed, but this was working before, but not now.

**Comment by mcmonkey4eva** [comment]
You forgot `default constants:`

**Comment by AnthonyAMC** [comment]
Should also mention that what are now ```script.yaml_keys``` were under the ```default constants:``` node

**Comment by uledrith** [comment]
That's what I actually had at first, see this script, same problem.
http://mcmonkey.org/haste/14228

**Comment by mcmonkey4eva** [comment]
debug of the default constants form please.

**Comment by uledrith** [comment]
debug
http://mcmonkey.org/haste/14230

**Comment by Morphan1** [comment]
I'm pretty sure this is fixed now
