### ISSUE TITLE
Logic problem when using braces

### ISSUE THREAD

**Issue by Dopplizzle** [DenizenScript/Denizen-For-Bukkit#976]
I'm not sure exactly when this cropped up, but the script parser seems to get confused when a compound statement involves no braces in one part and braces in another:
This fails with the error "ERROR! No enum constant net.aufdemrand.denizencore.scripts.commands.core.Comparable.Operator.NARRATE":
```
- if true narrate "true"
  else {
    - narrate "false"
  }
```

...but this works fine:
```
- if true {
    - narrate "true"
  }
  else {
    - narrate "false"
  }
```

**Comment by Morphan1** [comment]
In the latest versions, you're no longer allowed to change formatting like that.
Consistency is nice :smile_cat:

**Comment by Dopplizzle** [comment]
Gotcha. That would seem to avoid a mess of potential problems. Perhaps a more informative error message then? Like "Inconsistent logic bracing" or some such...

**Comment by Morphan1** [comment]
Sadly, I don't think there's an easy way for us to detect whether your bracing is correct or not
I may be wrong though... @mcmonkey4eva ?

**Comment by mcmonkey4eva** [comment]
That'd be... difficult. Possible. But difficult. I don't think it's really worth it.
