### ISSUE TITLE
flag duration problem in loop

### ISSUE THREAD

**Issue by Xericore** [DenizenScript/Denizen-For-Bukkit#981]
When - flag %value% is used in a loop (where %value% is p@...), the duration is not applied correctly.

See: http://mcmonkey.org/haste/14420
Using denizen dev build 159.

EDIT: added debug: http://mcmonkey.org/paste/14421

**Comment by mcmonkey4eva** [comment]
`1min` is not a valid duration. You're looking for `1m`.

User error.

**Comment by Xericore** [comment]
Oh man, thanks.
