### ISSUE TITLE
1.8 Adventure mode feature

### ISSUE THREAD

**Issue by writeescape** [DenizenScript/Denizen-For-Bukkit#983]
the ability to create custom items that the player in creative mode can only break certain blocks,

using Custom JSON based items maybe. 

As the way to do so currently is to use: execute asserver "give <player.name> item {CanDestroy:[Wood]}" shouldnt be a thing that needs to be done.

**Comment by mcmonkey4eva** [comment]
https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1184 let's direct discussion there, as it better represents the modern details of the issue or something like that. ALso, front page is magic~
