### ISSUE TITLE
.add tag problem

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#984]
script:  http://mcmonkey.org/haste/14478

debug: http://mcmonkey.org/haste/14479

Iine 15 of the script gives error no matter what combination I try with .add and .as_int.

**Comment by AnthonyAMC** [comment]
```- flag <context.entity> <player>:<context.entity.flag[<player>].add[<context.damage>].as_int>```
Tags MUST be encased in ```<>```

**Comment by mcmonkey4eva** [comment]
^
