### ISSUE TITLE
BUG right click event also triggers left click event sometimes with doors

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#985]
So i made lots of weapons on my server where you shoot with right click and reload with left click. But when you right click on doors and on chests you clear the rest of the script so that doors and chest can be used wihout shooting yourself.

Here is the script, i shortened it down.
http://hastebin.com/ujumetagah.xml

So I placed a door and a chest to test it. With chests there is no problem, but with doors in about 1-3% of the tests instead of the right click event the left cklick event was triggered and people started to reload their weapons. 

Could you take a look at that?

**Comment by GomaTerzu** [comment]
btw I am using Spigot 1.8.3 and latest Denizen Dev Build but i had this problem before the update, too.

**Comment by mcmonkey4eva** [comment]
Okay.
`/what/`.

**Comment by GomaTerzu** [comment]
How is the status in this one?

**Comment by mcmonkey4eva** [comment]
Did you never see my reply above?

**Comment by adw123** [comment]
I logged bug #1042 that may be related to this...Does your right-click event have code in it that uses animate? Does it only occur when your players have something in their hand?
