### ISSUE TITLE
SUGGESTION: Using the Achievement Announcement

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#986]
Hey, is it possible to use the achievement announcer with denizen somehow? 

I am not talking about the stuff that come in chat. I am talking about the box that pops up in the upper right corner, see here:

http://www.minecraft101.net/guides/images/first-night/03-getting-wood.jpg

**Comment by mcmonkey4eva** [comment]
@Morphan1 Think you can packet magic up something to do this?

**Comment by Morphan1** [comment]
Achievement messages are entirely clientside and cannot be controlled by the server
