### ISSUE TITLE
BUG problems with animate command

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#987]
Since it is not listed here as a bug, but known by people, I add it here.

I created a NPC via Citizens, gave him an item, and tried to use different animations on him. The following two don't work

- animate `<npc[77]>` sleep
- animate `<npc[77]>` start_use_item

The start_use_item does nothing
The sleep only sets the name of the npc at his feet.

**Comment by mcmonkey4eva** [comment]
What are you expecting start_use_item to do?

**Comment by GomaTerzu** [comment]
Repetitive movement of the arms or something. I just tested it and noticed it does nothing and I wondered why is there a start and an end_use_item option. So my guess was that it's broken.

**Comment by mcmonkey4eva** [comment]
It works fine, it just doesn't do what you expect it to. Give the NPC a sword and watch it perform magic.

**Comment by mcmonkey4eva** [comment]
Sleep anim is a Citizens issue -> https://github.com/CitizensDev/Citizens2/issues/262

**Comment by GomaTerzu** [comment]
Why is that a citizens issue when morphan says it is a denizen issue in there?

**Comment by Morphan1** [comment]
@GomaTerzu the issue's creator then said that he's using the API itself, which is what Denizen uses. Therefore it's a problem with Citizens itself (it's actually an issue with 1.8... It requires a bed below the NPC. But the bed can simply be removed after having them sleep on it, and they'll continue to sleep)

**Comment by mcmonkey4eva** [comment]
@Morphan1 post that on the c2 issue maybe. All the info available is important to have
