### ISSUE TITLE
i@potions

### ISSUE THREAD

**Issue by Kirrasio** [DenizenScript/Denizen-For-Bukkit#989]
Getting an error in potions, Player receives item but gets a line of code. I am using the helpful citizens base script. http://mcmonkey.org/paste/14537

**Comment by mcmonkey4eva** [comment]
There appears to be some errors handling potions... will investigate...

**Comment by mcmonkey4eva** [comment]
Is this fixed in http://ci.mineconomy.org/job/Denizen_Developmental/174/ or above?

**Comment by Kirrasio** [comment]
Yes the potions work now! Thank you, I've been a bit busy. I appreciate the
fix!
