### ISSUE TITLE
take command broken

### ISSUE THREAD

**Issue by Xericore** [DenizenScript/Denizen-For-Bukkit#990]
Happens only if user has potion of fire resistance (373/8227) in the first slot of the quick access bar/bottom inventory. Second potion of fire resistance (373/8259) works. A few other potions worked as well. Didn't test all of them.

Using denizen dev build 163.

Put potion of fire resistance (373/8227) in first slot of hotbar.
/ex take i@glass_bottle qty:1
or
/ex take i@sugar
"IllegalArgumentException: Level must be 1 for this potion"

Here's the debug: http://mcmonkey.org/paste/14539

**Comment by mcmonkey4eva** [comment]
Direct discussion to: https://github.com/DenizenScript/Denizen-For-Bukkit/issues/989
