### ISSUE TITLE
Health Command: causes NPCs to die twice

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#994]
```
MSLowerCryptBoss:
  type: assignment
  debug: false
  actions:
    on assignment:
    - ^flag global mslowercrypt_npc:<npc>
    - ^flag <npc> spawnpoint:l@-1284.1,49.9,-24.1,survive
    - ^adjust <npc> skin:Giik
    - ^flag <npc> aggro:!
    - ^flag <npc> highestdamage:0
```
If I remove the adjust line, using a simple "on entity death:" and narrate will only show once.  If I add the adjust line, it fires twice.

Also, the Citizens "NPC dies" displays twice.

**Comment by uledrith** [comment]
ok, I was wrong on this.  It's not the "adjust" mech causing this, but rather the 'health' command

```
MSLowerCryptBoss2:
  type: assignment
  debug: false
  actions:
    on assignment:
    - ^trigger name:damage toggle:true
    - ^vulnerable state:true
    - ^health <npc> 20
```
The above assignment script will cause two 'on npc dies' events to fire when the npc is killed.

**Comment by Morphan1** [comment]
Is this still an issue?

**Comment by mcmonkey4eva** [comment]
Closing due to lack of reply. Please leave a comment below if this needs to be reopened.
