### ISSUE TITLE
lil bit of depreciation wether its critical or not let you decide..

### ISSUE THREAD

**Issue by Sycholic** [DenizenScript/Denizen-For-Bukkit#995]
[05:12:35 WARN]: [Denizen] "Denizen v0.9.6-SNAPSHOT (build 1572)" has registered a listener for org.bukkit.event.player.PlayerChatEvent on method "public void net.aufdemrand.denizen.scripts.triggers.core.ChatTrigger.syncChatTrigger(org.bukkit.event.player.PlayerChatEvent)",
but the event is Deprecated. "Listening to this event forces chat to wait for the main thread, delaying chat messages."; please notify the authors [aufdemrand, mcmonkey].

This could be a critical thing or might not.. Im far from an expert dealing with Java let alone how java handles threading but now not sure why still using syncChatTrigger vs AsyncPlayerChatEvent

**Comment by mcmonkey4eva** [comment]
Someone stab spigot for me... this is a neccessity, not an error.

**Comment by Sycholic** [comment]
it only shows up when having depreciation warnings set to true otherwise I would never noticed it.  Like I said figured let yas look at it and see if its something.  What the warning stated was the only thing that pressed me to post possible bug.  But long as you dont see (and infact seems like its a requirement) that chat be sync not async all I needed to know.  thanks for the quick reply. as for who wrote it. spigot or CB inherit message Im not sure but I will throw a potato at whomever it was if I find out ^_^

**Comment by mcmonkey4eva** [comment]
Yeah that's Citizens. https://github.com/CitizensDev/Citizens2/issues
