### ISSUE TITLE
Show_Boss_Bar Low Health Showing Wither

### ISSUE THREAD

**Issue by Mickket** [DenizenScript/Denizen-For-Bukkit#996]
The low health mechanic and effect of the wither is causing the show_boss_bar to show the withers scrolling texture effect. I'm not sure if this can even be fixed due to the changes Mojang made recently.
![2015-03-24_02 41 19](https://cloud.githubusercontent.com/assets/11625939/6796828/1165e638-d1d0-11e4-9507-5037452d1315.png)

/ex adjust <player> show_boss_bar:1|1

**Comment by Morphan1** [comment]
This is an issue with withers not being able to not have their shield appear below half their health even when invisible. Until 1.9 comes out, it's either this or an ender dragon flapping its wings at that same place in front of you
