### ISSUE TITLE
Other plugins can't execute Denizen custom commands

### ISSUE THREAD

**Issue by vicknyaz112** [DenizenScript/Denizen-For-Bukkit#999]
Greetings!
Other plugins (like MythicMobs) can't execute custom commands created in Denizen.
Example: I created "customcmd" command:
on customcmd command:
  execute as_server "broadcast TEST"
  determine fulfilled
When I run the command from chat or console it works just fine. But when I try to run the command via MythicMobs event (raduiscmd), nothing happens. It just says "Unknown command" in console and doesn't even start a dCommand event. The same thing happens with any other plugin trying to execute Denizen command.

**Comment by AnthonyAMC** [comment]
Have you tried using the [command script container](http://mcmonkey.org/denizen/lngs/command%20script)?

**Comment by mcmonkey4eva** [comment]
We have a video on how to handle custom commands properly: http://mcmonkey.org/denizen/vids/Handling%20Player%20Commands

**Comment by vicknyaz112** [comment]
Thanks for help! Closing ticket

**Comment by vicknyaz112** [comment]
I know that sounds really weird, but is there any way to get command scripts in denizen 0.9.4 (CB 1.7.2)?
For several reasons I'm not able to update to 1.7.9, that's why I'm asking for help.
I understand that you are not supposed to support older versions, but I'd be very grateful if you'll help me.

**Comment by AnthonyAMC** [comment]
That's not older, that's ancient. We're on 1.8.3 now.

**Comment by mcmonkey4eva** [comment]
Please do update, it'll improve so much. http://wiki.citizensnpcs.co/Versions has a 'versionless' Denizen build that may or may not work for your needs.

**Comment by vicknyaz112** [comment]
Thanks a lot! I'll see if it works for me and report tomorrow!

**Comment by Morphan1** [comment]
The versionless build will not work as command script registration relies on version-specific internal code.

**Comment by vicknyaz112** [comment]
As Morphan1 said, it didn't work. But I believe I kinda figured out what to do. Anyways, thanks everybody for your help! Closing ticket. Now for sure.
